package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.sql.Connection;
import java.util.*;

final class EvaluationSets {
    final Store store;final Projects projects;
    EvaluationSets(Store store,Projects projects){this.store=store;this.projects=projects;}
    static void task(JsonObject project){if(!Annotations.TYPES.contains(Json.str(project,"taskType","")))throw new ApiError(422,"evaluation_task_unsupported","当前质量评测不支持该任务类型。");}
    JsonObject create(JsonObject p){String pid=Json.required(p,"projectId"),name=Json.required(p,"name");List<JsonObject> selected=new AssetFiles(store,projects).select(p);if(!p.has("assetIds")||selected.isEmpty()||Json.array(p,"assetIds").size()!=selected.size())throw new ApiError(400,"asset_selection_empty","评测集必须明确选择无重复的素材。");if(selected.size()>1000)throw new ApiError(413,"evaluation_sample_limit","第一段评测单集最多 1000 张素材。");
        JsonObject project=projects.get(pid);task(project);String id=Json.id();JsonArray assets=new JsonArray(),ids=new JsonArray();for(JsonObject a:selected){assets.add(input(a));ids.add(a.get("id"));}
        JsonObject result=Json.obj("id",id,"projectId",pid,"name",name,"taskType",project.get("taskType"),"revision",1,"assetIds",ids,"assets",assets,"template",project,"truthCount",0,"publishedVersions",new JsonArray(),"createdAt",Json.now(),"updatedAt",Json.now());
        return store.tx(c->{Store.update(c,"INSERT INTO evaluation_sets(id,project_id,data) VALUES(?,?,?)",id,pid,result);Store.event(c,"evaluation_set.created",null,null,null,Json.obj("setId",id,"projectId",pid,"sampleCount",assets.size()));return result;});
    }
    static JsonObject input(JsonObject a){JsonObject m=Json.object(a,"metadata");return Json.obj("assetId",a.get("id"),"name",a.get("name"),"width",a.get("width"),"height",a.get("height"),"contentHash",a.get("contentHash"),"sourceHash",m.get("sourceHash"),"sourceGroup",group(a),"normalization",Json.obj("version",m.get("normalizationVersion"),"sourceToBaseline",m.get("sourceToBaseline"),"alphaBackground",m.get("alphaBackground"),"inputVersion",m.get("inputVersion")));}
    static String group(JsonObject a){JsonObject m=Json.object(a,"metadata");if(m.has("evaluationSourceGroup"))return Json.required(m,"evaluationSourceGroup");for(String k:List.of("sourceVideoId","groupId","rootAssetId","parentAssetId")){String value=Json.str(m,k,"");if(!value.isEmpty())return (k.equals("rootAssetId")||k.equals("parentAssetId")?"asset-root":k)+":"+value;}return "asset-root:"+Json.str(a,"id",Json.str(a,"assetId","unknown"));}
    static JsonArray published(Connection c,String id)throws Exception{JsonArray result=new JsonArray();for(JsonObject row:Store.rows(c,"SELECT id,version,json_extract(data,'$.sampleCount') AS sampleCount,json_extract(data,'$.createdAt') AS createdAt FROM evaluation_set_versions WHERE set_id=? ORDER BY version DESC",id))result.add(row);return result;}
    JsonArray list(String pid){return store.read(c->{JsonArray result=Store.docs(c,"SELECT data FROM evaluation_sets WHERE project_id=? ORDER BY rowid DESC",pid);for(JsonElement e:result)e.getAsJsonObject().add("publishedVersions",published(c,Json.required(e.getAsJsonObject(),"id")));return result;});}
    JsonObject get(JsonObject p){String id=Json.required(p,"setId");if(p.has("versionId")){JsonObject version=version(Json.required(p,"versionId"));if(!Json.required(version,"setId").equals(id))throw new ApiError(400,"evaluation_set_mismatch","发布版本不属于该评测集。");return version;}return store.read(c->{JsonObject set=Store.document(c,"evaluation_sets",id);set.add("publishedVersions",published(c,id));return set;});}
    static JsonObject selected(JsonObject set,String aid){for(JsonElement e:Json.array(set,"assets")){JsonObject a=e.getAsJsonObject();if(Json.required(a,"assetId").equals(aid))return a;}throw new ApiError(400,"evaluation_asset_mismatch","素材不属于该固定评测集。");}
    JsonObject saveTruth(JsonObject p){String sid=Json.required(p,"setId"),aid=Json.required(p,"assetId"),source=Json.required(p,"source");if(!Set.of("manual","imported_human").contains(source))throw new ApiError(422,"evaluation_truth_source_invalid","真值必须来自明确的人工制作或人工答案导入。");if(!p.has("baseTruthVersion")||!p.has("annotations")||!p.get("annotations").isJsonArray())throw new ApiError(400,"invalid_argument","必须明确提供真值基线版本及 annotations。");
        return store.tx(c->{JsonObject set=Store.document(c,"evaluation_sets",sid),asset=selected(set,aid),previous=Store.one(c,"SELECT MAX(version) AS n FROM truth_versions WHERE set_id=? AND asset_id=?",sid,aid);int current=Json.integer(previous,"n",0);if(Json.integer(p,"baseTruthVersion",-1)!=current)throw new ApiError(409,"evaluation_truth_conflict","人工真值版本已变化，请重新检查后保存。",Json.obj("currentVersion",current));
            JsonArray annotations=Annotations.validate(Json.array(p,"annotations"),asset,Json.object(set,"template"));if(Json.required(set,"taskType").equals("classify")&&annotations.size()!=1)throw new ApiError(422,"evaluation_classification_truth_required","分类人工真值必须恰好包含一个类别，不能把未知类别保存为空答案。");int next=current+1,revision=Json.integer(set,"revision",0)+1;JsonObject data=Json.obj("setId",sid,"assetId",aid,"truthVersion",next,"annotations",annotations,"source",source,"note",Json.str(p,"note",""),"savedAt",Json.now());
            Store.update(c,"INSERT INTO truth_versions(set_id,asset_id,version,data) VALUES(?,?,?,?)",sid,aid,next,data);set.addProperty("revision",revision);set.addProperty("truthCount",Store.one(c,"SELECT COUNT(DISTINCT asset_id) AS n FROM truth_versions WHERE set_id=?",sid).get("n").getAsInt());set.addProperty("updatedAt",Json.now());Store.update(c,"UPDATE evaluation_sets SET data=? WHERE id=?",set,sid);Store.event(c,"evaluation_truth.saved",null,aid,null,Json.obj("setId",sid,"truthVersion",next,"setRevision",revision));return Json.obj("setId",sid,"assetId",aid,"truthVersion",next,"setRevision",revision,"savedAt",data.get("savedAt"));});
    }
    JsonObject truth(JsonObject p){return store.read(c->{String sid=Json.required(p,"setId"),aid=Json.required(p,"assetId");selected(Store.document(c,"evaluation_sets",sid),aid);JsonObject r=p.has("truthVersion")?Store.one(c,"SELECT data FROM truth_versions WHERE set_id=? AND asset_id=? AND version=?",sid,aid,Json.integer(p,"truthVersion",0)):Store.one(c,"SELECT data FROM truth_versions WHERE set_id=? AND asset_id=? ORDER BY version DESC LIMIT 1",sid,aid);if(r==null)throw new ApiError(404,"evaluation_truth_missing","该素材还没有独立人工真值。");return Json.parse(r.get("data").getAsString());});}
    JsonObject publish(JsonObject p)throws Exception{
        store.requireSpace(0);String sid=Json.required(p,"setId");if(!p.has("baseSetRevision"))throw new ApiError(400,"invalid_argument","发布必须指定 baseSetRevision。");
        JsonObject snapshot=store.read(c->{JsonObject set=Store.document(c,"evaluation_sets",sid);if(Json.integer(set,"revision",0)!=Json.integer(p,"baseSetRevision",-1))throw new ApiError(409,"evaluation_set_conflict","评测集真值已变化，请重新检查后发布。");JsonArray assets=Json.array(set,"assets").deepCopy();for(JsonElement e:assets){JsonObject a=e.getAsJsonObject();JsonObject row=Store.one(c,"SELECT data FROM truth_versions WHERE set_id=? AND asset_id=? ORDER BY version DESC LIMIT 1",sid,Json.required(a,"assetId"));if(row==null)throw new ApiError(422,"evaluation_truth_incomplete","每张素材都需要显式保存独立人工真值，包括无目标图片。");a.add("truth",Json.parse(row.get("data").getAsString()));}set.add("assets",assets);return set;});
        String id=Json.id();Path parent=store.root.resolve("evaluation-sets"),temporary=parent.resolve(".partial-"+id),destination=parent.resolve(id);Files.createDirectories(temporary.resolve("images"));int objects=0;Map<String,Integer> coverage=new LinkedHashMap<>();
        for(JsonElement e:Json.array(snapshot,"assets")){JsonObject a=e.getAsJsonObject();String aid=Json.required(a,"assetId");Path source=projects.path(aid);if(!Files.isRegularFile(source)||!Media.hash(source).equals(Json.required(a,"contentHash")))throw new ApiError(409,"evaluation_input_mismatch","素材内容与评测集创建时不一致，发布已停止。");String relative="images/"+aid+".png";Files.copy(source,temporary.resolve(relative));if(!Media.hash(temporary.resolve(relative)).equals(Json.required(a,"contentHash")))throw new ApiError(500,"evaluation_copy_failed","评测图片副本校验失败。");a.addProperty("image",relative);for(JsonElement annotation:Json.array(Json.object(a,"truth"),"annotations")){objects++;coverage.merge(Json.required(annotation.getAsJsonObject(),"classId"),1,Integer::sum);}}
        int objectCount=objects;
        return store.tx(c->{JsonObject current=Store.document(c,"evaluation_sets",sid);if(Json.integer(current,"revision",0)!=Json.integer(p,"baseSetRevision",-1))throw new ApiError(409,"evaluation_set_conflict","复制图片期间真值发生变化，本次没有发布。");int version=Store.one(c,"SELECT COALESCE(MAX(version),0)+1 AS n FROM evaluation_set_versions WHERE set_id=?",sid).get("n").getAsInt();
            JsonObject result=Json.obj("id",id,"setId",sid,"projectId",snapshot.get("projectId"),"name",snapshot.get("name"),"version",version,"setRevision",snapshot.get("revision"),"sampleCount",Json.array(snapshot,"assets").size(),"truthObjectCount",objectCount,"coverage",coverage,"taskType",snapshot.get("taskType"),"template",snapshot.get("template"),"assets",snapshot.get("assets"),"createdAt",Json.now());
            Files.writeString(temporary.resolve("manifest.json"),result.toString());String hash=Media.hash(temporary.resolve("manifest.json"));Files.move(temporary,destination,StandardCopyOption.ATOMIC_MOVE);result.addProperty("manifestHash",hash);Store.update(c,"INSERT INTO evaluation_set_versions(id,set_id,version,data) VALUES(?,?,?,?)",id,sid,version,result);Store.event(c,"evaluation_set.published",null,null,null,Json.obj("setId",sid,"setVersionId",id,"version",version,"sampleCount",result.get("sampleCount")));return result;});
    }
    JsonObject version(String id){JsonObject v=store.read(c->Store.document(c,"evaluation_set_versions",id));Path file=store.root.resolve("evaluation-sets").resolve(id).resolve("manifest.json");try{if(!Files.isRegularFile(file)||!Media.hash(file).equals(Json.required(v,"manifestHash")))throw new Exception();}catch(Exception e){throw new ApiError(409,"evaluation_snapshot_corrupt","已发布评测清单缺失或已被修改。");}return v;}
    Path image(String versionId,String assetId){JsonObject v=version(versionId),selected=null;for(JsonElement e:Json.array(v,"assets"))if(Json.required(e.getAsJsonObject(),"assetId").equals(assetId))selected=e.getAsJsonObject();if(selected==null)throw new ApiError(404,"evaluation_asset_mismatch","素材不属于发布评测集。");Path file=store.root.resolve("evaluation-sets").resolve(versionId).resolve("images").resolve(assetId+".png");try{if(!Files.isRegularFile(file)||!Media.hash(file).equals(Json.required(selected,"contentHash")))throw new Exception();}catch(Exception e){throw new ApiError(409,"evaluation_snapshot_corrupt","固定评测图片缺失或已被修改。");}return file;}
}
