package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.Path;
import java.nio.file.Files;
import java.sql.Connection;
import java.util.*;

final class EvaluationReruns {
    final Engine engine;final Store store;final EvaluationSets sets;
    static final Set<String> TERMINAL=Set.of("completed","completed_with_errors","cancelled");
    EvaluationReruns(Engine engine){this.engine=engine;store=engine.store;sets=new EvaluationSets(store,engine.projects);}
    record Prepared(JsonObject version,JsonArray plans,JsonArray issues,JsonObject match,String scope,long max,long planned,long estimated){}
    Prepared prepare(JsonObject p){
        JsonObject version=sets.version(Json.required(p,"setVersionId"));String scope=Json.required(p,"budgetScopeId");long max=Costs.integer(p,"maxRequests",1,1_000_000);JsonArray input=Json.array(p,"schemes");if(input.isEmpty()||input.size()>8)throw new ApiError(400,"evaluation_schemes_invalid","重跑比较需要 1～8 个完整方案。");
        JsonObject match=Json.object(p,"match").deepCopy();double iou=Json.decimal(match,"iouThreshold",0.5);if(!Double.isFinite(iou)||iou<0||iou>1||!Json.str(match,"poseNormalization","image_diagonal").equals("image_diagonal"))throw new ApiError(400,"evaluation_match_invalid","匹配阈值或关键点归一化方式无效。");match.addProperty("iouThreshold",iou);match.addProperty("poseNormalization","image_diagonal");
        Map<String,Path> paths=new HashMap<>();for(JsonElement item:Json.array(version,"assets")){JsonObject asset=item.getAsJsonObject();String aid=Json.required(asset,"assetId");paths.put(aid,sets.image(Json.required(version,"id"),aid));}
        return store.read(c->{JsonArray plans=new JsonArray(),issues=new JsonArray();long planned=(long)input.size()*Json.integer(version,"sampleCount",0),estimated=0;JsonObject budget=Store.one(c,"SELECT * FROM budgets WHERE id=?",scope);long used=budget==null?0:Json.number(budget,"used",0);
            if(budget!=null&&Json.number(budget,"max_requests",Long.MAX_VALUE)!=max&&Json.number(budget,"max_requests",Long.MAX_VALUE)!=Long.MAX_VALUE)issues.add(problem("budget_scope_conflict",null,"共享预算已有不同请求上限，请明确调整预算后重试。"));
            if(max-used<planned)issues.add(problem("evaluation_budget_insufficient",null,"剩余请求次数不能覆盖每个方案的全部样本，未省略方案。"));String currency=Json.str(Costs.view(c,scope),"currency",null);
            for(JsonElement entry:input){if(!entry.isJsonObject())throw new ApiError(400,"evaluation_schemes_invalid","每个方案必须为配置对象。");JsonObject spec=entry.getAsJsonObject();String providerId=Json.required(spec,"providerId"),model=Json.required(spec,"model"),prompt=Json.required(spec,"prompt"),runId=Json.id();JsonObject provider=Store.document(c,"providers",providerId);engine.providers.requireCredential(provider);
                int concurrency=spec.has("concurrency")?(int)Costs.integer(spec,"concurrency",1,32):1,retries=spec.has("maxRetries")?(int)Costs.integer(spec,"maxRetries",0,6):0;long runMax=spec.has("maxRequests")?Costs.integer(spec,"maxRequests",1,1_000_000):max;int samples=Json.integer(version,"sampleCount",0);if(runMax<samples)issues.add(problem("evaluation_budget_insufficient",runId,"单方案请求上限小于固定样本数。"));estimated+=(long)samples*(retries+1);
                JsonObject price=Costs.snapshot(provider,model);String unit=Json.str(price,"currency",null);if(unit!=null){if(currency!=null&&!currency.equals(unit))issues.add(problem("budget_currency_mismatch",runId,"同一比较预算不能混用币种。"));currency=unit;}String blocked=Costs.blockReason(c,scope,price);if(blocked!=null)issues.add(problem(blocked,runId,"方案受现有费用预算限制。"));
                JsonArray refs=Json.array(spec,"referenceAssetIds"),resourceSelections=Json.array(spec,"referenceResources"),references=new JsonArray();if((spec.has("referenceAssetIds")&&!spec.get("referenceAssetIds").isJsonArray())||(spec.has("referenceResources")&&!spec.get("referenceResources").isJsonArray()))throw new ApiError(400,"reference_invalid","参考素材必须为数组。");if(refs.size()+resourceSelections.size()>63||refs.size()+resourceSelections.size()+1>Json.integer(provider,"maxImages",8))throw new ApiError(422,"image_limit_exceeded","项目和资源库参考合计超过接口限制。");Set<String> seen=new HashSet<>();long referenceBytes=0;for(JsonElement ref:refs){String aid=ref.getAsString();if(!seen.add(aid))throw new ApiError(400,"reference_invalid","参考素材不能重复。");JsonObject asset=Store.document(c,"assets",aid);if(!Json.required(asset,"projectId").equals(Json.required(version,"projectId"))||!Set.of("confirmed","modified").contains(Json.str(asset,"status","")))throw new ApiError(422,"reference_invalid","参考必须是当前项目的人工标注素材。");
                    Path referencePath=engine.projects.path(aid);if(!Files.isRegularFile(referencePath)||!Media.hash(referencePath).equals(Json.required(asset,"contentHash")))throw new ApiError(409,"reference_changed","参考图片缺失或内容变化，没有创建比较。");referenceBytes+=Files.size(referencePath);
                    JsonObject reference=EvaluationSets.input(asset);for(JsonElement target:Json.array(version,"assets"))if(Evaluations.overlap(reference,target.getAsJsonObject()))issues.add(problem("evaluation_reference_overlap",runId,"参考与评测图片存在同内容或已知同源重叠。"));references.add(asset);}
                ResourceLibrary library=new ResourceLibrary(store,engine.projects);for(JsonElement selection:resourceSelections){if(!selection.isJsonObject())throw new ApiError(400,"reference_invalid","资源参考选择必须为对象。");JsonObject resolved=library.resolveReference(c,selection.getAsJsonObject(),Json.object(version,"template"));referenceBytes+=Files.size(Path.of(Json.required(resolved,"inputPath")));for(JsonElement target:Json.array(version,"assets"))if(Evaluations.overlap(EvaluationSets.input(resolved),target.getAsJsonObject()))issues.add(problem("evaluation_reference_overlap",runId,"资源参考与评测素材存在同内容或已知同源重叠。"));references.add(resolved);}
                for(Path path:paths.values())if(referenceBytes+Files.size(path)>32L*1024*1024)throw new ApiError(413,"model_images_too_large","参考与单张目标图片合计超过 32 MiB，没有创建比较。");JsonObject original=Json.object(version,"template"),settings=Json.object(original,"settings");JsonObject template=Json.obj("id",version.get("projectId"),"name",Json.str(original,"name",""),"taskType",version.get("taskType"),"classes",original.get("classes"),"settings",Json.obj("keypointNames",Json.array(settings,"keypointNames"),"keypointConnections",Json.array(settings,"keypointConnections")));
                JsonObject run=Json.obj("id",runId,"projectId",version.get("projectId"),"name",spec.has("name")?Json.required(spec,"name"):"固定输入重跑 · "+model,"status","running","createdAt",Json.now(),"updatedAt",Json.now(),"providerId",providerId,"model",model,"prompt",prompt,"concurrency",concurrency,"maxRetries",retries,"maxRequests",runMax,"total",samples,"requestsUsed",0,"retries",0,"reused",0,"plannedRequests",samples,"estimatedMaxRequests",(long)samples*(retries+1),"failurePolicy","continue","budgetScopeId",scope,"evaluationOnly",true,"setVersionId",version.get("id"),"source","fresh_run_snapshot","snapshot",Json.obj("project",template,"provider",provider,"references",references,"parserVersion","annotations-v1","validatorVersion",TaskTemplates.VALIDATOR_VERSION,"requestContractVersion",TaskTemplates.REQUEST_CONTRACT_VERSION,"credentialBindingVersion",engine.providers.credentialBindingVersion(providerId),"normalizationVersion",Media.NORMALIZATION_VERSION));
                JsonArray selected=new JsonArray();for(JsonElement item:Json.array(version,"assets")){JsonObject fixed=item.getAsJsonObject();String aid=Json.required(fixed,"assetId");Store.document(c,"assets",aid);JsonObject normalization=Json.object(fixed,"normalization"),asset=Json.obj("id",aid,"projectId",version.get("projectId"),"name",fixed.get("name"),"width",fixed.get("width"),"height",fixed.get("height"),"contentHash",fixed.get("contentHash"),"version",0,"status","unlabeled","annotations",new JsonArray(),"metadata",Json.obj("sourceHash",fixed.get("sourceHash"),"evaluationSourceGroup",fixed.get("sourceGroup"),"normalizationVersion",normalization.get("version"),"sourceToBaseline",normalization.get("sourceToBaseline"),"alphaBackground",normalization.get("alphaBackground"),"inputVersion",normalization.get("inputVersion")));
                    selected.add(Json.obj("id",Json.id(),"assetId",aid,"asset",asset,"inputPath",paths.get(aid).toString(),"baseVersion",0));}
                plans.add(Json.obj("run",run,"samples",selected));
            }return new Prepared(version,plans,issues,match,scope,max,planned,estimated);});
    }
    static JsonObject problem(String code,String scheme,String message){return Json.obj("severity","error","code",code,"schemeId",scheme,"message",message);}
    JsonObject preflight(JsonObject p){Prepared data=prepare(p);return Json.obj("canStart",data.issues.isEmpty(),"issues",data.issues,"setVersionId",data.version.get("id"),"projectId",data.version.get("projectId"),"sampleCount",data.version.get("sampleCount"),"schemeCount",data.plans.size(),"plannedRequests",data.planned,"estimatedMaxRequests",data.estimated,"budgetScopeId",data.scope,"maxRequests",data.max,"source","fresh_run_snapshot","nearDuplicateCheck","manual_review_required");}
    JsonObject create(JsonObject p){store.requireSpace(0);Prepared data=prepare(p);if(!data.issues.isEmpty())throw new ApiError(422,Json.required(data.issues.get(0).getAsJsonObject(),"code"),"重跑预检未通过，没有创建方案或发送请求。",Json.obj("issues",data.issues));String id=Json.id();
        return store.tx(c->{Budgets.ensure(c,data.scope,data.max,false);if(Json.number(Budgets.view(c,data.scope),"remaining",0)<data.planned)throw new ApiError(409,"evaluation_budget_insufficient","预检后预算已被其他调用占用，请重新检查。");JsonArray schemes=new JsonArray();
            // 所有方案与样本在一次事务提交，调度器只能看见完整比较；这里没有真值字段进入 run 或 sample。
            for(JsonElement item:data.plans){JsonObject plan=item.getAsJsonObject(),run=Json.object(plan,"run");String rid=Json.required(run,"id");Costs.reserve(c,data.scope,Costs.snapshot(Json.object(Json.object(run,"snapshot"),"provider"),Json.required(run,"model")));run.addProperty("comparisonId",id);Store.update(c,"INSERT INTO runs(id,project_id,status,data) VALUES(?,?,?,?)",rid,Json.required(run,"projectId"),"running",run);
                for(JsonElement sample:Json.array(plan,"samples")){JsonObject value=sample.getAsJsonObject();Store.update(c,"INSERT INTO samples(id,run_id,asset_id,input_id,status,data) VALUES(?,?,?,?,?,?)",Json.required(value,"id"),rid,Json.required(value,"assetId"),Json.required(value,"assetId"),"queued",value);}schemes.add(Json.obj("id",rid,"runId",rid,"name",run.get("name"),"providerId",run.get("providerId"),"model",run.get("model")));Store.event(c,"run.created",rid,null,null,Json.obj("comparisonId",id,"setVersionId",data.version.get("id"),"total",run.get("total"),"source","fresh_run_snapshot"));}
            JsonObject comparison=Json.obj("id",id,"comparisonId",id,"kind","evaluation_comparison","projectId",data.version.get("projectId"),"setVersionId",data.version.get("id"),"source","fresh_run_snapshot","status","running","schemes",schemes,"runIds",schemes.asList().stream().map(s->s.getAsJsonObject().get("runId").getAsString()).toList(),"budgetScopeId",data.scope,"maxRequests",data.max,"plannedRequests",data.planned,"estimatedMaxRequests",data.estimated,"match",data.match,"createdAt",Json.now());Store.update(c,"INSERT INTO resources(id,kind,data) VALUES(?,?,?)",id,"evaluation_comparison",comparison);Store.event(c,"evaluation_rerun.created",null,null,null,Json.obj("comparisonId",id,"runIds",comparison.get("runIds")));return comparison;});
    }
    static JsonObject record(Connection c,String id)throws Exception{JsonObject value=Store.document(c,"resources",id);if(!Json.str(value,"kind","").equals("evaluation_comparison"))throw new ApiError(404,"evaluation_comparison_missing","记录不是重跑比较。");return value;}
    JsonObject get(String id){return store.read(c->{JsonObject value=record(c,id);boolean ready=true,attention=false;for(JsonElement item:Json.array(value,"schemes")){JsonObject scheme=item.getAsJsonObject(),run=engine.runs.view(c,Json.required(scheme,"runId"),false);String status=Json.required(run,"status");scheme.addProperty("status",status);scheme.add("statistics",run.get("statistics"));ready&=TERMINAL.contains(status);attention|=Set.of("paused","needs_attention").contains(status);}if(!value.has("evaluationId"))value.addProperty("status",ready?"ready":attention?"needs_attention":"running");value.addProperty("canFinish",ready);value.add("budget",Budgets.view(c,Json.required(value,"budgetScopeId")));return value;});}
    JsonObject finish(String id)throws Exception{JsonObject comparison=get(id);if(comparison.has("evaluationId"))return new Evaluations(store,engine.projects).get(Json.required(comparison,"evaluationId"));if(!Json.bool(comparison,"canFinish",false))throw new ApiError(409,"evaluation_runs_unfinished","方案尚未全部结束；请处理暂停或未知状态，比较不会自动重跑。");return new Evaluations(store,engine.projects).createFromComparison(comparison);}
}
