package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;

final class Evaluations {
    final Store store;final EvaluationSets sets;
    Evaluations(Store store,Projects projects){this.store=store;sets=new EvaluationSets(store,projects);}
    record Prepared(JsonObject version,JsonObject match,JsonArray schemes,List<JsonObject> samples,JsonArray issues,int paired){}
    Prepared prepare(JsonObject p){JsonObject version=sets.version(Json.required(p,"setVersionId"));JsonArray inputs=Json.array(p,"schemes");if(inputs.isEmpty()||inputs.size()>8)throw new ApiError(400,"evaluation_schemes_invalid","请选择 1～8 个不重复的既有运行方案。");
        JsonObject match=Json.object(p,"match").deepCopy();double threshold=Json.decimal(match,"iouThreshold",0.5);if(!Double.isFinite(threshold)||threshold<0||threshold>1||!Json.str(match,"poseNormalization","image_diagonal").equals("image_diagonal"))throw new ApiError(400,"evaluation_match_invalid","IoU 阈值应为 0～1，关键点采用图片对角线归一化。");match.addProperty("iouThreshold",threshold);match.addProperty("poseNormalization","image_diagonal");match.addProperty("algorithmVersion",Matching.version(Json.required(version,"taskType")));match.addProperty("overlapMetric",Matching.overlapMetric(Json.required(version,"taskType")));
        return store.read(c->{JsonArray schemes=new JsonArray(),issues=new JsonArray();List<JsonObject> samples=new ArrayList<>();Set<String> seen=new HashSet<>(),paired=null;
            for(JsonElement entry:inputs){JsonObject input=entry.getAsJsonObject();String rid=Json.required(input,"runId");if(!seen.add(rid))throw new ApiError(400,"evaluation_schemes_invalid","同一运行不能重复作为比较方案。");JsonObject run=Store.document(c,"runs",rid),snapshot=Json.object(run,"snapshot"),template=Json.object(snapshot,"project");
                if(!Json.required(run,"projectId").equals(Json.required(version,"projectId"))||!compatible(template,Json.object(version,"template")))issues.add(issue("evaluation_input_mismatch",rid,null,"运行与评测集的项目、类别或点位模板不一致。"));
                for(JsonElement ref:Json.array(snapshot,"references")){JsonObject reference=EvaluationSets.input(ref.getAsJsonObject());for(JsonElement item:Json.array(version,"assets"))if(overlap(reference,item.getAsJsonObject())){issues.add(issue("evaluation_reference_overlap",rid,Json.required(item.getAsJsonObject(),"assetId"),"运行参考与评测素材存在相同内容或已知同源关系。"));break;}}
                JsonObject scheme=Json.obj("id",rid,"runId",rid,"name",Json.str(input,"name",Json.str(run,"name",rid)),"model",run.get("model"),"providerId",run.get("providerId"),"source","existing_run_snapshot","sourceRunStatus",run.get("status"),"sourceRunCreatedAt",run.get("createdAt"),"prompt",run.get("prompt"),"configurationSnapshot",snapshot,"requestsUsed",run.get("requestsUsed"),"usageScope","whole_source_run","capturedAt",Json.now(),"cost",Costs.runView(c,rid));schemes.add(scheme);Set<String> scorable=new HashSet<>();
                for(JsonElement item:Json.array(version,"assets")){JsonObject asset=item.getAsJsonObject();String aid=Json.required(asset,"assetId");JsonObject row=Store.one(c,"SELECT * FROM samples WHERE run_id=? AND asset_id=?",rid,aid);JsonObject result=Json.obj("id",Json.id(),"schemeId",rid,"runId",rid,"assetId",aid,"name",asset.get("name"),"truthVersion",Json.object(asset,"truth").get("truthVersion"),"candidateVersion",null,"status","missing","mediaUrl","autolabel-media://evaluation/"+Json.required(version,"id")+"/"+aid,"truthAnnotations",Json.object(asset,"truth").get("annotations"),"predictionAnnotations",null);
                    if(row!=null){JsonObject data=Json.parse(row.get("data").getAsString()),actual=Json.object(data,"asset");if(!sameInput(asset,EvaluationSets.input(actual)))issues.add(issue("evaluation_input_mismatch",rid,aid,"运行素材内容或规范化版本与固定评测集不一致。"));String status=Json.required(row,"status");result.addProperty("status",status.equals("failed")?"failed":status.equals("unknown")?"unknown":status.equals("cancelled")?"missing":status.equals("succeeded")?"invalid":"pending");result.add("errorCode",data.get("errorCode"));
                        if(status.equals("succeeded")){int candidate=Json.integer(data,"candidateVersion",-1);JsonObject saved=Store.one(c,"SELECT data FROM versions WHERE asset_id=? AND version=? AND source='api'",aid,candidate);if(saved!=null){JsonObject value=Json.parse(saved.get("data").getAsString());result.addProperty("candidateVersion",candidate);if(!rid.equals(Json.str(value,"runId",""))||!sameInput(asset,EvaluationSets.input(value)))issues.add(issue("evaluation_input_mismatch",rid,aid,"候选版本与运行标识或固定素材内容不一致。"));else{
                                    try{
                                        // 缺失字段不能使用空数组默认值，否则损坏的候选会被误计为成功无目标。
                                        if(!value.has("annotations")||!value.get("annotations").isJsonArray())throw new ApiError(422,"candidate_annotations_missing","候选版本缺少有效的 annotations 数组。");
                                        JsonArray annotations=Annotations.validate(Json.array(value,"annotations"),asset,Json.object(version,"template"));result.add("predictionAnnotations",annotations);result.addProperty("status","scorable");scorable.add(aid);
                                    }catch(ApiError failure){result.addProperty("status","invalid");result.addProperty("errorCode",failure.code);}}}
                            else result.addProperty("errorCode","candidate_version_missing");}
                        JsonArray attempts=new JsonArray();for(JsonObject a:Store.rows(c,"SELECT id,status,json_extract(data,'$.usage') AS usage,json_extract(data,'$.sentAt') AS sentAt,json_extract(data,'$.completedAt') AS completedAt FROM attempts WHERE run_id=? AND sample_id=? ORDER BY rowid",rid,Json.required(row,"id"))){String usage=Json.str(a,"usage",null);a.add("usage",usage==null?JsonNull.INSTANCE:JsonParser.parseString(usage));attempts.add(a);}result.add("attempts",attempts);
                    }samples.add(result);
                }if(paired==null)paired=new HashSet<>(scorable);else paired.retainAll(scorable);
            }return new Prepared(version,match,schemes,samples,issues,paired==null?0:paired.size());});
    }
    static JsonObject issue(String code,String run,String asset,String message){return Json.obj("severity","error","code",code,"runId",run,"assetId",asset,"message",message);}
    static boolean overlap(JsonObject a,JsonObject b){for(String key:List.of("contentHash","sourceHash","sourceGroup")){String x=Json.str(a,key,"");if(!x.isBlank()&&x.equals(Json.str(b,key,"")))return true;}return false;}
    static boolean sameInput(JsonObject a,JsonObject b){return Objects.equals(a.get("contentHash"),b.get("contentHash"))&&Objects.equals(a.get("width"),b.get("width"))&&Objects.equals(a.get("height"),b.get("height"))&&Objects.equals(a.get("normalization"),b.get("normalization"));}
    static boolean compatible(JsonObject a,JsonObject b){if(!Json.str(a,"taskType","").equals(Json.str(b,"taskType","")))return false;Map<String,String> ac=new TreeMap<>(),bc=new TreeMap<>();for(JsonElement e:Json.array(a,"classes")){JsonObject item=e.getAsJsonObject();ac.put(Json.required(item,"id"),Json.required(item,"name"));}for(JsonElement e:Json.array(b,"classes")){JsonObject item=e.getAsJsonObject();bc.put(Json.required(item,"id"),Json.required(item,"name"));}return ac.equals(bc)&&Json.array(Json.object(a,"settings"),"keypointNames").equals(Json.array(Json.object(b,"settings"),"keypointNames"));}
    JsonObject preflight(JsonObject p){Prepared data=prepare(p);return Json.obj("canEvaluate",data.issues.isEmpty(),"issues",data.issues,"schemes",data.schemes,"sampleCount",data.version.get("sampleCount"),"pairedComparableSamples",data.paired,"nearDuplicateCheck","manual_review_required");}
    JsonObject create(JsonObject p)throws Exception{return create(p,null);}
    JsonObject createFromComparison(JsonObject comparison)throws Exception{JsonArray schemes=new JsonArray();for(JsonElement item:Json.array(comparison,"schemes")){JsonObject scheme=item.getAsJsonObject();schemes.add(Json.obj("runId",scheme.get("runId"),"name",scheme.get("name")));}return create(Json.obj("setVersionId",comparison.get("setVersionId"),"schemes",schemes,"match",comparison.get("match")),Json.required(comparison,"id"));}
    private JsonObject create(JsonObject p,String comparisonId)throws Exception{
        store.requireSpace(0);Prepared data=prepare(p);if(!data.issues.isEmpty())throw new ApiError(422,Json.str(data.issues.get(0).getAsJsonObject(),"code","evaluation_input_mismatch"),"评测检查未通过，未生成质量指标。",Json.obj("issues",data.issues));
        Map<String,JsonObject> assets=new HashMap<>();for(JsonElement e:Json.array(data.version,"assets")){JsonObject a=e.getAsJsonObject();assets.put(Json.required(a,"assetId"),a);sets.image(Json.required(data.version,"id"),Json.required(a,"assetId"));}
        String id=Json.id();for(JsonObject result:data.samples){result.addProperty("evaluationId",id);if(!Json.required(result,"status").equals("scorable"))continue;JsonObject asset=assets.get(Json.required(result,"assetId"));try{JsonObject calculated=Matching.evaluate(Json.required(data.version,"taskType"),Json.array(result,"truthAnnotations"),Json.array(result,"predictionAnnotations"),Json.decimal(data.match,"iouThreshold",0.5),Math.hypot(Json.integer(asset,"width",1),Json.integer(asset,"height",1)));for(var field:calculated.entrySet())result.add(field.getKey(),field.getValue());}catch(ApiError error){result.addProperty("status","invalid");result.addProperty("errorCode",error.code);}}
        for(JsonElement scheme:data.schemes){JsonObject s=scheme.getAsJsonObject();List<JsonObject> selected=data.samples.stream().filter(r->Json.required(r,"schemeId").equals(Json.required(s,"id"))).toList();s.add("metrics",Matching.aggregate(Json.required(data.version,"taskType"),selected,Json.integer(data.version,"truthObjectCount",0)));if(comparisonId!=null)s.addProperty("source","fresh_run_snapshot");}
        Set<String> paired=null;for(JsonElement scheme:data.schemes){Set<String> ids=new HashSet<>();for(JsonObject row:data.samples)if(Json.required(row,"schemeId").equals(Json.required(scheme.getAsJsonObject(),"id"))&&Json.required(row,"status").equals("scorable"))ids.add(Json.required(row,"assetId"));if(paired==null)paired=ids;else paired.retainAll(ids);}
        JsonObject evaluation=Json.obj("id",id,"projectId",data.version.get("projectId"),"setVersionId",data.version.get("id"),"status","completed","source","existing_run_snapshot","taskType",data.version.get("taskType"),"sampleCount",data.version.get("sampleCount"),"schemes",data.schemes,"match",data.match,"pairedComparableSamples",paired==null?0:paired.size(),"nearDuplicateCheck","manual_review_required","createdAt",Json.now());
        if(comparisonId!=null){evaluation.addProperty("source","fresh_run_snapshot");evaluation.addProperty("comparisonId",comparisonId);}
        return store.tx(c->{if(comparisonId!=null){JsonObject comparison=EvaluationReruns.record(c,comparisonId);if(comparison.has("evaluationId"))return Store.document(c,"evaluations",Json.required(comparison,"evaluationId"));for(JsonElement item:data.schemes){JsonObject scheme=item.getAsJsonObject(),run=Store.document(c,"runs",Json.required(scheme,"runId"));if(!EvaluationReruns.TERMINAL.contains(Json.required(run,"status"))||Json.number(run,"requestsUsed",0)!=Json.number(scheme,"requestsUsed",0))throw new ApiError(409,"evaluation_runs_changed","固化期间方案状态或调用数变化，请重新检查。");}comparison.addProperty("status","completed");comparison.addProperty("evaluationId",id);comparison.addProperty("completedAt",Json.now());Store.update(c,"UPDATE resources SET data=? WHERE id=?",comparison,comparisonId);}
            Store.update(c,"INSERT INTO evaluations(id,project_id,data) VALUES(?,?,?)",id,Json.required(evaluation,"projectId"),evaluation);for(JsonObject result:data.samples)Store.update(c,"INSERT INTO evaluation_results(id,evaluation_id,scheme_id,asset_id,data) VALUES(?,?,?,?,?)",Json.required(result,"id"),id,Json.required(result,"schemeId"),Json.required(result,"assetId"),result);Store.event(c,"evaluation.completed",null,null,null,Json.obj("evaluationId",id,"setVersionId",data.version.get("id"),"source",evaluation.get("source"),"schemes",data.schemes.size()));return evaluation;});
    }
    JsonObject get(String id){return store.read(c->Store.document(c,"evaluations",id));}
    JsonArray list(String pid){return store.read(c->Store.docs(c,"SELECT data FROM evaluations WHERE project_id=? ORDER BY rowid DESC",pid));}
    JsonObject results(JsonObject p){String id=Json.required(p,"evaluationId");return store.read(c->{Store.document(c,"evaluations",id);String condition="evaluation_id=?";List<Object> args=new ArrayList<>(List.of(id));for(String key:List.of("schemeId","assetId"))if(p.has(key)){condition+=" AND "+(key.equals("schemeId")?"scheme_id":"asset_id")+"=?";args.add(Json.required(p,key));}long total=Store.one(c,"SELECT COUNT(*) AS n FROM evaluation_results WHERE "+condition,args.toArray()).get("n").getAsLong();args.add(Json.bounded(p,"limit",100,1,500));args.add(Json.bounded(p,"offset",0,0,Integer.MAX_VALUE));return Json.obj("total",total,"items",Store.docs(c,"SELECT data FROM evaluation_results WHERE "+condition+" ORDER BY rowid LIMIT ? OFFSET ?",args.toArray()));});}
}
