package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.sql.Connection;
import java.util.*;
import java.util.stream.Stream;

final class FlowPlans {
    static final Set<String> AVAILABLE=Set.of("import","filter","transform","api","local","review","export");
    static final int MAX_INPUTS=10_000;
    final Engine engine;final Store store;
    FlowPlans(Engine engine){this.engine=engine;store=engine.store;}
    record Step(JsonObject definition,JsonObject snapshot,int position,boolean scheduled){}
    record Plan(String id,JsonObject request,JsonObject project,List<JsonObject> input,List<Step> steps,JsonArray issues,JsonArray preview,String scope,long max,Long planned,Long estimated){}
    static JsonObject capabilities(){return Json.obj("definitionVersion",1,"availableSteps",Json.arr("import","filter","transform","api","local","review","export"),"unavailableSteps",new JsonArray(),"maxSteps",30,"viewReuse",true);}
    static void keys(JsonObject value,String... allowed){Set<String> names=Set.of(allowed);for(String name:value.keySet())if(!names.contains(name))throw new ApiError(400,"flow_parameter_unknown","不支持的流程参数："+name);}
    static String string(JsonObject p,String name,int max){JsonElement value=p.get(name);if(value==null||!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isString())throw new ApiError(400,"flow_parameter_missing","请填写流程参数："+name);String text=value.getAsString().strip();if(text.isEmpty()||text.length()>max)throw new ApiError(400,"flow_parameter_invalid","流程参数为空或过长："+name);return text;}
    static void bool(JsonObject p,String field){if(p.has(field)&&(!p.get(field).isJsonPrimitive()||!p.get(field).getAsJsonPrimitive().isBoolean()))throw new ApiError(400,"flow_parameter_invalid",field+" 必须为布尔值。");}
    static Set<String> ids(JsonObject p,String field,int max,boolean empty){
        if(!p.has(field)||!p.get(field).isJsonArray())throw new ApiError(400,"flow_parameter_invalid",field+" 必须为数组。");JsonArray values=p.getAsJsonArray(field);if(values.size()>max||(!empty&&values.isEmpty()))throw new ApiError(400,"flow_input_limit",field+" 数量超出范围。");Set<String> result=new LinkedHashSet<>();for(JsonElement value:values){if(!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isString()||value.getAsString().isBlank()||value.getAsString().length()>128||!result.add(value.getAsString()))throw new ApiError(400,"flow_parameter_invalid",field+" 存在无效或重复标识。");}return result;
    }
    static void issue(JsonArray issues,String step,ApiError error){JsonObject issue=Json.obj("code",error.code,"message",error.getMessage(),"severity","error");if(step!=null)issue.addProperty("stepId",step);issues.add(issue);}
    Plan prepare(JsonObject request,int from)throws Exception{
        keys(request,"projectId","definition","input","execution","budgetScopeId","maxRequests","failurePolicy");for(String field:List.of("definition","input","execution"))if(request.has(field)&&!request.get(field).isJsonObject())throw new ApiError(400,"flow_parameter_invalid",field+" 必须为对象。");String pid=string(request,"projectId",128),id=Json.id();JsonObject definition=Json.object(request,"definition");keys(definition,"version","name","steps");if(!Json.element(1).equals(definition.get("version"))||!definition.has("steps")||!definition.get("steps").isJsonArray()||Json.array(definition,"steps").isEmpty()||Json.array(definition,"steps").size()>30)throw new ApiError(400,"flow_definition_invalid","流程应为版本 1，并包含 1～30 个步骤。");string(definition,"name",200);
        JsonObject execution=Json.object(request,"execution");keys(execution,"mode","stepId");String mode=Json.str(execution,"mode","all");if(!Set.of("all","single").contains(mode)||(mode.equals("all")&&execution.has("stepId")))throw new ApiError(400,"flow_execution_invalid","执行模式应为全部或一个明确步骤。");String single=mode.equals("single")?string(execution,"stepId",128):null;
        String policy=Json.str(request,"failurePolicy","continue");if(!Set.of("continue","pause").contains(policy))throw new ApiError(400,"flow_parameter_invalid","失败策略应为 continue 或 pause。");String scope=request.has("budgetScopeId")?string(request,"budgetScopeId",128):id;long max=request.has("maxRequests")?Costs.integer(request,"maxRequests",1,1_000_000):0;
        return store.read(c->{JsonObject project=Store.document(c,"projects",pid);JsonArray issues=new JsonArray(),preview=new JsonArray();List<JsonObject> input=input(c,request,pid),working=new ArrayList<>();for(JsonObject item:input)working.add(item.deepCopy());List<Step> steps=new ArrayList<>();Set<String> seen=new HashSet<>();boolean first=true,exported=false,singleFound=single==null,uncertain=false;Long planned=0L,estimated=0L;int position=0;boolean hasApi=false;
            for(JsonElement element:Json.array(definition,"steps")){
                if(!element.isJsonObject())throw new ApiError(400,"flow_definition_invalid","每个步骤必须为对象。");JsonObject step=element.getAsJsonObject();keys(step,"id","kind","enabled","parameters");String sid=string(step,"id",128),kind=string(step,"kind",32);if(!sid.matches("[A-Za-z0-9_.-]{1,128}")||!seen.add(sid))throw new ApiError(400,"flow_step_id_invalid","步骤标识格式无效或重复。");if(!step.has("enabled"))throw new ApiError(400,"flow_definition_invalid","每个步骤必须明确 enabled 状态。");bool(step,"enabled");boolean enabled=Json.bool(step,"enabled",false),scheduled=enabled&&position>=from&&(single==null||single.equals(sid));if(single!=null&&single.equals(sid)){singleFound=true;if(!enabled)issue(issues,sid,new ApiError(422,"flow_step_disabled","不能单步执行已禁用节点。"));if(!first&&!Json.str(Json.object(request,"input"),"source","").equals("artifact"))issue(issues,sid,new ApiError(422,"flow_single_input_required","非首节点单步执行必须选择明确的上游固定产物。"));}
                if(step.has("parameters")&&!step.get("parameters").isJsonObject())throw new ApiError(400,"flow_parameter_invalid","步骤参数必须为对象。");JsonObject snapshot=Json.obj("project",project.deepCopy()),parameters=Json.object(step,"parameters");int inputCount=(int)working.stream().filter(FlowArtifacts::included).count();Long stepCalls=0L;
                if(enabled){if(!AVAILABLE.contains(kind))issue(issues,sid,new ApiError(422,"flow_step_unavailable","该步骤尚未实现："+kind));if(exported)issue(issues,sid,new ApiError(422,"flow_after_export","导出必须为最后一个启用节点。"));if(kind.equals("import")&&!first)issue(issues,sid,new ApiError(422,"flow_import_order","导入只能为第一个启用节点。"));if(kind.equals("export"))exported=true;}
                try{
                    validateParameters(kind,parameters);
                    if(scheduled&&AVAILABLE.contains(kind)){
                        if(kind.equals("api"))hasApi=true;if(Set.of("api","local","review","export").contains(kind)&&Json.array(project,"classes").isEmpty())throw new ApiError(422,"classes_required","请先配置标注类别。");
                        if(Set.of("api","local","review","export").contains(kind)&&Json.str(project,"taskType","").equals("pose")&&Json.array(Json.object(project,"settings"),"keypointNames").isEmpty())throw new ApiError(422,"flow_pose_template_missing","Pose 流程必须配置固定关键点名称与顺序。");
                        switch(kind){
                            case "import"->{JsonArray files=importFiles(parameters);snapshot.add("importFiles",files);int videoCount=0;if(parameters.has("mediaJobId")){JsonObject job=Store.document(c,"media_jobs",string(parameters,"mediaJobId",100));if(!Json.required(job,"projectId").equals(pid)||!Json.required(job,"kind").equals("video_extract")||!Json.bool(job,"artifactCommitted",false))throw new ApiError(422,"flow_media_not_ready","请选择当前项目已完整提交的抽帧产物。");videoCount=Json.integer(Json.object(job,"summary"),"frameCount",0);snapshot.add("mediaJob",Json.obj("id",job.get("id"),"manifestHash",job.get("manifestHash"),"completeHash",job.get("completeHash"),"frameCount",videoCount));}if(input.size()+files.size()+videoCount>MAX_INPUTS)throw new ApiError(413,"flow_input_limit","现有输入与待导入文件清单合计最多 10000 项。");if(!files.isEmpty()||videoCount>0)uncertain=true;}
                            case "filter"->{if(!uncertain){if(parameters.has("screening")&&working.stream().anyMatch(item->FlowArtifacts.included(item)&&Json.str(Json.object(item,"inputSnapshot"),"kind","").equals("view")))throw new ApiError(422,"screening_baseline_required","近重复和模糊筛选应放在裁剪、缩放或切片之前，对固定基准图执行。");if(Json.bool(parameters,"deduplicate",false)&&working.stream().anyMatch(item->FlowArtifacts.included(item)&&!item.has("contentHash")))uncertain=true;else working=filter(working,parameters);}}
                            case "transform"->{if(!uncertain){JsonObject transformPlans=new JsonObject();working=FlowTransforms.plan(working,parameters,transformPlans,null);snapshot.add("transformPlans",transformPlans);}}
                            case "local"->{snapshot.add("local",engine.localRuntime.freeze(parameters,project));for(JsonObject item:working)if(FlowArtifacts.included(item))item.addProperty("willAnnotate",true);}
                            case "api"->{hasApi=true;String providerId=string(parameters,"providerId",128),model=string(parameters,"model",1000);string(parameters,"prompt",100000);JsonObject provider=Store.document(c,"providers",providerId);engine.providers.requireCredential(provider);requireCapabilities(provider,model,parameters);JsonArray refs=references(c,parameters,project,provider,working);snapshot.add("provider",provider);snapshot.add("references",refs);snapshot.addProperty("credentialBindingVersion",engine.providers.credentialBindingVersion(providerId));snapshot.addProperty("parserVersion","annotations-v1");snapshot.addProperty("validatorVersion",TaskTemplates.VALIDATOR_VERSION);snapshot.addProperty("requestContractVersion",TaskTemplates.REQUEST_CONTRACT_VERSION);String costReason=Costs.blockReason(c,scope,Costs.snapshot(provider,model));if(costReason!=null)throw new ApiError(422,costReason,"该标注节点受到费用预算限制。");stepCalls=uncertain?null:(long)inputCount;if(stepCalls==null){planned=null;estimated=null;}else{if(planned!=null)planned+=stepCalls;if(estimated!=null)estimated+=stepCalls*(Json.integer(parameters,"maxRetries",Json.integer(provider,"maxRetries",2))+1);}for(JsonObject item:working)if(FlowArtifacts.included(item))item.addProperty("willAnnotate",true);}
                            case "review","export"->{if(kind.equals("export"))string(parameters,"outputDir",32767);if(!uncertain)for(JsonObject item:working)if(FlowArtifacts.included(item)&&!Json.bool(item,"willAnnotate",false)&&(item.get("selectedVersion")==null||item.get("selectedVersion").isJsonNull()))throw new ApiError(422,"flow_annotations_required","当前输入没有明确标注，也没有已执行或上游标注步骤。");}
                        }
                        if(!kind.equals("import")&&!uncertain&&inputCount==0)throw new ApiError(422,"flow_input_empty","该步骤没有可处理的固定输入。");
                    }
                }catch(ApiError error){issue(issues,sid,error);}catch(java.io.IOException|InvalidPathException error){issue(issues,sid,new ApiError(400,"flow_input_unavailable","无法读取已选择的流程输入，请检查文件和目录权限。"));}
                steps.add(new Step(step.deepCopy(),snapshot,position++,scheduled));preview.add(Json.obj("stepId",sid,"kind",kind,"enabled",enabled,"inputCount",uncertain?null:inputCount,"plannedRequests",kind.equals("api")&&scheduled?(Object)stepCalls:0));if(enabled)first=false;
            }
            if(!singleFound)issue(issues,null,new ApiError(422,"flow_step_missing","指定的单步节点不存在。"));if(steps.stream().noneMatch(Step::scheduled))issue(issues,null,new ApiError(422,"flow_empty","没有需要执行的启用步骤。"));if(hasApi&&max==0)issue(issues,null,new ApiError(400,"flow_budget_required","请设置本次流程的共享请求上限。"));
            if(max>0){JsonObject budget=Store.one(c,"SELECT max_requests FROM budgets WHERE id=?",scope);if(budget!=null&&Json.number(budget,"max_requests",Long.MAX_VALUE)!=Long.MAX_VALUE&&Json.number(budget,"max_requests",0)!=max)issue(issues,null,new ApiError(409,"budget_scope_conflict","共享预算上限与现有会话不同，请先明确调整预算。"));}
            if(input.isEmpty()&&steps.stream().noneMatch(step->step.scheduled&&Json.required(step.definition,"kind").equals("import")&&(!Json.array(step.snapshot,"importFiles").isEmpty()||step.snapshot.has("mediaJob"))))issue(issues,null,new ApiError(422,"flow_input_empty","请选择素材或在首步提供待导入文件。"));
            return new Plan(id,request.deepCopy(),project,input,steps,issues,preview,scope,max,planned,estimated);
        });
    }
    List<JsonObject> input(Connection c,JsonObject p,String pid)throws Exception{
        JsonObject input=Json.object(p,"input");keys(input,"source","selection","assetIds","artifactId");String source=string(input,"source",32);if(source.equals("artifact")){if(input.has("selection")||input.has("assetIds"))throw new ApiError(400,"flow_input_invalid","产物输入不能同时指定项目选图参数。");String id=string(input,"artifactId",128);JsonObject artifact=FlowArtifacts.requireComplete(c,id,pid);if(Json.str(artifact,"kind","").equals("export"))throw new ApiError(422,"flow_input_incompatible","导出目录不能作为图像步骤输入。");List<JsonObject> items=FlowArtifacts.items(c,id);for(JsonObject item:items)item.addProperty("sourceArtifactId",id);return items;}
        if(!source.equals("project")||input.has("artifactId"))throw new ApiError(400,"flow_input_invalid","请选择项目素材或固定流程产物。");String selection=string(input,"selection",32);if(!Set.of("all","unlabeled","explicit").contains(selection))throw new ApiError(400,"flow_input_invalid","项目输入范围无效。");Set<String> wanted=selection.equals("explicit")?ids(input,"assetIds",MAX_INPUTS,false):Set.of();if(!selection.equals("explicit")&&input.has("assetIds"))throw new ApiError(400,"flow_input_invalid","只有明确选图模式可以提供 assetIds。");List<Object> arguments=new ArrayList<>();arguments.add(pid);String sql="SELECT data,path FROM assets WHERE project_id=?";if(selection.equals("explicit")){sql+=" AND id IN ("+String.join(",",Collections.nCopies(wanted.size(),"?"))+")";arguments.addAll(wanted);}else if(selection.equals("unlabeled"))sql+=" AND json_extract(data,'$.status')='unlabeled'";sql+=" ORDER BY rowid LIMIT 10001";List<JsonObject> items=new ArrayList<>();for(JsonObject row:Store.rows(c,sql,arguments.toArray())){JsonObject asset=Json.parse(row.get("data").getAsString());items.add(FlowArtifacts.assetItem(c,asset,Json.required(row,"path")));if(items.size()>MAX_INPUTS)throw new ApiError(413,"flow_input_limit","单次流程最多固定 10000 张输入。");}if(selection.equals("explicit")&&items.size()!=wanted.size())throw new ApiError(422,"flow_input_project_mismatch","部分素材不属于当前项目。");return items;
    }
    static void validateParameters(String kind,JsonObject p){
        switch(kind){
            case "import"->{keys(p,"paths","mode","mediaJobId");if(p.has("mediaJobId")){string(p,"mediaJobId",100);if(p.has("paths")||p.has("mode"))throw new ApiError(400,"flow_parameter_invalid","视频产物导入不能同时提供文件路径或导入模式。");}if(p.has("paths")){if(!p.get("paths").isJsonArray()||Json.array(p,"paths").size()>MAX_INPUTS)throw new ApiError(400,"flow_input_limit","导入路径最多 10000 项。");for(JsonElement value:Json.array(p,"paths"))string(Json.obj("path",value),"path",32767);}if(!Set.of("copy","reference").contains(Json.str(p,"mode","copy")))throw new ApiError(400,"import_mode_invalid","导入方式应为 copy 或 reference。");}
            case "filter"->{keys(p,"assetIds","statuses","minWidth","minHeight","maxWidth","maxHeight","deduplicate","screening","excludeAssetIds");if(p.has("assetIds"))ids(p,"assetIds",MAX_INPUTS,false);if(p.has("excludeAssetIds"))ids(p,"excludeAssetIds",MAX_INPUTS,true);if(p.has("screening")){if(!p.get("screening").isJsonObject())throw new ApiError(400,"flow_parameter_invalid","screening 必须为对象。");MediaJobs.screeningParameters(Json.object(p,"screening"));}if(p.has("statuses")){Set<String> statuses=ids(p,"statuses",6,true);if(!Set.of("unlabeled","candidate","modified","confirmed","invalid","missing").containsAll(statuses))throw new ApiError(400,"flow_parameter_invalid","素材状态筛选无效。");}for(String field:List.of("minWidth","minHeight","maxWidth","maxHeight"))if(p.has(field))Costs.integer(p,field,1,100000);for(String axis:List.of("Width","Height"))if(Json.integer(p,"min"+axis,1)>Json.integer(p,"max"+axis,100000))throw new ApiError(400,"flow_parameter_invalid","最小尺寸不能大于最大尺寸。");bool(p,"deduplicate");}
            case "api"->{keys(p,"providerId","model","prompt","referenceAssetIds","referenceResources","concurrency","maxRetries","maxRequests","reuseEnabled","forceRerun","reuseMaxAgeSeconds");Runs.validateReuse(p);if(p.has("providerId"))string(p,"providerId",128);if(p.has("model"))string(p,"model",1000);if(p.has("prompt"))string(p,"prompt",100000);if(p.has("concurrency"))Costs.integer(p,"concurrency",1,32);if(p.has("maxRetries"))Costs.integer(p,"maxRetries",0,6);if(p.has("maxRequests"))Costs.integer(p,"maxRequests",1,1000000);if(p.has("referenceAssetIds"))ids(p,"referenceAssetIds",63,true);if(p.has("referenceResources")){if(!p.get("referenceResources").isJsonArray()||Json.array(p,"referenceResources").size()>63)throw new ApiError(400,"reference_invalid","参考资源数量无效。");for(JsonElement value:Json.array(p,"referenceResources")){if(!value.isJsonObject())throw new ApiError(400,"reference_invalid","参考选择应为对象。");JsonObject ref=value.getAsJsonObject();keys(ref,"resourceId","version","classMap");string(ref,"resourceId",128);if(ref.has("version"))Costs.integer(ref,"version",0,Integer.MAX_VALUE);if(ref.has("classMap")){if(!ref.get("classMap").isJsonObject())throw new ApiError(400,"reference_class_map_invalid","类别映射必须为对象。");for(var entry:ref.getAsJsonObject("classMap").entrySet())string(Json.obj("id",entry.getValue()),"id",128);}}}}
            case "transform"->FlowTransforms.validate(p);
            case "local"->LocalRuntime.validateParameters(p);
            case "review"->{keys(p,"buildIssues","randomSample","waitForHuman");bool(p,"buildIssues");bool(p,"waitForHuman");if(p.has("randomSample")){JsonObject random=Json.object(p,"randomSample");keys(random,"count","seed");Costs.integer(random,"count",1,1000);string(random,"seed",256);}}
            case "export"->{keys(p,"outputDir","trainRatio","onlyConfirmed","annotationSelection");if(p.has("outputDir"))string(p,"outputDir",32767);if(p.has("trainRatio")){if(!p.get("trainRatio").isJsonPrimitive()||!p.getAsJsonPrimitive("trainRatio").isNumber())throw new ApiError(400,"split_ratio_invalid","训练集比例必须为数值。");double value=Json.decimal(p,"trainRatio",0);if(!Double.isFinite(value)||value<=0||value>=1)throw new ApiError(400,"split_ratio_invalid","训练集比例必须在 0 与 1 之间。");}bool(p,"onlyConfirmed");if(!Set.of("protected","candidate").contains(Json.str(p,"annotationSelection","protected")))throw new ApiError(400,"flow_parameter_invalid","导出版本选择无效。");}
            default->{if(!Set.of("local","transform").contains(kind))throw new ApiError(400,"flow_step_unknown","未知流程步骤。");}
        }
    }
    static JsonArray importFiles(JsonObject parameters)throws Exception{
        LinkedHashSet<Path> files=new LinkedHashSet<>();for(JsonElement value:Json.array(parameters,"paths")){Path path=Path.of(value.getAsString()).toAbsolutePath().normalize();if(Files.isDirectory(path)){try(Stream<Path> walk=Files.walk(path,12)){for(Path file:walk.filter(Files::isRegularFile).filter(f->f.toString().toLowerCase(Locale.ROOT).matches(".*\\.(jpe?g|png)$")).limit(MAX_INPUTS+1).sorted().toList()){files.add(file);if(files.size()>MAX_INPUTS)throw new ApiError(413,"flow_input_limit","展开后最多导入 10000 张图片。");}}}else files.add(path);if(files.size()>MAX_INPUTS)throw new ApiError(413,"flow_input_limit","展开后最多导入 10000 张图片。");}
        JsonArray result=new JsonArray();for(Path file:files){if(!Files.isRegularFile(file))throw new ApiError(400,"file_missing","待导入图片不存在。");if(Files.size(file)>Media.MAX_FILE)throw new ApiError(413,"image_too_large","待导入图片超过 128 MiB。");result.add(Json.obj("sourcePath",file.toString(),"sourceHash",Media.hash(file),"name",file.getFileName().toString(),"importAssetId",Json.id()));}return result;
    }
    static List<JsonObject> filter(List<JsonObject> items,JsonObject p){
        Set<String> wanted=p.has("assetIds")?ids(p,"assetIds",MAX_INPUTS,false):null,statuses=p.has("statuses")?ids(p,"statuses",6,true):null,excluded=p.has("excludeAssetIds")?ids(p,"excludeAssetIds",MAX_INPUTS,true):Set.of(),available=new HashSet<>();for(JsonObject item:items)if(FlowArtifacts.included(item))available.add(Json.required(item,"assetId"));if(wanted!=null&&!available.containsAll(wanted)||!available.containsAll(excluded))throw new ApiError(422,"flow_filter_outside_input","筛选素材不属于该步骤输入范围。");
        List<JsonObject> output=new ArrayList<>();for(JsonObject original:items){JsonObject item=original.deepCopy();if(FlowArtifacts.included(item)){JsonObject asset=Json.object(item,"asset");String aid=Json.required(item,"assetId");boolean include=!excluded.contains(aid)&&(wanted==null||wanted.contains(aid))&&(statuses==null||statuses.contains(Json.str(item,"status",Json.str(asset,"status","unlabeled"))))&&Json.integer(item,"width",0)>=Json.integer(p,"minWidth",1)&&Json.integer(item,"width",0)<=Json.integer(p,"maxWidth",100000)&&Json.integer(item,"height",0)>=Json.integer(p,"minHeight",1)&&Json.integer(item,"height",0)<=Json.integer(p,"maxHeight",100000);if(!include){item.addProperty("outcome","excluded");item.addProperty("reason",excluded.contains(aid)?"manual_exclusion":"filter_condition");}}output.add(item);}
        if(Json.bool(p,"deduplicate",false)){Set<String> hashes=new HashSet<>();for(JsonObject item:output)if(FlowArtifacts.included(item)&&Json.bool(item,"manualProtected",false))hashes.add(Json.required(item,"contentHash"));for(JsonObject item:output)if(FlowArtifacts.included(item)&&!Json.bool(item,"manualProtected",false)&&!hashes.add(Json.required(item,"contentHash"))){item.addProperty("outcome","excluded");item.addProperty("reason","duplicate_content");}}return output;
    }
    static void requireCapabilities(JsonObject provider,String model,JsonObject p){JsonObject saved=Json.object(Json.object(provider,"capabilities"),model);for(String capability:Json.array(p,"referenceAssetIds").size()+Json.array(p,"referenceResources").size()>0?List.of("image","multiImage","structured"):List.of("image","structured")){JsonObject test=Json.object(saved,capability);if(!Json.str(test,"status","").equals("verified")||Json.integer(test,"revision",-1)!=Json.integer(provider,"revision",0))throw new ApiError(422,"flow_model_capability_unverified","请先验证该模型的图片及结构化输出能力："+capability);}}
    JsonArray references(Connection c,JsonObject p,JsonObject project,JsonObject provider,List<JsonObject> input)throws Exception{
        JsonArray refs=new JsonArray();Set<String> targetIds=new HashSet<>();for(JsonObject item:input)if(FlowArtifacts.included(item))targetIds.add(Json.required(item,"assetId"));for(JsonElement value:Json.array(p,"referenceAssetIds")){JsonObject asset=Store.document(c,"assets",value.getAsString());if(!Json.required(asset,"projectId").equals(Json.required(project,"id"))||!Set.of("modified","confirmed").contains(Json.str(asset,"status","")))throw new ApiError(422,"reference_invalid","参考必须为当前项目已保存的人工标注。");if(targetIds.contains(Json.required(asset,"id")))throw new ApiError(422,"reference_target_overlap","参考与流程目标输入不能重叠。");refs.add(asset);}
        ResourceLibrary library=new ResourceLibrary(store,engine.projects);for(JsonElement value:Json.array(p,"referenceResources")){if(!value.isJsonObject())throw new ApiError(400,"reference_invalid","参考选择应为对象。");JsonObject ref=library.resolveReference(c,value.getAsJsonObject(),project);if(targetIds.contains(Json.required(ref,"id")))throw new ApiError(422,"reference_target_overlap","参考源素材与流程目标不能重叠。");refs.add(ref);}if(refs.size()>63||refs.size()+1>Json.integer(provider,"maxImages",8))throw new ApiError(422,"image_limit_exceeded","参考加目标图片超过接口限制。");return refs;
    }
    JsonObject preflight(JsonObject p)throws Exception{Plan plan=prepare(p,0);return Json.obj("canStart",plan.issues.isEmpty(),"issues",plan.issues,"projectId",plan.project.get("id"),"inputCount",plan.input.size(),"plannedRequests",plan.planned,"estimatedMaxRequests",plan.estimated,"manualProtectedCount",plan.input.stream().filter(item->Json.bool(item,"manualProtected",false)).count(),"steps",plan.preview,"availableSteps",capabilities().get("availableSteps"));}
}
