package cn.autolabel.engine;

import com.google.gson.*;
import java.sql.Connection;
import java.util.*;
import java.util.concurrent.*;

final class Flows implements AutoCloseable {
    static final Set<String> TERMINAL=Set.of("completed","completed_with_errors","failed","cancelled");
    static final Set<String> DONE_STEPS=Set.of("completed","completed_with_errors","skipped");
    final Engine engine;final Store store;final FlowPlans plans;final FlowNodes nodes;
    private final ThreadPoolExecutor files=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(1),Thread.ofPlatform().name("flow-file-",0).factory(),new ThreadPoolExecutor.AbortPolicy());
    private volatile boolean closed;
    private final Set<String> pendingAggregation=ConcurrentHashMap.newKeySet();
    void aggregatePending(String runId){if(closed||files.getActiveCount()+files.getQueue().size()>0||!pendingAggregation.add(runId))return;try{files.execute(()->{try{for(JsonObject row:store.read(c->Store.rows(c,"SELECT asset_id FROM run_baselines WHERE run_id=?",runId)))engine.runResults.aggregate(runId,Json.required(row,"asset_id"));}catch(Exception error){System.err.println("input_aggregation_pending");}finally{pendingAggregation.remove(runId);}});}catch(RejectedExecutionException error){pendingAggregation.remove(runId);}}
    Flows(Engine engine){this.engine=engine;store=engine.store;plans=new FlowPlans(engine);nodes=new FlowNodes(this);recover();}
    void recover(){store.tx(c->{for(JsonObject row:Store.rows(c,"SELECT data FROM flow_runs WHERE status IN ('queued','running','pausing','cancelling')")){JsonObject flow=Json.parse(row.get("data").getAsString());boolean cancelled=Json.str(flow,"status","").equals("cancelling");flow.addProperty("status",cancelled?"cancelled":"paused");flow.addProperty("pauseReason","restart_review");saveFlow(c,flow);Store.flowEvent(c,"flow.recovered",Json.required(flow,"id"),null,null,null,null,Json.obj("status",flow.get("status")));}
        for(JsonObject row:Store.rows(c,"SELECT data FROM flow_steps WHERE status='running' OR json_extract(data,'$.workerActive')=1")){JsonObject step=Json.parse(row.get("data").getAsString());step.addProperty("workerActive",false);step.addProperty("status","paused");saveStep(c,step);}Store.update(c,"UPDATE flow_artifact_items SET data=json_set(data,'$.workStatus','queued') WHERE json_extract(data,'$.workStatus')='running' AND artifact_id IN (SELECT id FROM flow_artifacts WHERE json_extract(data,'$.status')='building')");return null;});}
    JsonObject create(JsonObject p)throws Exception{FlowPlans.Plan plan=plans.prepare(p,0);requirePlan(plan);return store.tx(c->insert(c,plan,null,0));}
    static void requirePlan(FlowPlans.Plan plan){if(!plan.issues().isEmpty())throw new ApiError(422,"flow_preflight_failed","流程预检未通过，没有启动步骤。",Json.obj("issues",plan.issues()));}
    JsonObject insert(Connection c,FlowPlans.Plan plan,JsonObject source,int from)throws Exception{
        JsonObject definition=Json.object(plan.request(),"definition"),flow=Json.obj("id",plan.id(),"projectId",plan.project().get("id"),"name",definition.get("name"),"revision",source==null?1:Json.integer(source,"revision",1)+1,"status","queued","createdAt",Json.now(),"updatedAt",Json.now(),"definition",definition,"request",plan.request(),"failurePolicy",Json.str(plan.request(),"failurePolicy","continue"),"snapshot",Json.obj("project",plan.project()),"inputCount",plan.input().stream().filter(item->item.has("assetId")).map(item->Json.required(item,"assetId")).distinct().count(),"inputViews",plan.input().stream().filter(item->Json.str(Json.object(item,"inputSnapshot"),"kind","").equals("view")).count());
        if(source!=null)flow.add("sourceFlowRunId",source.get("id"));if(plan.max()>0){Budgets.ensure(c,plan.scope(),plan.max(),false);flow.addProperty("budgetScopeId",plan.scope());flow.addProperty("maxRequests",plan.max());}
        Store.update(c,"INSERT INTO flow_runs(id,project_id,status,data) VALUES(?,?,?,?)",plan.id(),Json.required(flow,"projectId"),"queued",flow);String input=FlowArtifacts.create(c,flow,null,"assets",plan.input(),true);flow.addProperty("inputArtifactId",input);
        for(FlowPlans.Step prepared:plan.steps()){JsonObject spec=prepared.definition();String sid=Json.required(spec,"id");JsonObject step=Json.obj("id",Json.id(),"flowRunId",plan.id(),"stepId",sid,"kind",spec.get("kind"),"order",prepared.position(),"enabled",Json.bool(spec,"enabled",false),"status",prepared.scheduled()?"pending":"skipped","parameters",Json.object(spec,"parameters"),"snapshot",prepared.snapshot(),"statistics",FlowArtifacts.statistics());
            if(source!=null&&prepared.position()<from&&Json.bool(spec,"enabled",false)){JsonObject old=step(c,Json.required(source,"id"),sid);if(!DONE_STEPS.contains(Json.required(old,"status"))||!old.has("outputArtifactId"))throw new ApiError(409,"flow_upstream_unfinished","需要继承的上游步骤尚未完成。");String artifact=Json.required(old,"outputArtifactId");FlowArtifacts.requireComplete(c,artifact,Json.required(flow,"projectId"));step.addProperty("status","completed");step.addProperty("outputArtifactId",artifact);step.add("statistics",old.get("statistics"));step.add("inheritedFrom",Json.obj("flowRunId",source.get("id"),"stepId",sid,"artifactId",artifact));}
            Store.update(c,"INSERT INTO flow_steps(id,flow_run_id,step_id,position,status,data) VALUES(?,?,?,?,?,?)",Json.required(step,"id"),plan.id(),sid,prepared.position(),Json.required(step,"status"),step);
        }
        saveFlow(c,flow);Store.flowEvent(c,"flow.created",plan.id(),null,null,null,null,Json.obj("inputCount",plan.input().size(),"revision",flow.get("revision")));return view(c,plan.id());
    }
    static JsonObject step(Connection c,String flow,String step)throws Exception{JsonObject row=Store.one(c,"SELECT data FROM flow_steps WHERE flow_run_id=? AND step_id=?",flow,step);if(row==null)throw new ApiError(404,"flow_step_missing","流程步骤不存在。");return Json.parse(row.get("data").getAsString());}
    static List<JsonObject> steps(Connection c,String flow)throws Exception{List<JsonObject> result=new ArrayList<>();for(JsonObject row:Store.rows(c,"SELECT data FROM flow_steps WHERE flow_run_id=? ORDER BY position",flow))result.add(Json.parse(row.get("data").getAsString()));return result;}
    static void saveStep(Connection c,JsonObject step)throws Exception{Store.update(c,"UPDATE flow_steps SET status=?,child_run_id=?,data=? WHERE id=?",Json.required(step,"status"),Json.str(step,"childRunId",null),step,Json.required(step,"id"));}
    static void saveFlow(Connection c,JsonObject flow)throws Exception{flow.addProperty("updatedAt",Json.now());Store.update(c,"UPDATE flow_runs SET status=?,data=? WHERE id=?",Json.required(flow,"status"),flow,Json.required(flow,"id"));}
    JsonObject view(Connection c,String id)throws Exception{
        JsonObject flow=Store.document(c,"flow_runs",id),result=new JsonObject();for(String field:List.of("id","projectId","name","revision","sourceFlowRunId","status","pauseReason","createdAt","updatedAt","completedAt","definition","inputArtifactId","budgetScopeId"))if(flow.has(field))result.add(field,flow.get(field));
        int total=0,completed=0,failed=0,output=Json.integer(flow,"inputCount",0);long requests=0,reused=0;int inputViews=Json.integer(flow,"inputViews",0),inputAssets=Json.integer(flow,"inputCount",0);JsonArray visible=new JsonArray();for(JsonObject step:steps(c,id)){JsonObject value=new JsonObject();for(String field:List.of("stepId","kind","order","status","enabled","inputArtifactId","outputArtifactId","childRunId","startedAt","completedAt","errorCode","message","statistics","inheritedFrom"))if(step.has(field))value.add(field,step.get(field));if(Json.required(step,"kind").equals("local")){JsonObject local=Json.object(Json.object(step,"snapshot"),"local"),model=Json.object(local,"model");if(!model.isEmpty())value.add("local",Json.obj("modelId",model.get("id"),"modelVersion",model.get("version"),"device",local.get("requestedDevice")));}visible.add(value);String status=Json.required(step,"status");if(!status.equals("skipped"))total++;if(Set.of("completed","completed_with_errors").contains(status))completed++;if(Set.of("failed","completed_with_errors").contains(status))failed++;if(step.has("outputArtifactId")){JsonObject artifact=Store.document(c,"flow_artifacts",Json.required(step,"outputArtifactId"));output=Json.integer(Store.one(c,"SELECT COUNT(DISTINCT asset_id) AS n FROM flow_artifact_items WHERE artifact_id=? AND outcome='included'",Json.required(step,"outputArtifactId")),"n",0);if(Json.required(step,"kind").equals("import"))inputAssets=Math.max(inputAssets,Json.integer(Store.one(c,"SELECT COUNT(DISTINCT asset_id) AS n FROM flow_artifact_items WHERE artifact_id=?",Json.required(step,"outputArtifactId")),"n",0));if(Set.of("views","view_annotations").contains(Json.required(artifact,"kind")))inputViews=Math.max(inputViews,Json.integer(artifact,"total",0));}if(step.has("childRunId")){JsonObject child=Store.document(c,"runs",Json.required(step,"childRunId"));requests+=Json.number(child,"requestsUsed",0);reused+=Json.number(child,"reused",0);}}
        result.add("steps",visible);result.add("statistics",Json.obj("stepsTotal",total,"stepsCompleted",completed,"stepsFailed",failed,"inputAssets",inputAssets,"inputViews",inputViews,"outputAssets",output,"requestsUsed",requests,"reused",reused));if(flow.has("budgetScopeId"))result.add("budget",Budgets.view(c,Json.required(flow,"budgetScopeId")));result.addProperty("sequence",Store.cursor(c));return result;
    }
    JsonObject get(String id){return store.read(c->view(c,id));}
    JsonObject list(JsonObject p){int limit=Json.bounded(p,"limit",100,1,100),offset=Json.bounded(p,"offset",0,0,Integer.MAX_VALUE);return store.read(c->{String condition=p.has("projectId")?" WHERE project_id=?":"";List<Object> args=new ArrayList<>();if(p.has("projectId"))args.add(Json.required(p,"projectId"));long count=Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM flow_runs"+condition,args.toArray()),"n",0);args.add(limit);args.add(offset);JsonArray items=new JsonArray();for(JsonObject row:Store.rows(c,"SELECT id FROM flow_runs"+condition+" ORDER BY rowid DESC LIMIT ? OFFSET ?",args.toArray()))items.add(view(c,Json.required(row,"id")));return Json.obj("items",items,"total",count);});}
    boolean canContinue(String id){return !closed&&engine.runs.dispatchAllowed()&&store.read(c->{JsonObject flow=Store.document(c,"flow_runs",id);return Set.of("queued","running").contains(Json.required(flow,"status"));});}
    JsonObject diagnostics(){return Json.obj("activeWorkers",files.getActiveCount(),"queuedInMemory",files.getQueue().size());}
    void tick(){if(closed||!engine.runs.dispatchAllowed())return;try{List<JsonObject> pending=store.read(c->Store.rows(c,"SELECT id FROM flow_runs WHERE status IN ('queued','running','pausing','cancelling') ORDER BY rowid LIMIT 100"));for(JsonObject row:pending){String flowId=Json.required(row,"id");String local=store.tx(c->advance(c,flowId));if(local!=null){try{files.execute(()->work(flowId,local));}catch(RejectedExecutionException error){store.tx(c->{JsonObject step=Store.document(c,"flow_steps",local);step.addProperty("workerActive",false);step.addProperty("status","pending");saveStep(c,step);return null;});}return;}}}catch(ApiError error){if(error.code.startsWith("storage_")||error.code.equals("disk_space_low"))return;System.err.println("flow_dispatch_failed:"+error.code);}catch(Exception error){System.err.println("flow_dispatch_failed:internal_error");}}
    String advance(Connection c,String id)throws Exception{
        JsonObject flow=Store.document(c,"flow_runs",id);String state=Json.required(flow,"status");List<JsonObject> steps=steps(c,id);
        if(Set.of("pausing","cancelling").contains(state)){boolean active=false;for(JsonObject step:steps){active|=Json.bool(step,"workerActive",false);if(step.has("childRunId")){JsonObject stats=Json.object(engine.runs.view(c,Json.required(step,"childRunId"),false),"statistics");for(String field:List.of("preparing","sending","waiting","parsing","validating","saving"))active|=Json.integer(stats,field,0)>0;}}if(!active){flow.addProperty("status",state.equals("pausing")?"paused":"cancelled");if(state.equals("cancelling"))flow.addProperty("completedAt",Json.now());saveFlow(c,flow);Store.flowEvent(c,"flow."+Json.required(flow,"status"),id,null,null,null,null,new JsonObject());}return null;}
        if(!Set.of("queued","running").contains(state))return null;String input=Json.required(flow,"inputArtifactId");boolean hadErrors=false;
        for(JsonObject step:steps){String status=Json.required(step,"status");if(DONE_STEPS.contains(status)){hadErrors|=status.equals("completed_with_errors");if(step.has("outputArtifactId"))input=Json.required(step,"outputArtifactId");continue;}if(status.equals("failed")||status.equals("needs_attention")){flow.addProperty("status","needs_attention");flow.addProperty("pauseReason",Json.str(step,"errorCode","step_attention"));saveFlow(c,flow);return null;}if(Json.bool(step,"workerActive",false))return null;
            if(step.has("childRunId")){String childId=Json.required(step,"childRunId");JsonObject child=engine.runs.view(c,childId,false);JsonObject stats=apiStatistics(Json.object(child,"statistics"));progress(c,Json.required(step,"id"),stats);step.add("statistics",stats);String childStatus=Json.required(child,"status");if(Set.of("paused","needs_attention").contains(childStatus)){step.addProperty("status","needs_attention");step.addProperty("errorCode",Json.str(child,"pauseReason",childStatus));saveStep(c,step);flow.addProperty("status","needs_attention");flow.addProperty("pauseReason",Json.str(child,"pauseReason",childStatus));saveFlow(c,flow);return null;}if(Set.of("completed","completed_with_errors","cancelled").contains(childStatus)){JsonObject artifact=(Json.str(child,"kind","api").equals("local")||Json.bool(child,"inputResults",false))?localArtifact(c,flow,step,child):apiArtifact(c,flow,step,child);completeStep(c,flow,step,artifact);return null;}return null;}
            if(Set.of("api","local").contains(Json.required(step,"kind"))){try{if(Json.required(step,"kind").equals("local"))startLocal(c,flow,step,input);else startApi(c,flow,step,input);}catch(ApiError error){step.addProperty("status","failed");step.addProperty("errorCode",error.code);step.addProperty("message",error.getMessage());saveStep(c,step);flow.addProperty("status","failed");saveFlow(c,flow);Store.flowEvent(c,"flow.step.failed",id,Json.required(step,"stepId"),null,null,null,Json.obj("code",error.code));}return null;}
            if(files.getActiveCount()+files.getQueue().size()>0)return null;step.addProperty("inputArtifactId",input);step.addProperty("status","running");step.addProperty("workerActive",true);if(!step.has("startedAt"))step.addProperty("startedAt",Json.now());step.remove("errorCode");step.remove("message");saveStep(c,step);flow.addProperty("status","running");saveFlow(c,flow);Store.flowEvent(c,"flow.step.started",id,Json.required(step,"stepId"),null,null,null,Json.obj("kind",step.get("kind")));return Json.required(step,"id");
        }
        flow.addProperty("status",hadErrors?"completed_with_errors":"completed");flow.addProperty("completedAt",Json.now());saveFlow(c,flow);Store.flowEvent(c,"flow."+Json.required(flow,"status"),id,null,null,null,null,new JsonObject());return null;
    }
    void startApi(Connection c,JsonObject flow,JsonObject step,String input)throws Exception{
        List<JsonObject> items=FlowArtifacts.items(c,input),selected=new ArrayList<>(),inputs=new ArrayList<>();boolean views=items.stream().anyMatch(item->Json.str(Json.object(item,"inputSnapshot"),"kind","").equals("view"));for(JsonObject item:items)if(FlowArtifacts.included(item)){JsonObject asset=views?RunInputs.inputAsset(Json.obj("inputSnapshot",RunInputs.snapshot(item)),RunInputs.baseline(c,item)):Json.object(item,"asset");selected.add(Json.obj("data",asset.toString(),"path",item.get("inputPath")));inputs.add(item);}if(selected.isEmpty()){step.addProperty("status","failed");step.addProperty("errorCode","flow_input_empty");step.addProperty("message","没有可送入 API 的有效输入。");saveStep(c,step);flow.addProperty("status","failed");saveFlow(c,flow);return;}
        Set<String> targetIds=new HashSet<>();for(JsonObject row:selected)targetIds.add(Json.required(Json.parse(row.get("data").getAsString()),"id"));for(JsonElement ref:Json.array(Json.object(step,"snapshot"),"references"))if(targetIds.contains(Json.required(ref.getAsJsonObject(),"id")))throw new ApiError(422,"reference_target_overlap","实际导入结果与冻结人工参考重叠，未创建标注子任务。");
        JsonObject parameters=Json.object(step,"parameters").deepCopy(),snapshot=Json.object(step,"snapshot");parameters.addProperty("budgetScopeId",Json.required(flow,"budgetScopeId"));if(!parameters.has("maxRequests"))parameters.add("maxRequests",flow.get("maxRequests"));parameters.add("failurePolicy",flow.get("failurePolicy"));Runs.Prepared child=engine.runs.prepare(parameters,Json.id(),Json.object(snapshot,"project"),Json.object(snapshot,"provider"),Json.array(snapshot,"references"),selected);JsonObject run=child.run();Json.object(run,"snapshot").add("credentialBindingVersion",snapshot.get("credentialBindingVersion"));run.add("flowRunId",flow.get("id"));run.add("stepId",step.get("stepId"));run.addProperty("inputArtifactId",input);if(views){run.addProperty("inputResults",true);for(int index=0;index<inputs.size();index++){JsonObject item=inputs.get(index),sample=child.samples().get(index).getAsJsonObject(),baseline=RunInputs.baseline(c,item);sample.add("assetId",item.get("assetId"));sample.add("inputId",RunInputs.snapshot(item).get("inputId"));sample.add("inputSnapshot",RunInputs.snapshot(item));sample.add("name",item.get("name"));sample.add("baseVersion",Json.object(baseline,"asset").get("version"));}}Runs.insert(c,child);if(views)for(JsonObject item:inputs)RunInputs.insertBaseline(c,Json.required(run,"id"),item);step.addProperty("inputArtifactId",input);step.addProperty("childRunId",Json.required(run,"id"));step.addProperty("status","running");step.addProperty("startedAt",Json.now());step.remove("errorCode");step.remove("message");step.add("statistics",apiStatistics(Json.object(engine.runs.view(c,Json.required(run,"id"),false),"statistics")));saveStep(c,step);flow.addProperty("status","running");saveFlow(c,flow);Store.flowEvent(c,"flow.step.started",Json.required(flow,"id"),Json.required(step,"stepId"),Json.required(run,"id"),null,null,Json.obj("kind","api"));
    }
    void startLocal(Connection c,JsonObject flow,JsonObject step,String input)throws Exception{
        List<JsonObject> selected=new ArrayList<>();for(JsonObject item:FlowArtifacts.items(c,input))if(FlowArtifacts.included(item))selected.add(item);JsonObject snapshot=Json.object(step,"snapshot");String child=engine.localRuns.insert(c,Json.object(snapshot,"project"),Json.object(snapshot,"local"),selected,Json.str(flow,"failurePolicy","continue"),Json.required(flow,"id"),Json.required(step,"stepId"));step.addProperty("inputArtifactId",input);step.addProperty("childRunId",child);step.addProperty("status","running");step.addProperty("startedAt",Json.now());step.remove("errorCode");step.remove("message");saveStep(c,step);flow.addProperty("status","running");saveFlow(c,flow);Store.flowEvent(c,"flow.step.started",Json.required(flow,"id"),Json.required(step,"stepId"),child,null,null,Json.obj("kind","local"));
    }
    JsonObject localArtifact(Connection c,JsonObject flow,JsonObject step,JsonObject child)throws Exception{
        Map<String,JsonObject> samples=new HashMap<>();for(JsonObject row:Store.rows(c,"SELECT input_id,status,data FROM samples WHERE run_id=?",Json.required(child,"id")))samples.put(Json.required(row,"input_id"),row);List<JsonObject> output=new ArrayList<>();boolean views=false;for(JsonObject original:FlowArtifacts.items(c,Json.required(step,"inputArtifactId"))){JsonObject item=original.deepCopy();views|=Json.str(Json.object(item,"inputSnapshot"),"kind","").equals("view");if(FlowArtifacts.included(item)){JsonObject input=RunInputs.snapshot(item),row=samples.get(Json.required(input,"inputId"));if(row==null)throw new ApiError(409,"flow_child_sample_missing","子任务缺少固定模型输入。");JsonObject sample=Json.parse(row.get("data").getAsString());item.add("sourceRunId",child.get("id"));for(String stale:List.of("reused","reusedFrom","inputReusedFrom"))item.remove(stale);for(String field:List.of("resultId","candidateVersion","requiresGeometryReview","reused","inputReusedFrom"))if(sample.has(field))item.add(field,sample.get(field));String status=Json.required(row,"status");if(status.equals("succeeded")){if(sample.has("candidateVersion")&&!Json.bool(item,"manualProtected",false)){item.add("selectedVersion",sample.get("candidateVersion"));if(!Json.str(input,"kind","").equals("view"))item.add("asset",FlowArtifacts.selected(c,item,true));}}else{item.addProperty("outcome",status.equals("unknown")?"unknown":"failed");item.addProperty("reason",Json.str(sample,"errorCode",status));}}output.add(item);}
        String id=FlowArtifacts.create(c,flow,Json.required(step,"stepId"),views?"view_annotations":"annotations",output,true);return Store.document(c,"flow_artifacts",id);
    }
    static JsonObject apiStatistics(JsonObject source){JsonObject stats=FlowArtifacts.statistics();for(String field:List.of("total","succeeded","failed","unknown","reused","baselineTotal","baselineCompleted","inputTotal","inputCompleted"))stats.addProperty(field,Json.integer(source,field,0));stats.addProperty("queued",Json.integer(source,"queued",0)+Json.integer(source,"retry_wait",0));int active=0;for(String field:List.of("preparing","sending","waiting","parsing","validating","saving"))active+=Json.integer(source,field,0);stats.addProperty("inFlight",active);stats.addProperty("processed",Json.integer(source,"succeeded",0)+Json.integer(source,"failed",0)+Json.integer(source,"cancelled",0));return stats;}
    void progress(Connection c,String rowId,JsonObject stats)throws Exception{JsonObject step=Store.document(c,"flow_steps",rowId);if(stats.equals(step.get("statistics")))return;step.add("statistics",stats);saveStep(c,step);Store.flowEvent(c,"flow.step.progress",Json.required(step,"flowRunId"),Json.required(step,"stepId"),Json.str(step,"childRunId",null),null,null,Json.obj("statistics",stats));}
    JsonObject apiArtifact(Connection c,JsonObject flow,JsonObject step,JsonObject child)throws Exception{
        Map<String,JsonObject> samples=new HashMap<>();for(JsonObject row:Store.rows(c,"SELECT asset_id,status,data FROM samples WHERE run_id=?",Json.required(child,"id")))samples.put(Json.required(row,"asset_id"),row);List<JsonObject> output=new ArrayList<>();for(JsonObject original:FlowArtifacts.items(c,Json.required(step,"inputArtifactId"))){JsonObject item=original.deepCopy();if(FlowArtifacts.included(item)){JsonObject row=samples.get(Json.required(item,"assetId"));if(row==null)throw new ApiError(409,"flow_child_sample_missing","子任务缺少固定输入样本。");JsonObject sample=Json.parse(row.get("data").getAsString());item.add("sourceRunId",child.get("id"));String status=Json.required(row,"status");item.remove("reused");item.remove("reusedFrom");if(Json.bool(sample,"reused",false)){item.addProperty("reused",true);item.add("reusedFrom",sample.get("reusedFrom"));}if(status.equals("succeeded")&&sample.has("candidateVersion")){item.add("candidateVersion",sample.get("candidateVersion"));if(!Json.bool(item,"manualProtected",false)){item.add("selectedVersion",sample.get("candidateVersion"));JsonObject candidate=FlowArtifacts.selected(c,item,true);item.add("asset",candidate);}}else{item.addProperty("outcome",status.equals("unknown")?"unknown":"failed");item.addProperty("reason",Json.str(sample,"errorCode",status));}}output.add(item);}
        if(step.has("retrySourceArtifactId"))for(JsonObject item:output)item.add("sourceArtifactId",step.get("retrySourceArtifactId"));String id=FlowArtifacts.create(c,flow,Json.required(step,"stepId"),"annotations",output,true);return Store.document(c,"flow_artifacts",id);
    }
    void completeStep(Connection c,JsonObject flow,JsonObject step,JsonObject artifact)throws Exception{
        JsonObject stats=Json.object(artifact,"statistics");boolean errors=Json.integer(stats,"failed",0)+Json.integer(stats,"unknown",0)>0||step.has("childRunId")&&Json.required(Store.document(c,"runs",Json.required(step,"childRunId")),"status").equals("completed_with_errors");step.add("outputArtifactId",artifact.get("id"));step.add("statistics",stats);step.addProperty("workerActive",false);step.addProperty("completedAt",Json.now());String state=Json.required(flow,"status");
        if(Set.of("cancelling","cancelled").contains(state))step.addProperty("status","cancelled");else if(Json.required(step,"kind").equals("review")&&Json.bool(Json.object(step,"parameters"),"waitForHuman",false)){step.addProperty("status","needs_attention");if(!Set.of("pausing","paused").contains(state)){flow.addProperty("status","needs_attention");flow.addProperty("pauseReason","review");}}else step.addProperty("status",errors?"completed_with_errors":"completed");saveStep(c,step);saveFlow(c,flow);Store.flowEvent(c,"flow.step."+Json.required(step,"status"),Json.required(flow,"id"),Json.required(step,"stepId"),Json.str(step,"childRunId",null),null,null,Json.obj("outputArtifactId",artifact.get("id"),"statistics",stats));
    }
    void work(String flowId,String rowId){try{JsonObject flow=store.read(c->Store.document(c,"flow_runs",flowId)),step=store.read(c->Store.document(c,"flow_steps",rowId));JsonObject artifact=nodes.execute(flow,step);store.tx(c->{completeStep(c,Store.document(c,"flow_runs",flowId),Store.document(c,"flow_steps",rowId),artifact);return null;});}
        catch(Exception error){try{store.tx(c->{JsonObject flow=Store.document(c,"flow_runs",flowId),step=Store.document(c,"flow_steps",rowId);step.addProperty("workerActive",false);String state=Json.required(flow,"status");boolean interrupted=closed||!engine.runs.dispatchAllowed()||Set.of("pausing","paused","cancelling","cancelled").contains(state);if(state.equals("cancelling")||state.equals("cancelled"))step.addProperty("status","cancelled");else if(interrupted){step.addProperty("status","pending");if(closed){flow.addProperty("status","paused");flow.addProperty("pauseReason","restart_review");}}else{step.addProperty("status","failed");step.addProperty("errorCode",error instanceof ApiError a?a.code:"flow_step_failed");step.addProperty("message",error instanceof ApiError a?a.getMessage():"流程步骤执行失败。");flow.addProperty("status","failed");}saveStep(c,step);saveFlow(c,flow);Store.flowEvent(c,"flow.step."+Json.required(step,"status"),flowId,Json.required(step,"stepId"),null,null,null,Json.obj("code",step.get("errorCode")));return null;});}catch(Exception ignored){System.err.println("flow_result_not_saved");}}
    }
    JsonObject control(String action,JsonObject p){
        String id=Json.required(p,"flowRunId");Set<String> selected=new HashSet<>();
        if(p.has("retryUnknown")&&(!p.get("retryUnknown").isJsonPrimitive()||!p.getAsJsonPrimitive("retryUnknown").isBoolean()))throw new ApiError(400,"flow_control_invalid","retryUnknown 必须为布尔值。");
        if(p.has("assetIds")){if(!p.get("assetIds").isJsonArray()||Json.array(p,"assetIds").isEmpty()||Json.array(p,"assetIds").size()>10000)throw new ApiError(400,"flow_control_invalid","重试素材必须为 1 至 10000 个唯一标识。");for(JsonElement value:Json.array(p,"assetIds"))if(!value.isJsonPrimitive()||!value.getAsJsonPrimitive().isString()||value.getAsString().isBlank()||!selected.add(value.getAsString()))throw new ApiError(400,"flow_control_invalid","重试素材标识无效或重复。");}
        return store.tx(c->{JsonObject flow=Store.document(c,"flow_runs",id);List<JsonObject> steps=steps(c,id);String state=Json.required(flow,"status");
            if(Set.of("cancelled","cancelling").contains(state)){if(action.equals("cancel"))return view(c,id);throw new ApiError(409,"flow_cancelled","已取消流程需要新建运行。");}
            if(action.equals("cancel")&&TERMINAL.contains(state))return view(c,id);
            if(p.has("maxRequests")){long max=Costs.integer(p,"maxRequests",1,1000000);if(!flow.has("budgetScopeId"))throw new ApiError(400,"flow_budget_missing","此流程没有 API 预算。");Budgets.ensure(c,Json.required(flow,"budgetScopeId"),max,true);flow.addProperty("maxRequests",max);}
            if(action.equals("pause")||action.equals("cancel")){
                if(TERMINAL.contains(state))throw new ApiError(409,"flow_finished","流程已经结束。");flow.addProperty("status",action.equals("pause")?"pausing":"cancelling");flow.addProperty("pauseReason","user");
                for(JsonObject step:steps){String status=Json.required(step,"status");if(DONE_STEPS.contains(status))continue;if(step.has("childRunId")){JsonObject child=Store.document(c,"runs",Json.required(step,"childRunId"));if(!Set.of("completed","completed_with_errors","cancelled").contains(Json.required(child,"status")))engine.runs.control(c,action,Json.obj("runId",child.get("id")));}
                    // 已封存复核仍需人工确认，暂停不能抹去这个持久状态。
                    if(!Json.bool(step,"workerActive",false)){if(action.equals("cancel"))step.addProperty("status","cancelled");else if(!reviewGate(step))step.addProperty("status","paused");saveStep(c,step);}}
            }else if(action.equals("resume")||action.equals("retry")){
                if(state.equals("pausing"))throw new ApiError(409,"flow_pause_pending","请等待当前工作保存后再恢复。");boolean retry=action.equals("retry");int target=-1;
                if(p.has("stepId")){String wanted=Json.required(p,"stepId");for(int i=0;i<steps.size();i++)if(Json.required(steps.get(i),"stepId").equals(wanted)){target=i;break;}if(target<0)throw new ApiError(404,"flow_step_missing","流程步骤不存在。");}
                else for(int i=0;i<steps.size();i++){String status=Json.required(steps.get(i),"status");if(!DONE_STEPS.contains(status)||(retry&&status.equals("completed_with_errors"))){target=i;break;}}
                if(target<0)throw new ApiError(409,"flow_finished","没有未完成或可重试的步骤。");JsonObject step=steps.get(target);String status=Json.required(step,"status");
                if(DONE_STEPS.contains(status)&&!(retry&&status.equals("completed_with_errors")))throw new ApiError(409,"flow_finished","该步骤已经完成。");
                for(int i=0;i<target;i++)if(!DONE_STEPS.contains(Json.required(steps.get(i),"status")))throw new ApiError(409,"flow_upstream_unfinished","请先完成前面的流程步骤。");
                if(Json.bool(step,"workerActive",false))throw new ApiError(409,"flow_step_busy","步骤仍在执行。");
                for(int i=target+1;i<steps.size();i++)if(steps.get(i).has("outputArtifactId")||steps.get(i).has("childRunId")||Json.bool(steps.get(i),"workerActive",false))throw new ApiError(409,"flow_rerun_required","下游已经固定，请创建后续运行版本重跑上游。");
                if(reviewGate(step)){
                    if(retry||!Json.required(step,"stepId").equals(Json.str(p,"acknowledgeReviewStepId","")))throw new ApiError(409,"flow_review_acknowledgement_required","请明确确认该复核步骤后继续。");String reviewed=FlowArtifacts.resolvedReview(c,flow,step);step.addProperty("outputArtifactId",reviewed);step.add("statistics",Json.object(Store.document(c,"flow_artifacts",reviewed),"statistics"));JsonObject stats=Json.object(step,"statistics");step.addProperty("status",Json.integer(stats,"failed",0)+Json.integer(stats,"unknown",0)>0?"completed_with_errors":"completed");
                }else{
                    if(step.has("childRunId"))resumeChild(c,step,p,selected,retry);
                    else{if(retry&&step.has("workingArtifactId"))retryImport(c,flow,step,selected);else if(retry&&step.has("outputArtifactId"))throw new ApiError(409,"flow_rerun_required","该产物中的问题来自固定输入，请从相应上游新建运行版本。");else if(!selected.isEmpty())throw new ApiError(400,"flow_control_invalid","该步骤不支持按素材重试。");step.addProperty("status","pending");}
                    if(step.has("outputArtifactId")){step.add("retrySourceArtifactId",step.get("outputArtifactId"));step.remove("outputArtifactId");}step.remove("completedAt");step.remove("errorCode");step.remove("message");
                }
                saveStep(c,step);flow.addProperty("status","running");flow.remove("pauseReason");flow.remove("completedAt");
            }else throw new IllegalArgumentException();saveFlow(c,flow);Store.flowEvent(c,"flow."+action,id,null,null,null,null,Json.obj("status",flow.get("status"),"retryUnknown",Json.bool(p,"retryUnknown",false)));return view(c,id);
        });
    }
    static boolean reviewGate(JsonObject step){return Json.required(step,"kind").equals("review")&&step.has("outputArtifactId")&&Json.bool(Json.object(step,"parameters"),"waitForHuman",false)&&!DONE_STEPS.contains(Json.required(step,"status"));}
    void resumeChild(Connection c,JsonObject step,JsonObject p,Set<String> selected,boolean retry)throws Exception{
        String id=Json.required(step,"childRunId");JsonObject child=Store.document(c,"runs",id);if(Json.required(child,"status").equals("cancelled"))throw new ApiError(409,"flow_rerun_required","标注子任务已取消，请新建流程版本。");
        int eligible=0,unknown=0,queued=0;Set<String> known=new HashSet<>();for(JsonObject row:Store.rows(c,"SELECT asset_id,status FROM samples WHERE run_id=?",id)){String asset=Json.required(row,"asset_id"),status=Json.required(row,"status");known.add(asset);if(Set.of("preparing","sending","waiting","parsing","validating","saving").contains(status))throw new ApiError(409,"flow_step_busy","标注请求仍在执行。");if(Set.of("queued","retry_wait").contains(status))queued++;if(status.equals("unknown"))unknown++;if((selected.isEmpty()||selected.contains(asset))&&(status.equals("failed")||(status.equals("unknown")&&Json.bool(p,"retryUnknown",false))))eligible++;}
        if(!known.containsAll(selected))throw new ApiError(422,"flow_retry_asset_mismatch","重试素材不在该步骤固定输入内。");
        if(retry&&eligible==0)throw new ApiError(409,unknown>0?"flow_unknown_retry_required":"flow_retry_empty",unknown>0?"未知结果需显式 retryUnknown 后才能再次请求。":"所选范围没有可重试的失败项。");
        if(!retry&&queued==0){if(unknown>0)throw new ApiError(409,"flow_unknown_retry_required","未知结果需显式 retryUnknown 后才能再次请求。");if(Json.required(child,"status").equals("completed_with_errors"))throw new ApiError(409,"flow_retry_required","请明确重试失败项。");}
        JsonObject control=Json.obj("runId",id);for(String field:List.of("assetIds","retryUnknown","maxRequests"))if(p.has(field))control.add(field,p.get(field));engine.runs.control(c,retry?"retry":"resume",control);step.addProperty("status","running");
    }
    void retryImport(Connection c,JsonObject flow,JsonObject step,Set<String> selected)throws Exception{
        String previous=Json.required(step,"workingArtifactId");List<JsonObject> items=FlowArtifacts.items(c,previous);int eligible=0;for(JsonObject item:items)if(item.has("workStatus")&&Json.str(item,"outcome","").equals("failed")&&(selected.isEmpty()||selected.contains(Json.str(item,"assetId",Json.str(item,"importAssetId","")))))eligible++;
        if(eligible==0)throw new ApiError(409,"flow_retry_empty","所选范围没有可重试的导入失败项。");
        // 封存产物允许被其他运行继承；重试只改新工作副本，保留旧分项及统计。
        if(Json.required(Store.document(c,"flow_artifacts",previous),"status").equals("completed")){for(JsonObject item:items)item.addProperty("sourceArtifactId",previous);String next=FlowArtifacts.create(c,flow,Json.required(step,"stepId"),"assets",items,false);step.addProperty("workingArtifactId",next);items=FlowArtifacts.items(c,next);}
        for(JsonObject item:items)if(item.has("workStatus")&&Json.str(item,"outcome","").equals("failed")&&(selected.isEmpty()||selected.contains(Json.str(item,"assetId",Json.str(item,"importAssetId",""))))){item.addProperty("workStatus","queued");item.addProperty("outcome","included");item.remove("reason");FlowArtifacts.updateItem(c,item);}step.add("statistics",FlowArtifacts.statistics(items));
    }
    JsonObject rerun(JsonObject p)throws Exception{
        String id=Json.required(p,"flowRunId"),fromStep=Json.required(p,"fromStepId");JsonObject source=store.read(c->Store.document(c,"flow_runs",id));List<JsonObject> previous=store.read(c->steps(c,id));JsonObject definition=p.has("definition")?Json.object(p,"definition"):Json.object(source,"definition");int from=-1;for(int i=0;i<Json.array(definition,"steps").size();i++)if(Json.required(Json.array(definition,"steps").get(i).getAsJsonObject(),"id").equals(fromStep)){from=i;break;}if(from<0)throw new ApiError(404,"flow_step_missing","重跑起点不存在。");String input=Json.required(source,"inputArtifactId");JsonArray invalidated=new JsonArray();for(int i=0;i<Json.array(definition,"steps").size();i++){JsonObject spec=Json.array(definition,"steps").get(i).getAsJsonObject();if(i<from){if(i>=previous.size()||!Json.required(previous.get(i),"stepId").equals(Json.required(spec,"id"))||!Json.required(previous.get(i),"kind").equals(Json.required(spec,"kind"))||Json.bool(previous.get(i),"enabled",false)!=Json.bool(spec,"enabled",false)||!Json.object(previous.get(i),"parameters").equals(Json.object(spec,"parameters")))throw new ApiError(409,"flow_upstream_changed","上游配置已变化，必须从更早的步骤重跑。");if(Json.bool(spec,"enabled",false)){if(!previous.get(i).has("outputArtifactId"))throw new ApiError(409,"flow_upstream_unfinished","需要继承的上游产物尚未完成。");input=Json.required(previous.get(i),"outputArtifactId");}}else if(Json.bool(spec,"enabled",false))invalidated.add(Json.required(spec,"id"));}
        JsonObject request=Json.obj("projectId",source.get("projectId"),"definition",definition,"input",Json.obj("source","artifact","artifactId",input),"failurePolicy",Json.str(source,"failurePolicy","continue"));for(String field:List.of("budgetScopeId","maxRequests"))if(p.has(field))request.add(field,p.get(field));else if(source.has(field))request.add(field,source.get(field));FlowPlans.Plan plan=plans.prepare(request,from);requirePlan(plan);int first=from;for(JsonObject item:plan.input())FlowArtifacts.checkFile(item);JsonObject run=store.tx(c->insert(c,plan,source,first));return Json.obj("run",run,"invalidatedStepIds",invalidated);
    }
    @Override public void close(){closed=true;files.shutdownNow();try{files.awaitTermination(10,TimeUnit.SECONDS);}catch(InterruptedException error){Thread.currentThread().interrupt();}}
}
