package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.sql.Connection;
import java.util.*;

final class FlowNodes {
    final Flows flows;final Engine engine;final Store store;
    FlowNodes(Flows flows){this.flows=flows;engine=flows.engine;store=engine.store;}
    JsonObject execute(JsonObject flow,JsonObject step)throws Exception{
        String kind=Json.required(step,"kind"),fid=Json.required(flow,"id"),sid=Json.required(step,"stepId");check(fid);
        if(kind.equals("import"))return imports(flow,step);if(kind.equals("transform"))return new FlowTransforms(flows).execute(flow,step);
        List<JsonObject> items=store.read(c->FlowArtifacts.items(c,Json.required(step,"inputArtifactId")));JsonObject parameters=Json.object(step,"parameters");
        if(kind.equals("filter"))return filter(flow,step,items);
        if(kind.equals("review"))return review(flow,step,store.read(c->FlowArtifacts.parents(c,items)));
        if(kind.equals("export"))return export(flow,step,store.read(c->FlowArtifacts.parents(c,items)));
        throw new ApiError(422,"flow_step_unavailable","该文件步骤尚未实现。");
    }
    void check(String flow){if(!flows.canContinue(flow))throw new ApiError(409,"flow_step_interrupted","流程已停止分派，已保存的文件结果会保留。");}
    JsonObject imports(JsonObject flow,JsonObject step)throws Exception{
        if(Json.object(step,"parameters").has("mediaJobId"))return importVideo(flow,step);
        String fid=Json.required(flow,"id"),sid=Json.required(step,"stepId"),rowId=Json.required(step,"id");
        String output=store.tx(c->{JsonObject current=Store.document(c,"flow_steps",rowId);if(current.has("workingArtifactId"))return Json.required(current,"workingArtifactId");List<JsonObject> items=FlowArtifacts.items(c,Json.required(current,"inputArtifactId"));for(JsonElement file:Json.array(Json.object(current,"snapshot"),"importFiles")){JsonObject item=file.getAsJsonObject().deepCopy();item.addProperty("id",Json.id());item.addProperty("outcome","included");item.add("selectedVersion",JsonNull.INSTANCE);item.addProperty("workStatus","queued");items.add(item);}String id=FlowArtifacts.create(c,flow,sid,"assets",items,false);current.addProperty("workingArtifactId",id);Flows.saveStep(c,current);return id;});
        List<JsonObject> entries=store.read(c->FlowArtifacts.items(c,output));Set<String> seen=new HashSet<>();for(JsonObject item:entries)if(FlowArtifacts.included(item)&&!item.has("workStatus"))seen.add(Json.required(item,"assetId"));
        for(JsonObject original:entries){if(!original.has("workStatus"))continue;if(Json.str(original,"workStatus","").equals("done")){if(FlowArtifacts.included(original))seen.add(Json.required(original,"assetId"));continue;}check(fid);JsonObject item=original.deepCopy();item.addProperty("workStatus","running");store.tx(c->{FlowArtifacts.updateItem(c,item);return null;});
            try{JsonObject imported=importFile(flow,step,item);boolean duplicate=!seen.add(Json.required(imported,"assetId"));for(var entry:imported.entrySet())if(!entry.getKey().equals("id"))item.add(entry.getKey(),entry.getValue());if(duplicate){item.addProperty("outcome","excluded");item.addProperty("reason","already_in_input");}item.addProperty("workStatus","done");}
            catch(Exception error){if(!flows.canContinue(fid)){item.addProperty("workStatus","queued");store.tx(c->{FlowArtifacts.updateItem(c,item);return null;});throw new ApiError(409,"flow_step_interrupted","导入暂停，未保存文件留待恢复。");}if(error instanceof ApiError a&&(a.status>=500||a.code.equals("disk_space_low")))throw a;item.addProperty("outcome","failed");item.addProperty("reason",error instanceof ApiError a?a.code:"image_decode_failed");item.addProperty("workStatus","done");}
            store.tx(c->{FlowArtifacts.updateItem(c,item);flows.progress(c,rowId,FlowArtifacts.statistics(FlowArtifacts.items(c,output)));return null;});
        }
        check(fid);return store.tx(c->FlowArtifacts.seal(c,output,new JsonObject()));
    }
    private JsonObject awaitMedia(String flowId,String jobId)throws Exception{
        for(;;){check(flowId);JsonObject job=engine.mediaJobs.get(jobId);String status=Json.required(job,"status");if(status.equals("completed"))return job;if(Set.of("failed","cancelled","interrupted").contains(status))throw new ApiError(422,"flow_media_failed",Json.str(Json.object(job,"error"),"message","媒体任务未完成，请检查任务记录。"));Thread.sleep(80);}
    }
    private JsonObject importVideo(JsonObject flow,JsonObject step)throws Exception{
        String fid=Json.required(flow,"id"),sid=Json.required(step,"stepId"),pid=Json.required(flow,"projectId");JsonObject fixed=Json.object(Json.object(step,"snapshot"),"mediaJob");String jobId=Json.required(fixed,"id");
        store.read(c->{JsonObject current=Store.document(c,"media_jobs",jobId);if(!Json.required(current,"projectId").equals(pid)||!Objects.equals(current.get("manifestHash"),fixed.get("manifestHash"))||!Objects.equals(current.get("completeHash"),fixed.get("completeHash")))throw new ApiError(409,"flow_media_changed","固定抽帧产物身份已变化。");return null;});
        engine.mediaJobs.importVideo(Json.obj("jobId",jobId));JsonObject ready=awaitMedia(fid,jobId);if(!Json.bool(ready,"assetsCommitted",false))throw new ApiError(409,"flow_media_not_ready","视频帧素材事务尚未完成。");
        check(fid);return store.tx(c->{List<JsonObject> items=FlowArtifacts.items(c,Json.required(step,"inputArtifactId"));Set<String> seen=new HashSet<>();for(JsonObject item:items)if(item.has("assetId"))seen.add(Json.required(item,"assetId"));int frames=0;for(JsonObject row:Store.rows(c,"SELECT data,path FROM assets WHERE project_id=? AND json_extract(data,'$.metadata.mediaJobId')=? ORDER BY json_extract(data,'$.metadata.sourcePresentationIndex')",pid,jobId)){JsonObject asset=Json.parse(Json.required(row,"data"));if(seen.add(Json.required(asset,"id")))items.add(FlowArtifacts.assetItem(c,asset,Json.required(row,"path")));frames++;}if(frames!=Json.integer(fixed,"frameCount",-1))throw new ApiError(409,"flow_media_changed","已提交视频帧数量与固定清单不符。");String id=FlowArtifacts.create(c,flow,sid,"assets",items,true);return Store.document(c,"flow_artifacts",id);});
    }
    private JsonObject filter(JsonObject flow,JsonObject step,List<JsonObject> items)throws Exception{
        String fid=Json.required(flow,"id"),sid=Json.required(step,"stepId"),rowId=Json.required(step,"id");JsonObject parameters=Json.object(step,"parameters"),extra=new JsonObject();
        store.read(c->{for(JsonObject item:items)if(item.has("assetId")){JsonObject current=Store.document(c,"assets",Json.required(item,"assetId"));if(Set.of("modified","confirmed").contains(Json.str(current,"status",""))||Store.one(c,"SELECT asset_id FROM drafts WHERE asset_id=?",Json.required(item,"assetId"))!=null)item.addProperty("manualProtected",true);}return null;});
        if(parameters.has("screening")){
            JsonArray inputs=new JsonArray();for(JsonObject item:items)if(FlowArtifacts.included(item)){if(Json.str(Json.object(item,"inputSnapshot"),"kind","").equals("view"))throw new ApiError(422,"screening_baseline_required","近重复和模糊筛选应在图像处理前执行。");inputs.add(engine.mediaJobs.frozenAsset(Json.object(item,"asset"),Json.required(item,"inputPath"),Json.bool(item,"manualProtected",false)));}
            if(!inputs.isEmpty()){String jobId=Json.str(step,"screeningJobId",null);if(jobId==null||Set.of("failed","cancelled","interrupted").contains(Json.required(engine.mediaJobs.get(jobId),"status"))){JsonObject job=engine.mediaJobs.createFrozenScreening(Json.required(flow,"projectId"),inputs,Json.object(parameters,"screening"));jobId=Json.required(job,"id");String savedId=jobId;store.tx(c->{JsonObject current=Store.document(c,"flow_steps",rowId);current.addProperty("screeningJobId",savedId);Flows.saveStep(c,current);return null;});}
                JsonObject completed=awaitMedia(fid,jobId),result=engine.mediaJobs.screeningDocument(jobId);Map<String,JsonObject> rows=new HashMap<>();for(JsonElement value:Json.array(result,"items"))rows.put(Json.required(value.getAsJsonObject(),"assetId"),value.getAsJsonObject());for(JsonObject item:items){JsonObject row=rows.get(Json.str(item,"assetId",""));if(row!=null){item.add("screeningReasons",row.get("reasons"));item.add("screeningRecommendation",row.get("recommendation"));}}extra.addProperty("screeningJobId",jobId);extra.add("screeningSummary",completed.get("summary"));
            }
        }
        List<JsonObject> filtered=FlowPlans.filter(items,parameters);check(fid);return store.tx(c->{String inputKind=Json.required(Store.document(c,"flow_artifacts",Json.required(step,"inputArtifactId")),"kind");String id=FlowArtifacts.create(c,flow,sid,inputKind,filtered,false);return FlowArtifacts.seal(c,id,extra);});
    }
    JsonObject importFile(JsonObject flow,JsonObject step,JsonObject item)throws Exception{
        String pid=Json.required(flow,"projectId"),assetId=Json.required(item,"importAssetId");if(!assetId.matches("[0-9a-fA-F-]{36}"))throw new ApiError(409,"flow_snapshot_invalid","固定导入标识无效。");
        JsonObject existing=store.read(c->{JsonObject row=Store.one(c,"SELECT data,path FROM assets WHERE id=? AND project_id=?",assetId,pid);return row==null?null:FlowArtifacts.assetItem(c,Json.parse(row.get("data").getAsString()),Json.required(row,"path"));});if(existing!=null)return existing;
        Path source=Path.of(Json.required(item,"sourcePath"));if(!Files.isRegularFile(source)||!Media.hash(source).equals(Json.required(item,"sourceHash")))throw new ApiError(409,"flow_import_changed","待导入文件已变化，请创建新的流程输入。");
        cleanupUncommitted(assetId);JsonObject snapshot=Json.object(step,"snapshot"),project=Json.object(snapshot,"project");boolean copy=Json.str(Json.object(step,"parameters"),"mode","copy").equals("copy");Media.Normalized normalized=engine.projects.media.normalize(source,assetId,Json.str(Json.object(project,"settings"),"alphaBackground","#ffffff"),copy);
        if(!Json.required(normalized.metadata(),"sourceHash").equals(Json.required(item,"sourceHash")))throw new ApiError(409,"flow_import_changed","图片读取期间内容变化，未登记该输入。");
        JsonObject imported=store.tx(c->{JsonObject same=Store.one(c,"SELECT data,path FROM assets WHERE project_id=? AND json_extract(data,'$.contentHash')=? ORDER BY rowid LIMIT 1",pid,normalized.hash());if(same!=null)return FlowArtifacts.assetItem(c,Json.parse(same.get("data").getAsString()),Json.required(same,"path"));JsonObject asset=Json.obj("id",assetId,"projectId",pid,"name",item.get("name"),"mediaUrl","autolabel-media://asset/"+assetId,"thumbnailUrl","autolabel-media://asset/"+assetId,"contentHash",normalized.hash(),"width",normalized.width(),"height",normalized.height(),"status","unlabeled","annotations",new JsonArray(),"version",0,"source","import","metadata",normalized.metadata());Store.update(c,"INSERT INTO assets(id,project_id,data,path) VALUES(?,?,?,?)",assetId,pid,asset,normalized.path().toString());Store.flowEvent(c,"asset.imported",Json.required(flow,"id"),Json.required(step,"stepId"),null,assetId,null,Json.obj("projectId",pid));return FlowArtifacts.assetItem(c,asset,normalized.path().toString());});if(!Json.required(imported,"assetId").equals(assetId))cleanupUncommitted(assetId);return imported;
    }
    void cleanupUncommitted(String id)throws Exception{
        for(Path candidate:List.of(store.root.resolve("media").resolve(id+".png"),store.root.resolve("media").resolve(id+".tmp"),store.materialsRoot.resolve(id+".png"),store.materialsRoot.resolve(id+".jpg"))){Path path=candidate.toAbsolutePath().normalize();if(!(path.startsWith(store.root)||path.startsWith(store.materialsRoot))||!path.getFileName().toString().startsWith(id+"."))throw new ApiError(409,"flow_snapshot_invalid","导入暂存路径越界。");boolean referenced=store.read(c->Store.one(c,"SELECT id FROM assets WHERE path=? OR json_extract(data,'$.metadata.sourcePath')=? LIMIT 1",path.toString(),path.toString())!=null);if(!referenced)Files.deleteIfExists(path);}
    }
    JsonObject review(JsonObject flow,JsonObject step,List<JsonObject> source)throws Exception{
        String fid=Json.required(flow,"id"),sid=Json.required(step,"stepId"),pid=Json.required(flow,"projectId"),context="flow:"+fid+":"+sid;JsonObject parameters=Json.object(step,"parameters"),project=Json.object(Json.object(step,"snapshot"),"project");List<JsonObject> items=new ArrayList<>(),issues=new ArrayList<>(),valid=new ArrayList<>();
        for(JsonObject original:source){check(fid);JsonObject item=original.deepCopy();if(FlowArtifacts.included(item)){try{FlowArtifacts.checkFile(item);JsonObject asset=store.read(c->FlowArtifacts.selected(c,item,true));Annotations.validateStored(Json.array(asset,"annotations"),asset,project);if(Json.bool(Json.object(asset,"metadata"),"requiresGeometryReview",false))throw new ApiError(422,"geometry_review_required","候选包含未完成覆盖或几何问题，请先保存人工修订。");valid.add(item);}catch(ApiError error){item.addProperty("outcome","failed");item.addProperty("reason",error.code);}}
            if(Json.bool(parameters,"buildIssues",true)&&Set.of("failed","unknown").contains(Json.str(item,"outcome",""))&&item.has("assetId")){JsonElement version=item.has("candidateVersion")?item.get("candidateVersion"):item.get("selectedVersion");issues.add(Reviews.item(pid,Json.required(item,"assetId"),version,Json.str(item,"reason","flow_input_failed"),"error","execution",null,context,Json.obj("flowRunId",fid,"stepId",sid,"runId",Json.str(item,"sourceRunId",null))));}items.add(item);
        }
        Reviews reviews=new Reviews(store,engine.projects);if(!issues.isEmpty())reviews.saveItems(issues,null);JsonObject extra=new JsonObject();
        if(parameters.has("randomSample")){JsonObject random=Json.object(parameters,"randomSample");int count=Json.integer(random,"count",0);if(count>valid.size())throw new ApiError(422,"flow_random_sample_invalid","抽样数量超过有效候选范围。");String sampleId=Json.required(step,"id");JsonObject existing=store.read(c->Store.one(c,"SELECT id FROM review_samples WHERE id=?",sampleId));if(existing==null){valid.sort(Comparator.comparing(item->Json.required(item,"assetId")));JsonArray population=new JsonArray();for(JsonObject item:valid)population.add(Json.obj("assetId",item.get("assetId"),"version",item.has("candidateVersion")?item.get("candidateVersion"):item.get("selectedVersion")));long seed=ByteBuffer.wrap(MessageDigest.getInstance("SHA-256").digest(Json.required(random,"seed").getBytes(StandardCharsets.UTF_8))).getLong();Collections.shuffle(valid,new Random(seed));List<JsonObject> randomIssues=new ArrayList<>();JsonArray selected=new JsonArray();for(JsonObject item:valid.subList(0,count)){JsonElement version=item.has("candidateVersion")?item.get("candidateVersion"):item.get("selectedVersion");selected.add(Json.obj("assetId",item.get("assetId"),"version",version,"contentHash",item.get("contentHash")));randomIssues.add(Reviews.item(pid,Json.required(item,"assetId"),version,"random_sample","info","random",null,"sample:"+sampleId,Json.obj("flowRunId",fid,"stepId",sid,"sampleId",sampleId)));}reviews.saveItems(randomIssues,Json.obj("id",sampleId,"projectId",pid,"mode","random","populationCount",valid.size(),"count",count,"seed",random.get("seed"),"algorithm","sha256-java-shuffle-v1","population",population,"assetVersions",selected,"createdAt",Json.now()));}extra.addProperty("reviewSampleId",sampleId);}
        check(fid);return store.tx(c->{String id=FlowArtifacts.create(c,flow,sid,"review",items,false);return FlowArtifacts.seal(c,id,extra);});
    }
    JsonObject export(JsonObject flow,JsonObject step,List<JsonObject> items)throws Exception{
        String fid=Json.required(flow,"id"),sid=Json.required(step,"stepId"),rowId=Json.required(step,"id");JsonObject parameters=Json.object(step,"parameters"),project=Json.object(Json.object(step,"snapshot"),"project");boolean candidate=Json.str(parameters,"annotationSelection","protected").equals("candidate");List<JsonObject> selected=new ArrayList<>();Map<String,Path> paths=new HashMap<>();List<JsonObject> output=new ArrayList<>();for(JsonObject original:items){check(fid);JsonObject item=original.deepCopy();if(FlowArtifacts.included(item)){JsonObject asset=store.read(c->FlowArtifacts.selected(c,item,candidate));if(Json.bool(parameters,"onlyConfirmed",false)&&!Json.str(asset,"status","").equals("confirmed")){item.addProperty("outcome","excluded");item.addProperty("reason","not_confirmed");}else{FlowArtifacts.checkFile(item);selected.add(asset);paths.put(Json.required(asset,"id"),Path.of(Json.required(item,"inputPath")));item.add("selectedVersion",asset.get("version"));}}output.add(item);}
        JsonObject existing=store.read(c->{JsonObject current=Store.document(c,"flow_steps",rowId);return current.has("exportId")?Store.one(c,"SELECT data FROM exports WHERE id=?",Json.required(current,"exportId")):null;});JsonObject record=existing==null?null:Json.parse(existing.get("data").getAsString());
        if(record==null||!Json.str(record,"status","").equals("completed")){String exportId=Json.id();store.tx(c->{JsonObject current=Store.document(c,"flow_steps",rowId);current.addProperty("exportId",exportId);Flows.saveStep(c,current);return null;});record=engine.exporter.createFixed(parameters,new Exporter.Snapshot(project,selected,paths,Json.required(project,"taskType")),exportId,()->flows.canContinue(fid),fid,sid);}
        String exportId=Json.required(record,"id");check(fid);return store.tx(c->{String id=FlowArtifacts.create(c,flow,sid,"export",output,false);return FlowArtifacts.seal(c,id,Json.obj("exportId",exportId));});
    }
}
