package cn.autolabel.engine;

import com.google.gson.*;
import java.sql.Connection;
import java.time.Instant;
import java.util.*;

/** 复用独立输入结果，父图聚合始终重新执行并生成独立版本。 */
final class InputResultReuse {
    final Engine engine;final Store store;
    InputResultReuse(Engine engine){this.engine=engine;store=engine.store;}
    record Prepared(String fingerprint,JsonObject context,JsonObject run,JsonObject sample,long maxAge){}
    record Match(JsonObject result,JsonObject sourceRun,JsonObject sourceSample,JsonObject provenance){}
    static JsonObject runtimeIdentity(JsonObject environment){JsonObject identity=new JsonObject();for(String field:List.of("pythonVersion","ultralyticsVersion","torchVersion","cudaAvailable","onnxruntimeVersion","numpyVersion","opencvVersion"))if(environment.has(field))identity.add(field,environment.get(field));return identity;}
    Prepared api(JsonObject run,JsonObject row,JsonObject body,Providers.Credential credential)throws Exception{
        if(!Json.bool(run,"inputResults",false)||Json.integer(row,"attempt_count",0)!=0)return null;JsonObject sample=Json.parse(row.get("data").getAsString()),alias=sample.deepCopy(),aliasRow=row.deepCopy();alias.addProperty("assetId",RunInputs.inputId(sample));aliasRow.addProperty("asset_id",RunInputs.inputId(sample));aliasRow.addProperty("data",alias.toString());CandidateReuse.Prepared fixed=engine.runs.reuse.prepareAttempt(run,aliasRow,body,credential.bindingVersion);if(fixed==null)return null;
        return prepared(run,sample,Json.obj("source","api","actualRequestFingerprint",fixed.fingerprint(),"credentialBindingVersion",credential.bindingVersion));
    }
    Prepared local(JsonObject run,JsonObject sample)throws Exception{
        JsonObject local=Json.object(Json.object(run,"snapshot"),"local"),model=Json.object(local,"model"),p=Json.object(local,"parameters");if(!Json.bool(Json.object(local,"environment"),"available",false))return null;for(String field:List.of("pythonVersion","ultralyticsVersion","torchVersion","onnxruntimeVersion","numpyVersion","opencvVersion"))if(!Json.object(local,"environment").has(field))return null;JsonObject settings=Json.obj("classMap",p.get("classMap"),"confidence",Json.decimal(p,"confidence",.25),"iou",Json.decimal(p,"iou",.7),"imageSize",Json.integer(p,"imageSize",640),"maxDetections",Json.integer(p,"maxDetections",300));JsonObject environment=new JsonObject();for(String field:List.of("pythonVersion","ultralyticsVersion","torchVersion","cudaAvailable","onnxruntimeVersion","numpyVersion","opencvVersion"))if(Json.object(local,"environment").has(field))environment.add(field,Json.object(local,"environment").get(field));
        return prepared(run,sample,Json.obj("source","local","modelId",model.get("id"),"modelVersion",model.get("version"),"modelHash",model.get("modelHash"),"workerHash",local.get("workerHash"),"requestedDevice",local.get("requestedDevice"),"parameters",settings,"environment",environment));
    }
    private Prepared prepared(JsonObject run,JsonObject sample,JsonObject context)throws Exception{
        RunInputs.image(store,engine.projects,Json.obj("inputId",RunInputs.inputId(sample)));JsonObject baseline=store.read(c->RunInputs.baseline(c,Json.required(run,"id"),Json.required(sample,"assetId"))),input=RunInputs.publicSnapshot(Json.object(sample,"inputSnapshot"));input.remove("inputId");JsonObject snapshot=Json.object(run,"snapshot");context.addProperty("version","input-result-reuse-v2");context.add("input",input);context.add("baseline",RunInputs.identity(Json.object(baseline,"asset")));context.add("classConvention",TaskTemplates.classConvention(Json.object(snapshot,"project")));
        // 「提示口径」（reuseScope=hint）下提示词与模板提示只记录不比对：来源运行的快照里都留着，想查随时查得到。
        if(!Json.str(run,"reuseScope","template").equals("hint"))context.add("template",TaskTemplates.semantic(Json.object(snapshot,"project")));
        context.addProperty("validatorVersion",TaskTemplates.VALIDATOR_VERSION);context.addProperty("mappingVersion",TransformGeometry.MAPPING_VERSION);long age=run.has("reuseMaxAgeSeconds")&&!run.get("reuseMaxAgeSeconds").isJsonNull()?Math.multiplyExact(run.get("reuseMaxAgeSeconds").getAsLong(),1000):Long.MAX_VALUE;return new Prepared(RunInputs.hash(Json.element(CandidateReuse.canonical(context))),context,run.deepCopy(),sample.deepCopy(),age);
    }
    static boolean enabled(Prepared prepared){return prepared!=null&&Json.bool(prepared.run,"reuseEnabled",true)&&!Json.bool(prepared.run,"forceRerun",false)&&!Json.bool(prepared.sample,"retryRequested",false);}
    Match find(Prepared prepared)throws Exception{
        if(!enabled(prepared))return null;List<JsonObject> ids=store.read(c->Store.rows(c,"SELECT i.id FROM input_results i JOIN runs r ON r.id=i.run_id WHERE i.status='succeeded' AND i.source IN ('api','local') AND i.run_id<>? AND r.project_id=? AND json_extract(i.data,'$.reuseFingerprint')=? ORDER BY i.created_at DESC,i.rowid DESC LIMIT 64",Json.required(prepared.run,"id"),Json.required(prepared.run,"projectId"),prepared.fingerprint));
        for(JsonObject id:ids){Match found=store.read(c->checked(c,prepared,Json.required(id,"id")));if(found==null)continue;try{RunInputs.image(store,engine.projects,Json.obj("inputId",RunInputs.inputId(found.sourceSample)));}catch(Exception unavailable){continue;}return found;}return null;
    }
    Match checked(Connection c,Prepared prepared,String resultId)throws Exception{
        JsonObject row=Store.one(c,"SELECT i.data,r.data AS run,s.data AS sample,s.status AS sample_status,s.run_id,s.asset_id,s.input_id FROM input_results i JOIN samples s ON s.id=i.sample_id JOIN runs r ON r.id=i.run_id WHERE i.id=?",resultId);if(row==null)return null;JsonObject result=Json.parse(row.get("data").getAsString()),run=Json.parse(row.get("run").getAsString()),sample=Json.parse(row.get("sample").getAsString());String source=Json.str(result,"source","");
        if(!Set.of("api","local").contains(source)||!Json.str(result,"status","").equals("succeeded")||Json.bool(result,"requiresGeometryReview",true)||!prepared.fingerprint.equals(Json.str(result,"reuseFingerprint",""))||!prepared.context.equals(result.get("reuseContext"))||!Json.required(prepared.run,"projectId").equals(Json.str(run,"projectId",""))||Json.str(run,"status","").equals("cancelled"))return null;
        if(!Json.str(row,"sample_status","").equals("succeeded")||!resultId.equals(Json.str(sample,"resultId",""))||!Json.required(result,"runId").equals(Json.str(row,"run_id",""))||!Json.required(result,"sampleId").equals(Json.str(sample,"id",""))||!Json.required(result,"assetId").equals(Json.str(row,"asset_id",""))||!Json.required(result,"inputId").equals(Json.str(row,"input_id","")))return null;
        long created;try{created=Instant.parse(Json.required(result,"createdAt")).toEpochMilli();}catch(Exception invalid){return null;}long age=System.currentTimeMillis()-created;if(age<0||age>prepared.maxAge)return null;
        if(source.equals("api")){String attempt=Json.str(result,"attemptId",null);if(attempt==null)return null;JsonObject actual=Store.one(c,"SELECT status,run_id,sample_id,data FROM attempts WHERE id=?",attempt);if(actual==null||!Json.str(actual,"status","").equals("completed")||!Json.required(result,"runId").equals(Json.str(actual,"run_id",""))||!Json.required(result,"sampleId").equals(Json.str(actual,"sample_id",""))||!prepared.fingerprint.equals(Json.str(Json.parse(actual.get("data").getAsString()),"inputReuseFingerprint","")))return null;}
        if(source.equals("local")){JsonObject local=Json.object(Json.object(run,"snapshot"),"local"),actual=Json.object(result,"provenance");if(!runtimeIdentity(Json.object(local,"environment")).equals(runtimeIdentity(Json.object(actual,"environment")))||!Json.required(Json.object(local,"model"),"modelHash").equals(Json.str(actual,"modelHash",""))||!Json.required(local,"workerHash").equals(Json.str(actual,"workerHash","")))return null;}if(!result.has("rawResult")||!result.get("rawResult").isJsonObject()||!result.has("annotations")||!result.get("annotations").isJsonArray())return null;JsonObject baseline=RunInputs.baseline(c,Json.required(prepared.run,"id"),Json.required(prepared.sample,"assetId"));try{Annotations.validate(Json.array(result,"annotations"),RunInputs.inputAsset(prepared.sample,baseline),Json.object(Json.object(prepared.run,"snapshot"),"project"));}catch(ApiError invalid){return null;}
        JsonObject provenance=Json.obj("sourceResultId",resultId,"sourceRunId",result.get("runId"),"sourceSampleId",result.get("sampleId"),"sourceInputId",result.get("inputId"),"sourceAssetId",result.get("assetId"),"source",source,"sourceCompletedAt",result.get("createdAt"),"sourceModel",run.get("model"),"reuseFingerprint",prepared.fingerprint);if(result.has("attemptId"))provenance.add("sourceAttemptId",result.get("attemptId"));if(source.equals("local")){JsonObject local=Json.object(Json.object(run,"snapshot"),"local"),model=Json.object(local,"model");provenance.add("sourceModelId",model.get("id"));provenance.add("sourceModelVersion",model.get("version"));provenance.add("sourceModelHash",model.get("modelHash"));provenance.add("sourceWorkerHash",local.get("workerHash"));provenance.add("sourceRequestedDevice",local.get("requestedDevice"));JsonObject original=Json.object(result,"provenance");if(original.has("observedBackend"))provenance.add("sourceObservedBackend",original.get("observedBackend"));}return new Match(result,run,sample,provenance);
    }
    boolean apply(Prepared prepared,String claim)throws Exception{
        Match found=find(prepared);if(found==null)return false;JsonObject source=found.result,result=engine.runResults.result(prepared.run,prepared.sample,"reuse",null,Json.object(source,"rawResult").deepCopy(),Json.obj("reusedFrom",found.provenance),null);if(!Json.required(result,"status").equals("succeeded"))return false;attach(result,prepared);result.add("inputReusedFrom",found.provenance);
        boolean saved=engine.runResults.save(prepared.run,prepared.sample,claim,result,c->{if(!engine.runs.dispatchAllowed()||!Json.required(Store.document(c,"runs",Json.required(prepared.run,"id")),"status").equals("running")||!TaskTemplates.classConvention(Store.document(c,"projects",Json.required(prepared.run,"projectId"))).equals(TaskTemplates.classConvention(Json.object(Json.object(prepared.run,"snapshot"),"project"))))return false;JsonObject snapshot=Json.object(prepared.run,"snapshot");if(Json.str(prepared.run,"kind","api").equals("local")){if(!engine.localRuntime.authorizationMatches(Json.object(Json.object(snapshot,"local"),"model")))throw new ApiError(403,"local_model_authorization_required","模型执行授权已变化。");}else engine.providers.credentialFor(Json.object(snapshot,"provider"),snapshot);return checked(c,prepared,Json.required(found.result,"id"))!=null;});if(saved)engine.runResults.aggregate(Json.required(prepared.run,"id"),Json.required(prepared.sample,"assetId"));return saved;
    }
    static void attach(JsonObject result,Prepared prepared){if(prepared==null)return;result.addProperty("reuseFingerprint",prepared.fingerprint);result.add("reuseContext",prepared.context);}
}
