package cn.autolabel.engine;

import com.google.gson.*;
import java.sql.Connection;
import java.util.*;

final class LocalRuns implements AutoCloseable {
    final Engine engine;final Store store;volatile boolean closed;
    LocalRuns(Engine engine){this.engine=engine;store=engine.store;}
    JsonObject create(JsonObject p)throws Exception{
        FlowPlans.keys(p,"projectId","assetIds","modelId","modelVersion","device","classMap","textClasses","confidence","iou","imageSize","maxDetections","timeoutMs","failurePolicy","reuseEnabled","forceRerun","reuseMaxAgeSeconds");String projectId=FlowPlans.string(p,"projectId",128);JsonObject project=store.read(c->Store.document(c,"projects",projectId));if(Json.array(project,"classes").isEmpty())throw new ApiError(422,"classes_required","请先配置标注类别。");JsonObject parameters=p.deepCopy();for(String field:List.of("projectId","assetIds","failurePolicy"))parameters.remove(field);JsonObject local=engine.localRuntime.freeze(parameters,project);List<JsonObject> items=store.read(c->{Set<String> selected=p.has("assetIds")?FlowPlans.ids(p,"assetIds",10000,false):null;List<JsonObject> result=new ArrayList<>();List<Object> args=new ArrayList<>();args.add(projectId);String sql="SELECT data,path FROM assets WHERE project_id=?";if(selected!=null){sql+=" AND id IN ("+String.join(",",Collections.nCopies(selected.size(),"?"))+")";args.addAll(selected);}for(JsonObject row:Store.rows(c,sql+" ORDER BY rowid LIMIT 10001",args.toArray())){JsonObject asset=Json.parse(row.get("data").getAsString());if(selected==null||selected.contains(Json.required(asset,"id")))result.add(FlowArtifacts.assetItem(c,asset,Json.required(row,"path")));}if(result.isEmpty()||result.size()>10000||selected!=null&&result.size()!=selected.size())throw new ApiError(422,"local_inputs_invalid","请选择当前项目内 1 至 10000 个固定输入。");return result;});String policy=Json.str(p,"failurePolicy","continue");if(!Set.of("continue","pause").contains(policy))throw new ApiError(400,"failure_policy_invalid","失败策略须为 continue 或 pause。");return store.tx(c->{String id=insert(c,project,local,items,policy,null,null);return engine.runs.view(c,id,true);});
    }
    String insert(Connection c,JsonObject project,JsonObject local,List<JsonObject> items,String policy,String flowId,String stepId)throws Exception{
        if(items.isEmpty()||items.size()>10000)throw new ApiError(422,"local_inputs_invalid","本地执行须有 1 至 10000 个固定输入。");String id=Json.id();JsonObject model=Json.object(local,"model"),run=Json.obj("id",id,"projectId",project.get("id"),"name","本地标注 · "+Json.required(model,"name"),"kind","local","status","running","createdAt",Json.now(),"updatedAt",Json.now(),"modelId",model.get("id"),"modelVersion",model.get("version"),"model",model.get("name"),"device",local.get("requestedDevice"),"total",items.size(),"requestsUsed",0,"reused",0,"retries",0,"concurrency",1,"failurePolicy",policy,"snapshot",Json.obj("project",project.deepCopy(),"local",local.deepCopy(),"validatorVersion",TaskTemplates.VALIDATOR_VERSION,"normalizationVersion",Media.NORMALIZATION_VERSION));JsonObject policyParameters=Json.object(local,"parameters");for(String field:List.of("reuseEnabled","forceRerun","reuseMaxAgeSeconds"))if(policyParameters.has(field))run.add(field,policyParameters.get(field));if(flowId!=null){run.addProperty("flowRunId",flowId);run.addProperty("stepId",stepId);}Store.update(c,"INSERT INTO runs(id,project_id,status,data) VALUES(?,?,?,?)",id,Json.required(project,"id"),"running",run);
        Set<String> inputs=new HashSet<>();for(JsonObject item:items){RunInputs.insertBaseline(c,id,item);JsonObject baseline=RunInputs.baseline(c,id,Json.required(item,"assetId")),input=RunInputs.snapshot(item);String inputId=Json.required(input,"inputId");if(!inputs.add(inputId))throw new ApiError(409,"input_identity_duplicate","一个运行不能重复处理同一输入身份。");JsonObject sample=Json.obj("id",Json.id(),"assetId",item.get("assetId"),"inputId",inputId,"name",Json.str(item,"name",Json.str(Json.object(baseline,"asset"),"name",inputId)),"baseVersion",Json.object(baseline,"asset").get("version"),"inputPath",item.get("inputPath"),"inputSnapshot",input);
                // 样本必须带上基准素材快照，与云端运行保持一致：评测的可比性检查读的就是它。
                // 少了这一份，本机结果即便写进了候选版本，也会被判成「运行素材与固定评测集不一致」。
                sample.add("asset",Json.object(baseline,"asset").deepCopy());Store.update(c,"INSERT INTO samples(id,run_id,asset_id,input_id,status,data) VALUES(?,?,?,?,?,?)",Json.required(sample,"id"),id,Json.required(sample,"assetId"),inputId,"queued",sample);}Store.event(c,"run.created",id,null,null,Json.obj("kind","local","total",items.size(),"requestsUsed",0));return id;
    }
    void tick(){if(closed||!engine.runs.dispatchAllowed())return;try{List<JsonObject> runs=store.read(c->Store.rows(c,"SELECT data FROM runs WHERE status='running' AND json_extract(data,'$.kind')='local' ORDER BY rowid LIMIT 100"));for(JsonObject value:runs){JsonObject run=Json.parse(value.get("data").getAsString());String id=Json.required(run,"id");JsonObject row=store.read(c->Store.one(c,"SELECT * FROM samples WHERE run_id=? AND status='queued' ORDER BY rowid LIMIT 1",id));if(row==null){engine.runResults.schedulePending(id);settle(id);continue;}String sampleId=Json.required(row,"id"),inputId=Json.required(row,"input_id"),claim=Json.id();LocalRuntime.Slot slot;
                try{slot=engine.localRuntime.reserve(Json.required(run,"device"),id,inputId);}catch(ApiError error){engine.runs.pauseBudget(id,error.code);continue;}if(slot==null)continue;boolean claimed;try{claimed=store.tx(c->{if(!Json.required(Store.document(c,"runs",id),"status").equals("running"))return false;int changed=Store.update(c,"UPDATE samples SET status='preparing',active_attempt=? WHERE id=? AND status='queued'",claim,sampleId);if(changed==1)Store.event(c,"sample.preparing",id,Json.required(row,"asset_id"),null,Json.obj("inputId",inputId,"source","local"));return changed==1;});}catch(Exception error){engine.localRuntime.release(slot);throw error;}if(!claimed){engine.localRuntime.release(slot);continue;}try{slot.execute(()->execute(run,row,claim,slot));}catch(ApiError error){engine.runs.releasePreparation(id,sampleId,claim,0);}return;}
        }catch(ApiError error){if(!error.code.startsWith("storage_"))System.err.println("local_dispatch_failed:"+error.code);}catch(Exception error){System.err.println("local_dispatch_failed:internal_error");}}
    void execute(JsonObject run,JsonObject row,String claim,LocalRuntime.Slot slot){String runId=Json.required(run,"id"),assetId=Json.required(row,"asset_id"),sampleId=Json.required(row,"id");JsonObject sample=Json.parse(row.get("data").getAsString());boolean predictStarted=false;InputResultReuse.Prepared reusePrepared=null;try{
            JsonObject snapshot=Json.object(run,"snapshot"),local=Json.object(snapshot,"local"),model=Json.object(local,"model"),parameters=Json.object(local,"parameters");engine.localRuntime.requireAuthorized(model);if(!ready(runId)){engine.runs.releasePreparation(runId,sampleId,claim,0);return;}JsonObject loaded;synchronized(engine.localRuntime){loaded=slot.loaded==null?null:slot.loaded.deepCopy();}if(loaded==null||!Json.required(model,"modelHash").equals(Json.str(loaded,"modelHash",""))||Json.integer(model,"version",0)!=Json.integer(loaded,"modelVersion",-1)||!Json.required(model,"id").equals(Json.str(loaded,"modelId","")))engine.localRuntime.load(slot,model,LocalRuntime.timeout(parameters,120000));synchronized(engine.localRuntime){loaded=slot.loaded.deepCopy();}if(!Json.required(local,"workerHash").equals(Json.str(loaded,"workerHash","")))throw new ApiError(409,"local_worker_changed","本地组件版本与运行快照不一致，请新建运行。");engine.localRuntime.requireAuthorized(model);if(!ready(runId)){engine.runs.releasePreparation(runId,sampleId,claim,0);return;}
            if(!InputResultReuse.runtimeIdentity(Json.object(local,"environment")).equals(InputResultReuse.runtimeIdentity(Json.object(loaded,"environment"))))throw new ApiError(409,"local_environment_changed","当前本地环境版本与运行快照不同，请新建运行或恢复原环境。");reusePrepared=engine.inputReuse.local(run,sample);if(reusePrepared!=null&&engine.inputReuse.apply(reusePrepared,claim))return;JsonObject baseline=store.read(c->RunInputs.baseline(c,runId,assetId)),inputAsset=RunInputs.inputAsset(sample,baseline),request=parameters.deepCopy();for(String field:List.of("modelId","modelVersion","device","timeoutMs","reuseEnabled","forceRerun","reuseMaxAgeSeconds"))request.remove(field);request.addProperty("requestId",claim);request.addProperty("assetId",RunInputs.inputId(sample));request.add("imagePath",sample.get("inputPath"));request.add("expectedModelHash",model.get("modelHash"));request.add("expectedInputHash",inputAsset.get("contentHash"));boolean dispatch=store.tx(c->{if(!ready(c,runId))return false;Store.update(c,"UPDATE samples SET status='waiting' WHERE id=? AND active_attempt=?",sampleId,claim);Store.event(c,"sample.waiting",runId,assetId,null,Json.obj("inputId",RunInputs.inputId(sample),"source","local"));return true;});if(!dispatch){engine.runs.releasePreparation(runId,sampleId,claim,0);return;}
            predictStarted=true;LocalInference.Prediction prediction=slot.bridge.predict(request,inputAsset,Json.object(snapshot,"project"),LocalRuntime.timeout(parameters,120000),event->store.tx(c->{Store.event(c,"local.progress",runId,assetId,null,Json.obj("inputId",RunInputs.inputId(sample),"progress",event));return null;}));JsonObject result=engine.runResults.result(run,sample,"local",null,prediction.rawResult(),prediction.provenance(),null);InputResultReuse.attach(result,reusePrepared);if(engine.runResults.save(run,sample,claim,result))engine.runResults.aggregate(runId,assetId);
        }catch(Exception error){try{if(closed||!engine.runs.dispatchAllowed()&&!predictStarted){engine.runs.releasePreparation(runId,sampleId,claim,0);return;}if(error instanceof ApiError a&&Set.of("local_model_authorization_required","local_model_changed","local_worker_changed","local_python_required","local_environment_changed").contains(a.code)){engine.runs.pauseBudget(runId,a.code);engine.runs.releasePreparation(runId,sampleId,claim,0);return;}JsonObject result=engine.runResults.result(run,sample,"local",null,null,Json.obj("executionId",claim),error);if(engine.runResults.save(run,sample,claim,result))engine.runResults.aggregate(runId,assetId);}catch(Exception storage){System.err.println("local_result_not_saved");}}
        finally{try{settle(runId);}catch(Exception ignored){System.err.println("local_settle_failed");}}
    }
    boolean ready(String runId){return !closed&&engine.runs.dispatchAllowed()&&store.read(c->ready(c,runId));}
    boolean ready(Connection c,String runId)throws Exception{return !closed&&engine.runs.dispatchAllowed()&&Json.required(Store.document(c,"runs",runId),"status").equals("running");}
    void settle(String runId){store.tx(c->{JsonObject run=Store.document(c,"runs",runId);if(!Json.required(run,"status").equals("running"))return null;JsonObject stats=Json.object(engine.runs.view(c,runId,false),"statistics");for(String field:List.of("queued","preparing","sending","waiting","parsing","validating","saving","retry_wait"))if(Json.integer(stats,field,0)>0)return null;if(!RunResults.aggregated(c,runId))return null;boolean review=Store.one(c,"SELECT r.id FROM run_asset_results r WHERE r.run_id=? AND r.status='needs_attention' AND r.rowid=(SELECT MAX(x.rowid) FROM run_asset_results x WHERE x.run_id=r.run_id AND x.asset_id=r.asset_id) LIMIT 1",runId)!=null;String status=Json.integer(stats,"unknown",0)>0?"needs_attention":Json.integer(stats,"failed",0)>0||review?"completed_with_errors":"completed";run.addProperty("status",status);run.addProperty("completedAt",Json.now());Store.update(c,"UPDATE runs SET status=?,data=? WHERE id=?",status,run,runId);Store.event(c,"run."+status,runId,null,null,Json.obj("statistics",stats));return null;});}
    void cancel(String runId){JsonObject run=store.read(c->Store.document(c,"runs",runId));if(Json.str(run,"kind","api").equals("local"))engine.localRuntime.cancel(runId);}
    void cancelFlow(String flowId){for(JsonObject row:store.read(c->Store.rows(c,"SELECT id FROM runs WHERE json_extract(data,'$.flowRunId')=? AND json_extract(data,'$.kind')='local'",flowId)))engine.localRuntime.cancel(Json.required(row,"id"));}
    @Override public void close(){closed=true;engine.localRuntime.close();}
}
