package cn.autolabel.engine;

import com.google.gson.*;
import java.util.*;

final class Matching {
    static final String VERSION="max-cardinality-max-iou-v1";
    static String overlapMetric(String task){return switch(task){case "obb"->"rotated_iou";case "segment"->"polygon_iou";case "classify"->null;default->"bbox_iou";};}
    static String version(String task){return task.equals("classify")?"single-label-confusion-v1":Set.of("obb","segment").contains(task)?"max-cardinality-region-iou-v1":VERSION;}
    static String inferTask(JsonArray truth,JsonArray prediction){return !truth.isEmpty()?Json.required(truth.get(0).getAsJsonObject(),"type"):!prediction.isEmpty()?Json.required(prediction.get(0).getAsJsonObject(),"type"):"detect";}
    record Pair(int truth,int prediction,double iou){}
    private static final class Edge {int to,reverse,capacity;double cost;Edge(int to,int reverse,int capacity,double cost){this.to=to;this.reverse=reverse;this.capacity=capacity;this.cost=cost;}}
    private static void edge(List<List<Edge>> graph,int from,int to,double cost){Edge forward=new Edge(to,graph.get(to).size(),1,cost),backward=new Edge(from,graph.get(from).size(),0,-cost);graph.get(from).add(forward);graph.get(to).add(backward);}
    static double iou(JsonObject a,JsonObject b){String type=Json.required(a,"type");if(!type.equals(Json.required(b,"type")))return 0;if(Set.of("obb","segment").contains(type))return RegionGeometry.iou(RegionGeometry.region(a),RegionGeometry.region(b));if(type.equals("classify"))throw new ApiError(422,"evaluation_metric_invalid","分类任务不能使用几何 IoU。");JsonObject x=Json.object(a,"bbox"),y=Json.object(b,"bbox");double ax=Annotations.num(x,"x"),ay=Annotations.num(x,"y"),aw=Annotations.num(x,"width"),ah=Annotations.num(x,"height"),bx=Annotations.num(y,"x"),by=Annotations.num(y,"y"),bw=Annotations.num(y,"width"),bh=Annotations.num(y,"height");double intersection=Math.max(0,Math.min(ax+aw,bx+bw)-Math.max(ax,bx))*Math.max(0,Math.min(ay+ah,by+bh)-Math.max(ay,by));return intersection/(aw*ah+bw*bh-intersection);}
    static List<Pair> maximum(JsonArray truth,JsonArray prediction,double threshold){
        if(truth.size()+prediction.size()>1000)throw new ApiError(422,"evaluation_object_limit","单张真值与预测合计最多 1000 个对象。");
        Map<JsonObject,RegionGeometry.Region> regions=new IdentityHashMap<>();for(JsonArray array:List.of(truth,prediction))for(JsonElement e:array){JsonObject object=e.getAsJsonObject();if(Set.of("obb","segment").contains(Json.required(object,"type")))regions.put(object,RegionGeometry.region(object));}
        List<Integer> t=new ArrayList<>(),p=new ArrayList<>();for(int i=0;i<truth.size();i++)t.add(i);for(int i=0;i<prediction.size();i++)p.add(i);t.sort(Comparator.comparing(i->Json.required(truth.get(i).getAsJsonObject(),"id")));p.sort(Comparator.comparing(i->Json.required(prediction.get(i).getAsJsonObject(),"id")));
        int n=t.size(),m=p.size(),sink=n+m+1;List<List<Edge>> graph=new ArrayList<>();for(int i=0;i<=sink;i++)graph.add(new ArrayList<>());for(int i=0;i<n;i++)edge(graph,0,i+1,0);for(int j=0;j<m;j++)edge(graph,n+1+j,sink,0);
        for(int i=0;i<n;i++)for(int j=0;j<m;j++){JsonObject a=truth.get(t.get(i)).getAsJsonObject(),b=prediction.get(p.get(j)).getAsJsonObject();if(!Json.required(a,"classId").equals(Json.required(b,"classId"))||!Json.required(a,"type").equals(Json.required(b,"type")))continue;double overlap=regions.containsKey(a)?RegionGeometry.iou(regions.get(a),regions.get(b)):iou(a,b);if(overlap+1e-12>=threshold)edge(graph,i+1,n+1+j,1-overlap);}
        // 残量网络持续增广直到不能再配对；在最大基数约束下，最小费用对应最大总 IoU。
        while(true){double[] distance=new double[sink+1];Arrays.fill(distance,Double.POSITIVE_INFINITY);distance[0]=0;int[] previous=new int[sink+1],index=new int[sink+1];Arrays.fill(previous,-1);boolean[] queued=new boolean[sink+1];ArrayDeque<Integer> queue=new ArrayDeque<>();queue.add(0);queued[0]=true;
            while(!queue.isEmpty()){int vertex=queue.remove();queued[vertex]=false;for(int k=0;k<graph.get(vertex).size();k++){Edge e=graph.get(vertex).get(k);if(e.capacity>0&&distance[e.to]>distance[vertex]+e.cost+1e-12){distance[e.to]=distance[vertex]+e.cost;previous[e.to]=vertex;index[e.to]=k;if(!queued[e.to]){queued[e.to]=true;queue.add(e.to);}}}}
            if(previous[sink]<0)break;for(int v=sink;v!=0;v=previous[v]){Edge e=graph.get(previous[v]).get(index[v]);e.capacity--;graph.get(v).get(e.reverse).capacity++;}}
        List<Pair> result=new ArrayList<>();for(int i=0;i<n;i++)for(Edge e:graph.get(i+1))if(e.to>=n+1&&e.to<n+1+m&&e.capacity==0)result.add(new Pair(t.get(i),p.get(e.to-n-1),1-e.cost));return result;
    }
    static JsonObject evaluate(JsonArray truth,JsonArray prediction,double threshold,double diagonal){return evaluate(inferTask(truth,prediction),truth,prediction,threshold,diagonal);}
    static JsonObject evaluate(String task,JsonArray truth,JsonArray prediction,double threshold,double diagonal){
        if(task.equals("classify"))return classification(truth,prediction);
        List<Pair> matches=maximum(truth,prediction,threshold);Set<Integer> matchedTruth=new HashSet<>(),matchedPrediction=new HashSet<>();JsonArray pairs=new JsonArray(),missed=new JsonArray(),extra=new JsonArray();double overlapSum=0,centerSum=0,pointSum=0;int pairedPoints=0,missingPoints=0,unknownTruth=0,unmatchedObjectPoints=0,locatedTruth=0;
        if(task.equals("pose"))for(JsonElement e:truth)for(JsonElement k:Json.array(e.getAsJsonObject(),"keypoints"))if(Json.integer(k.getAsJsonObject(),"visibility",0)>0)locatedTruth++;else unknownTruth++;
        for(Pair match:matches){matchedTruth.add(match.truth);matchedPrediction.add(match.prediction);JsonObject a=truth.get(match.truth).getAsJsonObject(),b=prediction.get(match.prediction).getAsJsonObject();double[] ac=RegionGeometry.center(a),bc=RegionGeometry.center(b);double center=Math.hypot(ac[0]-bc[0],ac[1]-bc[1]);overlapSum+=match.iou;centerSum+=center;
            JsonArray errors=new JsonArray(),missingNames=new JsonArray();JsonArray tk=task.equals("pose")?Json.array(a,"keypoints"):new JsonArray(),pk=Json.array(b,"keypoints");for(int i=0;i<tk.size();i++){JsonObject gt=tk.get(i).getAsJsonObject();if(Json.integer(gt,"visibility",0)==0)continue;if(i>=pk.size()||Json.integer(pk.get(i).getAsJsonObject(),"visibility",0)==0){missingPoints++;missingNames.add(gt.get("name"));continue;}JsonObject pr=pk.get(i).getAsJsonObject();if(!Json.required(gt,"name").equals(Json.required(pr,"name")))throw new ApiError(422,"evaluation_input_mismatch","候选关键点名称或顺序与真值不符。");double error=Math.hypot(Annotations.num(gt,"x")-Annotations.num(pr,"x"),Annotations.num(gt,"y")-Annotations.num(pr,"y"));pairedPoints++;pointSum+=error;errors.add(Json.obj("index",i,"name",gt.get("name"),"errorPixels",error,"errorNormalized",error/diagonal));}
            pairs.add(Json.obj("truthId",a.get("id"),"predictionId",b.get("id"),"iou",match.iou,"centerErrorPixels",center,"keypointErrors",errors,"missingPredictedKeypoints",missingNames));}
        for(int i=0;i<truth.size();i++)if(!matchedTruth.contains(i)){JsonObject a=truth.get(i).getAsJsonObject();missed.add(a.get("id"));if(task.equals("pose"))for(JsonElement k:Json.array(a,"keypoints"))if(Json.integer(k.getAsJsonObject(),"visibility",0)>0)unmatchedObjectPoints++;}
        for(int i=0;i<prediction.size();i++)if(!matchedPrediction.contains(i))extra.add(prediction.get(i).getAsJsonObject().get("id"));
        JsonObject metrics=Json.obj("scorableTruthObjects",truth.size(),"scorablePredictedObjects",prediction.size(),"matchedObjects",matches.size(),"missedObjects",missed.size(),"extraObjects",extra.size(),"missedRate",ratio(missed.size(),truth.size()),"extraRate",ratio(extra.size(),prediction.size()),"meanMatchedIoU",ratio(overlapSum,matches.size()),"meanCenterErrorPixels",ratio(centerSum,matches.size()),"pairedKeypoints",pairedPoints,"locatedTruthKeypoints",locatedTruth,"missingPredictedKeypoints",missingPoints,"unmatchedObjectKeypoints",unmatchedObjectPoints,"ignoredUnknownTruthKeypoints",unknownTruth,"meanPointErrorPixels",ratio(pointSum,pairedPoints),"meanPointErrorNormalized",ratio(pointSum/diagonal,pairedPoints));
        metrics.addProperty("metricKind","object_overlap");metrics.addProperty("overlapMetric",overlapMetric(task));reasons(metrics);return Json.obj("metrics",metrics,"pairs",pairs,"unmatchedTruthIds",missed,"unmatchedPredictionIds",extra);
    }
    static Double ratio(double numerator,long denominator){return denominator==0?null:numerator/denominator;}
    static void reasons(JsonObject metrics){JsonObject reasons=new JsonObject();for(String key:List.of("missedRate","extraRate","meanMatchedIoU","meanCenterErrorPixels","meanPointErrorPixels","meanPointErrorNormalized"))if(metrics.get(key).isJsonNull())reasons.addProperty(key,"zero_denominator");metrics.add("notApplicableReasons",reasons);}
    static JsonObject aggregate(List<JsonObject> results,int totalTruth){return aggregate("detect",results,totalTruth);}
    static JsonObject aggregate(String task,List<JsonObject> results,int totalTruth){if(task.equals("classify"))return aggregateClassification(results,totalTruth);JsonObject counts=Json.obj("metricKind","object_overlap","overlapMetric",overlapMetric(task),"scorableSamples",0,"failedSamples",0,"unknownSamples",0,"pendingSamples",0,"missingSamples",0,"invalidSamples",0,"totalTruthObjects",totalTruth);for(String key:List.of("scorableTruthObjects","scorablePredictedObjects","matchedObjects","missedObjects","extraObjects","pairedKeypoints","locatedTruthKeypoints","missingPredictedKeypoints","unmatchedObjectKeypoints","ignoredUnknownTruthKeypoints"))counts.addProperty(key,0);
        double iou=0,center=0,pixels=0,normalized=0;for(JsonObject result:results){String status=Json.required(result,"status");if(!status.equals("scorable")){String key=Set.of("failed","unknown","pending","missing").contains(status)?status+"Samples":"invalidSamples";counts.addProperty(key,Json.integer(counts,key,0)+1);continue;}
            counts.addProperty("scorableSamples",Json.integer(counts,"scorableSamples",0)+1);JsonObject m=Json.object(result,"metrics");for(String key:List.of("scorableTruthObjects","scorablePredictedObjects","matchedObjects","missedObjects","extraObjects","pairedKeypoints","locatedTruthKeypoints","missingPredictedKeypoints","unmatchedObjectKeypoints","ignoredUnknownTruthKeypoints"))counts.addProperty(key,Json.number(counts,key,0)+Json.number(m,key,0));long matched=Json.number(m,"matchedObjects",0),paired=Json.number(m,"pairedKeypoints",0);iou+=Json.decimal(m,"meanMatchedIoU",0)*matched;center+=Json.decimal(m,"meanCenterErrorPixels",0)*matched;pixels+=Json.decimal(m,"meanPointErrorPixels",0)*paired;normalized+=Json.decimal(m,"meanPointErrorNormalized",0)*paired;}
        counts.add("missedRate",Json.element(ratio(Json.number(counts,"missedObjects",0),Json.number(counts,"scorableTruthObjects",0))));counts.add("extraRate",Json.element(ratio(Json.number(counts,"extraObjects",0),Json.number(counts,"scorablePredictedObjects",0))));counts.add("meanMatchedIoU",Json.element(ratio(iou,Json.number(counts,"matchedObjects",0))));counts.add("meanCenterErrorPixels",Json.element(ratio(center,Json.number(counts,"matchedObjects",0))));counts.add("meanPointErrorPixels",Json.element(ratio(pixels,Json.number(counts,"pairedKeypoints",0))));counts.add("meanPointErrorNormalized",Json.element(ratio(normalized,Json.number(counts,"pairedKeypoints",0))));reasons(counts);return counts;
    }
    static JsonObject classificationMetrics(int samples,int correct,int incorrect,int missing,JsonArray confusion){
        JsonObject metrics=Json.obj("metricKind","classification","overlapMetric",null,"classification",Json.obj("samples",samples,"correct",correct,"incorrect",incorrect,"missingPrediction",missing,"accuracy",ratio(correct,samples),"confusion",confusion)),reasons=new JsonObject();
        for(String key:List.of("scorableTruthObjects","scorablePredictedObjects","matchedObjects","missedObjects","extraObjects","missedRate","extraRate","meanMatchedIoU","meanCenterErrorPixels","pairedKeypoints","locatedTruthKeypoints","missingPredictedKeypoints","unmatchedObjectKeypoints","ignoredUnknownTruthKeypoints","meanPointErrorPixels","meanPointErrorNormalized","totalTruthObjects")){metrics.add(key,JsonNull.INSTANCE);reasons.addProperty(key,"task_not_applicable");}if(samples==0)reasons.addProperty("classification.accuracy","zero_denominator");metrics.add("notApplicableReasons",reasons);return metrics;
    }
    static JsonObject classification(JsonArray truth,JsonArray prediction){if(truth.size()!=1)throw new ApiError(422,"evaluation_classification_truth_required","分类评测的人工真值必须恰好包含一个类别。");if(prediction.size()>1)throw Annotations.error("分类候选至多包含一个类别。");String actual=Json.required(truth.get(0).getAsJsonObject(),"classId"),predicted=prediction.isEmpty()?null:Json.required(prediction.get(0).getAsJsonObject(),"classId");boolean correct=actual.equals(predicted),missing=predicted==null;
        JsonObject metrics=classificationMetrics(1,correct?1:0,!correct&&!missing?1:0,missing?1:0,Json.arr(Json.obj("truthClassId",actual,"predictionClassId",predicted,"count",1)));metrics.addProperty("totalTruthLabels",1);return Json.obj("metrics",metrics,"classResult",Json.obj("truthClassId",actual,"predictionClassId",predicted,"correct",correct,"missingPrediction",missing),"pairs",new JsonArray(),"unmatchedTruthIds",new JsonArray(),"unmatchedPredictionIds",new JsonArray());}
    record Classes(String truth,String prediction){}
    static JsonObject aggregateClassification(List<JsonObject> results,int totalTruth){
        int samples=0,correct=0,incorrect=0,missing=0;Map<Classes,Integer> confusion=new TreeMap<>(Comparator.comparing(Classes::truth).thenComparing(Classes::prediction,Comparator.nullsFirst(Comparator.naturalOrder())));JsonObject states=Json.obj("scorableSamples",0,"failedSamples",0,"unknownSamples",0,"pendingSamples",0,"missingSamples",0,"invalidSamples",0);
        for(JsonObject result:results){String status=Json.required(result,"status");if(!status.equals("scorable")){String key=Set.of("failed","unknown","pending","missing").contains(status)?status+"Samples":"invalidSamples";states.addProperty(key,Json.integer(states,key,0)+1);continue;}samples++;JsonObject value=Json.object(result,"classResult");if(Json.bool(value,"correct",false))correct++;else if(Json.bool(value,"missingPrediction",false))missing++;else incorrect++;Classes pair=new Classes(Json.required(value,"truthClassId"),Json.str(value,"predictionClassId",null));confusion.merge(pair,1,Integer::sum);}
        JsonArray cells=new JsonArray();confusion.forEach((pair,count)->cells.add(Json.obj("truthClassId",pair.truth,"predictionClassId",pair.prediction,"count",count)));JsonObject metrics=classificationMetrics(samples,correct,incorrect,missing,cells);states.addProperty("scorableSamples",samples);for(var value:states.entrySet())metrics.add(value.getKey(),value.getValue());metrics.addProperty("totalTruthLabels",totalTruth);return metrics;
    }
}
