package cn.autolabel.engine;

import com.google.gson.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.Connection;
import java.util.*;
import java.util.concurrent.*;

/** 媒体处理只占用一个有界执行资源；文件完成与素材事务提交分别持久化。 */
final class MediaJobs implements AutoCloseable {
    private static final Set<String> ACTIVE=Set.of("queued","running","cancelling");
    private static final Set<String> RETRYABLE=Set.of("cancelled","failed","interrupted");
    private static final List<String> SECTIONS=List.of("items","exactGroups","nearPairs","sourceLeakageGroups");
    private static final long MAX_SAFE=9_007_199_254_740_991L;
    final Engine engine;final Store store;
    private final Object gate=new Object();
    private final ThreadPoolExecutor worker=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(1),Thread.ofPlatform().name("media-job-",0).factory(),new ThreadPoolExecutor.AbortPolicy());
    private volatile Path ffmpeg,ffprobe;
    private volatile VideoFrames bridge;
    private volatile String currentId;
    private volatile boolean cancelled,closed,committing;
    private long lastProgress;

    MediaJobs(Engine engine,JsonObject startup){
        this.engine=engine;store=engine.store;
        ffmpeg=startupPath(startup,"mediaFfmpegPath");ffprobe=startupPath(startup,"mediaFfprobePath");
        JsonArray interrupted=store.read(c->Store.docs(c,"SELECT data FROM media_jobs WHERE status IN ('queued','running','cancelling')"));for(JsonElement value:interrupted){JsonObject job=value.getAsJsonObject();recoverCompletedArtifact(job);store.tx(c->{job.addProperty("status","interrupted");job.add("error",Json.obj("code","media_restart_interrupted","message","引擎重启中断了媒体操作；已完成产物可校验后导入，其余可重新运行。"));save(c,job,"interrupted");return null;});}
    }
    private static Path startupPath(JsonObject p,String key){if(!p.has(key)||p.get(key).isJsonNull())return null;return executable(Json.required(p,key));}
    private static Path executable(String value){try{Path path=Path.of(value);if(!path.isAbsolute()||!Files.isRegularFile(path))throw new IOException();return path.toRealPath();}catch(Exception e){throw error(400,"media_tool_invalid","媒体工具必须是已存在的绝对文件路径。");}}
    JsonObject runtime(){synchronized(gate){return Json.obj("configured",ffmpeg!=null&&ffprobe!=null,"ffmpegConfigured",ffmpeg!=null,"ffprobeConfigured",ffprobe!=null,"busy",currentId!=null);}}
    JsonObject configure(JsonObject p){FlowPlans.keys(p,"ffmpegPath","ffprobePath");if(!p.has("ffmpegPath")||!p.has("ffprobePath"))throw error(400,"media_tool_invalid","请同时指定 FFmpeg 和 FFprobe 配置。");
        Path nextFfmpeg=p.get("ffmpegPath").isJsonNull()?null:executable(Json.required(p,"ffmpegPath")),nextFfprobe=p.get("ffprobePath").isJsonNull()?null:executable(Json.required(p,"ffprobePath"));
        synchronized(gate){if(currentId!=null)throw error(409,"media_busy","媒体资源正在使用，完成或取消后再配置工具。");ffmpeg=nextFfmpeg;ffprobe=nextFfprobe;return runtime();}}
    private VideoFrames bridge(){if(ffmpeg==null||ffprobe==null)throw error(422,"media_runtime_missing","请先配置 FFmpeg 和 FFprobe。");VideoFrames value=new VideoFrames(ffmpeg,ffprobe);bridge=value;return value;}

    JsonObject inspect(JsonObject p)throws Exception{
        FlowPlans.keys(p,"sourcePath","streamIndex");JsonObject request=Json.obj("sourcePath",source(p),"mode","interval","intervalSeconds",1,"ranges",Json.arr(Json.obj("start",0,"end",604800)),"maxFrames",10000);if(p.has("streamIndex"))request.add("streamIndex",p.get("streamIndex"));
        Future<JsonObject> pending;synchronized(gate){if(closed||currentId!=null)throw error(409,"media_busy","媒体资源正在使用，请稍后探测视频。");currentId=Json.id();cancelled=false;request.addProperty("jobId",currentId);
            pending=worker.submit(()->{try(VideoFrames helper=bridge()){JsonObject plan=helper.inspect(request,600000,inspectionControl());safeTimeBase(plan);JsonObject metadata=Json.object(plan,"sourceMetadata");Double duration=finitePositive(Json.str(metadata,"reportedDuration",null));Long count=positiveLong(Json.str(metadata,"reportedFrameCount",null));return Json.obj("sourceName",Path.of(Json.required(plan,"sourcePath")).getFileName().toString(),"sourceVideoId",plan.get("sourceVideoId"),"sourceHash",plan.get("sourceHash"),"streamIndex",plan.get("streamIndex"),"width",plan.get("outputWidth"),"height",plan.get("outputHeight"),"durationSeconds",duration,"reportedFrameRate",metadata.get("reportedFrameRate"),"reportedFrameCount",count,"timeBase",plan.get("timeBase"),"sampleAspectRatioAssumed",metadata.get("sampleAspectRatioAssumed"),"geometryNotice",metadata.get("geometryNotice"));}finally{release();}});
        }
        try{return pending.get();}catch(ExecutionException e){if(e.getCause() instanceof ApiError a)throw a;throw error(500,"media_inspect_failed","视频探测失败。");}catch(InterruptedException e){cancelActive();Thread.currentThread().interrupt();throw error(499,"media_cancelled","视频探测已中断。");}
    }
    private static Double finitePositive(String value){try{double v=Double.parseDouble(value);return Double.isFinite(v)&&v>0?v:null;}catch(Exception e){return null;}}
    private static Long positiveLong(String value){try{long v=Long.parseLong(value);return v>=0&&v<=MAX_SAFE?v:null;}catch(Exception e){return null;}}
    private void recoverCompletedArtifact(JsonObject job){
        // FFmpeg 已提交完成标记而数据库尚未记账的崩溃间隙，只恢复完整清单；导入仍逐帧复核。
        if(!Json.required(job,"kind").equals("video_extract")||Json.bool(job,"artifactCommitted",false)||!job.has("frozenPlan"))return;
        try{String id=Json.required(job,"id");Path directory=generation(id),complete=directory.resolve("complete.json"),manifest=directory.resolve("frames.jsonl");if(!Files.isRegularFile(complete)||Files.size(complete)>65536||!Files.isRegularFile(manifest)||Files.size(manifest)>64L*1024*1024)return;JsonObject summary=Json.parse(Files.readString(complete));if(!id.equals(Json.required(summary,"jobId"))||!Json.required(summary,"sourceHash").equals(Json.required(Json.object(job,"frozenPlan"),"sourceHash"))||!Media.hash(manifest).equals(Json.required(summary,"manifestHash")))return;summary.remove("manifestPath");job.addProperty("artifactCommitted",true);job.addProperty("manifestHash",Json.required(summary,"manifestHash"));job.addProperty("completeHash",Media.hash(complete));job.add("summary",summary);job.addProperty("stage","ready");}catch(Exception ignored){/* 不完整或损坏的目录不升级为已提交产物。 */}
    }
    private static String source(JsonObject p){String value=FlowPlans.string(p,"sourcePath",32767);Path path=Path.of(value);if(!path.isAbsolute()||!Files.isRegularFile(path))throw error(400,"video_source_missing","请选择已存在的本地视频文件。");return path.toAbsolutePath().normalize().toString();}
    static JsonObject videoParameters(JsonObject p){
        FlowPlans.keys(p,"streamIndex","ranges","mode","intervalSeconds","everyNFrames","targetFps","format","outputSize","jpegQuality","maxFrames","maxOutputBytes","timeoutMs");
        String mode=Json.str(p,"mode","");if(!Set.of("interval","every_n","fps").contains(mode))throw error(400,"video_parameters_invalid","请选择时间间隔、每 N 帧或目标帧率。");
        for(var entry:Map.of("intervalSeconds","interval","everyNFrames","every_n","targetFps","fps").entrySet())if(p.has(entry.getKey())&&!mode.equals(entry.getValue()))throw error(400,"video_parameters_invalid","不同抽样方式的专属参数不能混用。");
        if(!p.has("ranges")||!p.get("ranges").isJsonArray()||Json.array(p,"ranges").isEmpty()||Json.array(p,"ranges").size()>32)throw error(400,"video_ranges_invalid","请提供 1～32 个时间段。");
        double previous=-1;for(JsonElement element:Json.array(p,"ranges")){if(!element.isJsonObject())throw error(400,"video_ranges_invalid","时间段必须包含起止秒数。");JsonObject range=element.getAsJsonObject();FlowPlans.keys(range,"start","end");double start=number(range,"start",0,604800),end=number(range,"end",0,604800);if(end<=start||start<previous)throw error(400,"video_ranges_invalid","时间段须按时间排列，左闭右开且不能重叠。");previous=end;}
        if(mode.equals("interval"))number(p,"intervalSeconds",0.001,604800);if(mode.equals("fps"))number(p,"targetFps",0.001,240);if(mode.equals("every_n"))videoInteger(p,"everyNFrames",1,1000000);
        if(!Set.of("png","jpg").contains(Json.str(p,"format","png")))throw error(400,"video_parameters_invalid","图片格式应为 png 或 jpg。");
        JsonObject result=p.deepCopy();for(String key:List.of("streamIndex","jpegQuality","maxFrames","maxOutputBytes","timeoutMs"))if(p.has(key))videoInteger(p,key,key.equals("streamIndex")?0:key.equals("jpegQuality")?2:1,switch(key){case "streamIndex"->65535;case "jpegQuality"->31;case "maxFrames"->10000;case "timeoutMs"->86400000;default->MAX_SAFE;});
        if(p.has("outputSize")){if(!p.get("outputSize").isJsonObject())throw error(400,"video_parameters_invalid","输出尺寸无效。");JsonObject size=Json.object(p,"outputSize");FlowPlans.keys(size,"width","height","fit");long width=videoInteger(size,"width",1,20000),height=videoInteger(size,"height",1,20000);if(width*height>Media.MAX_PIXELS||!Set.of("contain","stretch").contains(Json.str(size,"fit","contain")))throw error(400,"video_parameters_invalid","输出尺寸或缩放方式无效。");}
        if(result.has("outputSize")&&!Json.object(result,"outputSize").has("fit"))Json.object(result,"outputSize").addProperty("fit","contain");for(var entry:Json.obj("format","png","jpegQuality",3,"maxFrames",10000,"maxOutputBytes",8L*1024*1024*1024,"timeoutMs",600000).entrySet())if(!result.has(entry.getKey()))result.add(entry.getKey(),entry.getValue());return result;
    }
    private static long videoInteger(JsonObject p,String key,long min,long max){try{return Costs.integer(p,key,min,max);}catch(ApiError e){throw error(400,"video_parameters_invalid",key+" 超出允许范围。");}}
    static JsonObject screeningParameters(JsonObject p){FlowPlans.keys(p,"deduplicate","nearEnabled","blurEnabled","nearMaxDistance","aspectRatioTolerance","maxComparisons","maxPairs","blurThreshold");return ImageScreening.policy(p);}
    private static double number(JsonObject p,String key,double min,double max){if(!p.has(key)||!p.get(key).isJsonPrimitive()||!p.getAsJsonPrimitive(key).isNumber())throw error(400,"video_parameters_invalid",key+" 必须为数值。");double value=p.get(key).getAsDouble();if(!Double.isFinite(value)||value<min||value>max)throw error(400,"video_parameters_invalid",key+" 超出允许范围。");return value;}
    private static void safeTimeBase(JsonObject plan){JsonObject time=Json.object(plan,"timeBase");for(String key:List.of("numerator","denominator"))Costs.integer(time,key,1,MAX_SAFE);}

    JsonObject createVideo(JsonObject p){FlowPlans.keys(p,"projectId","sourcePath","parameters","expectedSourceHash");JsonObject parameters=videoParameters(object(p,"parameters"));String path=source(p),pid=Json.required(p,"projectId");engine.projects.get(pid);if(ffmpeg==null||ffprobe==null)throw error(422,"media_runtime_missing","请先配置 FFmpeg 和 FFprobe。");
        JsonObject job=newJob(pid,"video_extract",parameters);job.addProperty("sourcePath",path);job.addProperty("sourceName",Path.of(path).getFileName().toString());if(p.has("expectedSourceHash")){String hash=Json.required(p,"expectedSourceHash");if(!hash.matches("[a-f0-9]{64}"))throw error(400,"video_source_hash_invalid","来源摘要无效。");job.addProperty("expectedSourceHash",hash);}return insert(job);
    }
    JsonObject createScreening(JsonObject p){FlowPlans.keys(p,"projectId","assetIds","parameters");String pid=Json.required(p,"projectId");JsonObject parameters=screeningParameters(object(p,"parameters"));
        JsonArray inputs=store.read(c->freeze(c,pid,p));JsonObject job=newJob(pid,"image_screening",parameters);job.add("privateInputs",inputs);job.add("progress",Json.obj("phase","queued","completed",0,"total",inputs.size()));return insert(job);
    }
    JsonObject createFrozenScreening(String pid,JsonArray inputs,JsonObject parameters){if(inputs.isEmpty()||inputs.size()>10000)throw error(422,"screening_input_scope_invalid","筛选须固定 1～10000 张基准图。");JsonObject job=newJob(pid,"image_screening",screeningParameters(parameters));job.add("privateInputs",inputs.deepCopy());return insert(job);}
    private static JsonObject object(JsonObject p,String key){if(!p.has(key)||!p.get(key).isJsonObject())throw error(400,"media_parameters_invalid",key+" 必须为对象。");return Json.object(p,key);}
    private JsonObject newJob(String pid,String kind,JsonObject parameters){return Json.obj("id",Json.id(),"projectId",pid,"kind",kind,"status","queued","stage","queued","operation",kind,"createdAt",Json.now(),"updatedAt",Json.now(),"parameters",parameters,"artifactCommitted",false,"assetsCommitted",false,"progress",Json.obj("phase","queued","completed",0,"total",null));}
    private JsonObject insert(JsonObject job){store.requireSpace(128L*1024*1024);return store.tx(c->{if(Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM media_jobs WHERE status IN ('queued','running','cancelling')"),"n",0)>=128)throw error(429,"media_queue_full","媒体排队任务已达到 128 个，请先完成或取消任务。");Store.update(c,"INSERT INTO media_jobs(id,project_id,kind,status,data) VALUES(?,?,?,?,?)",Json.required(job,"id"),Json.required(job,"projectId"),Json.required(job,"kind"),"queued",job);save(c,job,"created");return view(job);});}
    JsonArray freeze(Connection c,String pid,JsonObject p)throws Exception{
        Store.document(c,"projects",pid);Set<String> selected=p.has("assetIds")?FlowPlans.ids(p,"assetIds",10000,false):null;List<Object> arguments=new ArrayList<>(List.of(pid));String condition="project_id=?";if(selected!=null){condition+=" AND id IN ("+String.join(",",Collections.nCopies(selected.size(),"?"))+")";arguments.addAll(selected);}
        JsonArray inputs=new JsonArray();for(JsonObject row:Store.rows(c,"SELECT data,path FROM assets WHERE "+condition+" ORDER BY id LIMIT 10001",arguments.toArray())){
            JsonObject asset=Json.parse(Json.required(row,"data"));String aid=Json.required(asset,"id");boolean draft=Store.one(c,"SELECT asset_id FROM drafts WHERE asset_id=?",aid)!=null;inputs.add(frozenAsset(asset,Json.required(row,"path"),draft));
        }if(inputs.isEmpty()||inputs.size()>10000||selected!=null&&selected.size()!=inputs.size())throw error(422,"screening_input_scope_invalid","筛选须固定当前项目的 1～10000 张素材。");return inputs;
    }
    JsonObject frozenAsset(JsonObject asset,String path,boolean draft){
        JsonObject metadata=Json.object(asset,"metadata"),input=Json.obj("assetId",asset.get("id"),"contentHash",asset.get("contentHash"),"width",asset.get("width"),"height",asset.get("height"),"inputVersion",Json.integer(metadata,"inputVersion",1),"normalizationVersion",Json.str(metadata,"normalizationVersion",Media.NORMALIZATION_VERSION),"version",asset.get("version"),"status",draft?"modified":asset.get("status"),"draftProtected",draft,"name",asset.get("name"),"inputImage",relative(Path.of(path)),"metadata",publicMetadata(metadata));
        for(String field:List.of("sourceVideoId","groupId","partition"))if(metadata.has(field))input.add(field,metadata.get(field));return input;
    }
    static JsonObject publicMetadata(JsonObject metadata){JsonObject result=new JsonObject();for(String key:List.of("sourceVideoId","videoSourceHash","sourceHash","streamIndex","sourcePresentationIndex","sourcePts","originPts","relativePts","timeBase","timeSeconds","rangeIndex","bucketIndex","codedVideoToFrame","selectionVersion","frameId","mediaJobId","sceneId","groupId","partition"))if(metadata.has(key))result.add(key,metadata.get(key));return result;}
    private JsonObject view(JsonObject job){JsonObject result=new JsonObject();for(String field:List.of("id","projectId","kind","status","stage","sequence","createdAt","updatedAt","completedAt","originalJobId","sourceVideoId","sourceName","parameters","progress","summary","error","artifactCommitted","assetsCommitted"))if(job.has(field))result.add(field,job.get(field).deepCopy());String status=Json.required(job,"status");boolean active=ACTIVE.contains(status);result.addProperty("canCancel",active&&!status.equals("cancelling")&&!(Json.required(job,"id").equals(currentId)&&committing));result.addProperty("canRetry",RETRYABLE.contains(status));result.addProperty("canImport",Json.required(job,"kind").equals("video_extract")&&Json.bool(job,"artifactCommitted",false)&&!Json.bool(job,"assetsCommitted",false)&&!active);return result;}
    JsonObject get(String id){return store.read(c->view(Store.document(c,"media_jobs",id)));}
    JsonObject list(JsonObject p){FlowPlans.keys(p,"projectId","kind","limit","offset");int limit=Json.bounded(p,"limit",100,1,100),offset=Json.bounded(p,"offset",0,0,Integer.MAX_VALUE);return store.read(c->{List<Object> arguments=new ArrayList<>();String condition=" WHERE 1=1";for(String field:List.of("projectId","kind"))if(p.has(field)){condition+=" AND "+(field.equals("projectId")?"project_id":"kind")+"=?";arguments.add(Json.required(p,field));}long count=Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM media_jobs"+condition,arguments.toArray()),"n",0);arguments.add(limit);arguments.add(offset);JsonArray items=new JsonArray();for(JsonElement job:Store.docs(c,"SELECT data FROM media_jobs"+condition+" ORDER BY rowid DESC LIMIT ? OFFSET ?",arguments.toArray()))items.add(view(job.getAsJsonObject()));return Json.obj("items",items,"total",count);});}
    private static void save(Connection c,JsonObject job,String event)throws Exception{job.addProperty("updatedAt",Json.now());Store.event(c,"media.job."+event,null,null,null,Json.obj("jobId",job.get("id"),"projectId",job.get("projectId"),"kind",job.get("kind"),"status",job.get("status"),"stage",job.get("stage"),"progress",job.get("progress")));job.addProperty("sequence",Store.cursor(c));Store.update(c,"UPDATE media_jobs SET status=?,data=? WHERE id=?",Json.required(job,"status"),job,Json.required(job,"id"));}
    JsonObject cancel(JsonObject p){FlowPlans.keys(p,"jobId");String id=Json.required(p,"jobId");JsonObject result;synchronized(gate){result=store.tx(c->{JsonObject job=Store.document(c,"media_jobs",id);if(!ACTIVE.contains(Json.required(job,"status")))return view(job);if(id.equals(currentId)&&committing)throw error(409,"media_commit_in_progress","素材正在原子提交，请等待明确提交结果。");if(id.equals(currentId))cancelled=true;job.addProperty("status",id.equals(currentId)?"cancelling":"cancelled");if(!id.equals(currentId))job.addProperty("completedAt",Json.now());save(c,job,"cancelled");return view(job);});}if(id.equals(currentId)){VideoFrames helper=bridge;if(helper!=null)helper.cancel(id);}return result;}
    JsonObject retry(JsonObject p){FlowPlans.keys(p,"jobId");JsonObject original=store.read(c->Store.document(c,"media_jobs",Json.required(p,"jobId")));if(!RETRYABLE.contains(Json.required(original,"status")))throw error(409,"media_retry_invalid","只有失败、取消或中断的媒体任务可以重新运行。");JsonObject job=newJob(Json.required(original,"projectId"),Json.required(original,"kind"),Json.object(original,"parameters").deepCopy());for(String field:List.of("sourcePath","sourceName","expectedSourceHash","privateInputs"))if(original.has(field))job.add(field,original.get(field).deepCopy());job.addProperty("originalJobId",Json.required(original,"id"));return insert(job);}
    JsonObject importVideo(JsonObject p){FlowPlans.keys(p,"jobId");String id=Json.required(p,"jobId");synchronized(gate){return store.tx(c->{JsonObject job=Store.document(c,"media_jobs",id);if(!Json.required(job,"kind").equals("video_extract"))throw error(422,"media_job_kind_invalid","该任务不是视频抽帧任务。");if(Json.bool(job,"assetsCommitted",false))return view(job);if(ACTIVE.contains(Json.required(job,"status"))){if(Json.str(job,"operation","").equals("import"))return view(job);throw error(409,"media_job_not_ready","抽帧尚未完成。");}if(!Json.bool(job,"artifactCommitted",false))throw error(409,"media_artifact_incomplete","抽帧产物未完成，不能导入素材。");job.addProperty("status","queued");job.addProperty("stage","importing");job.addProperty("operation","import");job.remove("error");job.remove("completedAt");save(c,job,"import_queued");return view(job);});}}

    void tick(){synchronized(gate){if(closed||currentId!=null||!engine.runs.dispatchAllowed())return;JsonObject job=store.tx(c->{JsonObject row=Store.one(c,"SELECT data FROM media_jobs WHERE status='queued' ORDER BY rowid LIMIT 1");if(row==null)return null;JsonObject value=Json.parse(Json.required(row,"data"));value.addProperty("status","running");save(c,value,"started");return value;});if(job==null)return;currentId=Json.required(job,"id");cancelled=false;committing=false;lastProgress=0;worker.execute(()->execute(job));}}
    private void execute(JsonObject job){try{checkpoint();String operation=Json.required(job,"operation");switch(operation){case "video_extract"->extract(job);case "image_screening"->screen(job);case "import"->importFrames(job);default->throw error(422,"media_operation_invalid","媒体操作类型无效。");}}catch(Exception e){try{store.tx(c->{JsonObject value=Store.document(c,"media_jobs",Json.required(job,"id"));boolean stopped=cancelled||closed||e instanceof ApiError a&&a.status==499;value.addProperty("status",closed?"interrupted":stopped?"cancelled":"failed");value.addProperty("completedAt",Json.now());value.add("error",Json.obj("code",closed?"media_restart_interrupted":stopped?"media_cancelled":e instanceof ApiError a?a.code:"media_operation_failed","message",closed?"媒体操作随引擎退出而中断，可重新运行。":stopped?"媒体操作已取消，未完成产物不能导入。":e instanceof ApiError a?a.getMessage():"媒体文件处理失败，请检查内容、空间和目录权限。"));save(c,value,"finished");return null;});}catch(Exception ignored){/* 写入失败由存储状态阻止后续分派，重启按持久记录恢复。 */}}finally{release();}}
    private void release(){synchronized(gate){bridge=null;currentId=null;committing=false;cancelled=false;}}
    private void checkpoint(){if(closed||cancelled||Thread.currentThread().isInterrupted())throw error(499,"media_cancelled","媒体操作已取消。");if(store.writeFailed)throw error(503,"storage_write_failed","存储写入失败，媒体操作已停止。");}
    private void progress(String id,String stage,JsonObject progress,boolean force){long now=System.nanoTime();if(!force&&now-lastProgress<TimeUnit.MILLISECONDS.toNanos(250))return;lastProgress=now;store.tx(c->{JsonObject job=Store.document(c,"media_jobs",id);if(!ACTIVE.contains(Json.required(job,"status")))return null;job.addProperty("stage",stage);job.add("progress",progress.deepCopy());save(c,job,"progress");return null;});}
    private void extract(JsonObject job)throws Exception{
        String id=Json.required(job,"id");progress(id,"inspecting",Json.obj("phase","inspecting","completed",0,"total",null),true);JsonObject request=Json.object(job,"parameters").deepCopy();request.addProperty("jobId",id);request.add("sourcePath",job.get("sourcePath"));if(job.has("expectedSourceHash"))request.add("sourceHash",job.get("expectedSourceHash"));
        try(VideoFrames helper=bridge()){
            checkpoint();JsonObject fixed=helper.inspect(request,Json.number(request,"timeoutMs",600000),inspectionControl());checkpoint();safeTimeBase(fixed);String videoId=Json.required(fixed,"sourceVideoId");
            store.tx(c->{JsonObject value=Store.document(c,"media_jobs",id);value.add("frozenPlan",fixed);value.addProperty("sourceVideoId",videoId);value.addProperty("sourceHash",Json.required(fixed,"sourceHash"));JsonObject source=Json.obj("id",videoId,"sourcePath",fixed.get("sourcePath"),"sourceName",job.get("sourceName"),"contentHash",fixed.get("sourceHash"),"bytes",fixed.get("sourceBytes"),"metadata",fixed.get("sourceMetadata"));Store.update(c,"INSERT INTO video_sources(id,data) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data",videoId,source);save(c,value,"inspected");return null;});
            Path generation=generation(id);Files.createDirectories(generation.getParent());VideoFrames.Extraction output=helper.extract(fixed,generation,new VideoFrames.Control(){public boolean cancelled(){return cancelled||closed||store.writeFailed;}public void progress(JsonObject event){JsonObject value=Json.obj("phase",Json.str(event,"phase","validating"),"completed",Json.number(event,"completedFrames",Json.number(event,"frameCount",0)),"total",event.has("frameCount")?event.get("frameCount"):JsonNull.INSTANCE);for(String field:List.of("completedFrames","decodedFrames","sourceTimeSeconds","outputBytes"))if(event.has(field))value.add(field,event.get(field));MediaJobs.this.progress(id,"extracting",value,false);}});
            JsonObject summary=output.summary().deepCopy();summary.remove("manifestPath");String manifestHash=Json.required(summary,"manifestHash"),completeHash=Media.hash(generation.resolve("complete.json"));
            synchronized(gate){store.tx(c->{JsonObject value=Store.document(c,"media_jobs",id);value.addProperty("artifactCommitted",true);value.addProperty("manifestHash",manifestHash);value.addProperty("completeHash",completeHash);value.add("summary",summary);value.addProperty("status",cancelled?"cancelled":"completed");value.addProperty("stage","ready");value.addProperty("completedAt",Json.now());value.add("progress",Json.obj("phase","ready","completed",summary.get("frameCount"),"total",summary.get("frameCount"),"outputBytes",summary.get("outputBytes")));save(c,value,"artifact_committed");return null;});}
        }
    }
    private List<JsonObject> verifyFrames(JsonObject job)throws Exception{
        String id=Json.required(job,"id");if(!Json.bool(job,"artifactCommitted",false))throw error(409,"media_artifact_incomplete","抽帧产物未完成。");Path generation=generation(id),complete=generation.resolve("complete.json"),manifest=generation.resolve("frames.jsonl");
        if(!Files.isRegularFile(complete)||!Media.hash(complete).equals(Json.required(job,"completeHash"))||!Files.isRegularFile(manifest)||Files.size(manifest)>64L*1024*1024||!Media.hash(manifest).equals(Json.required(job,"manifestHash")))throw error(422,"media_artifact_changed","抽帧完成标记或清单缺失、变化。");JsonObject summary=Json.parse(Files.readString(complete));if(!id.equals(Json.required(summary,"jobId"))||!Json.required(job,"manifestHash").equals(Json.required(summary,"manifestHash")))throw error(422,"media_artifact_changed","抽帧清单与完成标记不一致。");
        List<JsonObject> frames=new ArrayList<>();Set<String> identities=new HashSet<>();long bytes=0;try(BufferedReader reader=Files.newBufferedReader(manifest)){String line;while((line=reader.readLine())!=null){checkpoint();if(line.length()>65536||frames.size()>=10000)throw error(413,"media_manifest_limit","抽帧清单超出导入限制。");JsonObject frame=Json.parse(line);String frameId=Json.required(frame,"frameId"),image=Json.required(frame,"imagePath");if(!frameId.matches("frame-[0-9]{8}")||!image.matches("frames/"+frameId+"\\.(png|jpg)")||!identities.add(frameId)||!Json.required(frame,"sourceVideoId").equals(Json.required(job,"sourceVideoId")))throw error(422,"media_artifact_changed","抽帧身份或相对路径无效。");Path file=confined(generation.resolve(image));if(!Files.isRegularFile(file)||Files.size(file)!=Json.number(frame,"bytes",-1)||!Media.hash(file).equals(Json.required(frame,"contentHash")))throw error(422,"media_artifact_changed","抽帧图片缺失或内容变化。");bytes+=Files.size(file);frames.add(frame);}}
        if(frames.size()!=Json.integer(summary,"frameCount",-1)||bytes!=Json.number(summary,"outputBytes",-1))throw error(422,"media_artifact_changed","抽帧数量或总大小与完成记录不一致。");return frames;
    }
    JsonObject frames(JsonObject p)throws Exception{FlowPlans.keys(p,"jobId","limit","offset");String id=Json.required(p,"jobId");int offset=Json.bounded(p,"offset",0,0,Integer.MAX_VALUE),limit=Json.bounded(p,"limit",100,1,500);JsonObject job=store.read(c->Store.document(c,"media_jobs",id));if(!Json.bool(job,"artifactCommitted",false))throw error(409,"media_artifact_incomplete","抽帧产物未完成。");Path manifest=generation(id).resolve("frames.jsonl");if(!Files.isRegularFile(manifest)||Files.size(manifest)>64L*1024*1024||!Media.hash(manifest).equals(Json.required(job,"manifestHash")))throw error(422,"media_artifact_changed","抽帧清单缺失或变化。");JsonArray items=new JsonArray();int position=0;try(BufferedReader reader=Files.newBufferedReader(manifest)){String line;while((line=reader.readLine())!=null){if(position>=offset&&items.size()<limit){JsonObject frame=Json.parse(line);frame.remove("imagePath");if(Json.bool(job,"assetsCommitted",false))frame.addProperty("assetId",assetId(id,Json.required(frame,"frameId")));items.add(frame);}position++;}}return Json.obj("items",items,"total",position);}
    private static String assetId(String id,String frame){return "vf-"+id+"-"+frame;}
    private void importFrames(JsonObject job)throws Exception{
        String id=Json.required(job,"id"),pid=Json.required(job,"projectId");progress(id,"validating",Json.obj("phase","validating","completed",0,"total",null),true);List<JsonObject> frames=verifyFrames(job);checkpoint();JsonObject project=engine.projects.get(pid);List<JsonObject> assets=new ArrayList<>();List<Path> temporaryFiles=new ArrayList<>();boolean published=false;
        try{int done=0;for(JsonObject frame:frames){checkpoint();String aid=assetId(id,Json.required(frame,"frameId"));Path image=generation(id).resolve(Json.required(frame,"imagePath"));String fileId="prepared-"+Json.id();Media.Normalized normalized=engine.projects.media.normalize(image,fileId,Json.str(Json.object(project,"settings"),"alphaBackground","#ffffff"),false);temporaryFiles.add(normalized.path());if(!Media.hash(image).equals(Json.required(frame,"contentHash")))throw error(422,"media_artifact_changed","抽帧图片在导入期间发生变化。");
                JsonObject metadata=normalized.metadata();for(var entry:frame.entrySet())if(!Set.of("imagePath","contentHash","width","height","bytes").contains(entry.getKey()))metadata.add(entry.getKey(),entry.getValue());metadata.addProperty("mediaJobId",id);metadata.addProperty("frameContentHash",Json.required(frame,"contentHash"));metadata.addProperty("sourceHash",Json.required(frame,"contentHash"));metadata.addProperty("videoSourceHash",Json.required(frame,"sourceHash"));
                JsonObject asset=Json.obj("id",aid,"projectId",pid,"name",Json.str(job,"sourceName","视频")+" · "+Json.required(frame,"frameId"),"width",normalized.width(),"height",normalized.height(),"contentHash",normalized.hash(),"status","unlabeled","annotations",new JsonArray(),"version",0,"source","video_frame","metadata",metadata,"mediaUrl","autolabel-media://asset/"+aid,"thumbnailUrl","autolabel-media://asset/"+aid,"privatePath",normalized.path().toString());assets.add(asset);progress(id,"importing",Json.obj("phase","importing","completed",++done,"total",frames.size()),false);
            }
            synchronized(gate){checkpoint();committing=true;store.tx(c->{JsonObject current=Store.document(c,"media_jobs",id);if(Json.bool(current,"assetsCommitted",false))return null;if(Json.required(current,"status").equals("cancelling"))throw error(499,"media_cancelled","导入已取消。");JsonObject currentProject=Store.document(c,"projects",pid);if(!Json.str(Json.object(currentProject,"settings"),"alphaBackground","#ffffff").equals(Json.str(Json.object(project,"settings"),"alphaBackground","#ffffff")))throw error(409,"media_project_changed","导入期间项目基准图设置发生变化。");
                for(JsonObject asset:assets){String path=Json.required(asset,"privatePath");asset.remove("privatePath");Store.update(c,"INSERT INTO assets(id,project_id,data,path) VALUES(?,?,?,?)",Json.required(asset,"id"),pid,asset,path);}
                current.addProperty("assetsCommitted",true);current.addProperty("status","completed");current.addProperty("stage","done");current.addProperty("completedAt",Json.now());current.add("progress",Json.obj("phase","done","completed",assets.size(),"total",assets.size()));Json.object(current,"summary").addProperty("importedAssets",assets.size());save(c,current,"assets_committed");Store.event(c,"asset.imported",null,null,null,Json.obj("projectId",pid,"mediaJobId",id,"imported",assets.size()));return null;});published=true;}
        }finally{if(!published)for(Path file:temporaryFiles)Files.deleteIfExists(file);}
    }
    JsonObject planScreening(JsonArray inputs,JsonObject parameters,ImageScreening.Control control){
        List<ImageScreening.Feature> features=new ArrayList<>();Map<String,ImageScreening.Feature> cache=new HashMap<>();JsonArray resolved=new JsonArray();
        for(JsonElement value:inputs){JsonObject input=value.getAsJsonObject().deepCopy();input.addProperty("inputPath",managed(Json.required(input,"inputImage")).toString());input.remove("inputImage");resolved.add(input);String key=Json.required(input,"contentHash")+":"+Json.integer(input,"width",0)+"x"+Json.integer(input,"height",0)+":"+Json.required(input,"normalizationVersion")+":"+Json.integer(input,"inputVersion",1)+":"+ImageScreening.FEATURE_VERSION;ImageScreening.Feature feature=cache.get(key);
            if(feature==null){JsonObject row=store.read(c->Store.one(c,"SELECT data FROM screening_features WHERE id=?",key));if(row!=null)try{feature=Json.GSON.fromJson(Json.required(row,"data"),ImageScreening.Feature.class);}catch(RuntimeException ignored){/* 缓存不满足当前特征约束时重新计算，不将旧缓存作为成功分析。 */}if(feature==null){feature=ImageScreening.feature(input,control);ImageScreening.Feature saved=feature;store.tx(c->{Store.update(c,"INSERT INTO screening_features(id,data) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data",saved.cacheKey(),saved.json());return null;});}cache.put(key,feature);}features.add(feature);
        }
        JsonObject result=ImageScreening.plan(resolved,features,parameters,control);for(JsonElement value:Json.array(result,"items"))Json.object(value.getAsJsonObject(),"input").remove("inputPath");return result;
    }
    private void screen(JsonObject job)throws Exception{
        String id=Json.required(job,"id");JsonArray inputs=Json.array(job,"privateInputs");Set<String> processed=new HashSet<>();progress(id,"screening",Json.obj("phase","screening","completed",0,"total",inputs.size()),true);
        JsonObject result=planScreening(inputs,Json.object(job,"parameters"),new ImageScreening.Control(){public boolean cancelled(){return cancelled||closed||store.writeFailed;}public void progress(JsonObject event){if(Json.str(event,"phase","").equals("feature_ready"))processed.add(Json.str(event,"assetId",""));JsonObject value=event.deepCopy();if(!value.has("completed"))value.addProperty("completed",value.has("comparedContentPairs")?Json.number(value,"comparedContentPairs",0):processed.size());if(!value.has("total"))value.addProperty("total",value.has("totalContentPairs")?Json.number(value,"totalContentPairs",0):inputs.size());MediaJobs.this.progress(id,"screening",value,false);}});
        checkpoint();Path output=jobDirectory(id).resolve("screening.json");writeAtomic(output,result);String hash=Media.hash(output);JsonObject summary=result.deepCopy();for(String key:SECTIONS)summary.remove(key);summary.remove("parameters");
        synchronized(gate){checkpoint();committing=true;store.tx(c->{JsonObject current=Store.document(c,"media_jobs",id);current.addProperty("screeningHash",hash);current.addProperty("artifactCommitted",true);current.add("summary",summary);current.addProperty("status","completed");current.addProperty("stage","done");current.addProperty("completedAt",Json.now());current.add("progress",Json.obj("phase","done","completed",inputs.size(),"total",inputs.size()));save(c,current,"screening_completed");return null;});}
    }
    JsonObject screeningResult(JsonObject p)throws Exception{FlowPlans.keys(p,"jobId","section","limit","offset");String id=Json.required(p,"jobId"),section=Json.str(p,"section","items");if(!SECTIONS.contains(section))throw error(400,"screening_section_invalid","筛选结果分类无效。");int limit=Json.bounded(p,"limit",100,1,500),offset=Json.bounded(p,"offset",0,0,Integer.MAX_VALUE);JsonObject job=store.read(c->Store.document(c,"media_jobs",id));if(!Json.required(job,"kind").equals("image_screening")||!Json.bool(job,"artifactCommitted",false))throw error(409,"screening_result_incomplete","筛选结果尚未完整提交。");Path path=jobDirectory(id).resolve("screening.json");if(!Files.isRegularFile(path)||Files.size(path)>128L*1024*1024||!Media.hash(path).equals(Json.required(job,"screeningHash")))throw error(422,"screening_result_changed","筛选结果缺失或内容变化。");JsonObject result=Json.parse(Files.readString(path));JsonArray all=Json.array(result,section),items=new JsonArray();for(int i=offset;i<all.size()&&items.size()<limit;i++)items.add(all.get(i));return Json.obj("jobId",id,"section",section,"parameters",result.get("parameters"),"summary",job.get("summary"),"items",items,"total",all.size(),"offset",offset,"limit",limit);}
    JsonObject screeningDocument(String id)throws Exception{JsonObject job=store.read(c->Store.document(c,"media_jobs",id));if(!Json.required(job,"kind").equals("image_screening")||!Json.bool(job,"artifactCommitted",false))throw error(409,"screening_result_incomplete","筛选结果尚未完整提交。");Path file=jobDirectory(id).resolve("screening.json");if(!Files.isRegularFile(file)||Files.size(file)>128L*1024*1024||!Media.hash(file).equals(Json.required(job,"screeningHash")))throw error(422,"screening_result_changed","筛选结果缺失或内容变化。");return Json.parse(Files.readString(file));}
    JsonObject exportInspection(String projectId,List<JsonObject> assets){
        Map<String,JsonObject> selected=new HashMap<>();for(JsonObject asset:assets)selected.put(Json.required(asset,"id"),asset);
        JsonArray jobs=store.read(c->Store.docs(c,"SELECT data FROM media_jobs WHERE project_id=? AND kind='image_screening' AND json_extract(data,'$.artifactCommitted')=1 ORDER BY rowid DESC LIMIT 20",projectId));
        for(JsonElement value:jobs){JsonObject job=value.getAsJsonObject();JsonArray inputs=Json.array(job,"privateInputs");if(inputs.size()!=selected.size())continue;boolean matches=true;for(JsonElement element:inputs){JsonObject input=element.getAsJsonObject(),asset=selected.get(Json.required(input,"assetId"));if(asset==null||!Objects.equals(input.get("contentHash"),asset.get("contentHash"))||Json.integer(input,"inputVersion",1)!=Json.integer(Json.object(asset,"metadata"),"inputVersion",1)){matches=false;break;}}if(!matches)continue;
            try{JsonObject result=screeningDocument(Json.required(job,"id"));return Json.obj("status",result.get("status"),"jobId",job.get("id"),"parameters",result.get("parameters"),"summary",job.get("summary"),"nearPairs",result.get("nearPairs"),"scope","exact_selected_baselines");}catch(Exception failure){return Json.obj("status","incomplete","reason","screening_result_unavailable","scope","exact_selected_baselines");}
        }return Json.obj("status","not_run","reason","no_matching_frozen_scope","scope","exact_selected_baselines");
    }
    private Path generation(String id){return jobDirectory(id).resolve("generation");}
    private Path jobDirectory(String id){if(!id.matches("[A-Za-z0-9_-]{1,100}"))throw error(400,"media_job_id_invalid","媒体任务标识无效。");return managed("media-jobs/"+id);}
    private Path managed(String relative){Path path=store.root.resolve(relative).normalize();if(!path.startsWith(store.root)||Path.of(relative).isAbsolute())throw error(422,"media_path_invalid","媒体依赖必须位于受管目录。");return confined(path);}
    private Path confined(Path path){try{Path normalized=path.toAbsolutePath().normalize();if(!normalized.startsWith(store.root))throw new IOException();for(Path cursor=normalized;cursor!=null&&cursor.startsWith(store.root);cursor=cursor.getParent())if(Files.exists(cursor)&&!cursor.toRealPath().startsWith(store.root.toRealPath()))throw new IOException();return normalized;}catch(Exception e){throw error(422,"media_path_invalid","媒体依赖不能越过受管目录。");}}
    private String relative(Path path){return store.root.relativize(confined(path)).toString().replace('\\','/');}
    private void writeAtomic(Path path,JsonObject value)throws Exception{Files.createDirectories(path.getParent());String text=value.toString();if(text.length()>128L*1024*1024)throw error(413,"screening_result_limit","筛选结果超出持久化大小限制。");store.requireSpace(Math.max(128L*1024*1024,text.length()*4L));Path pending=path.resolveSibling(path.getFileName()+".partial");Files.writeString(pending,text,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);Files.move(pending,path,StandardCopyOption.ATOMIC_MOVE);}
    JsonObject diagnostics(){return Json.obj("activeWorkers",currentId==null?0:1,"queuedInMemory",worker.getQueue().size());}
    private VideoFrames.Control inspectionControl(){return new VideoFrames.Control(){public boolean cancelled(){return cancelled||closed||store.writeFailed;}};}
    private void cancelActive(){cancelled=true;VideoFrames value=bridge;String id=currentId;if(value!=null){if(closed)value.close();else if(id!=null)value.cancel(id);}}
    @Override public void close(){synchronized(gate){closed=true;cancelActive();}worker.shutdown();try{if(!worker.awaitTermination(30,TimeUnit.SECONDS)){VideoFrames value=bridge;if(value!=null)value.close();worker.shutdownNow();worker.awaitTermination(10,TimeUnit.SECONDS);}}catch(InterruptedException e){worker.shutdownNow();Thread.currentThread().interrupt();}}
    private static ApiError error(int status,String code,String message){return new ApiError(status,code,message);}
}
