package cn.autolabel.engine;

import com.google.gson.*;
import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.geom.*;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;

final class OverlayRenderer {
    private final Store store;private final Projects projects;
    OverlayRenderer(Store store,Projects projects){this.store=store;this.projects=projects;}
    JsonObject render(JsonObject p)throws Exception{
        String aid=Json.required(p,"assetId");JsonObject saved=store.read(c->{JsonObject current=Store.document(c,"assets",aid);if(!p.has("version")||Json.integer(p,"version",0)==Json.integer(current,"version",0))return current;
            JsonObject row=Store.one(c,"SELECT data FROM versions WHERE asset_id=? AND version=?",aid,Json.integer(p,"version",0));if(row==null)throw new ApiError(404,"annotation_version_not_found","标注历史版本不存在。");return Json.parse(row.get("data").getAsString());});
        if(Json.integer(saved,"version",0)<1)throw new ApiError(422,"annotation_not_saved","请先保存正式标注，草稿不能作为已保存效果图输出。");
        Path target=Path.of(Json.required(p,"outputPath")).toAbsolutePath().normalize();String format=Json.str(p,"format",target.toString().toLowerCase().matches(".*\\.jpe?g$")?"jpeg":"png");if(!Set.of("png","jpeg").contains(format))throw new ApiError(400,"image_format_unsupported","效果图支持 PNG、JPEG。");
        protectTarget(target);Path image=projects.path(aid);if(!Files.isRegularFile(image))throw new ApiError(404,"media_missing","基准图不存在。");if(!Media.hash(image).equals(Json.required(saved,"contentHash")))throw new ApiError(409,"media_content_changed","基准图片内容与保存版本不一致。");
        BufferedImage baseline=ImageIO.read(image.toFile());if(baseline==null)throw new ApiError(422,"image_corrupt","基准图无法解码。");BufferedImage overlay=new BufferedImage(baseline.getWidth(),baseline.getHeight(),BufferedImage.TYPE_INT_RGB);Graphics2D g=overlay.createGraphics();g.drawImage(baseline,0,0,null);baseline.flush();
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,RenderingHints.VALUE_ANTIALIAS_ON);float stroke=Math.max(2f,Math.min(8f,overlay.getWidth()/400f));g.setStroke(new BasicStroke(stroke));g.setFont(new Font(Font.SANS_SERIF,Font.BOLD,Math.max(14,(int)(stroke*6))));
        JsonObject template=Json.object(Json.object(saved,"metadata"),"annotationTemplate");boolean savedTemplate=template.has("classes");JsonObject project=savedTemplate?template:projects.get(Json.required(saved,"projectId"));Map<String,JsonObject> classes=new HashMap<>();for(JsonElement e:Json.array(project,"classes"))classes.put(Json.required(e.getAsJsonObject(),"id"),e.getAsJsonObject());int classificationY=30;
        for(JsonElement e:Json.array(saved,"annotations")){JsonObject a=e.getAsJsonObject(),clazz=classes.get(Json.required(a,"classId"));Color color=Color.decode(clazz==null?"#3b82f6":Json.str(clazz,"color","#3b82f6"));g.setColor(color);String type=Json.required(a,"type");double lx=10,ly=classificationY;
            if(type.equals("detect")||type.equals("pose")){JsonObject b=Json.object(a,"bbox");lx=Annotations.num(b,"x");ly=Annotations.num(b,"y");if(Json.bool(p,"showGeometry",true))g.draw(new Rectangle2D.Double(lx,ly,Annotations.num(b,"width"),Annotations.num(b,"height")));}
            else if(type.equals("obb")||type.equals("segment")){JsonArray points=type.equals("obb")?Annotations.obb(a):Json.array(a,"points");Path2D path=new Path2D.Double();for(int i=0;i<points.size();i++){JsonObject pt=points.get(i).getAsJsonObject();double x=Annotations.num(pt,"x"),y=Annotations.num(pt,"y");if(i==0){path.moveTo(x,y);lx=x;ly=y;}else path.lineTo(x,y);}path.closePath();if(Json.bool(p,"showGeometry",true))g.draw(path);}
            if(type.equals("pose")&&Json.bool(p,"showKeypoints",true)){
                JsonArray points=Json.array(a,"keypoints"),connections=Json.array(Json.object(project,"settings"),"keypointConnections");for(JsonElement connection:connections){JsonArray pair=connection.isJsonArray()?connection.getAsJsonArray():new JsonArray();if(pair.size()!=2)continue;int left=pointIndex(points,pair.get(0)),right=pointIndex(points,pair.get(1));if(left<0||right<0)continue;JsonObject from=points.get(left).getAsJsonObject(),to=points.get(right).getAsJsonObject();if(Json.integer(from,"visibility",0)>0&&Json.integer(to,"visibility",0)>0)g.draw(new Line2D.Double(Annotations.num(from,"x"),Annotations.num(from,"y"),Annotations.num(to,"x"),Annotations.num(to,"y")));}
                for(JsonElement keypoint:points){JsonObject k=keypoint.getAsJsonObject();int visibility=Json.integer(k,"visibility",0);if(visibility==0)continue;double x=Annotations.num(k,"x"),y=Annotations.num(k,"y"),r=stroke*2;Shape circle=new Ellipse2D.Double(x-r,y-r,r*2,r*2);if(visibility==2)g.fill(circle);else g.draw(circle);if(Json.bool(p,"showLabels",true))g.drawString(Json.required(k,"name"),(float)(x+r+2),(float)y);}}
            if(Json.bool(p,"showLabels",true)){String label=clazz==null?Json.required(a,"classId"):Json.required(clazz,"name");int x=(int)Math.max(2,lx),y=(int)Math.max(g.getFontMetrics().getAscent()+3,ly-4);int width=g.getFontMetrics().stringWidth(label)+10;g.setColor(new Color(color.getRed(),color.getGreen(),color.getBlue(),220));g.fillRoundRect(x,y-g.getFontMetrics().getAscent()-3,width,g.getFontMetrics().getHeight()+4,5,5);g.setColor(Color.WHITE);g.drawString(label,x+5,y);classificationY+=g.getFontMetrics().getHeight()+12;}
        }g.dispose();Files.createDirectories(target.getParent());Path temporary=target.resolveSibling("."+target.getFileName()+"."+Json.id()+".partial");if(!ImageIO.write(overlay,format,temporary.toFile()))throw new ApiError(500,"image_write_failed","效果图编码器不可用。");int w=overlay.getWidth(),h=overlay.getHeight();overlay.flush();Files.move(temporary,target);String imageHash=Media.hash(target);store.tx(c->{Store.event(c,"annotation.rendered",null,aid,null,Json.obj("version",saved.get("version"),"imageHash",imageHash,"format",format,"fileName",target.getFileName().toString()));return null;});return Json.obj("path",target.toString(),"assetId",aid,"version",saved.get("version"),"width",w,"height",h,"source","saved_annotation_overlay","templateSource",savedTemplate?"saved_version":"current_project_fallback");
    }
    void protectTarget(Path target){if(Files.exists(target))throw new ApiError(409,"output_exists","输出文件已存在，请选择新文件名。");if(target.startsWith(store.root.resolve("media"))||target.startsWith(store.root.resolve("originals")))throw new ApiError(409,"overlay_target_protected","效果图不能写入受管训练原图目录。");
        store.read(c->{for(JsonObject r:Store.rows(c,"SELECT path,data FROM assets")){if(target.equals(Path.of(Json.required(r,"path")).toAbsolutePath().normalize()))throw new ApiError(409,"overlay_target_protected","效果图不能覆盖基准图。");String source=Json.str(Json.object(Json.parse(Json.required(r,"data")),"metadata"),"sourcePath","");if(!source.isEmpty()&&target.equals(Path.of(source).toAbsolutePath().normalize()))throw new ApiError(409,"overlay_target_protected","效果图不能覆盖源图片。");}
            for(JsonElement e:Store.docs(c,"SELECT data FROM exports")){String path=Json.str(e.getAsJsonObject(),"path","");if(!path.isEmpty()&&target.startsWith(Path.of(path).toAbsolutePath().normalize()))throw new ApiError(409,"overlay_target_protected","效果图不能写入历史训练导出目录。");}return null;});}
    static int pointIndex(JsonArray points,JsonElement value){if(value.isJsonPrimitive()&&value.getAsJsonPrimitive().isNumber()){int i=value.getAsInt();return i>=0&&i<points.size()?i:-1;}for(int i=0;i<points.size();i++)if(Json.required(points.get(i).getAsJsonObject(),"name").equals(value.getAsString()))return i;return -1;}
}
