package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;

final class Reviews {
    final Store store;final Projects projects;
    static final Set<String> STATUSES=Set.of("pending","checked","dismissed","request_relabel");
    Reviews(Store store,Projects projects){this.store=store;this.projects=projects;}
    static JsonObject item(String pid,String aid,JsonElement version,String reason,String severity,String source,String objectId,String context,JsonObject links){
        String id=Json.id();JsonObject value=Json.obj("id",id,"projectId",pid,"assetId",aid,"candidateVersion",version,"objectId",objectId,"reason",reason,"severity",severity,"source",source,"status","pending","createdAt",Json.now());for(var link:links.entrySet())value.add(link.getKey(),link.getValue());value.addProperty("identityKey",context+":"+aid+":"+String.valueOf(version)+":"+reason+":"+String.valueOf(objectId));return value;
    }
    JsonObject build(JsonObject p){if(p.has("evaluationId")==p.has("runId"))throw new ApiError(400,"review_source_invalid","请指定 evaluationId 或 runId，不能同时提供。");JsonObject rules=Json.object(p,"rules");for(String key:List.of("minMatchedIoU","maxNormalizedPointError"))if(rules.has(key)){double v=Json.decimal(rules,key,-1);if(!Double.isFinite(v)||v<0||v>1)throw new ApiError(400,"review_rule_invalid","复核定位阈值必须在 0～1 内。");}
        List<JsonObject> items=store.read(c->{List<JsonObject> result=new ArrayList<>();if(p.has("evaluationId")){String eid=Json.required(p,"evaluationId");JsonObject evaluation=Store.document(c,"evaluations",eid);String pid=Json.required(evaluation,"projectId");for(JsonElement entry:Store.docs(c,"SELECT data FROM evaluation_results WHERE evaluation_id=? ORDER BY rowid",eid)){
                    JsonObject row=entry.getAsJsonObject();String aid=Json.required(row,"assetId"),rid=Json.required(row,"runId"),context="evaluation:"+eid+":"+rid;JsonElement version=row.get("candidateVersion");JsonObject links=Json.obj("evaluationId",eid,"runId",rid,"schemeId",rid,"rules",new JsonObject());
                    if(!Json.required(row,"status").equals("scorable")){String status=Json.required(row,"status"),severity=status.equals("pending")?"info":status.equals("missing")?"warning":"error";result.add(item(pid,aid,version,"prediction_"+status,severity,"execution",null,context,links));}
                    else if(row.has("classResult")){JsonObject classification=Json.object(row,"classResult");if(!Json.bool(classification,"correct",false))result.add(item(pid,aid,version,Json.bool(classification,"missingPrediction",false)?"classification_missing":"classification_wrong","warning","truth_comparison",null,context,links));}
                    else{for(JsonElement id:Json.array(row,"unmatchedTruthIds"))result.add(item(pid,aid,version,"missed_object","error","truth_comparison",id.getAsString(),context,links));for(JsonElement id:Json.array(row,"unmatchedPredictionIds"))result.add(item(pid,aid,version,"extra_object","warning","truth_comparison",id.getAsString(),context,links));
                        for(JsonElement pair:Json.array(row,"pairs")){JsonObject matched=pair.getAsJsonObject();String object=Json.required(matched,"predictionId");if(rules.has("minMatchedIoU")&&Json.decimal(matched,"iou",1)<Json.decimal(rules,"minMatchedIoU",0))result.add(ruleItem(pid,aid,version,"localization_iou",object,context,links,rules,"minMatchedIoU"));
                            if(!Json.array(matched,"missingPredictedKeypoints").isEmpty())result.add(item(pid,aid,version,"missing_keypoint","warning","truth_comparison",object,context,links));
                            if(rules.has("maxNormalizedPointError"))for(JsonElement error:Json.array(matched,"keypointErrors"))if(Json.decimal(error.getAsJsonObject(),"errorNormalized",0)>Json.decimal(rules,"maxNormalizedPointError",1)){result.add(ruleItem(pid,aid,version,"keypoint_location",object,context,links,rules,"maxNormalizedPointError"));break;}}
                    }if(result.size()>10000)throw new ApiError(413,"review_issue_limit","单次复核构建超过 10000 项，请缩小评测范围。");}
            }else{String rid=Json.required(p,"runId");JsonObject run=Store.document(c,"runs",rid);String pid=Json.required(run,"projectId");for(JsonObject sample:Store.rows(c,"SELECT asset_id,status,data FROM samples WHERE run_id=? AND status IN ('failed','unknown')",rid)){JsonObject data=Json.parse(sample.get("data").getAsString());result.add(item(pid,Json.required(sample,"asset_id"),data.get("candidateVersion"),"prediction_"+Json.required(sample,"status"),"error","execution",null,"run:"+rid,Json.obj("runId",rid,"errorCode",data.get("errorCode"))));}}
            return result;});return saveItems(items,null);
    }
    static JsonObject ruleItem(String pid,String aid,JsonElement version,String reason,String objectId,String context,JsonObject links,JsonObject rules,String key){
        // 只把实际触发该项的规则纳入身份，改变阈值不会复用旧判断，无关规则也不会重复创建事实项。
        double threshold=Json.decimal(rules,key,0);JsonObject snapshot=links.deepCopy();snapshot.add("rules",Json.obj(key,threshold));return item(pid,aid,version,reason,"warning","truth_comparison",objectId,context+":"+key+"="+threshold,snapshot);
    }
    JsonObject saveItems(List<JsonObject> items,JsonObject sample){return store.tx(c->{if(sample!=null)Store.update(c,"INSERT INTO review_samples(id,project_id,data) VALUES(?,?,?)",Json.required(sample,"id"),Json.required(sample,"projectId"),sample);int created=0;JsonArray output=new JsonArray();
        for(JsonObject item:items){int inserted=Store.update(c,"INSERT OR IGNORE INTO review_items(id,project_id,evaluation_id,run_id,sample_id,asset_id,candidate_version,status,identity_key,data) VALUES(?,?,?,?,?,?,?,?,?,?)",Json.required(item,"id"),Json.required(item,"projectId"),Json.str(item,"evaluationId",null),Json.str(item,"runId",null),Json.str(item,"sampleId",null),Json.required(item,"assetId"),item.get("candidateVersion")==null||item.get("candidateVersion").isJsonNull()?null:item.get("candidateVersion").getAsInt(),"pending",Json.required(item,"identityKey"),item);created+=inserted;if(output.size()<500){if(inserted==1)output.add(item);else output.add(Json.parse(Json.required(Store.one(c,"SELECT data FROM review_items WHERE identity_key=?",Json.required(item,"identityKey")),"data")));}}
        Store.event(c,sample==null?"review.built":"review.sampled",null,null,null,Json.obj("created",created,"existing",items.size()-created,"sampleId",sample==null?null:sample.get("id")));return sample==null?Json.obj("created",created,"existing",items.size()-created,"items",output,"itemsTruncated",items.size()>500):sample;});}
    JsonObject list(JsonObject p){String pid=Json.required(p,"projectId");if(p.has("source")&&!Set.of("execution","truth_comparison","random").contains(Json.required(p,"source")))throw new ApiError(400,"review_source_invalid","复核来源无效。");if(p.has("status")&&!STATUSES.contains(Json.required(p,"status")))throw new ApiError(400,"review_status_invalid","复核状态无效。");return store.read(c->{String condition="project_id=?";List<Object> args=new ArrayList<>(List.of(pid));for(String key:List.of("evaluationId","runId","sampleId","status","source"))if(p.has(key)){String column=switch(key){case "evaluationId"->"evaluation_id";case "runId"->"run_id";case "sampleId"->"sample_id";case "source"->"json_extract(data,'$.source')";default->"status";};condition+=" AND "+column+"=?";args.add(Json.required(p,key));}long total=Store.one(c,"SELECT COUNT(*) AS n FROM review_items WHERE "+condition,args.toArray()).get("n").getAsLong();args.add(Json.bounded(p,"limit",100,1,500));args.add(Json.bounded(p,"offset",0,0,Integer.MAX_VALUE));return Json.obj("items",Store.docs(c,"SELECT data FROM review_items WHERE "+condition+" ORDER BY CASE json_extract(data,'$.severity') WHEN 'error' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,rowid LIMIT ? OFFSET ?",args.toArray()),"total",total);});}
    JsonObject resolve(JsonObject p){String id=Json.required(p,"itemId"),action=Json.required(p,"action");if(!Set.of("checked","dismissed","request_relabel").contains(action))throw new ApiError(400,"review_action_invalid","不支持该复核操作。");if(!p.has("baseCandidateVersion"))throw new ApiError(400,"invalid_argument","请明确提供 baseCandidateVersion，失败无候选时为 null。");return store.tx(c->{JsonObject item=Store.document(c,"review_items",id);JsonElement current=item.has("candidateVersion")?item.get("candidateVersion"):JsonNull.INSTANCE;if(!Objects.equals(current,p.get("baseCandidateVersion")))throw new ApiError(409,"review_version_conflict","复核项对应版本与提交版本不同。");item.addProperty("status",action);item.addProperty("note",Json.str(p,"note",""));item.addProperty("resolvedAt",Json.now());Store.update(c,"UPDATE review_items SET status=?,data=? WHERE id=?",action,item,id);Store.event(c,"review.resolved",Json.str(item,"runId",null),Json.required(item,"assetId"),null,Json.obj("itemId",id,"status",action,"candidateVersion",current));return item;});}
    JsonObject sample(JsonObject p)throws Exception{String pid=Json.required(p,"projectId"),seed=Json.required(p,"seed");if(seed.length()>256)throw new ApiError(400,"review_seed_invalid","抽样种子最长 256 个字符。");List<JsonObject> assets=new AssetFiles(store,projects).select(p);if(!p.has("assetIds")||assets.isEmpty()||assets.size()>1000||Json.array(p,"assetIds").size()!=assets.size())throw new ApiError(400,"asset_selection_empty","请选择 1～1000 张无重复素材作为抽样范围。");int count=Json.bounded(p,"count",0,1,assets.size());assets.sort(Comparator.comparing(a->Json.required(a,"id")));long rng=ByteBuffer.wrap(MessageDigest.getInstance("SHA-256").digest(seed.getBytes(StandardCharsets.UTF_8))).getLong();Collections.shuffle(assets,new Random(rng));String id=Json.id();JsonArray versions=new JsonArray(),population=new JsonArray();for(JsonObject asset:assets)population.add(Json.obj("assetId",asset.get("id"),"version",asset.get("version")));List<JsonObject> items=new ArrayList<>();
        for(JsonObject asset:assets.subList(0,count)){String aid=Json.required(asset,"id");versions.add(Json.obj("assetId",aid,"version",asset.get("version"),"contentHash",asset.get("contentHash")));items.add(item(pid,aid,asset.get("version"),"random_sample","info","random",null,"sample:"+id,Json.obj("sampleId",id)));}
        JsonObject sample=Json.obj("id",id,"projectId",pid,"mode","random","populationCount",assets.size(),"count",count,"seed",seed,"algorithm","sha256-java-shuffle-v1","population",population,"assetVersions",versions,"createdAt",Json.now());return saveItems(items,sample);
    }
}
