package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Connection;
import java.util.*;
import javax.imageio.*;
import javax.imageio.stream.ImageInputStream;

final class RunInputs {
    static JsonObject identity(JsonObject asset){return Json.obj("assetId",asset.get("id"),"contentHash",asset.get("contentHash"),"width",asset.get("width"),"height",asset.get("height"),"normalizationVersion",Media.NORMALIZATION_VERSION,"inputVersion",Math.max(1,Json.integer(Json.object(asset,"metadata"),"inputVersion",1)));}
    static JsonObject baseline(Connection c,JsonObject item)throws Exception{
        JsonObject origin=item;if(item.has("baselineItemId"))origin=Store.document(c,"flow_artifact_items",Json.required(item,"baselineItemId"));JsonObject asset=Json.object(origin,"asset");if(asset.isEmpty())throw new ApiError(409,"input_baseline_missing","固定输入缺少基准父图快照。");return Json.obj("asset",asset.deepCopy(),"inputPath",origin.get("inputPath"),"manualProtected",Json.bool(origin,"manualProtected",false),"selectedVersion",origin.get("selectedVersion"));
    }
    static JsonObject baseline(Connection c,String runId,String assetId)throws Exception{JsonObject row=Store.one(c,"SELECT data FROM run_baselines WHERE run_id=? AND asset_id=?",runId,assetId);if(row==null)throw new ApiError(409,"input_baseline_missing","运行缺少固定基准父图。");return Json.parse(row.get("data").getAsString());}
    static JsonObject snapshot(JsonObject item){if(item.has("inputSnapshot"))return Json.object(item,"inputSnapshot").deepCopy();JsonObject asset=Json.object(item,"asset");return Json.obj("inputId",asset.get("id"),"assetId",asset.get("id"),"kind","baseline","contentHash",asset.get("contentHash"),"width",asset.get("width"),"height",asset.get("height"),"normalizationVersion",Media.NORMALIZATION_VERSION);}
    static JsonObject inputAsset(JsonObject sample,JsonObject baseline){JsonObject snapshot=Json.object(sample,"inputSnapshot");if(snapshot.isEmpty())return Json.object(sample,"asset").deepCopy();return Json.obj("id",snapshot.get("inputId"),"projectId",Json.object(baseline,"asset").get("projectId"),"width",snapshot.get("width"),"height",snapshot.get("height"),"contentHash",snapshot.get("contentHash"),"metadata",Json.obj("normalizationVersion",snapshot.get("normalizationVersion")),"annotations",new JsonArray(),"version",0,"status","unlabeled");}
    static JsonObject publicSnapshot(JsonObject snapshot){JsonObject result=new JsonObject();for(String field:List.of("inputId","kind","assetId","contentHash","width","height","normalizationVersion","viewId","planHash","inputTransform","pixelTransformVersion"))if(snapshot.has(field))result.add(field,snapshot.get(field));return result;}
    static String hash(JsonElement value)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value.toString().getBytes(StandardCharsets.UTF_8)));}
    static String inputId(JsonObject sample){return Json.str(sample,"inputId",Json.required(sample,"assetId"));}
    static void insertBaseline(Connection c,String runId,JsonObject item)throws Exception{String assetId=Json.required(item,"assetId");if(Store.one(c,"SELECT asset_id FROM run_baselines WHERE run_id=? AND asset_id=?",runId,assetId)!=null)return;JsonObject baseline=baseline(c,item),plan;if(item.has("planStepId")){JsonObject producer=Store.document(c,"flow_steps",Json.required(item,"planStepId"));plan=Json.object(Json.object(Json.object(producer,"snapshot"),"transformPlans"),assetId);}else plan=TransformGeometry.plan(identity(Json.object(baseline,"asset")),new JsonArray());if(plan.isEmpty())throw new ApiError(409,"input_plan_missing","变换输入的固定计划不可用。");baseline.add("plan",plan);Store.update(c,"INSERT INTO run_baselines(run_id,asset_id,data) VALUES(?,?,?)",runId,assetId,baseline);}
    static JsonObject image(Store store,Projects projects,JsonObject p)throws Exception{FlowPlans.keys(p,"inputId");String id=FlowPlans.string(p,"inputId",128);JsonObject descriptor=store.read(c->{JsonObject baseline=Store.one(c,"SELECT data,path FROM assets WHERE id=?",id);if(baseline!=null){JsonObject asset=Json.parse(baseline.get("data").getAsString());return Json.obj("inputId",id,"assetId",id,"path",baseline.get("path"),"contentHash",asset.get("contentHash"),"width",asset.get("width"),"height",asset.get("height"),"kind","baseline");}JsonObject origin=Store.document(c,"flow_artifact_items",id),input=Json.object(origin,"inputSnapshot");if(!id.equals(Json.str(input,"inputId","")))throw new ApiError(409,"input_identity_invalid","变换输入身份不匹配。");return Json.obj("inputId",id,"assetId",origin.get("assetId"),"path",origin.get("inputPath"),"contentHash",input.get("contentHash"),"width",input.get("width"),"height",input.get("height"),"kind","view");});Path path=Path.of(Json.required(descriptor,"path")),base=store.root.resolve(Json.required(descriptor,"kind").equals("baseline")?"media":"flow-inputs");if(!Files.isDirectory(base)||!Files.isRegularFile(path)||!path.toRealPath().startsWith(base.toRealPath())||!base.toRealPath().startsWith(store.root.toRealPath()))throw new ApiError(403,"input_path_invalid","输入图片不在当前数据目录的受管范围。");if(!Media.hash(path).equals(Json.required(descriptor,"contentHash")))throw new ApiError(409,"input_content_changed","固定输入图片已变化。");try(ImageInputStream image=ImageIO.createImageInputStream(path.toFile())){Iterator<ImageReader> readers=ImageIO.getImageReaders(image);if(!readers.hasNext())throw new ApiError(409,"input_image_invalid","输入图片不可解码。");ImageReader reader=readers.next();try{reader.setInput(image,true,true);if(!reader.getFormatName().equalsIgnoreCase("png")||reader.getWidth(0)!=Json.integer(descriptor,"width",0)||reader.getHeight(0)!=Json.integer(descriptor,"height",0))throw new ApiError(409,"input_image_invalid","输入图片尺寸或格式与固定记录不符。");}finally{reader.dispose();}}descriptor.remove("kind");descriptor.addProperty("path",path.toRealPath().toString());descriptor.addProperty("mimeType","image/png");return descriptor;}
}
