package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.util.*;

final class RunResults {
    static final int MAX_RESULT_BYTES=32*1024*1024;
    final Engine engine;final Store store;
    RunResults(Engine engine){this.engine=engine;store=engine.store;}
    JsonObject get(JsonObject p){FlowPlans.keys(p,"resultId");return store.read(c->{JsonObject value=Store.document(c,"input_results",FlowPlans.string(p,"resultId",128));Json.object(value,"provenance").remove("modelPath");Json.object(Json.object(value,"provenance"),"parameters").remove("imagePath");int bytes=value.toString().getBytes(StandardCharsets.UTF_8).length;if(bytes>MAX_RESULT_BYTES)throw new ApiError(413,"input_result_too_large","结果详情超过 32 MiB，完整原始与回映结果已不可变保存在数据库中。",Json.obj("resultId",value.get("id"),"stored",true,"serializedBytes",bytes,"requiresGeometryReview",true));return value;});}
    JsonObject result(JsonObject run,JsonObject sample,String source,String attempt,JsonObject raw,JsonObject provenance,Exception failure)throws Exception{
        JsonObject baseline=store.read(c->RunInputs.baseline(c,Json.required(run,"id"),Json.required(sample,"assetId"))),mapping=null;String status="succeeded",code=null,message=null;JsonArray issues=new JsonArray(),annotations=null;
        if(failure!=null){code=failure instanceof ApiError a?a.code:failure instanceof Providers.RemoteError remote?remote.code:"input_result_failed";message=failure instanceof ApiError a?a.getMessage():"该输入执行未完成，原始失败已保留。";status=Set.of("local_timeout","local_worker_exited","local_worker_closed").contains(code)||failure instanceof Providers.RemoteError remote&&remote.unknown?"unknown":code.equals("local_cancelled")?"cancelled":"failed";}
        else try{JsonObject project=Json.object(Json.object(run,"snapshot"),"project");try{if(raw.has("annotations")&&raw.get("annotations").isJsonArray())annotations=Annotations.validate(Json.array(raw,"annotations"),RunInputs.inputAsset(sample,baseline),project);}catch(ApiError invalid){annotations=null;}String view=Json.str(Json.object(sample,"inputSnapshot"),"viewId","view-00000");mapping=TransformGeometry.readPlan(Json.object(baseline,"plan")).inverse(view,raw,project);issues=Json.array(mapping,"geometryIssues");if(Json.bool(mapping,"requiresGeometryReview",false))status="needs_attention";}catch(ApiError error){status="needs_attention";code=error.code;message=error.getMessage();issues.add(Json.obj("code",code,"severity","error","message",message));}
        JsonObject result=Json.obj("id",Json.id(),"runId",run.get("id"),"sampleId",sample.get("id"),"inputId",RunInputs.inputId(sample),"assetId",sample.get("assetId"),"source",source,"status",status,"createdAt",Json.now(),"annotations",annotations,"rawResult",raw,"mappedResult",mapping,"geometryIssues",issues,"requiresGeometryReview",!status.equals("succeeded"),"provenance",provenance==null?new JsonObject():provenance);if(attempt!=null)result.addProperty("attemptId",attempt);if(code!=null){result.addProperty("errorCode",code);result.addProperty("message",message);}
        int bytes=result.toString().getBytes(StandardCharsets.UTF_8).length;if(bytes>MAX_RESULT_BYTES){result.addProperty("status","needs_attention");result.addProperty("requiresGeometryReview",true);result.addProperty("errorCode","input_result_too_large");result.addProperty("message","单份输入结果详情超过 32 MiB，完整原始与回映结果已保存，未将其作为完整标注采用。");result.add("geometryIssues",Json.arr(Json.obj("code","input_result_too_large","severity","error","message","结果详情超过返回边界，需缩小输入或目标范围。","serializedBytes",bytes)));}
        return result;
    }
    interface Guard{boolean validate(Connection c)throws Exception;}
    boolean save(JsonObject run,JsonObject sample,String claim,JsonObject result){return save(run,sample,claim,result,null);}
    boolean save(JsonObject run,JsonObject sample,String claim,JsonObject result,Guard guard){return store.tx(c->{if(guard!=null&&!guard.validate(c))return false;JsonObject current=Store.one(c,"SELECT data,active_attempt FROM samples WHERE id=?",Json.required(sample,"id"));if(current==null||!claim.equals(Json.str(current,"active_attempt","")))return false;JsonObject persisted=Json.parse(current.get("data").getAsString()),live=Store.document(c,"runs",Json.required(run,"id"));boolean cancelled=Json.required(live,"status").equals("cancelled");String resultStatus=Json.required(result,"status"),status=cancelled?"cancelled":Set.of("succeeded","needs_attention").contains(resultStatus)?"succeeded":resultStatus;
            Store.update(c,"INSERT INTO input_results(id,run_id,sample_id,asset_id,input_id,attempt_id,source,status,created_at,data) VALUES(?,?,?,?,?,?,?,?,?,?)",Json.required(result,"id"),Json.required(run,"id"),Json.required(sample,"id"),Json.required(sample,"assetId"),RunInputs.inputId(sample),Json.str(result,"attemptId",null),Json.required(result,"source"),resultStatus,Json.required(result,"createdAt"),result);if(Json.str(result,"source","").equals("api")&&result.has("attemptId")){String attemptId=Json.required(result,"attemptId");JsonObject actual=Json.parse(Store.one(c,"SELECT data FROM attempts WHERE id=?",attemptId).get("data").getAsString());actual.addProperty("status","completed");actual.addProperty("completedAt",Json.now());Store.update(c,"UPDATE attempts SET status='completed',data=? WHERE id=?",actual,attemptId);}persisted.add("resultId",result.get("id"));persisted.addProperty("completedAt",Json.now());persisted.addProperty("requiresGeometryReview",Json.bool(result,"requiresGeometryReview",false));persisted.remove("errorCode");persisted.remove("message");persisted.remove("reused");persisted.remove("inputReusedFrom");if(result.has("inputReusedFrom")){persisted.addProperty("reused",true);persisted.add("inputReusedFrom",result.get("inputReusedFrom"));live.addProperty("reused",Json.integer(live,"reused",0)+1);Store.update(c,"UPDATE runs SET data=? WHERE id=?",live,Json.required(run,"id"));}for(String field:List.of("errorCode","message"))if(result.has(field))persisted.add(field,result.get(field));Store.update(c,"UPDATE samples SET status=?,active_attempt=NULL,data=? WHERE id=? AND active_attempt=?",status,persisted,Json.required(sample,"id"),claim);if(!cancelled&&Set.of("failed","unknown").contains(status)&&Json.str(live,"failurePolicy","continue").equals("pause")){live.addProperty("status","paused");live.addProperty("pauseReason",status.equals("unknown")?"result_unknown":"sample_failed");Store.update(c,"UPDATE runs SET status='paused',data=? WHERE id=?",live,Json.required(run,"id"));}Store.event(c,"sample."+status,Json.required(run,"id"),Json.required(sample,"assetId"),Json.str(result,"attemptId",null),Json.obj("inputId",RunInputs.inputId(sample),"resultId",result.get("id"),"requiresGeometryReview",result.get("requiresGeometryReview")));return true;});}
    record Group(JsonObject run,JsonObject baseline,JsonArray expected,JsonArray results,String signature){}
    static boolean aggregated(Connection c,String runId)throws Exception{for(JsonObject row:Store.rows(c,"SELECT asset_id FROM run_baselines WHERE run_id=?",runId)){String assetId=Json.required(row,"asset_id"),signature=signature(c,runId,assetId);if(Store.one(c,"SELECT id FROM run_asset_results WHERE run_id=? AND asset_id=? AND json_extract(data,'$.sampleSetHash')=?",runId,assetId,signature)==null)return false;}return true;}
    void schedulePending(String runId){if(store.read(c->aggregated(c,runId)))return;engine.flows.aggregatePending(runId);}
    void apiFailure(JsonObject run,JsonObject sample,String claim,boolean sent,JsonObject raw,Exception error)throws Exception{
        JsonObject result=result(run,sample,"api",sent?claim:null,raw,Json.obj("responseRecordedInAttempt",sent),error);boolean saved=store.tx(c->{JsonObject row=Store.one(c,"SELECT active_attempt,data FROM samples WHERE id=?",Json.required(sample,"id"));if(row==null||!claim.equals(Json.str(row,"active_attempt","")))return false;JsonObject data=Json.parse(row.get("data").getAsString());Store.update(c,"INSERT INTO input_results(id,run_id,sample_id,asset_id,input_id,attempt_id,source,status,created_at,data) VALUES(?,?,?,?,?,?,?,?,?,?)",Json.required(result,"id"),Json.required(run,"id"),Json.required(sample,"id"),Json.required(sample,"assetId"),RunInputs.inputId(sample),sent?claim:null,"api",Json.required(result,"status"),Json.required(result,"createdAt"),result);data.add("resultId",result.get("id"));data.addProperty("requiresGeometryReview",true);Store.update(c,"UPDATE samples SET data=? WHERE id=?",data,Json.required(sample,"id"));return true;});if(saved)aggregate(Json.required(run,"id"),Json.required(sample,"assetId"));
    }
    static String signature(Connection c,String run,String asset)throws Exception{return RunInputs.hash(Json.element(Store.rows(c,"SELECT input_id,status,json_extract(data,'$.resultId') AS result FROM samples WHERE run_id=? AND asset_id=? ORDER BY input_id",run,asset)));}
    void aggregate(String runId,String assetId)throws Exception{
        Group group=store.read(c->{JsonObject run=Store.document(c,"runs",runId);if(Json.required(run,"status").equals("cancelled"))return null;List<JsonObject> samples=Store.rows(c,"SELECT status,data FROM samples WHERE run_id=? AND asset_id=? ORDER BY input_id",runId,assetId);for(JsonObject row:samples)if(!Set.of("succeeded","failed","unknown","cancelled").contains(Json.required(row,"status")))return null;JsonObject baseline=RunInputs.baseline(c,runId,assetId),asset=Json.object(baseline,"asset");JsonArray expected=new JsonArray(),results=new JsonArray();for(JsonObject row:samples){JsonObject sample=Json.parse(row.get("data").getAsString()),input=Json.object(sample,"inputSnapshot"),rect=Json.object(Json.object(input,"inputTransform"),"baselineCoverageRect");if(rect.isEmpty())rect=Json.obj("x",0,"y",0,"width",asset.get("width"),"height",asset.get("height"));expected.add(Json.obj("inputId",RunInputs.inputId(sample),"baselineCoverageRect",rect));if(sample.has("resultId")){JsonObject result=Store.document(c,"input_results",Json.required(sample,"resultId"));results.add(Json.obj("inputId",RunInputs.inputId(sample),"resultId",result.get("id"),"status",result.get("status"),"mapping",result.get("mappedResult")));}}return new Group(run,baseline,expected,results,signature(c,runId,assetId));});if(group==null)return;
        JsonObject asset=Json.object(group.baseline,"asset"),project=Json.object(Json.object(group.run,"snapshot"),"project"),aggregate;try{aggregate=InputAggregation.aggregate(asset,project,group.expected,group.results);}catch(ApiError error){JsonArray ids=new JsonArray();for(JsonElement value:group.results)ids.add(value.getAsJsonObject().get("resultId"));aggregate=Json.obj("resultSetHash",RunInputs.hash(Json.obj("signature",group.signature,"aggregationVersion",InputAggregation.VERSION,"error",error.code)),"annotations",new JsonArray(),"requiresGeometryReview",true,"geometryIssues",Json.arr(Json.obj("code",error.code,"severity","error","message",error.getMessage())),"coverage",Json.obj("area",0,"totalArea",Json.integer(asset,"width",0)*(double)Json.integer(asset,"height",0),"complete",false),"statistics",Json.obj("inputsTotal",group.expected.size()),"resultIds",ids,"objectSources",new JsonArray());}
        JsonObject fixed=aggregate;store.tx(c->{JsonObject live=Store.document(c,"runs",runId);if(Json.required(live,"status").equals("cancelled")||!group.signature.equals(signature(c,runId,assetId)))return null;String hash=Json.required(fixed,"resultSetHash");if(Store.one(c,"SELECT id FROM run_asset_results WHERE run_id=? AND asset_id=? AND result_set_hash=?",runId,assetId,hash)!=null)return null;JsonObject current=Store.document(c,"assets",assetId);int version=Projects.nextVersion(c,assetId);String id=Json.id(),source=Json.str(live,"kind","api").equals("local")?"local":"api";JsonObject candidate=asset.deepCopy();candidate.add("annotations",fixed.get("annotations"));candidate.addProperty("version",version);candidate.addProperty("status","candidate");candidate.addProperty("source",source);candidate.addProperty("runId",runId);candidate.addProperty("resultGroupId",id);candidate.remove("attemptId");candidate.remove("reused");candidate.remove("reusedFrom");JsonObject metadata=Json.object(candidate,"metadata");metadata.addProperty("requiresGeometryReview",Json.bool(fixed,"requiresGeometryReview",false));metadata.add("geometryIssues",fixed.get("geometryIssues"));metadata.add("coverage",fixed.get("coverage"));metadata.add("inputResultIds",fixed.get("resultIds"));metadata.addProperty("aggregationVersion",InputAggregation.VERSION);metadata.add("annotationTemplate",TaskTemplates.snapshot(project));candidate.add("metadata",metadata);Store.update(c,"INSERT INTO versions(asset_id,version,source,data,attempt_id,created_at) VALUES(?,?,?,?,NULL,?)",assetId,version,source,candidate,Json.now());boolean protectedHuman=Json.bool(group.baseline,"manualProtected",false)||Set.of("modified","confirmed").contains(Json.str(current,"status",""))||Json.integer(current,"version",0)!=Json.integer(asset,"version",0)||Store.one(c,"SELECT asset_id FROM drafts WHERE asset_id=?",assetId)!=null||!TaskTemplates.semantic(Store.document(c,"projects",Json.required(live,"projectId"))).equals(TaskTemplates.semantic(project));if(!protectedHuman)Store.update(c,"UPDATE assets SET data=? WHERE id=?",candidate,assetId);
            JsonObject record=fixed.deepCopy();record.addProperty("id",id);record.addProperty("runId",runId);record.addProperty("assetId",assetId);record.addProperty("candidateVersion",version);record.addProperty("createdAt",Json.now());record.addProperty("sampleSetHash",group.signature);String status=Json.bool(fixed,"requiresGeometryReview",false)?"needs_attention":"completed";record.addProperty("status",status);Store.update(c,"INSERT INTO run_asset_results(id,run_id,asset_id,result_set_hash,candidate_version,status,created_at,data) VALUES(?,?,?,?,?,?,?,?)",id,runId,assetId,hash,version,status,Json.required(record,"createdAt"),record);Store.update(c,"UPDATE samples SET data=json_set(data,'$.candidateVersion',?,'$.requiresGeometryReview',json(?)) WHERE run_id=? AND asset_id=?",version,Json.bool(fixed,"requiresGeometryReview",false)?"true":"false",runId,assetId);Store.event(c,"annotation.candidate",runId,assetId,null,Json.obj("version",version,"resultGroupId",id,"requiresGeometryReview",fixed.get("requiresGeometryReview"),"manualProtected",protectedHuman));return null;});
    }
}
