package cn.autolabel.engine;

import com.google.gson.*;
import java.sql.Connection;
import java.math.BigInteger;
import java.util.*;
import java.util.concurrent.*;
import static cn.autolabel.engine.TrackTimelines.*;

/** 冻结计划按帧提交，贡献头只表示当前机器候选；人工保存始终拥有整帧优先权。 */
final class TrackGenerations implements AutoCloseable {
    private static final Set<String> ACTIVE=Set.of("queued","running","cancelling");
    final Engine engine;final Store store;final Tracks tracks;
    private final Object gate=new Object();
    private final ThreadPoolExecutor worker=new ThreadPoolExecutor(1,1,0,TimeUnit.MILLISECONDS,new ArrayBlockingQueue<>(1),Thread.ofPlatform().name("track-generation-",0).factory(),new ThreadPoolExecutor.AbortPolicy());
    private volatile String activeId;private volatile boolean closed,cancelled;

    TrackGenerations(Engine engine,Tracks tracks){this.engine=engine;store=engine.store;this.tracks=tracks;
        store.tx(c->{for(JsonElement value:Store.docs(c,"SELECT data FROM track_generations WHERE status IN ('queued','running','cancelling')")){JsonObject job=value.getAsJsonObject();job.addProperty("status","interrupted");job.add("error",Json.obj("code","track_restart_interrupted","message","引擎重启中断了生成；已提交帧保留，可显式重试剩余范围。"));save(c,job,"interrupted");}return null;});
    }
    static JsonObject publicView(JsonObject job){JsonObject out=new JsonObject();for(var entry:job.entrySet())if(!entry.getKey().equals("plan"))out.add(entry.getKey(),entry.getValue());out.addProperty("canCancel",ACTIVE.contains(Json.required(job,"status")));return out;}
    static JsonObject issue(String code,String message){return Json.obj("code",code,"message",message,"severity","error");}
    static void save(Connection c,JsonObject job,String event)throws Exception{
        job.addProperty("updatedAt",Json.now());JsonObject timeline=Store.document(c,"track_timelines",Json.required(job,"timelineId"));
        TrackTimelines.event(c,"generation."+event,timeline,Json.required(job,"trackId"),Json.required(job,"id"),Json.obj("status",job.get("status"),"progress",job.get("progress")));
        job.addProperty("sequence",Store.cursor(c));Store.update(c,"UPDATE track_generations SET status=?,data=? WHERE id=?",Json.required(job,"status"),publicView(job),Json.required(job,"id"));
    }
    static JsonArray heads(Connection c,String assetId)throws Exception{return Store.docs(c,"SELECT c.data FROM track_contribution_heads h JOIN track_contributions c ON c.id=h.contribution_id WHERE h.asset_id=? ORDER BY h.track_id",assetId);}
    static JsonArray baseAnnotations(JsonObject asset,JsonArray heads){Set<String> owned=new HashSet<>();for(JsonElement value:heads)for(JsonElement annotation:Json.array(value.getAsJsonObject(),"annotations"))owned.add(Json.required(annotation.getAsJsonObject(),"id"));JsonArray result=new JsonArray();for(JsonElement value:Json.array(asset,"annotations"))if(!owned.contains(Json.required(value.getAsJsonObject(),"id")))result.add(value.deepCopy());return result;}
    private static Set<String> frameScope(List<JsonObject> frames,List<JsonObject> outputs){Map<String,Integer> positions=new HashMap<>();for(int i=0;i<frames.size();i++)positions.put(Json.required(frames.get(i),"frameId"),i);Set<String> scope=new LinkedHashSet<>();for(JsonObject track:outputs){int first=Integer.MAX_VALUE,last=-1;for(JsonElement value:Json.array(track,"keyframes")){int index=positions.get(Json.required(value.getAsJsonObject(),"frameId"));first=Math.min(first,index);last=Math.max(last,index);}for(int i=first;i<=last;i++)scope.add(Json.required(frames.get(i),"frameId"));}return scope;}
    private static void anchors(Connection c,JsonObject timeline,List<JsonObject> outputs)throws Exception{
        for(JsonObject track:outputs)for(JsonElement value:Json.array(track,"keyframes")){JsonObject key=value.getAsJsonObject();if(Json.required(key,"state").equals("unlocatable"))continue;JsonObject f=frame(c,Json.required(timeline,"id"),Json.required(key,"frameId")),asset=current(c,f),state=state(c,f);boolean found=false;for(JsonElement annotation:Json.array(asset,"annotations"))found|=annotation.equals(key.get("annotation"));if(!found||!state.get("draftSavedAt").isJsonNull())throw error(409,"track_keyframe_source_changed","关键帧绑定对象或草稿已变化，请重新保存并绑定该关键帧。");}
    }
    private JsonObject plan(Connection c,JsonObject timeline,JsonObject owner,List<JsonObject> outputs,List<JsonObject> retired,Set<String> requested,JsonObject parameters,String scope)throws Exception{
        currentTemplate(c,timeline);anchors(c,timeline,outputs);List<JsonObject> frames=TrackTimelines.frames(c,Json.required(timeline,"id"));JsonObject helper=helperTimeline(c,timeline);Map<String,JsonObject> byFrame=new LinkedHashMap<>();for(JsonObject frame:frames)byFrame.put(Json.required(frame,"frameId"),frame);
        Set<String> ids=new LinkedHashSet<>(requested);JsonArray reports=new JsonArray(),intervals=new JsonArray(),skipped=new JsonArray(),issues=new JsonArray();
        for(JsonObject track:outputs){JsonObject report=Json.array(track,"keyframes").isEmpty()?Json.obj("candidates",new JsonArray(),"intervals",new JsonArray(),"skipped",new JsonArray()):TrackInterpolation.interpolate(Json.object(timeline,"template"),helper,Tracks.helper(track),parameters);
            Set<String> rangeBlocked=new HashSet<>();for(JsonElement value:Json.array(report,"intervals")){JsonObject interval=value.getAsJsonObject();JsonObject left=byFrame.get(Json.required(interval,"leftFrameId")),right=byFrame.get(Json.required(interval,"rightFrameId"));if(Json.integer(left,"rangeIndex",0)!=Json.integer(right,"rangeIndex",0)){interval.addProperty("blocked",true);interval.addProperty("requiresReview",true);interval.addProperty("candidateCount",0);Json.array(interval,"reviewIssues").add(issue("range_gap","区间跨越独立抽帧时间段，不能连接。"));rangeBlocked.add(Json.required(interval,"intervalId"));}intervals.add(interval);for(JsonElement item:Json.array(interval,"reviewIssues"))issues.add(item);}
            JsonArray valid=new JsonArray();for(JsonElement value:Json.array(report,"candidates")){JsonObject candidate=value.getAsJsonObject();if(rangeBlocked.contains(Json.required(Json.object(candidate,"source"),"intervalId"))){JsonObject f=byFrame.get(Json.required(candidate,"frameId"));Json.array(report,"skipped").add(Json.obj("frameId",f.get("frameId"),"reason","range_gap","message","不跨越独立抽帧时间段生成。","annotationState",state(c,f).get("annotationState"),"annotationVersion",state(c,f).get("annotationVersion")));continue;}try{Annotations.validate(Json.array(candidate,"annotations"),byFrame.get(Json.required(candidate,"frameId")),Json.object(timeline,"template"));candidate.addProperty("valid",true);}catch(ApiError e){candidate.addProperty("valid",false);candidate.addProperty("requiresReview",true);JsonObject problem=issue(e.code,e.getMessage());problem.add("frameId",candidate.get("frameId"));Json.array(candidate,"reviewIssues").add(problem);issues.add(problem);}valid.add(candidate);}
            report.add("candidates",valid);report.addProperty("trackId",Json.required(track,"id"));reports.add(report);for(JsonElement value:Json.array(report,"skipped"))if(ids.contains(Json.required(value.getAsJsonObject(),"frameId")))skipped.add(value);
        }
        JsonArray frozenFrames=new JsonArray(),scopeIds=new JsonArray();for(JsonObject f:frames)if(ids.contains(Json.required(f,"frameId"))){JsonObject copy=f.deepCopy(),asset=current(c,f);copy.add("expected",state(c,f));copy.add("baseAnnotations",baseAnnotations(asset,heads(c,Json.required(f,"assetId"))));frozenFrames.add(copy);scopeIds.add(f.get("frameId"));}
        JsonArray involved=new JsonArray();Set<String> seen=new HashSet<>();for(JsonObject track:concat(outputs,retired))if(seen.add(Json.required(track,"id")))involved.add(track.deepCopy());if(seen.add(Json.required(owner,"id")))involved.add(owner.deepCopy());
        JsonObject result=Json.obj("timeline",timeline.deepCopy(),"owner",owner.deepCopy(),"outputs",Json.element(outputs),"retired",Json.element(retired),"involved",involved,"frames",frozenFrames,"frameIds",scopeIds,"reports",reports,"intervals",intervals,"skipped",skipped,"issues",issues,"parameters",parameters,"scope",scope);
        result.addProperty("planHash",hash(result));return result;
    }
    private static List<JsonObject> concat(List<JsonObject> a,List<JsonObject> b){List<JsonObject> result=new ArrayList<>(a);result.addAll(b);return result;}
    private static List<JsonObject> objects(JsonArray values){List<JsonObject> out=new ArrayList<>();for(JsonElement value:values)out.add(value.getAsJsonObject());return out;}
    static Set<String> outputScope(Connection c,JsonObject timeline,List<JsonObject> outputs)throws Exception{return frameScope(TrackTimelines.frames(c,Json.required(timeline,"id")),outputs);}
    private record Prepared(Map<String,List<JsonObject>> candidates,Map<String,JsonArray> blocked,Map<String,JsonObject> keys){}
    private record Exact(BigInteger numerator,BigInteger denominator) implements Comparable<Exact>{public int compareTo(Exact other){return numerator.multiply(other.denominator).compareTo(other.numerator.multiply(denominator));}}
    private static Exact exact(JsonObject time){return new Exact(new BigInteger(Json.required(time,"numerator")),new BigInteger(Json.required(time,"denominator")));}
    private static Prepared prepare(JsonObject plan){
        Map<String,List<JsonObject>> candidates=new HashMap<>();Map<String,JsonArray> blocked=new HashMap<>();Map<String,JsonObject> keys=new HashMap<>();
        for(JsonElement track:Json.array(plan,"outputs"))for(JsonElement key:Json.array(track.getAsJsonObject(),"keyframes"))keys.put(Json.required(key.getAsJsonObject(),"keyframeId"),key.getAsJsonObject());
        for(JsonElement value:Json.array(plan,"reports")){JsonObject report=value.getAsJsonObject();for(JsonElement item:Json.array(report,"candidates")){JsonObject candidate=item.getAsJsonObject().deepCopy();candidate.add("trackId",report.get("trackId"));candidates.computeIfAbsent(Json.required(candidate,"frameId"),ignored->new ArrayList<>()).add(candidate);}}
        // 先索引本次范围，逐帧提交不反复扫描整个候选清单。
        NavigableMap<Exact,JsonObject> ordered=new TreeMap<>();for(JsonElement value:Json.array(plan,"frames")){JsonObject frame=value.getAsJsonObject(),base=Json.object(frame,"timeBase");ordered.put(new Exact(new BigInteger(Json.required(frame,"sourcePts")).multiply(new BigInteger(Json.required(base,"numerator"))),new BigInteger(Json.required(base,"denominator"))),frame);}
        for(JsonElement value:Json.array(plan,"intervals")){JsonObject interval=value.getAsJsonObject();if(!Json.bool(interval,"blocked",false))continue;for(JsonObject f:ordered.subMap(exact(Json.object(interval,"startTime")),false,exact(Json.object(interval,"endTime")),false).values()){JsonArray reasons=blocked.computeIfAbsent(Json.required(f,"frameId"),ignored->new JsonArray());for(JsonElement issue:Json.array(interval,"reviewIssues"))reasons.add(issue);}}
        return new Prepared(candidates,blocked,keys);
    }
    private JsonObject requestedPlan(JsonObject p){FlowPlans.keys(p,"trackId","baseVersion","timelineVersion","parameters","scope","expectedPlanHash");String trackId=id(p,"trackId"),scope=Json.str(p,"scope","affected");if(!Set.of("affected","all").contains(scope))throw error(400,"track_scope_invalid","生成范围无效。");if(p.has("parameters")&&!p.get("parameters").isJsonObject())throw error(400,"track_parameters_invalid","生成参数必须是对象。");JsonObject parameters=TrackInterpolation.options(p.has("parameters")?Json.object(p,"parameters"):null);long expected=version(p,"baseVersion"),timelineVersion=version(p,"timelineVersion");
        return store.read(c->{JsonObject track=Tracks.require(c,trackId,expected,true),timeline=Tracks.timeline(c,track,timelineVersion);Set<String> ids=new LinkedHashSet<>();for(JsonObject row:Store.rows(c,"SELECT frame_id FROM track_dirty_frames WHERE track_id=?",trackId))ids.add(Json.required(row,"frame_id"));JsonObject prior=Store.one(c,"SELECT data FROM track_generations WHERE track_id=? ORDER BY rowid DESC LIMIT 1",trackId);boolean changedParameters=prior!=null&&!parameters.equals(Json.object(Json.parse(Json.required(prior,"data")),"parameters"));if(scope.equals("all")||changedParameters||prior==null){ids.addAll(frameScope(TrackTimelines.frames(c,Json.required(timeline,"id")),List.of(track)));ids.addAll(Tracks.headFrames(c,Json.required(timeline,"id"),List.of(trackId)));}return plan(c,timeline,track,List.of(track),List.of(),ids,parameters,scope);});
    }
    JsonObject preview(JsonObject p){JsonObject plan=requestedPlan(p),result=Json.obj("canGenerate",true,"planHash",plan.get("planHash"),"frameCount",Json.object(plan,"timeline").get("frameCount"),"affectedCount",Json.array(plan,"frames").size(),"parameters",plan.get("parameters"));int protectedCount=0;for(JsonElement value:Json.array(plan,"frames"))if(Json.bool(Json.object(value.getAsJsonObject(),"expected"),"protected",false))protectedCount++;result.addProperty("protectedCount",protectedCount);result.add("issues",slice(Json.array(plan,"issues"),0,100));result.addProperty("issueCount",Json.array(plan,"issues").size());result.add("intervals",slice(Json.array(plan,"intervals"),0,500));result.addProperty("intervalsTotal",Json.array(plan,"intervals").size());result.addProperty("intervalsTruncated",Json.array(plan,"intervals").size()>500);return result;}
    JsonObject generate(JsonObject p){JsonObject plan=requestedPlan(p);if(p.has("expectedPlanHash")&&!FlowPlans.string(p,"expectedPlanHash",128).equals(Json.required(plan,"planHash")))throw error(409,"track_plan_changed","预览依赖已经变化，请重新预览。");return store.tx(c->{validate(c,plan,true);return insert(c,plan,null);});}
    JsonObject structural(Connection c,JsonObject timeline,JsonObject owner,List<JsonObject> outputs,List<JsonObject> retired,Set<String> ids)throws Exception{Set<String> scope=new LinkedHashSet<>(ids);scope.addAll(frameScope(TrackTimelines.frames(c,Json.required(timeline,"id")),outputs));for(JsonObject track:concat(outputs,retired))Tracks.dirty(c,Json.required(track,"id"),scope);return insert(c,plan(c,timeline,owner,outputs,retired,scope,TrackInterpolation.options(null),"affected"),null);}
    private JsonObject insert(Connection c,JsonObject plan,String original)throws Exception{
        if(Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM track_generations WHERE status IN ('queued','running','cancelling')"),"n",0)>=128)throw error(429,"track_queue_full","轨迹生成队列已满，请等待现有任务完成。");JsonObject owner=Json.object(plan,"owner"),timeline=Json.object(plan,"timeline");JsonArray involved=new JsonArray();for(JsonElement value:Json.array(plan,"involved"))involved.add(value.getAsJsonObject().get("id"));JsonObject job=Json.obj("id",Json.id(),"trackId",owner.get("id"),"timelineId",timeline.get("id"),"trackVersion",owner.get("version"),"timelineVersion",timeline.get("version"),"involvedTrackIds",involved,"status","queued","createdAt",Json.now(),"updatedAt",Json.now(),"parameters",plan.get("parameters"),"scope",plan.get("scope"),"progress",Json.obj("phase","queued","completed",0,"total",Json.array(plan,"frames").size(),"applied",0,"protected",0,"conflicts",0,"failed",0),"candidateOnly",true,"humanConfirmed",false,"requestsUsed",0,"plan",plan);if(original!=null)job.addProperty("originalGenerationId",original);Store.update(c,"INSERT INTO track_generations(id,track_id,status,data) VALUES(?,?,?,?)",Json.required(job,"id"),Json.required(job,"trackId"),"queued",publicView(job));Store.update(c,"INSERT INTO track_generation_plans(generation_id,data) VALUES(?,?)",Json.required(job,"id"),plan);save(c,job,"queued");return publicView(job);
    }
    /**
     * 受控外部调用方（本地 Detect 跟踪候选提升）提交已冻结计划。
     * 仍走同一版本校验、排队和逐帧提交路径，产物保持候选态；不使用 interpolate，避免用插值伪造成实际检测结果。
     */
    JsonObject enqueueExternal(Connection c,JsonObject plan,String original)throws Exception{validate(c,plan,true);return insert(c,plan,original);}
    static JsonObject storedPlan(Connection c,String id)throws Exception{JsonObject row=Store.one(c,"SELECT data FROM track_generation_plans WHERE generation_id=?",id);if(row==null)throw error(409,"track_generation_plan_missing","生成的冻结计划缺失，不能自动继续。");return Json.parse(Json.required(row,"data"));}
    private static JsonArray slice(JsonArray values,int offset,int limit){JsonArray out=new JsonArray();for(int i=offset;i<values.size()&&out.size()<limit;i++)out.add(values.get(i));return out;}
    JsonObject get(JsonObject p){FlowPlans.keys(p,"generationId");return store.read(c->publicView(Store.document(c,"track_generations",id(p,"generationId"))));}
    JsonObject list(JsonObject p){FlowPlans.keys(p,"trackId","offset","limit");String trackId=id(p,"trackId");int offset=pageInt(p,"offset",0,0,Integer.MAX_VALUE),limit=pageInt(p,"limit",100,1,100);return store.read(c->{Store.document(c,"tracks",trackId);JsonArray items=new JsonArray();for(JsonElement value:Store.docs(c,"SELECT data FROM track_generations WHERE track_id=? ORDER BY rowid DESC LIMIT ? OFFSET ?",trackId,limit,offset))items.add(publicView(value.getAsJsonObject()));return Json.obj("items",items,"total",Store.one(c,"SELECT COUNT(*) AS n FROM track_generations WHERE track_id=?",trackId).get("n"));});}
    JsonObject results(JsonObject p){FlowPlans.keys(p,"generationId","section","offset","limit");String generationId=id(p,"generationId"),section=Json.str(p,"section","frames");if(!Set.of("frames","intervals","skipped").contains(section))throw error(400,"track_section_invalid","生成结果分区无效。");int offset=pageInt(p,"offset",0,0,Integer.MAX_VALUE),limit=pageInt(p,"limit",100,1,500);return store.read(c->{JsonObject job=Store.document(c,"track_generations",generationId);JsonArray items;int total;if(section.equals("frames")){items=Store.docs(c,"SELECT data FROM track_generation_frames WHERE generation_id=? ORDER BY rowid LIMIT ? OFFSET ?",generationId,limit,offset);total=Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM track_generation_frames WHERE generation_id=?",generationId),"n",0);}else{JsonArray all=Json.array(storedPlan(c,generationId),section);items=slice(all,offset,limit);total=all.size();}return Json.obj("generationId",generationId,"section",section,"items",items,"total",total,"offset",offset,"limit",limit);});}
    JsonObject cancel(JsonObject p){FlowPlans.keys(p,"generationId");String id=id(p,"generationId");synchronized(gate){if(id.equals(activeId))cancelled=true;return store.tx(c->{JsonObject job=Store.document(c,"track_generations",id);String status=Json.required(job,"status");if(ACTIVE.contains(status)){job.addProperty("status",status.equals("queued")?"cancelled":"cancelling");save(c,job,"cancel_requested");}return publicView(job);});}}
    JsonObject retry(JsonObject p){FlowPlans.keys(p,"generationId");String id=id(p,"generationId");return store.tx(c->{JsonObject old=Store.document(c,"track_generations",id);if(!Set.of("cancelled","interrupted","failed","completed_with_errors").contains(Json.required(old,"status")))throw error(409,"track_retry_invalid","该生成记录没有可重试的中断或失败范围。");JsonObject prior=storedPlan(c,id);validate(c,prior,false);Set<String> remaining=new LinkedHashSet<>(Tracks.strings(Json.array(prior,"frameIds")));for(JsonObject row:Store.rows(c,"SELECT data FROM track_generation_frames WHERE generation_id=? AND status IN ('applied','removed','unchanged','protected')",id))remaining.remove(Json.required(Json.parse(Json.required(row,"data")),"frameId"));JsonObject next=plan(c,Json.object(prior,"timeline"),Json.object(prior,"owner"),objects(Json.array(prior,"outputs")),objects(Json.array(prior,"retired")),remaining,Json.object(old,"parameters"),Json.required(old,"scope"));return insert(c,next,id);});}
    private static void validateVersions(Connection c,JsonObject plan)throws Exception{
        JsonObject frozen=Json.object(plan,"timeline"),live=Store.document(c,"track_timelines",Json.required(frozen,"id"));expect(Json.number(frozen,"version",0),Json.number(live,"version",0));currentTemplate(c,live);for(JsonElement value:Json.array(plan,"involved")){JsonObject fixed=value.getAsJsonObject();Tracks.require(c,Json.required(fixed,"id"),Json.number(fixed,"version",0),false);}
    }
    private static void validate(Connection c,JsonObject plan,boolean frameStates)throws Exception{
        JsonObject frozen=Json.object(plan,"timeline"),live=Store.document(c,"track_timelines",Json.required(frozen,"id"));expect(Json.number(frozen,"version",0),Json.number(live,"version",0));currentTemplate(c,live);for(JsonElement value:Json.array(plan,"involved")){JsonObject fixed=value.getAsJsonObject();Tracks.require(c,Json.required(fixed,"id"),Json.number(fixed,"version",0),false);}anchors(c,live,objects(Json.array(plan,"outputs")));
        if(frameStates)for(JsonElement value:Json.array(plan,"frames")){JsonObject frame=value.getAsJsonObject();if(!state(c,frame).equals(Json.object(frame,"expected")))throw error(409,"track_plan_changed","生成计划中的素材版本或草稿已经变化，请重新预览。");}
    }
    void tick(){synchronized(gate){if(closed||activeId!=null)return;JsonObject job=store.read(c->{JsonObject row=Store.one(c,"SELECT data FROM track_generations WHERE status='queued' ORDER BY rowid LIMIT 1");return row==null?null:Json.parse(Json.required(row,"data"));});if(job==null)return;activeId=Json.required(job,"id");cancelled=false;String id=activeId;worker.execute(()->{try{execute(id);}finally{synchronized(gate){activeId=null;cancelled=false;}}});}}
    int active(){return activeId==null?0:1;}
    private boolean stopping(){return closed||cancelled||Thread.currentThread().isInterrupted();}
    private void execute(String id){
        try{JsonObject job=store.tx(c->{JsonObject current=Store.document(c,"track_generations",id);if(!Json.required(current,"status").equals("queued"))return null;current.add("plan",storedPlan(c,id));validate(c,Json.object(current,"plan"),false);current.addProperty("status","running");Json.object(current,"progress").addProperty("phase","applying");save(c,current,"started");return current;});if(job==null)return;JsonObject plan=Json.object(job,"plan");Prepared prepared=prepare(plan);
            for(JsonElement value:Json.array(plan,"frames")){if(stopping())break;JsonObject frame=value.getAsJsonObject();try{tracks.timelines.verifyFile(frame);store.tx(c->{JsonObject current=Store.document(c,"track_generations",id);if(stopping()||!Json.required(current,"status").equals("running"))return null;validateVersions(c,plan);Set<String> endpointIds=new HashSet<>();for(JsonObject candidate:prepared.candidates.getOrDefault(Json.required(frame,"frameId"),List.of()))for(JsonElement key:Json.array(Json.object(candidate,"source"),"keyframeIds"))endpointIds.add(key.getAsString());JsonArray keys=new JsonArray();for(String key:endpointIds)keys.add(prepared.keys.get(key));anchors(c,Json.object(plan,"timeline"),List.of(Json.obj("keyframes",keys)));current.add("plan",plan);JsonObject result=apply(c,current,frame,prepared);record(c,current,result);return null;});}catch(ApiError e){if(Set.of("track_version_conflict","track_template_changed","track_keyframe_source_changed").contains(e.code))throw e;store.tx(c->{JsonObject current=Store.document(c,"track_generations",id);current.add("plan",plan);record(c,current,frameResult(frame,"conflict",new JsonArray(),Json.arr(issue(e.code,e.getMessage())),true));return null;});}}
            store.tx(c->{JsonObject current=Store.document(c,"track_generations",id),progress=Json.object(current,"progress");String status=closed?"interrupted":cancelled||Json.required(current,"status").equals("cancelling")?"cancelled":Json.integer(progress,"conflicts",0)+Json.integer(progress,"failed",0)>0?"completed_with_errors":"completed";current.addProperty("status",status);progress.addProperty("phase",status);current.add("summary",progress.deepCopy());save(c,current,status);return null;});
        }catch(Exception e){store.tx(c->{JsonObject job=Store.document(c,"track_generations",id);job.addProperty("status",closed?"interrupted":cancelled?"cancelled":"failed");job.add("error",Json.obj("code",e instanceof ApiError a?a.code:"track_generation_failed","message",e instanceof ApiError?e.getMessage():"轨迹生成未完成，已提交的逐帧结果保留。"));save(c,job,"failed");return null;});}
    }
    private static JsonObject frameResult(JsonObject frame,String status,JsonArray annotations,JsonArray reasons,boolean review){return Json.obj("frameId",frame.get("frameId"),"assetId",frame.get("assetId"),"status",status,"annotations",annotations,"requiresReview",review,"reasons",reasons);}
    private static void record(Connection c,JsonObject job,JsonObject result)throws Exception{String status=Json.required(result,"status");Store.update(c,"INSERT INTO track_generation_frames(id,generation_id,asset_id,status,data) VALUES(?,?,?,?,?)",Json.id(),Json.required(job,"id"),Json.required(result,"assetId"),status,result);JsonObject progress=Json.object(job,"progress");progress.addProperty("completed",Json.integer(progress,"completed",0)+1);String field=switch(status){case "applied","removed"->"applied";case "protected"->"protected";case "conflict"->"conflicts";case "blocked"->"failed";default->null;};if(field!=null)progress.addProperty(field,Json.integer(progress,field,0)+1);if(!Set.of("blocked","conflict").contains(status))for(JsonElement value:Json.array(Json.object(job,"plan"),"involved"))Store.update(c,"DELETE FROM track_dirty_frames WHERE track_id=? AND frame_id=?",Json.required(value.getAsJsonObject(),"id"),Json.required(result,"frameId"));save(c,job,"progress");}
    private JsonObject apply(Connection c,JsonObject job,JsonObject frame,Prepared prepared)throws Exception{
        JsonObject plan=Json.object(job,"plan"),timeline=Json.object(plan,"timeline"),asset=current(c,frame),state=state(c,frame);String assetId=Json.required(frame,"assetId"),frameId=Json.required(frame,"frameId"),generationId=Json.required(job,"id");JsonArray oldHeads=heads(c,assetId),base=baseAnnotations(asset,oldHeads);
        if(Json.bool(state,"protected",false))return frameResult(frame,"protected",new JsonArray(),Json.arr(issue("human_protected","该帧已有人工修改、确认或草稿，保留整帧。")),false);
        if(!base.equals(Json.array(frame,"baseAnnotations"))||Json.number(state,"annotationVersion",0)!=Json.number(Json.object(frame,"expected"),"annotationVersion",0)&&!Json.str(asset,"source","").equals("track"))return frameResult(frame,"conflict",new JsonArray(),Json.arr(issue("track_asset_changed","素材标注在排队后变化，请重新预览。")),true);
        Set<String> replaced=new HashSet<>();for(JsonElement value:Json.array(plan,"involved"))replaced.add(Json.required(value.getAsJsonObject(),"id"));JsonArray combined=base.deepCopy(),nextHeads=new JsonArray(),raw=new JsonArray(),reasons=new JsonArray();boolean invalid=false,review=false;String firstContribution=null;
        for(JsonElement value:oldHeads){JsonObject contribution=value.getAsJsonObject();if(!replaced.contains(Json.required(contribution,"trackId"))){nextHeads.add(contribution);for(JsonElement annotation:Json.array(contribution,"annotations"))combined.add(annotation);review|=Json.bool(contribution,"requiresReview",false);}}
        for(JsonObject candidate:prepared.candidates.getOrDefault(frameId,List.of())){JsonObject contribution=candidate.deepCopy();String contributionId=Json.id();contribution.addProperty("id",contributionId);contribution.addProperty("trackId",Json.required(candidate,"trackId"));contribution.addProperty("generationId",generationId);contribution.addProperty("assetId",assetId);contribution.addProperty("createdAt",Json.now());Store.update(c,"INSERT INTO track_contributions(id,generation_id,track_id,asset_id,data) VALUES(?,?,?,?,?)",contributionId,generationId,Json.required(candidate,"trackId"),assetId,contribution);if(firstContribution==null)firstContribution=contributionId;for(JsonElement annotation:Json.array(candidate,"annotations"))raw.add(annotation);for(JsonElement reason:Json.array(candidate,"reviewIssues"))reasons.add(reason);review|=Json.bool(candidate,"requiresReview",false);if(!Json.bool(candidate,"valid",false)){invalid=true;continue;}nextHeads.add(contribution);for(JsonElement annotation:Json.array(candidate,"annotations"))combined.add(annotation);}
        for(JsonElement reason:prepared.blocked.getOrDefault(frameId,new JsonArray()))reasons.add(reason);review|=!reasons.isEmpty();
        try{Annotations.validate(combined,asset,Json.object(timeline,"template"));}catch(ApiError e){reasons.add(issue(e.code,e.getMessage()));return frameResult(frame,"blocked",raw,reasons,true);}
        // 只有贡献所属对象被替换；同帧其他轨迹和无关对象一起组成新的候选版本。
        for(String trackId:replaced)Store.update(c,"DELETE FROM track_contribution_heads WHERE track_id=? AND asset_id=?",trackId,assetId);for(JsonElement value:nextHeads){JsonObject contribution=value.getAsJsonObject();Store.update(c,"INSERT INTO track_contribution_heads(track_id,asset_id,contribution_id) VALUES(?,?,?) ON CONFLICT(track_id,asset_id) DO UPDATE SET contribution_id=excluded.contribution_id",Json.required(contribution,"trackId"),assetId,Json.required(contribution,"id"));}
        boolean ownedBefore=false;for(JsonElement value:oldHeads)ownedBefore|=replaced.contains(Json.required(value.getAsJsonObject(),"trackId"));boolean changed=!combined.equals(Json.array(asset,"annotations"))||invalid||!raw.isEmpty();String status=invalid?"blocked":!raw.isEmpty()?"applied":ownedBefore?"removed":"unchanged";
        if(changed){int version=Projects.nextVersion(c,assetId);asset.add("annotations",combined);asset.addProperty("version",version);asset.addProperty("status","candidate");asset.addProperty("source","track");JsonObject metadata=Json.object(asset,"metadata");metadata.add("annotationTemplate",Json.object(timeline,"template").deepCopy());metadata.addProperty("requiresTrackReview",review||invalid||combined.isEmpty()&&ownedBefore);metadata.addProperty("trackGenerationId",generationId);JsonArray provenance=new JsonArray();for(JsonElement value:nextHeads){JsonObject contribution=value.getAsJsonObject();provenance.add(Json.obj("trackId",contribution.get("trackId"),"contributionId",contribution.get("id"),"generationId",contribution.get("generationId"),"requiresReview",contribution.get("requiresReview")));}metadata.add("trackContributions",provenance);metadata.add("trackReviewIssues",reasons.deepCopy());asset.add("metadata",metadata);Store.update(c,"INSERT INTO versions(asset_id,version,source,data,created_at) VALUES(?,?,?,?,?)",assetId,version,"track",asset,Json.now());Store.update(c,"UPDATE assets SET data=? WHERE id=?",asset,assetId);Store.event(c,"annotation.saved",null,assetId,null,Json.obj("projectId",timeline.get("projectId"),"version",version,"source","track","generationId",generationId));}
        JsonObject result=frameResult(frame,status,raw,reasons,review||invalid);if(firstContribution!=null)result.addProperty("contributionId",firstContribution);if(changed)result.add("candidateVersion",asset.get("version"));return result;
    }
    @Override public void close(){closed=true;cancelled=true;worker.shutdownNow();try{worker.awaitTermination(10,TimeUnit.SECONDS);}catch(InterruptedException e){Thread.currentThread().interrupt();}}
}
