package cn.autolabel.engine;

import com.google.gson.*;
import java.math.BigInteger;
import java.nio.file.*;
import java.sql.Connection;
import java.util.*;

/** 一个时间轴固定同一抽帧批次和模板语义，帧文件身份不会随素材当前标注版本变化。 */
final class TrackTimelines {
    final Engine engine;final Store store;
    TrackTimelines(Engine engine){this.engine=engine;store=engine.store;}
    static long version(JsonObject p,String key){return Costs.integer(p,key,key.equals("baseAnnotationVersion")?0:1,9_007_199_254_740_991L);}
    static String id(JsonObject p,String key){return FlowPlans.string(p,key,128);}
    static String name(JsonObject p,String key,String fallback){return p.has(key)?FlowPlans.string(p,key,200):fallback==null?null:fallback.substring(0,Math.min(fallback.length(),200));}
    static int pageInt(JsonObject p,String key,int fallback,int min,int max){return p.has(key)?(int)Costs.integer(p,key,min,max):fallback;}
    static void expect(long expected,long actual){if(expected!=actual)throw error(409,"track_version_conflict","轨迹或时间轴版本已变化，请重新载入后操作。");}
    static ApiError error(int status,String code,String message){return new ApiError(status,code,message);}
    static String hash(JsonElement value){try{return java.util.HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
    static JsonObject definition(JsonObject project){JsonObject snapshot=TaskTemplates.snapshot(project);TrackInterpolation.templateHash(snapshot);return snapshot;}

    JsonObject create(JsonObject p){FlowPlans.keys(p,"projectId","mediaJobId","name");String pid=id(p,"projectId"),jobId=id(p,"mediaJobId");String title=name(p,"name","视频轨迹时间轴");
        return store.tx(c->{JsonObject project=Store.document(c,"projects",pid),template=definition(project),job=Store.document(c,"media_jobs",jobId);String templateHash=TrackInterpolation.templateHash(template);if(!pid.equals(Json.required(job,"projectId"))||!Json.required(job,"kind").equals("video_extract")||!Json.bool(job,"assetsCommitted",false))throw error(422,"track_video_not_imported","时间轴需要当前项目已完整入库的抽帧任务。");
            JsonObject existing=Store.one(c,"SELECT data FROM track_timelines WHERE project_id=? AND media_job_id=? AND template_hash=?",pid,jobId,templateHash);if(existing!=null)return view(Json.parse(Json.required(existing,"data")));
            List<JsonObject> assets=Store.rows(c,"SELECT data,path FROM assets WHERE project_id=? AND json_extract(data,'$.metadata.mediaJobId')=?",pid,jobId);if(assets.isEmpty()||assets.size()>10000||assets.size()!=Json.integer(Json.object(job,"summary"),"frameCount",-1))throw error(409,"track_frames_changed","已入库视频帧数量与完成记录不符。");
            assets.sort(Comparator.comparing(row->new BigInteger(Json.required(Json.object(Json.parse(Json.required(row,"data")),"metadata"),"sourcePts"))));String timelineId=Json.id(),now=Json.now();JsonArray frames=new JsonArray();int width=-1,height=-1;BigInteger previous=null;Set<String> frameIds=new HashSet<>();
            for(JsonObject row:assets){JsonObject asset=Json.parse(Json.required(row,"data")),metadata=Json.object(asset,"metadata");String frameId=Json.required(metadata,"frameId"),source=Json.required(metadata,"sourceVideoId");BigInteger pts=new BigInteger(Json.required(metadata,"sourcePts"));if(!source.equals(Json.required(job,"sourceVideoId"))||!frameIds.add(frameId)||previous!=null&&pts.compareTo(previous)<=0)throw error(409,"track_frames_changed","抽帧批次存在重复时间、来源混合或帧身份冲突。");previous=pts;int w=Json.integer(asset,"width",0),h=Json.integer(asset,"height",0);if(width<0){width=w;height=h;}else if(w!=width||h!=height)throw error(422,"track_frame_geometry_mismatch","同一时间轴需要同尺寸的固定基准图。");
                JsonObject frame=Json.obj("frameId",frameId,"sourceFrameId",frameId,"assetId",asset.get("id"),"contentHash",asset.get("contentHash"),"width",w,"height",h,"inputVersion",Json.integer(metadata,"inputVersion",1),"normalizationVersion",Json.str(metadata,"normalizationVersion",Media.NORMALIZATION_VERSION),"sceneId",null,"inputImage",relative(Path.of(Json.required(row,"path"))));
                for(String field:List.of("sourceVideoId","videoSourceHash","sourcePresentationIndex","sourcePts","originPts","relativePts","timeBase","timeSeconds","rangeIndex"))frame.add(field,metadata.get(field));frames.add(frame);
            }
            JsonObject timeline=Json.obj("id",timelineId,"projectId",pid,"mediaJobId",jobId,"sourceVideoId",job.get("sourceVideoId"),"name",title,"version",1,"taskType",project.get("taskType"),"templateHash",templateHash,"template",template,"frameCount",frames.size(),"width",width,"height",height,"createdAt",now,"updatedAt",now);
            Store.update(c,"INSERT INTO track_timelines(id,project_id,media_job_id,template_hash,version,data) VALUES(?,?,?,?,?,?)",timelineId,pid,jobId,templateHash,1,timeline);int position=0;for(JsonElement element:frames){JsonObject frame=element.getAsJsonObject();Store.update(c,"INSERT INTO timeline_frames(id,timeline_id,frame_id,asset_id,position,data) VALUES(?,?,?,?,?,?)",Json.id(),timelineId,Json.required(frame,"frameId"),Json.required(frame,"assetId"),position++,frame);}event(c,"timeline.created",timeline,null,null,new JsonObject());save(c,timeline);return view(timeline);
        });
    }
    static JsonObject view(JsonObject timeline){JsonObject result=timeline.deepCopy();result.remove("template");return result;}
    JsonObject get(JsonObject p){FlowPlans.keys(p,"timelineId");return store.read(c->Store.document(c,"track_timelines",id(p,"timelineId")));}
    JsonObject list(JsonObject p){FlowPlans.keys(p,"projectId","limit","offset");String pid=id(p,"projectId");int limit=pageInt(p,"limit",100,1,100),offset=pageInt(p,"offset",0,0,Integer.MAX_VALUE);return store.read(c->{Store.document(c,"projects",pid);JsonArray items=new JsonArray();for(JsonElement value:Store.docs(c,"SELECT data FROM track_timelines WHERE project_id=? ORDER BY rowid DESC LIMIT ? OFFSET ?",pid,limit,offset))items.add(view(value.getAsJsonObject()));return Json.obj("items",items,"total",Store.one(c,"SELECT COUNT(*) AS n FROM track_timelines WHERE project_id=?",pid).get("n"));});}
    static List<JsonObject> frames(Connection c,String timelineId)throws Exception{List<JsonObject> frames=new ArrayList<>();for(JsonElement element:Store.docs(c,"SELECT data FROM timeline_frames WHERE timeline_id=? ORDER BY position",timelineId))frames.add(element.getAsJsonObject());return frames;}
    static JsonObject frame(Connection c,String timelineId,String frameId)throws Exception{JsonObject row=Store.one(c,"SELECT data FROM timeline_frames WHERE timeline_id=? AND frame_id=?",timelineId,frameId);if(row==null)throw error(404,"track_frame_missing","该帧不在固定时间轴中。");return Json.parse(Json.required(row,"data"));}
    static void currentTemplate(Connection c,JsonObject timeline)throws Exception{JsonObject project=Store.document(c,"projects",Json.required(timeline,"projectId"));if(!TrackInterpolation.templateHash(definition(project)).equals(Json.required(timeline,"templateHash")))throw error(409,"track_template_changed","项目模板语义已变化，请使用该模板新建时间轴或恢复原模板后继续。");}
    static JsonObject current(Connection c,JsonObject frame)throws Exception{
        JsonObject asset=Store.document(c,"assets",Json.required(frame,"assetId")),metadata=Json.object(asset,"metadata");if(!Objects.equals(asset.get("contentHash"),frame.get("contentHash"))||!Objects.equals(asset.get("width"),frame.get("width"))||!Objects.equals(asset.get("height"),frame.get("height"))||Json.integer(metadata,"inputVersion",1)!=Json.integer(frame,"inputVersion",1)||!Objects.equals(metadata.get("sourceVideoId"),frame.get("sourceVideoId"))||!Objects.equals(metadata.get("sourcePts"),frame.get("sourcePts"))||!Objects.equals(metadata.get("timeBase"),frame.get("timeBase")))throw error(409,"track_baseline_changed","时间轴基准图或精确来源时间已变化，不能继续生成。");return asset;
    }
    static JsonObject state(Connection c,JsonObject frame)throws Exception{
        JsonObject asset=current(c,frame),draft=Store.one(c,"SELECT saved_at,data FROM drafts WHERE asset_id=?",Json.required(frame,"assetId"));String status=Json.str(asset,"status","unlabeled"),state=status.equals("confirmed")?"confirmed":status.equals("modified")||draft!=null?"manual":status.equals("candidate")?"candidate":"empty";
        return Json.obj("annotationVersion",Json.integer(asset,"version",0),"annotationState",state,"draftSavedAt",draft==null?null:Json.required(draft,"saved_at"),"draftHash",draft==null?null:hash(JsonParser.parseString(Json.required(draft,"data"))),"protected",Set.of("manual","confirmed").contains(state));
    }
    JsonObject page(JsonObject p){FlowPlans.keys(p,"timelineId","trackId","limit","offset","aroundFrameId");String timelineId=id(p,"timelineId"),trackId=p.has("trackId")?id(p,"trackId"):null;int limit=pageInt(p,"limit",100,1,500),offset=pageInt(p,"offset",0,0,Integer.MAX_VALUE);return store.read(c->{int pageOffset=offset;if(p.has("aroundFrameId")){if(p.has("offset"))throw error(400,"track_page_invalid","aroundFrameId 与 offset 不能同时提供。");JsonObject position=Store.one(c,"SELECT position FROM timeline_frames WHERE timeline_id=? AND frame_id=?",timelineId,id(p,"aroundFrameId"));if(position==null)throw error(404,"track_frame_missing","定位帧不在时间轴中。");pageOffset=Math.max(0,Json.integer(position,"position",0)-limit/2);}JsonObject timeline=Store.document(c,"track_timelines",timelineId),track=trackId==null?null:Store.document(c,"tracks",trackId);if(track!=null&&!Json.required(track,"timelineId").equals(timelineId))throw error(422,"track_timeline_mismatch","轨迹不属于该时间轴。");Map<String,JsonObject> keys=new HashMap<>();if(track!=null)for(JsonElement value:Json.array(track,"keyframes"))keys.put(Json.required(value.getAsJsonObject(),"frameId"),value.getAsJsonObject());JsonArray items=new JsonArray();for(JsonElement value:Store.docs(c,"SELECT data FROM timeline_frames WHERE timeline_id=? ORDER BY position LIMIT ? OFFSET ?",timelineId,limit,pageOffset)){JsonObject frame=value.getAsJsonObject(),output=frame.deepCopy();output.remove("inputImage");for(var entry:state(c,frame).entrySet())if(!entry.getKey().equals("draftHash"))output.add(entry.getKey(),entry.getValue());if(track!=null)output.add("keyframe",keys.containsKey(Json.required(frame,"frameId"))?keyView(keys.get(Json.required(frame,"frameId")),frame):JsonNull.INSTANCE);
                JsonArray contributions=new JsonArray();for(JsonObject row:Store.rows(c,"SELECT h.track_id,c.data FROM track_contribution_heads h JOIN track_contributions c ON c.id=h.contribution_id WHERE h.asset_id=?",Json.required(frame,"assetId"))){JsonObject contribution=Json.parse(Json.required(row,"data"));contributions.add(Json.obj("contributionId",contribution.get("id"),"trackId",row.get("track_id"),"generationId",contribution.get("generationId"),"requiresReview",Json.bool(contribution,"requiresReview",false)));}output.add("contributions",contributions);items.add(output);}return Json.obj("items",items,"total",timeline.get("frameCount"),"offset",pageOffset,"limit",limit);});}
    static JsonObject keyView(JsonObject key,JsonObject frame){JsonObject result=new JsonObject();for(String field:List.of("keyframeId","frameId","objectId","state","annotation"))result.add(field,key.get(field));for(String field:List.of("assetId","sourcePts","timeSeconds"))result.add(field,frame.get(field));return result;}
    static JsonObject helperTimeline(Connection c,JsonObject timeline)throws Exception{JsonArray result=new JsonArray();for(JsonObject frame:frames(c,Json.required(timeline,"id"))){JsonObject state=state(c,frame);result.add(Json.obj("frameId",frame.get("frameId"),"sourceVideoId",frame.get("sourceVideoId"),"pts",frame.get("sourcePts"),"timeBase",frame.get("timeBase"),"sceneId",frame.get("sceneId"),"baseline",Json.obj("id",frame.get("assetId"),"contentHash",frame.get("contentHash"),"width",frame.get("width"),"height",frame.get("height"),"version",frame.get("inputVersion")),"annotationVersion",state.get("annotationVersion"),"annotationState",state.get("annotationState")));}return Json.obj("sourceVideoId",timeline.get("sourceVideoId"),"frames",result);}
    JsonObject update(JsonObject p){FlowPlans.keys(p,"timelineId","baseVersion","name","scenes");String timelineId=id(p,"timelineId");long expected=version(p,"baseVersion");if(!p.has("name")&&!p.has("scenes"))throw error(400,"track_update_empty","请提供名称或明确场景范围。");if(p.has("name"))name(p,"name",null);if(p.has("scenes")&&(!p.get("scenes").isJsonArray()||Json.array(p,"scenes").size()>10000))throw error(400,"track_scene_invalid","场景范围须为至多 10000 项的数组。");
        return store.tx(c->{JsonObject timeline=Store.document(c,"track_timelines",timelineId);expect(expected,Json.number(timeline,"version",0));currentTemplate(c,timeline);List<JsonObject> frames=frames(c,timelineId);Map<String,Integer> positions=new HashMap<>();for(int i=0;i<frames.size();i++){positions.put(Json.required(frames.get(i),"frameId"),i);current(c,frames.get(i));}Set<Integer> changed=new TreeSet<>(),covered=new HashSet<>();
            for(JsonElement value:Json.array(p,"scenes")){if(!value.isJsonObject())throw error(400,"track_scene_invalid","场景范围必须是对象。");JsonObject range=value.getAsJsonObject();FlowPlans.keys(range,"startFrameId","endFrameId","sceneId");Integer start=positions.get(id(range,"startFrameId")),end=positions.get(id(range,"endFrameId"));if(start==null||end==null||start>end||!range.has("sceneId"))throw error(400,"track_scene_invalid","场景范围端点不存在或顺序错误。");JsonElement scene=range.get("sceneId");if(!scene.isJsonNull())FlowPlans.string(range,"sceneId",128);for(int i=start;i<=end;i++){if(!covered.add(i))throw error(400,"track_scene_invalid","本次场景范围不能相互重叠。");if(!Objects.equals(frames.get(i).get("sceneId"),scene)){frames.get(i).add("sceneId",scene);changed.add(i);}}}
            JsonArray affectedTracks=new JsonArray();for(JsonElement value:Store.docs(c,"SELECT data FROM tracks WHERE timeline_id=? AND status='active'",timelineId)){JsonObject track=value.getAsJsonObject();String trackId=Json.required(track,"id");List<Integer> keys=new ArrayList<>();for(JsonElement key:Json.array(track,"keyframes"))keys.add(positions.get(Json.required(key.getAsJsonObject(),"frameId")));Collections.sort(keys);boolean dirty=false;for(int i=1;i<keys.size();i++){int start=keys.get(i-1),end=keys.get(i);if(changed.stream().anyMatch(index->index>=start&&index<=end)){for(int index=start;index<=end;index++)Store.update(c,"INSERT OR IGNORE INTO track_dirty_frames(track_id,frame_id) VALUES(?,?)",trackId,Json.required(frames.get(index),"frameId"));dirty=true;}}if(dirty)affectedTracks.add(trackId);}
            for(int index:changed){JsonObject frame=frames.get(index);Store.update(c,"UPDATE timeline_frames SET data=? WHERE timeline_id=? AND frame_id=?",frame,timelineId,Json.required(frame,"frameId"));}if(p.has("name"))timeline.addProperty("name",name(p,"name",null));timeline.addProperty("version",expected+1);event(c,"timeline.updated",timeline,null,null,Json.obj("changedFrames",changed.size(),"affectedTrackIds",affectedTracks));save(c,timeline);return Json.obj("timeline",view(timeline),"affectedTrackIds",affectedTracks);
        });
    }
    static void save(Connection c,JsonObject timeline)throws Exception{timeline.addProperty("updatedAt",Json.now());timeline.addProperty("sequence",Store.cursor(c));Store.update(c,"UPDATE track_timelines SET version=?,data=? WHERE id=?",Json.number(timeline,"version",1),timeline,Json.required(timeline,"id"));}
    static void event(Connection c,String type,JsonObject timeline,String trackId,String generationId,JsonObject payload)throws Exception{JsonObject value=payload.deepCopy();value.add("timelineId",timeline.get("id"));value.add("projectId",timeline.get("projectId"));if(trackId!=null)value.addProperty("trackId",trackId);if(generationId!=null)value.addProperty("generationId",generationId);Store.event(c,"track."+type,null,null,null,value);}
    Path path(JsonObject frame){String relative=Json.required(frame,"inputImage");Path path=store.root.resolve(relative).normalize();try{if(Path.of(relative).isAbsolute()||!path.startsWith(store.root)||!Files.isRegularFile(path)||!path.toRealPath().startsWith(store.root.toRealPath()))throw new Exception();return path;}catch(Exception e){throw error(409,"track_baseline_missing","时间轴基准图片缺失或越过受管目录。");}}
    void verifyFile(JsonObject frame){try{if(!Media.hash(path(frame)).equals(Json.required(frame,"contentHash")))throw error(409,"track_baseline_changed","时间轴基准图片内容已变化。");}catch(ApiError e){throw e;}catch(Exception e){throw error(409,"track_baseline_missing","时间轴基准图片不可读取。");}}
    private String relative(Path path){Path normalized=path.toAbsolutePath().normalize();if(!normalized.startsWith(store.root))throw error(409,"track_baseline_unmanaged","时间轴只能使用受管基准图片。");return store.root.relativize(normalized).toString().replace('\\','/');}
}
