import { useState } from 'react';
import type { ScreeningParameters as Parameters } from '../../shared/media';
import { useApp } from './context';
import { isDemo } from './bridge';
import { Button, Field, Notice } from './ui';
import { statusNames } from './types';
import ScreeningParameters from './ScreeningParameters';
import ScreeningPreview from './ScreeningPreview';

export default function FilterParameters({ value: p, onChange, disabled }: { value: Record<string, unknown>; onChange: (key: string, value: unknown) => void; disabled: boolean }) {
  const { project, selectedAssetIds } = useApp(), [preview, setPreview] = useState(false);
  const screening = p.screening && typeof p.screening === 'object' ? p.screening as Parameters : {}, excludeIds = Array.isArray(p.excludeAssetIds) ? p.excludeAssetIds.map(String) : [];
  return <><Notice>筛选只改变流程输入与固定产物，不删除项目素材，不覆盖人工标注。</Notice><div className="field-grid">{(['minWidth', 'maxWidth', 'minHeight', 'maxHeight'] as const).map((key, i) => <Field key={key} label={['最小宽度', '最大宽度', '最小高度', '最大高度'][i]}><input disabled={disabled} aria-label={key} type="number" min={1} max={100000} value={p[key] === undefined ? '' : String(p[key])} placeholder="不限" onChange={e => onChange(key, e.target.value ? Number(e.target.value) : undefined)}/></Field>)}</div><Field label="保留状态" hint="未勾选任何状态表示不限制状态。"><div className="flow-status-picks">{['unlabeled', 'candidate', 'modified', 'confirmed', 'invalid', 'missing'].map(status => <label key={status}><input disabled={disabled} type="checkbox" checked={Array.isArray(p.statuses) && p.statuses.includes(status)} onChange={e => { const values = Array.isArray(p.statuses) ? p.statuses : []; const next = e.target.checked ? [...values, status] : values.filter(v => v !== status); onChange('statuses', next.length ? next : undefined); }}/>{statusNames[status]}</label>)}</div></Field><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={Boolean(p.deduplicate)} onChange={e => onChange('deduplicate', e.target.checked)}/>执行时按图片内容去重</label><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={Array.isArray(p.assetIds)} onChange={e => onChange('assetIds', e.target.checked ? [...selectedAssetIds] : undefined)}/>仅保留工作台已勾选素材</label>{Array.isArray(p.assetIds) && <p className="muted tiny">已固定 {p.assetIds.length} 张。重新勾选可更新列表；空集合会阻止执行。</p>}<ScreeningParameters value={screening} disabled={disabled} onChange={value => onChange('screening', value)}/><Button disabled={disabled || isDemo || !project} onClick={() => setPreview(true)}>预览已有素材筛选</Button><p className="muted tiny">显式排除 {excludeIds.length} 张；更改分析参数后需重新预览，旧建议不会自动更新。</p>{excludeIds.length > 0 && <Button disabled={disabled} onClick={() => onChange('excludeAssetIds', undefined)}>清除本节点明确排除项</Button>}{preview && project && <ScreeningPreview projectId={project.id} parameters={screening} fixedAssetIds={Array.isArray(p.assetIds) ? p.assetIds.map(String) : undefined} selectedAssetIds={[...selectedAssetIds]} excludeIds={excludeIds} onClose={() => setPreview(false)} onApply={ids => { onChange('excludeAssetIds', ids.length ? ids : undefined); setPreview(false); }}/>}</>;
}
