import { FolderOpen } from 'lucide-react';
import type { FlowStep } from '../../shared/flow';
import { resolveConfiguration } from '../../shared/configuration';
import type { ReferenceSelection } from '../../shared/resources';
import { useApp } from './context';
import { getBridge, errorMessage } from './bridge';
import { Button, Field, Notice } from './ui';
import ConfigurationView from './ConfigurationView';
import ReferencePicker from './ReferencePicker';
import ReusePolicyFields from './ReusePolicyFields';
import TransformParametersEditor from './TransformParametersEditor';
import LocalStepParameters from './LocalStepParameters';
import FilterParameters from './FilterParameters';

export default function FlowParameters({ step, onChange, onParametersChange, disabled, canExecute }: { step: FlowStep; onParametersChange: (parameters: Record<string, unknown>) => void; onChange: (key: string, value: unknown) => void; disabled: boolean; canExecute: boolean }) {
  const { project, prefs, providers, notify } = useApp();
  const p = step.parameters;
  const resolved = resolveConfiguration('annotation', prefs, project?.settings, p);
  async function choose(kind: 'images' | 'directory') {
    try { const paths = await (await getBridge()).chooseFiles({ kind, multiple: kind === 'images' }); if (!paths.length) return; if (paths.length > 10000) throw new Error('单个导入步骤最多选择 10000 个文件或目录。'); onChange(kind === 'images' ? 'paths' : 'outputDir', kind === 'images' ? paths : paths[0]); }
    catch (e) { notify(errorMessage(e), true); }
  }
  if (step.kind === 'local') return <LocalStepParameters project={project} value={p} onChange={onParametersChange} disabled={disabled} canExecute={canExecute}/>;
  if (step.kind === 'transform') return <>{!canExecute && <Notice>当前引擎尚未开放图像处理，可编辑并保存停用计划；能力开放后才能启用。</Notice>}<TransformParametersEditor value={p} onChange={onChange} disabled={disabled}/></>;
  if (step.kind === 'import') return <><Notice>导入只放在第一个启用步骤。文件在流程执行时导入；从模板载入的路径需要重新选择授权。</Notice><Button disabled={disabled} onClick={() => void choose('images')}><FolderOpen size={14}/>选择流程导入图片</Button><p className="muted tiny">已选 {Array.isArray(p.paths) ? p.paths.length : 0} 个路径</p>{Array.isArray(p.paths) && <details><summary>查看所选路径</summary><div className="flow-paths">{p.paths.slice(0, 20).map((v, i) => <p className="break-word" key={i}>{String(v)}</p>)}{p.paths.length > 20 && <p>其余 {p.paths.length - 20} 个路径也包含在步骤中。</p>}</div></details>}<Field label="导入方式"><select disabled={disabled} value={String(p.mode ?? 'copy')} onChange={e => onChange('mode', e.target.value)}><option value="copy">复制原素材到工作空间</option><option value="reference">引用原素材位置</option></select></Field></>;
  if (step.kind === 'filter') return <FilterParameters value={p} onChange={onChange} disabled={disabled}/>;
  if (step.kind === 'api') return <><ConfigurationView value={resolved} providers={providers}/><ReusePolicyFields value={p} onChange={onChange} disabled={disabled}/><Field label="接口配置"><select disabled={disabled} aria-label="步骤接口" value={String(p.providerId ?? '')} onChange={e => onChange('providerId', e.target.value || undefined)}><option value="">继承项目 / 全局</option>{providers.map(provider => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></Field><Field label="标注模型"><input disabled={disabled} aria-label="步骤模型" value={String(p.model ?? '')} placeholder={resolved.model ? `继承 ${resolved.model}` : '输入当前接口模型'} onChange={e => onChange('model', e.target.value || undefined)}/></Field><Field label="标注规则"><textarea disabled={disabled} aria-label="步骤标注规则" rows={5} maxLength={100000} value={String(p.prompt ?? '')} placeholder={resolved.prompt ? `继承：${resolved.prompt}` : '描述类别、边界及遮挡处理规则'} onChange={e => onChange('prompt', e.target.value)}/></Field><Field label="并发数"><input disabled={disabled} type="number" aria-label="步骤并发" min={1} max={32} value={p.concurrency === undefined ? '' : String(p.concurrency)} placeholder={`继承 ${resolved.concurrency ?? '接口默认'}`} onChange={e => onChange('concurrency', e.target.value ? Number(e.target.value) : undefined)}/></Field><Field label="失败重试次数"><input disabled={disabled} type="number" min={0} max={6} value={p.maxRetries === undefined ? '' : String(p.maxRetries)} placeholder="接口默认" onChange={e => onChange('maxRetries', e.target.value ? Number(e.target.value) : undefined)}/></Field><Field label="节点请求上限" hint="可选的节点限制；整个流程的共享上限仍生效，包含重试。"><input disabled={disabled} type="number" aria-label="步骤请求上限" min={1} max={1000000} value={String(resolved.maxRequests ?? '')} placeholder="未设置" onChange={e => onChange('maxRequests', e.target.value ? Number(e.target.value) : null)}/></Field><Button disabled={disabled} onClick={() => onChange('maxRequests', undefined)}>请求上限恢复继承</Button>{project && <ReferencePicker project={project} value={Array.isArray(p.referenceResources) ? p.referenceResources as ReferenceSelection[] : []} onChange={v => onChange('referenceResources', v)} disabled={disabled}/>}</>;
  if (step.kind === 'review') {
    const sample = p.randomSample as { count: number; seed: string } | undefined;
    return <><Notice>等待人工检查只暂停流程。点击放行不会确认或覆盖项目标注。</Notice><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={p.buildIssues !== false} onChange={e => onChange('buildIssues', e.target.checked)}/>建立问题清单</label><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={p.waitForHuman !== false} onChange={e => onChange('waitForHuman', e.target.checked)}/>等待人工检查后再继续</label><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={Boolean(sample)} onChange={e => onChange('randomSample', e.target.checked ? { count: 1, seed: 'manual-review' } : undefined)}/>建立随机抽查样本</label>{sample && <><Field label="抽查数量"><input disabled={disabled} type="number" min={1} max={1000} value={sample.count} onChange={e => onChange('randomSample', { ...sample, count: Number(e.target.value) })}/></Field><Field label="抽样种子"><input disabled={disabled} maxLength={256} value={sample.seed} onChange={e => onChange('randomSample', { ...sample, seed: e.target.value })}/></Field></> }</>;
  }
  if (step.kind === 'export') return <><Field label="流程导出目录" hint="路径必须通过本次桌面对话框选择；从模板读取的路径不自动获得权限。"><input disabled={disabled} readOnly aria-label="流程导出目录" value={String(p.outputDir ?? '')} placeholder="请选择目录"/></Field><Button disabled={disabled} onClick={() => void choose('directory')}><FolderOpen size={14}/>选择流程导出目录</Button><Field label="训练集比例"><input disabled={disabled} type="number" min={0.01} max={0.99} step={0.05} value={Number(p.trainRatio ?? .8)} onChange={e => onChange('trainRatio', Number(e.target.value))}/></Field><Field label="标注版本选择" hint="从固定产物读取所选版本；手工修改不会自动进入已固定的流程输入。"><select disabled={disabled} value={String(p.annotationSelection ?? 'protected')} onChange={e => onChange('annotationSelection', e.target.value)}><option value="protected">保留人工保护的已选版本</option><option value="candidate">明确选择本流程候选版本</option></select></Field><label className="checkbox-row"><input disabled={disabled} type="checkbox" checked={Boolean(p.onlyConfirmed)} onChange={e => onChange('onlyConfirmed', e.target.checked)}/>仅导出人工确认的图片</label></>;
  return <Notice>当前引擎尚未开放此模块，保留为禁用步骤。</Notice>;
}
