import { useEffect, useState } from 'react';
import type { FlowArtifact, FlowRun } from '../../shared/flow';
import { STEP_LABELS } from '../../shared/flow';
import { request, errorMessage } from './bridge';
import { Button, Field, Loading } from './ui';
import ReuseProvenance from './ReuseProvenance';
import InputReuseSource from './InputReuseSource';
import ModelInputResult from './ModelInputResult';
import { ScreeningReasons, screeningRecommendations } from './ScreeningResults';

export const artifactNames = { assets: '素材集合', annotations: '标注集合', review: '复核清单', export: '导出副本', views: '模型输入视图', view_annotations: '视图标注集合' };
export function ArtifactPicker({ projectId, value, onChange, disabled }: { projectId: string; value: string; onChange: (id: string) => void; disabled: boolean }) {
  const [runs, setRuns] = useState<FlowRun[]>([]), [run, setRun] = useState<FlowRun | null>(null);
  const [offset, setOffset] = useState(0), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const [total, setTotal] = useState(0);
  useEffect(() => { let live = true; setLoading(true); void request<{ items: FlowRun[]; total: number }>('flow.list', { projectId, offset, limit: 50 }).then(result => { if (live) { setRuns(result.items); setTotal(result.total); } }).catch(e => { if (live) setError(errorMessage(e)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [projectId, offset]);
  const artifacts = run ? [{ id: run.inputArtifactId, label: '流程固定输入' }, ...run.steps.filter(s => s.outputArtifactId && ['completed', 'completed_with_errors', 'paused', 'needs_attention'].includes(s.status)).map(s => ({ id: s.outputArtifactId!, label: `${s.order + 1}. ${STEP_LABELS[s.kind]}产物` }))] : [];
  return <div className="flow-artifact-picker"><Field label="来源自动流程"><select disabled={disabled || loading} value={run?.id ?? ''} onChange={e => { onChange(''); setRun(null); setError(''); if (e.target.value) { setLoading(true); void request<FlowRun>('flow.get', { flowRunId: e.target.value }).then(setRun).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)); } }}><option value="">选择当前项目运行</option>{runs.map(r => <option key={r.id} value={r.id}>{r.name} · 修订 {r.revision} · {r.id.slice(0, 8)}</option>)}</select></Field><div className="pagination"><Button disabled={disabled || loading || offset === 0} onClick={() => setOffset(v => Math.max(0, v - 50))}>前一页运行</Button><span>第 {offset / 50 + 1} 页</span><Button disabled={disabled || loading || offset + runs.length >= total} onClick={() => setOffset(v => v + 50)}>后一页运行</Button></div><Field label="固定输入产物"><select aria-label="固定输入产物" disabled={disabled || loading || !run} value={value} onChange={e => onChange(e.target.value)}><option value="">明确选择一个已完成产物</option>{artifacts.map(a => <option key={a.id} value={a.id}>{a.label} · {a.id.slice(0, 8)}</option>)}</select></Field>{value && <ArtifactView key={value} artifactId={value} compact/>}{error && <p className="inline-error" role="alert">{error}</p>}</div>;
}
export function ArtifactView({ artifactId, compact = false }: { artifactId: string; compact?: boolean }) {
  const [artifact, setArtifact] = useState<FlowArtifact | null>(null), [offset, setOffset] = useState(0), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const limit = compact ? 5 : 100;
  useEffect(() => { let live = true; setLoading(true); setError(''); void request<FlowArtifact>('flow.artifact', { artifactId, offset, limit }).then(value => { if (live) setArtifact(value); }).catch(e => { if (live) setError(errorMessage(e)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [artifactId, offset, limit]);
  return <div className="flow-artifact-view">{loading ? <Loading compact label="正在读取固定产物…" /> : artifact && <><h3>{artifactNames[artifact.kind]} · {artifact.total} 项</h3><p className="muted tiny">固定标注版本不会随项目编辑变化 · 成功 {artifact.statistics.succeeded}（含复用 {artifact.statistics.reused}）</p><details className="artifact-diagnostics"><summary>产物诊断信息</summary><p>产物 ID：{artifact.id}</p><p>来源流程 ID：{artifact.flowRunId}</p><p>生成时间：{new Date(artifact.createdAt).toLocaleString('zh-CN')}</p></details><div className="flow-artifact-table">{artifact.items.map(item => <div key={item.id}><strong>{item.name}</strong><span>{({ included: '纳入', excluded: '已排除', failed: '失败', unknown: '结果未知' })[item.outcome]}{item.reused && ' · 复用成功'}</span><small>选定版本 {item.selectedVersion ?? '无'}{item.candidateVersion != null && ` · 候选版本 ${item.candidateVersion}`}</small>{item.reason && <p>{item.reason === 'manual_exclusion' ? '按明确选择排除' : item.reason}</p>}{item.screeningRecommendation && <p>{screeningRecommendations[item.screeningRecommendation]}</p>}{item.screeningReasons && <ScreeningReasons reasons={item.screeningReasons}/>}{item.requiresGeometryReview && <p className="text-error">需要几何复核</p>}{(item.inputId||item.resultId)&&<div className="artifact-input-action"><ModelInputResult inputId={item.inputId} resultId={item.resultId} snapshot={item.inputSnapshot} name={item.name}/></div>}{item.inputReusedFrom ? <InputReuseSource source={item.inputReusedFrom}/> : item.reused && <ReuseProvenance source={item.reusedFrom}/>}</div>)}</div>{compact && artifact.total > limit && <small>预览前 {limit} 项；完整结果可在运行详情查看。</small>}{!compact && <div className="pagination"><Button disabled={loading || offset === 0} onClick={() => setOffset(v => Math.max(0, v - limit))}>上一页产物</Button><span>{artifact.total ? offset + 1 : 0}–{offset + artifact.items.length} / {artifact.total}</span><Button disabled={loading || offset + artifact.items.length >= artifact.total} onClick={() => setOffset(v => v + limit)}>下一页产物</Button></div>}</>}{error && <p className="inline-error" role="alert">{error}</p>}</div>;
}
