import { useEffect, useRef, useState } from 'react';
import type { LoadedLocalModel, LocalModel, LocalRuntimeState } from '../../shared/inference';
import type { Project } from './types';
import { request, errorMessage, isDemo } from './bridge';
import { Button, Field, Notice } from './ui';
import { LocalBackend } from './LocalModels';
import { LocalError } from './LocalRuntimeSettings';
import ReusePolicyFields from './ReusePolicyFields';

export default function LocalStepParameters({ project, value, onChange, disabled, canExecute }: { project: Project | null; value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void; disabled: boolean; canExecute: boolean }) {
  const [models, setModels] = useState<LocalModel[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [runtime, setRuntime] = useState<LocalRuntimeState | null>(null);
  const [registered, setRegistered] = useState<LocalModel | null>(null);
  const [loaded, setLoaded] = useState<LoadedLocalModel | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const generation = useRef(0);
  useEffect(() => { const stamp = ++generation.current; if (!project || isDemo) return; setBusy(true); setError(''); void Promise.allSettled([request<{ items: LocalModel[]; total: number }>('local.model.list', { taskType: project.taskType, offset, limit: 50 }), request<LocalRuntimeState>('local.runtime.get')]).then(values => { if (stamp !== generation.current) return; if (values[0].status === 'fulfilled') { setModels(values[0].value.items); setTotal(values[0].value.total); } else setError(errorMessage(values[0].reason)); if (values[1].status === 'fulfilled') setRuntime(values[1].value); else { setRuntime(null); setError(errorMessage(values[1].reason)); } setBusy(false); }); return () => { generation.current++; }; }, [project?.id, offset]);
  const locked = disabled || busy, modelId = String(value.modelId ?? ''), device = String(value.device ?? '');
  useEffect(() => { let live = true; setRegistered(null); if (modelId && !isDemo) void request<LocalModel>('local.model.get', { modelId, ...(value.modelVersion !== undefined ? { modelVersion: value.modelVersion } : {}) }).then(model => { if (live) setRegistered(model); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [modelId, value.modelVersion]);
  const classMap = value.classMap && typeof value.classMap === 'object' && !Array.isArray(value.classMap) ? value.classMap as Record<string, string | null> : {};
  const missing = loaded?.classes.filter(c => !Object.hasOwn(classMap, c.id) || (classMap[c.id] !== null && !project?.classes.some(p => p.id === classMap[c.id]))).length;
  function set(key: string, next: unknown) { const parameters = { ...value }; if (next === undefined) delete parameters[key]; else parameters[key] = next; onChange(parameters); }
  async function load() { if (!modelId || !runtime?.available) return; const stamp = ++generation.current; setBusy(true); setError(''); setLoaded(null); try { const next = await request<LoadedLocalModel>('local.model.load', { modelId, ...(value.modelVersion !== undefined ? { modelVersion: value.modelVersion } : {}), ...(device ? { device } : {}) }); if (stamp === generation.current) { setLoaded(next); onChange({ ...value, modelVersion: next.model.version, classMap }); } } catch (e) { if (stamp === generation.current) setError(errorMessage(e)); } finally { if (stamp === generation.current) setBusy(false); } }
  return <div className="local-step-parameters">{!canExecute && <Notice>当前引擎尚未开放本地预标注，可保存停用计划。环境和模型状态确认后才能启用执行。</Notice>}{!project ? <Notice>请先打开项目，再选择匹配任务类型的本地模型。</Notice> : <>
    <Field label="本地模型"><select aria-label="步骤本地模型" disabled={locked} value={modelId} onChange={e => { const model = models.find(m => m.id === e.target.value); setLoaded(null); const next = { ...value, modelId: e.target.value, classMap: {} }; delete (next as Record<string, unknown>).modelVersion; if (model) (next as Record<string, unknown>).modelVersion = model.version; onChange(next); }}><option value="">选择已登记模型</option>{modelId && !models.some(m => m.id === modelId) && <option value={modelId}>{registered ? `${registered.name} · 版本 ${registered.version}` : '已保存的模型（本页未列出）'}</option>}{models.map(m => <option key={m.id} value={m.id}>{m.name} · 版本 {m.version}</option>)}</select></Field>
    <div className="pagination"><Button disabled={locked || offset === 0} onClick={() => setOffset(n => Math.max(0, n - 50))}>前一页模型</Button><span>{offset / 50 + 1}</span><Button disabled={locked || offset + models.length >= total} onClick={() => setOffset(n => n + 50)}>后一页模型</Button></div>{value.modelVersion !== undefined && <p className="muted tiny">计划固定模型版本：{String(value.modelVersion)}{registered && ` · ${registered.name}`}</p>}
    <Field label="执行设备"><select aria-label="步骤本地设备" disabled={locked} value={device} onChange={e => { setLoaded(null); set('device', e.target.value || undefined); }}><option value="">由引擎选择</option>{device && !runtime?.devices.some(d => d.id === device) && <option value={device}>已保存设备：{device}（未确认）</option>}{runtime?.devices.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field><Button disabled={locked || !modelId || !runtime?.available} onClick={() => void load()}>加载模型并配置类别</Button>{!runtime?.available && <p className="muted tiny">请在“设置 → 本地推理”完成环境检测，并在模型中心登记模型。</p>}
    <ReusePolicyFields value={value} mode="local" disabled={locked} onChange={(key, next) => set(key, next)}/>
    {loaded ? <><LocalBackend loaded={loaded}/><h3>完整类别映射</h3><p className="muted tiny">每个模型类别都必须明确选择项目类别或忽略。尚有 {missing} 类待处理。</p><div className="local-class-mapping">{loaded.classes.map(c => <Field key={c.id} label={`${c.name}（原编号 ${c.id}）`}><select aria-label={`本地类别 ${c.id} 映射`} disabled={locked} value={Object.hasOwn(classMap, c.id) ? JSON.stringify(classMap[c.id]) : ''} onChange={e => { const next = { ...classMap }; if (!e.target.value) delete next[c.id]; else next[c.id] = JSON.parse(e.target.value); set('classMap', next); }}><option value="">请选择映射</option><option value="null">忽略这个模型类别</option>{classMap[c.id] != null && !project.classes.some(p => p.id === classMap[c.id]) && <option value={JSON.stringify(classMap[c.id])}>已保存类别已失效，请重选</option>}{project.classes.map(p => <option key={p.id} value={JSON.stringify(p.id)}>{p.name}</option>)}</select></Field>)}</div></> : <p className="muted tiny">加载模型后，按其实际返回的全部原始类别配置映射。已保存 {Object.keys(classMap).length} 个映射，尚未核对完整性。</p>}
    <details className="local-inference-options"><summary>推理参数</summary><div className="field-grid">{([['confidence', '置信度阈值', 0, 1, .05], ['iou', '重叠抑制阈值', 0, 1, .05], ['imageSize', '模型输入尺寸', 1, undefined, 1], ['maxDetections', '最大目标数', 1, undefined, 1], ['timeoutMs', '超时（毫秒）', 1, undefined, 1]] as const).map(([key, label, min, max, step]) => <Field label={label} key={key}><input aria-label={`本地${key}`} disabled={locked} type="number" min={min} max={max} step={step} value={value[key] === undefined ? '' : String(value[key])} placeholder="引擎默认" onChange={e => set(key, e.target.value === '' ? undefined : Number(e.target.value))}/></Field>)}</div></details>
  </>}<LocalError error={error}/></div>;
}
