import { useEffect, useState } from 'react';
import type { MediaJob, MediaJobList, VideoFrameList } from '../../shared/media';
import { useApp } from './context';
import { request, errorMessage, isDemo } from './bridge';
import { Button, Notice } from './ui';
import { MediaError, MediaProgressView, mediaJobName, mediaStatuses, videoFrameScopeNotice } from './mediaUi';
import ScreeningResults from './ScreeningResults';

export default function MediaJobs({ initialJobId }: { initialJobId?: string }) {
  const { project, events } = useApp();
  const [list, setList] = useState<MediaJob[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [selected, setSelected] = useState(initialJobId ?? ''), [error, setError] = useState(''), [loading, setLoading] = useState(false), [revision, setRevision] = useState(0);
  useEffect(() => { if (initialJobId) setSelected(initialJobId); }, [initialJobId]);
  const mediaEvent = [...events].reverse().find(e => e.mediaJobId)?.sequence;
  useEffect(() => { if (mediaEvent === undefined) return; const timer = setTimeout(() => setRevision(n => n + 1), 180); return () => clearTimeout(timer); }, [mediaEvent]);
  useEffect(() => { if (isDemo) return; let live = true; setLoading(true); void request<MediaJobList>('media.job.list', { ...(project ? { projectId: project.id } : {}), offset, limit: 50 }).then(r => { if (live) { setList(r.items); setTotal(r.total); setError(''); } }).catch(e => { if (live) setError(errorMessage(e)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [project?.id, offset, revision]);
  if (isDemo) return <Notice>视频与素材分析任务需要桌面引擎，演示模式不生成任务。</Notice>;
  return <div className="media-jobs"><div className="section-toolbar"><h2>素材任务</h2><Button busy={loading} onClick={() => setRevision(n => n + 1)}>刷新素材任务</Button></div><div className="media-jobs-layout"><aside className="media-job-list">{list.map(job => <button key={job.id} className={job.id === selected ? 'selected' : ''} onClick={() => setSelected(job.id)}><strong>{mediaJobName(job)}</strong><span>{mediaStatuses[job.status]}{job.kind === 'video_extract' && ` · ${job.assetsCommitted ? '已入库' : job.canImport ? '待导入' : '尚未入库'}`}</span><small>{new Date(job.createdAt).toLocaleString('zh-CN')}</small></button>)}{!list.length && <p className="quiet-empty">此范围尚无素材任务。</p>}<div className="pagination"><Button disabled={loading || offset === 0} onClick={() => setOffset(n => Math.max(0, n - 50))}>上一页任务</Button><span>{offset / 50 + 1}</span><Button disabled={loading || offset + list.length >= total} onClick={() => setOffset(n => n + 50)}>下一页任务</Button></div></aside>{selected ? <MediaJobDetail key={selected} jobId={selected} onRetry={setSelected}/> : <p className="quiet-empty">选择任务，查看真实进度和已提交结果。</p>}</div><MediaError error={error}/></div>;
}
export function MediaJobDetail({ jobId, onRetry, excludeIds, onApplyExclude }: { jobId: string; onRetry?: (id: string) => void; excludeIds?: string[]; onApplyExclude?: (ids: string[]) => void }) {
  const { openProject, refreshAssets, refreshProjects, navigate } = useApp();
  const [job, setJob] = useState<MediaJob | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [showFrames, setShowFrames] = useState(false), [readError, setReadError] = useState('');
  useEffect(() => { let live = true, timer: ReturnType<typeof setTimeout>; async function read() { try { const r = await request<MediaJob>('media.job.get', { jobId }); if (live) { setReadError(''); setJob(current => !current || r.sequence >= current.sequence ? r : current); timer = setTimeout(() => void read(), ['queued', 'running', 'cancelling'].includes(r.status) ? 800 : 3000); } } catch (e) { if (live) { setReadError(errorMessage(e)); timer = setTimeout(() => void read(), 5000); } } } void read(); return () => { live = false; clearTimeout(timer); }; }, [jobId]);
  async function action(command: string) { setBusy(true); setError(''); try { const next = await request<MediaJob>(command, { jobId }); if (next.id !== jobId) onRetry?.(next.id); else setJob(current => !current || next.sequence >= current.sequence ? next : current); if (next.assetsCommitted) await Promise.all([refreshAssets(), refreshProjects()]); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  // 抽帧素材的可用范围只在入库那一刻才有意义，但导入是异步完成的（也可能是自动导入），
  // 因此按任务状态派生而不是绑在按钮回调上：状态一旦报告已入库就展示，不会漏。
  const framesCommitted = job?.kind === 'video_extract' && job.assetsCommitted;
  async function open() { if (!job || job.status !== 'completed' || job.stage !== 'done' || !job.assetsCommitted) return; setBusy(true); setError(''); try { await openProject(await request('project.open', { projectId: job.projectId })); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <section className="media-job-detail">{job ? <><h3>{mediaJobName(job)}</h3><MediaProgressView job={job}/>{typeof job.summary?.geometryNotice === 'string' && <Notice>{job.summary.geometryNotice}</Notice>}<div className="actions"><Button busy={busy} disabled={!job.canCancel} onClick={() => void action('media.job.cancel')}>{job.status === 'cancelling' ? '正在取消' : '取消素材任务'}</Button>{onRetry && <Button busy={busy} disabled={!job.canRetry} onClick={() => void action('media.job.retry')}>创建重试任务</Button>}{job.kind === 'video_extract' && <><Button className="primary" busy={busy} disabled={job.status !== 'completed' || job.stage !== 'ready' || !job.artifactCommitted || !job.canImport} onClick={() => void action('media.video.import')}>将抽帧导入项目</Button><Button busy={busy} disabled={job.status !== 'completed' || job.stage !== 'done' || !job.assetsCommitted} onClick={() => void open()}>打开已导入素材</Button></>}</div>{framesCommitted&&<Notice>{videoFrameScopeNotice}</Notice>}{job.kind === 'video_extract' && <><p className="muted tiny">抽帧结果：{job.artifactCommitted ? '已封存' : '尚未封存'} · 项目素材：{job.assetsCommitted ? '已提交' : '尚未提交'}</p>{job.artifactCommitted && <><Button onClick={() => setShowFrames(v => !v)}>{showFrames ? '收起帧记录' : '查看抽帧记录'}</Button>{showFrames && <VideoFrames key={`${job.id}-${job.assetsCommitted}`} jobId={job.id}/>}</>}</>}{job.kind === 'image_screening' && job.status === 'completed' && job.artifactCommitted && <ScreeningResults jobId={job.id} excludeIds={excludeIds} onApplyExclude={onApplyExclude}/>}{job.error && <MediaError error={`[${job.error.code}] ${job.error.message}`} busy={busy} handlers={{ openMediaRuntime: () => void navigate('settings', 'media'), ...(job.canRetry ? { retry: () => void action('media.job.retry') } : {}) }}/>}<details className="media-job-diagnostics"><summary>任务与参数诊断信息</summary><p>任务 ID：{job.id}</p><p>更新时间：{new Date(job.updatedAt).toLocaleString('zh-CN')}</p>{job.originalJobId && <p>来源任务 ID：{job.originalJobId}</p>}<pre>{JSON.stringify({ parameters: job.parameters, progress: job.progress, summary: job.summary }, null, 2)}</pre></details></> : <p className="muted">正在读取素材任务…</p>}<MediaError error={readError}/><MediaError error={error}/></section>;
}
function VideoFrames({ jobId }: { jobId: string }) {
  const [page, setPage] = useState<VideoFrameList | null>(null), [offset, setOffset] = useState(0), [error, setError] = useState('');
  useEffect(() => { let live = true; setPage(null); setError(''); void request<VideoFrameList>('media.video.frames', { jobId, offset, limit: 20 }).then(r => { if (live) setPage(r); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [jobId, offset]);
  return <div className="video-frame-list">{page ? <>{page.items.map(frame => <div key={frame.frameId}><strong>源帧 {frame.sourcePresentationIndex} · {frame.timeSeconds.toFixed(3)} 秒</strong><span>{frame.width} × {frame.height} · 时间段 {frame.rangeIndex + 1} · {frame.assetId ? '已入库' : '尚未入库'}</span><details><summary>帧身份与坐标诊断</summary><pre>{JSON.stringify(frame, null, 2)}</pre></details></div>)}<div className="pagination"><Button disabled={offset === 0} onClick={() => setOffset(n => Math.max(0, n - 20))}>上一页帧</Button><span>{page.total ? offset + 1 : 0}–{offset + page.items.length} / {page.total}</span><Button disabled={offset + page.items.length >= page.total} onClick={() => setOffset(n => n + 20)}>下一页帧</Button></div></> : <p className="muted">正在读取已封存帧记录…</p>}<MediaError error={error}/></div>;
}
