import { useEffect, useRef, useState } from 'react';
import { MousePointer2, SquareDashed, Trash2 } from 'lucide-react';
import type { Annotation, LabelClass, Point, TaskType } from './types';
import { Button, Field, Notice } from './ui';
import { keypointEdges } from './keypointEdges';
import AttributeValues from './AttributeValues';
import TemplateRuleSummary from './TemplateRuleSummary';
import { deletePolygonPoint, insertPolygonPoint, MAX_POLYGON_POINTS } from './polygonEditing';

interface Props {mediaUrl:string;width?:number;height?:number;annotations:Annotation[]|null;classes?:LabelClass[];title:string;taskType?:TaskType;keypointNames?:string[];keypointConnections?:unknown;templateSettings?:Record<string,unknown>;purpose?:'truth'|'keyframe';maxObjects?:number;onChange?:(annotations:Annotation[])=>void;disabled?:boolean;imageAlt?:string;onImageDimensions?:(size:{width:number;height:number})=>void;onImageReady?:(ready:boolean)=>void;onPendingChange?:(pending:boolean)=>void}
interface Gesture {start:Point;original:Annotation[];id:string;kind:'draw'|'move'|'resize'|'vertex';handle?:string;index?:number}
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
function vertices(a:Annotation):Point[]{
  if(a.points)return a.points;if(!a.bbox)return [];const b=a.bbox,c={x:b.x+b.width/2,y:b.y+b.height/2},angle=(a.rotation??0)*Math.PI/180;
  return [{x:b.x,y:b.y},{x:b.x+b.width,y:b.y},{x:b.x+b.width,y:b.y+b.height},{x:b.x,y:b.y+b.height}].map(p=>a.type==='obb'?{x:c.x+(p.x-c.x)*Math.cos(angle)-(p.y-c.y)*Math.sin(angle),y:c.y+(p.x-c.x)*Math.sin(angle)+(p.y-c.y)*Math.cos(angle)}:p);
}
export default function QualityCanvas({mediaUrl,width,height,annotations,classes=[],title,taskType='detect',keypointNames=[],keypointConnections,templateSettings,purpose='truth',maxObjects,onChange,disabled,imageAlt,onImageDimensions,onImageReady,onPendingChange}:Props){
  const [natural,setNatural]=useState({width:width??1,height:height??1});const [error,setError]=useState(false);const [showNames,setShowNames]=useState(false);
  const [tool,setTool]=useState<'select'|'draw'>('select');const [selected,setSelected]=useState<string|null>(purpose==='keyframe'?annotations?.[0]?.id??null:null);const [polygon,setPolygon]=useState<Point[]>([]);const [drawing,setDrawing]=useState(false);
  const [vertex,setVertex]=useState<{id:string;index:number}|null>(null);const [inserting,setInserting]=useState(false);
  const [pointTarget,setPointTarget]=useState<number|null>(null);const [preview,setPreview]=useState<Annotation[]|null>(null);const drag=useRef<Gesture|null>(null);const previewValue=useRef<Annotation[]|null>(null);
  const list=preview??annotations??[];const current=list.find(a=>a.id===selected);const w=width??natural.width,h=height??natural.height,editable=Boolean(onChange)&&!disabled,scale=Math.max(w/650,1),color='#437fe5';
  useEffect(()=>{onPendingChange?.(drawing||polygon.length>0);},[drawing,polygon.length,onPendingChange]);
  function position(e:React.PointerEvent<SVGSVGElement>){const bounds=e.currentTarget.getBoundingClientRect();return{x:clamp((e.clientX-bounds.left)/bounds.width*w,0,w),y:clamp((e.clientY-bounds.top)/bounds.height*h,0,h)};}
  function update(change:Partial<Annotation>){if(current&&editable)onChange!(list.map(a=>a.id===current.id?{...a,...change}:a));}
  function finishPolygon(){if(!editable||polygon.length<3||polygon.length>MAX_POLYGON_POINTS)return;const shape:Annotation={id:crypto.randomUUID(),classId:classes[0]?.id??'',type:'segment',points:polygon};onChange!([...(annotations??[]),shape]);setSelected(shape.id);setPolygon([]);setTool('select');}
  function deleteVertex(){if(!editable||drag.current||polygon.length||vertex?.id!==current?.id||!current?.points||vertex===null)return;const points=deletePolygonPoint(current.points,vertex.index);if(points){update({points});setVertex(null);}}
  function down(e:React.PointerEvent<SVGSVGElement>){
    if(!editable||error||e.button!==0||taskType==='classify')return;const start=position(e);e.currentTarget.focus();
    if(pointTarget!==null&&current?.keypoints){update({keypoints:current.keypoints.map((p,i)=>i===pointTarget?{...p,...start,visibility:2}:p)});setPointTarget(null);return;}
    if(tool==='draw'&&maxObjects!==undefined&&list.length>=maxObjects)return;
    if(tool==='draw'&&taskType==='segment'){if(polygon.length<MAX_POLYGON_POINTS)setPolygon(points=>[...points,start]);return;}
    const edge=(e.target as SVGElement).getAttribute('data-quality-edge');if(inserting&&current?.type==='segment'&&current.points&&edge!==null){const points=insertPolygonPoint(current.points,Number(edge),start);if(points){update({points});setVertex({id:current.id,index:Number(edge)+1});setInserting(false);}return;}
    const target=(e.target as SVGElement).closest('[data-quality-object]');const id=tool==='draw'?crypto.randomUUID():target?.getAttribute('data-quality-object');if(!id){setSelected(null);setVertex(null);setInserting(false);return;}
    const handle=(e.target as SVGElement).getAttribute('data-quality-handle')??undefined,vertex=(e.target as SVGElement).getAttribute('data-quality-vertex');setSelected(id);setVertex(vertex!==null&&list.find(a=>a.id===id)?.type==='segment'?{id,index:Number(vertex)}:null);if(id!==selected)setInserting(false);e.currentTarget.setPointerCapture(e.pointerId);setDrawing(true);
    drag.current={start,original:structuredClone(annotations??[]),id,kind:tool==='draw'?'draw':vertex!==null?'vertex':handle?'resize':'move',handle,index:vertex!==null?Number(vertex):undefined};
  }
  function move(e:React.PointerEvent<SVGSVGElement>){
    const state=drag.current;if(!state)return;const p=position(e);let next=structuredClone(state.original);
    if(state.kind==='draw')next.push({id:state.id,classId:classes[0]?.id??'',type:taskType,bbox:{x:Math.min(state.start.x,p.x),y:Math.min(state.start.y,p.y),width:Math.abs(p.x-state.start.x),height:Math.abs(p.y-state.start.y)},...(taskType==='obb'?{rotation:0}:{}),...(taskType==='pose'?{keypoints:keypointNames.map(name=>({name,x:0,y:0,visibility:0 as const}))}:{})});
    else next=next.map(a=>{
      if(a.id!==state.id)return a;if(state.kind==='vertex'&&a.points)return {...a,points:a.points.map((pt,i)=>i===state.index?p:pt)};
      const b=a.bbox;if(state.kind==='resize'&&b){const x=state.handle?.includes('w')?Math.min(p.x,b.x+b.width-1):b.x,y=state.handle?.includes('n')?Math.min(p.y,b.y+b.height-1):b.y;return{...a,bbox:{x,y,width:(state.handle?.includes('e')?Math.max(p.x,x+1):b.x+b.width)-x,height:(state.handle?.includes('s')?Math.max(p.y,y+1):b.y+b.height)-y}};}
      const points=[...vertices(a),...(a.keypoints??[]).filter(k=>k.visibility>0)];if(!points.length)return a;const dx=clamp(p.x-state.start.x,-Math.min(...points.map(v=>v.x)),w-Math.max(...points.map(v=>v.x))),dy=clamp(p.y-state.start.y,-Math.min(...points.map(v=>v.y)),h-Math.max(...points.map(v=>v.y)));
      return {...a,...(b?{bbox:{...b,x:b.x+dx,y:b.y+dy}}:{}),...(a.points?{points:a.points.map(pt=>({x:pt.x+dx,y:pt.y+dy}))}:{}),...(a.keypoints?{keypoints:a.keypoints.map(k=>k.visibility>0?{...k,x:k.x+dx,y:k.y+dy}:k)}:{})};
    });previewValue.current=next;setPreview(next);
  }
  function up(event:React.PointerEvent<SVGSVGElement>){const state=drag.current;if(state)move(event);drag.current=null;setDrawing(false);if(state&&previewValue.current){const next=previewValue.current.filter(a=>a.id!==state.id||!a.bbox||(a.bbox.width>=2&&a.bbox.height>=2));onChange?.(next);setTool('select');}previewValue.current=null;setPreview(null);}
  return <div className={`quality-canvas ${onChange?'editable':''}`}><div className="quality-canvas-heading"><strong>{title}</strong>{list.some(a=>a.keypoints?.length)&&<label className="checkbox-row"><input type="checkbox" checked={showNames} onChange={e=>setShowNames(e.target.checked)}/>显示点名</label>}{onChange&&taskType!=='classify'&&<div className="actions"><Button disabled={!editable||polygon.length>0} aria-pressed={tool==='select'} onClick={()=>{setTool('select');setPointTarget(null);}}><MousePointer2 size={13}/>选择</Button><Button disabled={!editable||polygon.length>0||maxObjects!==undefined&&list.length>=maxObjects} aria-pressed={tool==='draw'} onClick={()=>{setTool('draw');setPointTarget(null);}}><SquareDashed size={13}/>{taskType==='segment'?'绘制标准多边形':taskType==='obb'?'绘制标准旋转框':purpose==='keyframe'?'绘制对象框':'绘制标准框'}</Button></div>}</div>
    <div className="quality-canvas-columns"><div><div className="quality-image"><img src={mediaUrl} alt={imageAlt??(purpose==='keyframe'?'视频关键帧原图':'评测样本原图')} onLoad={e=>{setNatural({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight});onImageDimensions?.({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight});setError(false);onImageReady?.(true);}} onError={()=>{setError(true);onImageReady?.(false);}}/>{!error&&<svg aria-label={onChange?purpose==='keyframe'?'关键帧标注画布':'独立标准答案画布':title} tabIndex={onChange?0:undefined} viewBox={`0 0 ${w} ${h}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null;previewValue.current=null;setPreview(null);setDrawing(false);}} onKeyDown={e=>{if(e.key==='Enter'&&polygon.length){e.preventDefault();finishPolygon();}if(e.key==='Escape'){setPolygon([]);setPointTarget(null);setVertex(null);setInserting(false);setTool('select');}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();e.stopPropagation();deleteVertex();}}}>
      {list.map(a=>{const b=a.type==='obb'&&a.points?undefined:a.bbox,c=classes.find(c=>c.id===a.classId),stroke=c?.color??color,points=vertices(a),anchor=points.length?{x:Math.min(...points.map(p=>p.x)),y:Math.min(...points.map(p=>p.y))}:null;return <g key={a.id} data-quality-object={a.id}>
        {b&&<g transform={a.type==='obb'?`rotate(${a.rotation??0},${b.x+b.width/2},${b.y+b.height/2})`:undefined}><rect x={b.x} y={b.y} width={b.width} height={b.height} stroke={stroke} fill={onChange&&selected===a.id?'#437fe51a':'transparent'} strokeWidth={2*scale}/>{editable&&selected===a.id&&a.type!=='obb'&&[['nw',b.x,b.y],['ne',b.x+b.width,b.y],['sw',b.x,b.y+b.height],['se',b.x+b.width,b.y+b.height]].map(([handle,x,y])=><rect key={handle} data-quality-handle={handle} x={Number(x)-4*scale} y={Number(y)-4*scale} width={8*scale} height={8*scale} fill="white" stroke={stroke}/>)}</g>}
        {a.points&&<><polygon points={a.points.map(p=>`${p.x},${p.y}`).join(' ')} stroke={stroke} fill={`${stroke}18`} strokeWidth={2*scale}/>{editable&&selected===a.id&&a.type==='segment'&&<>{inserting&&a.points.map((p,i)=><line key={`edge-${i}`} data-quality-edge={i} x1={p.x} y1={p.y} x2={a.points![(i+1)%a.points!.length].x} y2={a.points![(i+1)%a.points!.length].y} stroke="transparent" strokeWidth={14*scale} className="segment-insert-edge"/>)}{a.points.map((p,i)=><circle key={i} data-quality-vertex={i} cx={p.x} cy={p.y} r={4*scale} fill={vertex?.id===a.id&&vertex.index===i?stroke:'white'} stroke={stroke}/>)}</>}</>}
        {anchor&&<text x={anchor.x+4*scale} y={Math.max(15*scale,anchor.y-5*scale)} fill={stroke} paintOrder="stroke" stroke="#fff" strokeWidth={2*scale} fontSize={12*scale}>{c?.name??a.classId}</text>}
        {a.type==='classify'&&<g><rect x={10*scale} y={10*scale} width={Math.min(w-20*scale,Math.max(110,(c?.name??a.classId).length*13)*scale)} height={30*scale} rx={4*scale} fill={stroke}/><text x={18*scale} y={30*scale} fill="white" fontSize={14*scale}>{c?.name??a.classId}</text></g>}
        {keypointEdges(a.keypoints,keypointConnections).map(([from,to],edge)=><line key={edge} data-keypoint-edge x1={from.x} y1={from.y} x2={to.x} y2={to.y} stroke={stroke} strokeWidth={1.5*scale}/>)}
        {a.keypoints?.filter(p=>p.visibility>0).map(p=><g key={p.name}><circle cx={p.x} cy={p.y} r={4*scale} fill={p.visibility===2?stroke:'white'} stroke={stroke} strokeWidth={1.5*scale}/>{showNames&&<text x={p.x+6*scale} y={p.y-6*scale} fill={stroke} fontSize={10*scale} paintOrder="stroke" stroke="white" strokeWidth={2*scale}>{p.name}</text>}</g>)}
      </g>;})}{polygon.length>0&&<polyline points={polygon.map(p=>`${p.x},${p.y}`).join(' ')} stroke={color} fill={`${color}18`} strokeWidth={2*scale}/>}</svg>}</div>
      {error&&<p className="inline-error">此来源的样本图片无法读取，未替换为其他图片。</p>}{annotations===null&&<Notice>此样本没有可用候选，不能按“成功但无目标”解释。</Notice>}{annotations?.length===0&&taskType==='classify'&&!onChange&&<p className="muted">模型成功返回，但没有分类结果。</p>}
      {onChange&&<p className="muted tiny">{inserting?'点击选中多边形的边插入顶点。':vertex?.id===current?.id&&vertex?`选中顶点 ${vertex.index+1}，Delete 删点；删除对象使用独立按钮。`:pointTarget!==null?`点击图片定位关键点：${current?.keypoints?.[pointTarget]?.name}`:taskType==='classify'?'在右侧明确选择一个人工标准类别。':tool==='draw'?taskType==='segment'?'逐点点击边界，至少三个点后完成多边形。':taskType==='pose'?'拖动绘制对象框；关键点初始为不可定位，需人工逐点设置。':taskType==='obb'?'拖动绘制对象框，在右侧调整旋转角度。':purpose==='keyframe'?'拖动绘制对象框。':'拖动绘制标准对象框。':'点击对象选择，可拖动或调整几何参数。'}</p>}
      {polygon.length>0&&<div className="actions"><Button disabled={!editable||polygon.length<3} onClick={finishPolygon}>完成标准多边形</Button><Button disabled={!editable} onClick={()=>setPolygon(p=>p.slice(0,-1))}>撤销最后一点</Button><Button disabled={!editable} onClick={()=>{setPolygon([]);setTool('select');}}>取消当前多边形</Button></div>}
    </div>{onChange&&<aside className="truth-properties">{taskType==='classify'?<Field label="人工标准类别" hint="每张图片必须明确选择一个类别。"><select aria-label="人工标准分类" value={list[0]?.classId??''} disabled={!editable} onChange={e=>{if(e.target.value)onChange!([{...list[0],id:list[0]?.id??crypto.randomUUID(),classId:e.target.value,type:'classify'}]);}}><option value="">尚未选择</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>:<>
      {list.length>0&&<Field label={purpose==='keyframe'?'关键帧对象':'标准答案对象'}><select value={selected??''} disabled={!editable} onChange={e=>{setSelected(e.target.value);setPointTarget(null);setVertex(null);setInserting(false);}}><option value="">选择对象</option>{list.map((a,i)=><option key={a.id} value={a.id}>{i+1} · {classes.find(c=>c.id===a.classId)?.name??a.classId}</option>)}</select></Field>}
      {current?<><Field label={purpose==='keyframe'?'对象类别':'标准答案类别'}><select value={current.classId} disabled={!editable} onChange={e=>update({classId:e.target.value})}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>{current.bbox&&!(current.type==='obb'&&current.points)&&<div className="geometry-fields">{(['x','y','width','height'] as const).map((key,i)=><Field key={key} label={['X','Y','宽度','高度'][i]}><input aria-label={`${purpose==='keyframe'?'关键帧对象':'标准答案对象'}${key}`} type="number" value={Math.round(current.bbox![key]*100)/100} disabled={!editable} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))update({bbox:{...current.bbox!,[key]:n}});}}/></Field>)}</div>}
      {current.type==='obb'&&<Field label="标准旋转角度"><input aria-label="标准旋转角度" type="number" min={-180} max={180} step={1} disabled={!editable} value={current.points&&current.points.length===4?Math.round(Math.atan2(current.points[1].y-current.points[0].y,current.points[1].x-current.points[0].x)*180/Math.PI*100)/100:current.rotation??0} onChange={e=>{const value=Number(e.target.value);if(!Number.isFinite(value))return;if(current.points?.length===4){const points=current.points,c={x:points.reduce((n,p)=>n+p.x,0)/4,y:points.reduce((n,p)=>n+p.y,0)/4},delta=value*Math.PI/180-Math.atan2(points[1].y-points[0].y,points[1].x-points[0].x);update({bbox:undefined,rotation:undefined,points:points.map(p=>({x:c.x+(p.x-c.x)*Math.cos(delta)-(p.y-c.y)*Math.sin(delta),y:c.y+(p.x-c.x)*Math.sin(delta)+(p.y-c.y)*Math.cos(delta)}))});}else update({rotation:value});}}/></Field>}
      <AttributeValues definition={templateSettings?.attributes} value={current.attributes} onChange={attributes=>update({attributes})} disabled={!editable}/>
      {current.type==='segment'&&current.points&&<div className="segment-controls"><div className="actions"><Button type="button" disabled={!editable||current.points.length>=MAX_POLYGON_POINTS} aria-pressed={inserting} onClick={()=>{setInserting(v=>!v);setVertex(null);setTool('select');}}>在边上插点</Button><Button type="button" disabled={!editable||vertex?.id!==current.id||current.points.length<=3} onClick={deleteVertex}>删除选中顶点</Button></div><small>3–4096 个顶点；选中点后 Delete 删点。</small></div>}
      {current.type==='segment'&&current.points?.map((point,i)=><div className="truth-point" key={i}><button type="button" className="text-button" aria-label={`选择标准顶点${i+1}`} aria-pressed={vertex?.id===current.id&&vertex.index===i} onClick={e=>{setVertex({id:current.id,index:i});setInserting(false);setTool('select');e.currentTarget.closest('.quality-canvas')?.querySelector('svg')?.focus();}}>边界点 {i+1}</button><div className="point-row">{(['x','y'] as const).map(key=><input aria-label={`标准边界点${i+1}${key}`} key={key} type="number" disabled={!editable} value={Math.round(point[key]*100)/100} onChange={e=>update({points:current.points!.map((p,j)=>j===i?{...p,[key]:Number(e.target.value)}:p)})}/>)}</div></div>)}
      {current.keypoints?.map((point,i)=><div className="truth-point" key={point.name}><strong>{point.name}</strong><select aria-label={`${point.name}${purpose==='keyframe'?'':'标准'}可见性`} value={point.visibility} disabled={!editable} onChange={e=>update({keypoints:current.keypoints!.map((p,j)=>j===i?{...p,visibility:Number(e.target.value) as 0|1|2}:p)})}><option value={0}>不可定位</option><option value={1}>遮挡，可定位</option><option value={2}>可见</option></select><small>{point.visibility>0?`${Math.round(point.x)}, ${Math.round(point.y)}`:'位置不计入误差'}</small><Button disabled={!editable} onClick={()=>setPointTarget(i)}>在图上定位</Button></div>)}<Button disabled={!editable} onClick={()=>{onChange!(list.filter(a=>a.id!==current.id));setSelected(null);setVertex(null);setInserting(false);}}><Trash2 size={13}/>{purpose==='keyframe'?'删除此对象':'删除标准对象'}</Button></>:<p className="muted">{purpose==='keyframe'?'绘制或选择一个对象。':'绘制或选择一个标准对象。'}</p>}
    </>}{taskType==='classify'&&list[0]&&<AttributeValues definition={templateSettings?.attributes} value={list[0].attributes} disabled={!editable} onChange={attributes=>onChange!([{...list[0],attributes}])}/>}</aside>}</div><TemplateRuleSummary settings={templateSettings}/>{!onChange&&templateSettings?.attributes!==undefined&&<details className="fixed-attribute-values"><summary>固定对象属性</summary>{list.map((a,i)=><section key={a.id}><strong>对象 {i+1}</strong><AttributeValues definition={templateSettings.attributes} value={a.attributes}/></section>)}</details>}</div>;
}
