import { useEffect, useState } from 'react';
import type { LibraryResource, ReferenceContent } from '../../shared/resources';
import { useApp } from './context';
import { request, errorMessage } from './bridge';
import { Button, Field, Modal, Notice } from './ui';
import type { Asset } from './types';

export default function ReferenceDialog({head,onSaved,onClose}:{head?:LibraryResource;onSaved:(r:LibraryResource)=>void;onClose:()=>void}){
  const {projects,project}=useApp();const old=head?.content as ReferenceContent|undefined;const [projectId,setProjectId]=useState(old?.sourceProjectId??project?.id??projects[0]?.id??'');const [assets,setAssets]=useState<Asset[]>([]);const [assetId,setAssetId]=useState('');const [name,setName]=useState(head?.name??'');const [category,setCategory]=useState(head?.category??'');const [note,setNote]=useState(head?.note??'');const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const selected=assets.find(a=>a.id===assetId);
  useEffect(()=>{let live=true;setLoading(true);setAssets([]);setAssetId('');setAck(false);if(projectId)void request<{items:Asset[]}>('asset.list',{projectId,limit:500}).then(data=>{if(live)setAssets(data.items.filter(a=>['manual','preset_manual'].includes(a.source)&&['modified','confirmed'].includes(a.status)));}).catch(e=>{if(live)setError(errorMessage(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[projectId]);
  async function save(){if(!selected)return;setBusy(true);setError('');try{const result=await request<LibraryResource>('resource.reference',{...(head?{id:head.id,baseVersion:head.version}:{}),assetId:selected.id,assetVersion:selected.version,name:name.trim(),category,note});onSaved(result);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title={head?'建立参考的新版本':'保存人工参考样例'} onClose={()=>{if(!busy)onClose();}}><div className="form-stack"><Notice>将所选人工版本的图片、标注、模板及说明保存为独立副本，之后源项目修改不会改写这个版本。</Notice><Field label="来源项目"><select aria-label="参考来源项目" disabled={busy} value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name} · {p.taskType.toUpperCase()}</option>)}</select></Field><Field label="已保存的人工标注" hint="列出前 500 张素材中可作为人工参考的版本；API 候选和未保存草稿不能直接加入。"><select aria-label="参考来源素材" disabled={busy||loading} value={assetId} onChange={e=>{setAssetId(e.target.value);setAck(false);if(!name)setName(assets.find(a=>a.id===e.target.value)?.name??'');}}><option value="">明确选择一张素材</option>{assets.map(a=><option key={a.id} value={a.id}>{a.name} · 人工版本 {a.version}</option>)}</select></Field>{selected&&<p className="muted tiny">本次保存人工版本 {selected.version} · {selected.annotations.length} 个对象 · {selected.source}</p>}<Field label="参考名称"><input aria-label="参考名称" value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></Field><Field label="分类标签"><input value={category} disabled={busy} onChange={e=>setCategory(e.target.value)}/></Field><Field label="人工说明" hint="这段说明会与固定参考图片和标注一同传给标注模型。"><textarea aria-label="参考人工说明" value={note} disabled={busy} rows={3} onChange={e=>setNote(e.target.value)}/></Field><label className="checkbox-row"><input aria-label="确认保存人工参考" type="checkbox" disabled={busy||!selected} checked={ack} onChange={e=>setAck(e.target.checked)}/>已核对图片、人工版本与参考说明</label>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-actions"><Button disabled={busy} onClick={onClose}>取消</Button><Button className="primary" busy={busy} disabled={!selected||!name.trim()||!ack} onClick={()=>void save()}>保存固定人工参考</Button></div></div></Modal>;
}
