import { useState } from 'react';
import type { LibraryResource, ResourceField, ResourceApplication } from '../../shared/resources';
import { useApp } from './context';
import { request, errorMessage } from './bridge';
import { Button, Field, Modal, Notice } from './ui';

const fields:Record<ResourceField,string>={prompt:'标注提示词',classes:'类别定义',keypointNames:'关键点名称与顺序',keypointConnections:'关键点连接',attributes:'属性定义',rules:'标注规则',occlusionRules:'遮挡规则',blurRules:'模糊规则',flow:'完整流程'};
export function availableFields(resource:LibraryResource):ResourceField[]{if(resource.kind==='prompt')return ['prompt'];if(resource.kind==='flow')return ['flow'];if(resource.kind!=='template')return [];const content=resource.content as Record<string,unknown>,settings=(content.settings??{}) as Record<string,unknown>;return (Object.keys(fields) as ResourceField[]).filter(f=>content[f]!=null||settings[f]!=null);}
export default function ResourceApply({resource,onClose}:{resource:LibraryResource;onClose:()=>void}){
  const {project,projects,setProject,refreshProjects,notify}=useApp();const [projectId,setProjectId]=useState(project?.id??projects[0]?.id??'');const [picked,setPicked]=useState<ResourceField[]>([]);const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const choices=availableFields(resource);
  async function apply(){setBusy(true);setError('');try{const result=await request<ResourceApplication>('resource.apply',{projectId,resourceId:resource.id,version:resource.version,fields:picked});if(project?.id===result.project.id)setProject(result.project);await refreshProjects();notify(`已应用资源版本 ${result.resourceVersion}：${result.fields.map(f=>fields[f]).join('、')}。`);onClose();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  return <Modal title="应用资源到项目" onClose={()=>{if(!busy)onClose();}}><div className="form-stack"><p><strong>{resource.name}</strong> · 固定版本 {resource.version}</p><Field label="目标项目"><select aria-label="资源目标项目" value={projectId} disabled={busy} onChange={e=>{setProjectId(e.target.value);setAck(false);}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · {p.taskType.toUpperCase()}</option>)}</select></Field><Notice>只覆盖本次勾选的字段。类别或点位变更会经过已有标注兼容检查；不兼容时保留原项目。</Notice><div className="resource-field-picks">{choices.map(f=><label className="checkbox-row" key={f}><input aria-label={`应用${fields[f]}`} type="checkbox" checked={picked.includes(f)} disabled={busy} onChange={e=>{setPicked(list=>e.target.checked?[...list,f]:list.filter(v=>v!==f));setAck(false);}}/>{fields[f]}</label>)}</div><label className="checkbox-row"><input aria-label="确认覆盖资源字段" type="checkbox" checked={ack} disabled={busy||!picked.length} onChange={e=>setAck(e.target.checked)}/>确认将所选字段覆盖到这个项目</label>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="modal-actions"><Button disabled={busy} onClick={onClose}>取消</Button><Button className="primary" disabled={!projectId||!picked.length||!ack} busy={busy} onClick={()=>void apply()}>应用所选字段</Button></div></div></Modal>;
}
