import { useEffect, useRef, useState } from 'react';
import { Plus, FileText, GitBranch, Image, Workflow, Save, Library, ArrowUpRight } from 'lucide-react';
import type { LibraryResource, ReferenceContent, ResourceKind } from '../../shared/resources';
import { useApp } from './context';
import { request, errorMessage, isDemo } from './bridge';
import { Button, Empty, Field, Loading, PageHeader, SearchField } from './ui';
import TruthSets from './TruthSets';
import QualityCanvas from './QualityCanvas';
import ReferenceDialog from './ReferenceDialog';
import ResourceApply from './ResourceApply';
import { TemplateResourceEditor } from './TemplateSettingsEditor';

const kinds:Record<ResourceKind,string>={prompt:'提示词',template:'标注模板',reference:'人工参考',flow:'流程'},icons={prompt:FileText,template:GitBranch,reference:Image,flow:Workflow};
export default function Resources(){
  const {project,notify,navigate,guard,syncWindowDirtySource}=useApp();const [standards,setStandards]=useState(false);const [reference,setReference]=useState<LibraryResource|null|undefined>(undefined);const [applying,setApplying]=useState(false);
  const [resources,setResources]=useState<LibraryResource[]>([]);const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [categoryFilter,setCategoryFilter]=useState('');const [offset,setOffset]=useState(0);const [hasMore,setHasMore]=useState(false);const [loading,setLoading]=useState(false);const generation=useRef(0);
  const [head,setHead]=useState<LibraryResource|null>(null);const [selected,setSelected]=useState<LibraryResource|null>(null);const [version,setVersion]=useState(0);const [name,setName]=useState('');const [category,setCategory]=useState('');const [note,setNote]=useState('');const [kind,setKind]=useState<ResourceKind>('prompt');const [content,setContent]=useState('');const [editing,setEditing]=useState(false);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{if(!dirty)return;const beforeLeave=async()=>{throw new Error('资源内容尚未保存，请先保存，或点击“放弃编辑并收起”。');};guard.current=beforeLeave;return()=>{if(guard.current===beforeLeave)guard.current=null;};},[dirty,guard]);
  useEffect(()=>{syncWindowDirtySource('resources',dirty);return()=>syncWindowDirtySource('resources',false);},[dirty,syncWindowDirtySource]);
  async function refresh(){const stamp=++generation.current;setLoading(true);try{const rows=await request<LibraryResource[]>('resource.list',{...(filter==='all'?{}:{kind:filter}),...(search?{query:search}:{}),...(categoryFilter?{category:categoryFilter}:{}),offset,limit:100});if(stamp===generation.current){setResources(rows.filter(r=>r.kind in kinds));setHasMore(rows.length===100);setError('');}}catch(e){if(stamp===generation.current)setError(errorMessage(e));}finally{if(stamp===generation.current)setLoading(false);}}
  useEffect(()=>{const timer=setTimeout(()=>void refresh(),180);return()=>{clearTimeout(timer);generation.current++;};},[filter,search,categoryFilter,offset]);
  function show(resource:LibraryResource|null,asHead=true){setSelected(resource);if(asHead)setHead(resource);setVersion(resource?.version??0);setName(resource?.name??'');setCategory(resource?.category??'');setNote(resource?.note??'');setKind(resource?.kind??'prompt');setContent(resource?typeof resource.content==='string'?resource.content:JSON.stringify(resource.content,null,2):'');setEditing(true);setDirty(false);setError('');}
  async function open(resource:LibraryResource){setBusy(true);try{show(isDemo?resource:await request('resource.get',{resourceId:resource.id}));}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function loadVersion(){if(!head)return;setBusy(true);try{show(await request('resource.get',{resourceId:head.id,version}),false);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const parsed=kind==='prompt'?content:JSON.parse(content);const result=await request<LibraryResource>('resource.save',{...(head?{id:head.id,baseVersion:head.version??0}:{}),name:name.trim(),kind,category,note,content:parsed});show(result);await refresh();notify(`资源版本 ${result.version??0} 已保存。`);}catch(e){setError(e instanceof SyntaxError?'请输入有效 JSON；提示词使用纯文本。':errorMessage(e));}finally{setBusy(false);}}
  function saveTemplate(){if(!project)return;show(null);setName(project.name+' · 标注模板');setKind('template');const values:Record<string,unknown>={taskType:project.taskType,classes:project.classes};for(const key of ['keypointNames','keypointConnections','attributes','rules','occlusionRules','blurRules','prompt'])if(project.settings[key]!==undefined)values[key]=project.settings[key];setContent(JSON.stringify(values,null,2));setDirty(true);}
  const readonly=Boolean(head&&selected&&selected.version!==head.version)||kind==='reference',rawReference=kind==='reference'?selected?.content as ReferenceContent:undefined,referenceContent=rawReference?.template&&Array.isArray(rawReference.annotations)&&rawReference.width&&rawReference.height?rawReference:undefined;
  return <div className="content resources-page">{standards&&<TruthSets onClose={()=>setStandards(false)}/>}<PageHeader title="资源库" description="跨项目保存提示词、模板、人工参考与流程，每个版本独立保留" actions={<><Button onClick={()=>setStandards(true)}>标准答案集</Button><Button disabled={isDemo||busy||dirty} onClick={()=>setReference(null)}>保存人工参考</Button><Button disabled={!project||busy||dirty} onClick={saveTemplate}>保存项目模板</Button><Button className="primary" disabled={busy||dirty} onClick={()=>show(null)}><Plus size={14}/>新建资源</Button></>}/><div className="section-toolbar"><div className="tabs">{[['all','全部资源'],...Object.entries(kinds)].map(([key,label])=><button key={key} className={filter===key?'selected':''} onClick={()=>{setFilter(key);setOffset(0);}}>{label}</button>)}</div><SearchField placeholder="搜索名称、说明或内容" value={search} onChange={v=>{setSearch(v);setOffset(0);}}/></div><Field label="分类标签筛选"><input aria-label="资源分类筛选" placeholder="留空显示全部分类" value={categoryFilter} onChange={e=>{setCategoryFilter(e.target.value);setOffset(0);}}/></Field>
    {error&&!editing&&<p className="inline-error" role="alert">{error}</p>}<div className={`resources-layout ${editing?'editing':''}`}><div><div className="resource-list">{loading?<Loading label="正在读取资源…" />:resources.length?resources.map(resource=>{const Icon=icons[resource.kind];return <button key={resource.id} disabled={busy||dirty} className={`resource-row ${head?.id===resource.id&&editing?'selected':''}`} onClick={()=>void open(resource)}><div className="resource-icon"><Icon size={21}/></div><div><h3>{resource.name}</h3><p>{kinds[resource.kind]} · 版本 {resource.version??0} · {resource.category||'未分类'}</p><small>{resource.note|| (typeof resource.content==='string'?resource.content:'打开查看固定内容与应用范围')}</small></div><ArrowUpRight size={15}/></button>;}):<Empty icon={<Library size={26}/>} title="此范围没有资源" description="调整筛选，或保存可跨项目复用的规则。"><Button className="primary" disabled={busy||dirty} onClick={()=>show(null)}><Plus size={14}/>新建资源</Button></Empty>}</div><div className="pagination"><Button disabled={loading||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-100))}>上一页</Button><span>第 {Math.floor(offset/100)+1} 页 · {resources.length} 项</span><Button disabled={loading||!hasMore} onClick={()=>setOffset(v=>v+100)}>下一页</Button></div></div>
    {editing&&<form className="resource-editor" onSubmit={save}><div className="section-toolbar"><h2>{head?readonly?'固定版本内容':'编辑资源新版本':'新建资源'}</h2><Button type="button" disabled={busy} onClick={()=>{setEditing(false);setDirty(false);}}> {dirty?'放弃编辑并收起':'收起'} </Button></div>{head&&!isDemo&&<div className="field-grid"><Field label="查看固定版本"><input aria-label="资源版本" type="number" min={0} max={head.version} disabled={busy||dirty} value={version} onChange={e=>setVersion(Number(e.target.value))}/></Field><div className="actions"><Button type="button" disabled={busy||dirty} onClick={()=>void loadVersion()}>读取指定版本</Button><Button type="button" disabled={busy||dirty} onClick={()=>void open(head)}>读取最新版本</Button></div></div>}<Field label="资源名称"><input aria-label="资源名称" required value={name} disabled={busy||readonly} onChange={e=>{setName(e.target.value);setDirty(true);}}/></Field><div className="field-grid"><Field label="类型"><select aria-label="资源类型" value={kind} disabled={Boolean(head)||busy} onChange={e=>{setKind(e.target.value as ResourceKind);setDirty(true);}}>{Object.entries(kinds).filter(([key])=>key!=='reference'||kind==='reference').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="分类标签"><input aria-label="资源分类" disabled={busy||readonly} value={category} onChange={e=>{setCategory(e.target.value);setDirty(true);}}/></Field></div><Field label="资源说明"><textarea aria-label="资源说明" rows={2} disabled={busy||readonly} value={note} onChange={e=>{setNote(e.target.value);setDirty(true);}}/></Field>
      {kind==='reference'&&!referenceContent&&<><p className="muted">旧参考记录没有固定的图片与人工版本，请从人工标注重新保存。</p><Button type="button" onClick={()=>setReference(head)}>重新保存人工参考</Button></>}{kind==='template'&&<TemplateResourceEditor key={`${selected?.id??'new'}-${selected?.version??0}`} content={content} disabled={busy||readonly} onChange={value=>{setContent(value);setDirty(true);}}/>}{referenceContent?<><p className="muted tiny">来源项目 {referenceContent.sourceProjectId?.slice(0,8)} · 人工标注版本 {referenceContent.sourceAssetVersion} · 固定资源版本 {selected!.version}</p><QualityCanvas mediaUrl={`autolabel-media://resource/${selected!.id}/${selected!.version}`} width={referenceContent.width} height={referenceContent.height} annotations={referenceContent.annotations??null} classes={referenceContent.template?.classes} taskType={referenceContent.template?.taskType} keypointConnections={referenceContent.template?.settings.keypointConnections} templateSettings={referenceContent.template?.settings} title="固定人工参考"/><Button type="button" disabled={busy||!head} onClick={()=>setReference(head)}>从人工标注建立新版本</Button></>:<Field label={kind==='prompt'?'提示词内容':'模板或流程内容 · JSON'} hint={kind==='template'?'可从当前项目保存模板，再调整需要复用的字段。':undefined}><textarea aria-label="资源内容" required readOnly={readonly} disabled={busy} className={kind==='prompt'?'resource-text':'resource-text code'} value={content} onChange={e=>{setContent(e.target.value);setDirty(true);}}/></Field>}
      {error&&<p className="inline-error" role="alert">{error}</p>}<div className="actions">{kind==='flow'&&<Button type="button" onClick={()=>void navigate('workflow')}>打开流程编辑器</Button>}{head&&kind!=='reference'&&<Button type="button" disabled={busy||dirty||isDemo} onClick={()=>setApplying(true)}>应用当前版本到项目</Button>}{!readonly&&<Button type="submit" className="primary" busy={busy}><Save size={14}/>{head?'保存为新版本':'保存资源'}</Button>}</div>{dirty&&<p className="muted tiny">存在未保存编辑。保存或明确放弃后再切换资源与版本。</p>}</form>}
    </div>{reference!==undefined&&<ReferenceDialog head={reference??undefined} onClose={()=>setReference(undefined)} onSaved={r=>{show(r);void refresh();notify('人工参考固定版本已保存。');}}/>}{applying&&selected&&<ResourceApply resource={selected} onClose={()=>setApplying(false)}/>}</div>;
}
