import { useEffect, useState } from 'react';
import type { ScreeningExactGroup, ScreeningItem, ScreeningNearPair, ScreeningReason, ScreeningResult, ScreeningSection, ScreeningSourceGroup } from '../../shared/media';
import { errorMessage, request } from './bridge';
import { Button, Notice } from './ui';
import { MediaError } from './mediaUi';

export const screeningRecommendations = { keep: '未发现排除建议', keep_protected: '保留人工保护素材', review_suggested: '建议检查', exclude_suggested: '建议排除重复项' };
const sectionNames: Record<ScreeningSection, string> = { items: '逐图分析', exactGroups: '精确重复', nearPairs: '近重复候选', sourceLeakageGroups: '来源跨分区' };
export function ScreeningReasons({ reasons }: { reasons: ScreeningReason[] }) {
  return <div className="screening-reasons">{reasons.map((r, i) => <div key={i}><p>{r.code === 'blur_candidate' ? `清晰度需检查：分析图分数 ${typeof r.score === 'number' ? r.score.toFixed(3) : String(r.score)}，阈值 ${String(r.threshold)}` : r.code === 'blur_unexamined' ? '分析图过小，尚未完成模糊检查' : r.code === 'exact_duplicate_content' ? '存在内容完全相同的素材，身份与标注分别保留' : '存在需要检查的筛选提示'}</p><details><summary>理由详情</summary><pre>{JSON.stringify(r, null, 2)}</pre></details></div>)}</div>;
}
function AssetLabel({ id }: { id: string }) {
  const [name, setName] = useState('');
  useEffect(() => { let live = true; void request<{ name: string }>('asset.get', { assetId: id }).then(a => { if (live) setName(a.name); }).catch(() => {}); return () => { live = false; }; }, [id]);
  return <span title={id}>{name || '素材名称未读取'}</span>;
}
function ScreeningThumbnail({ assetId, contentHash }: { assetId: string; contentHash: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { let live = true; void request<{ contentHash: string; mediaUrl?: string }>('asset.get', { assetId }).then(a => { if (live && a.contentHash === contentHash) setUrl(a.mediaUrl ?? ''); }).catch(() => {}); return () => { live = false; }; }, [assetId, contentHash]);
  return url ? <img className="screening-thumbnail" src={url} alt="与分析内容一致的基准图" onError={() => setUrl('')}/> : null;
}
function Members({ ids }: { ids: string[] }) { return <div className="screening-members">{ids.slice(0, 6).map(id => <AssetLabel key={id} id={id}/>)}{ids.length > 6 && <small>另有 {ids.length - 6} 项，完整身份见诊断</small>}</div>; }
export default function ScreeningResults({ jobId, excludeIds, onApplyExclude }: { jobId: string; excludeIds?: string[]; onApplyExclude?: (ids: string[]) => void }) {
  const [section, setSection] = useState<ScreeningSection>('items'), [offset, setOffset] = useState(0), [result, setResult] = useState<ScreeningResult<ScreeningSection> | null>(null), [loading, setLoading] = useState(false), [error, setError] = useState('');
  const [selected, setSelected] = useState<string[]>(excludeIds ?? []);
  useEffect(() => { let live = true; setResult(null); setLoading(true); setError(''); void request<ScreeningResult<ScreeningSection>>('media.screening.result', { jobId, section, offset, limit: 20 }).then(r => { if (live) setResult(r); }).catch(e => { if (live) setError(errorMessage(e)); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, [jobId, section, offset]);
  const summary = result?.summary;
  return <section className="screening-results"><h3>筛选分析结果</h3>{summary && <><div className="screening-summary"><strong>{summary.status === 'complete' && summary.partitionCheck.status === 'complete' ? '本次分析已完成' : '本次分析包含未完成范围'}</strong><p>固定输入 {summary.inputCount} 张 · 不同内容 {summary.distinctContentCount} 组</p><p>近重复：{summary.nearCheck.status === 'disabled' ? '未启用' : `已比较 ${summary.nearCheck.comparedContentPairs} / ${summary.nearCheck.totalContentPairs} 个内容组对，未检查 ${summary.nearCheck.unexaminedContentPairs} 对`}</p>{summary.nearCheck.status === 'incomplete' && <p className="text-error">受分析上限影响，尚有最多 {summary.nearCheck.unexaminedIdentityPairUpperBound} 对素材身份未检查。<span> 停止原因：{['comparison_limit', 'maxComparisons', 'comparison_budget'].includes(summary.nearCheck.stopReason ?? '') ? '达到比较数量上限' : ['pair_limit', 'maxPairs', 'pair_budget'].includes(summary.nearCheck.stopReason ?? '') ? '达到候选数量上限' : summary.nearCheck.stopReason ?? '未提供'}</span></p>}<p>模糊检查未完成 {summary.unexaminedBlurAssetIds.length} 张 · 分区未指定 {summary.partitionCheck.unassignedInputs} 张</p>{summary.partitionCheck.status === 'incomplete' && <p className="muted tiny">来源分组未覆盖所有分区关系，不能据此认为不存在跨分区重复。</p>}{summary.unexaminedBlurAssetIds.length > 0 && <details><summary>查看未完成模糊检查的范围</summary><Members ids={summary.unexaminedBlurAssetIds}/><pre>{JSON.stringify(summary.unexaminedBlurAssetIds, null, 2)}</pre></details>}</div><Notice>{summary.scoreMeaning ?? '分数与距离仅用于筛选提示，需要人工检查。'} 本次分析未修改素材或标注。</Notice><details className="screening-effective"><summary>实际使用的阈值与参数</summary><p>精确重复建议：{result.parameters.deduplicate ? '启用' : '停用'} · 近重复：{result.parameters.nearEnabled ? '启用' : '停用'} · 模糊检查：{result.parameters.blurEnabled ? '启用' : '停用'}</p><p>近重复距离上限 {result.parameters.nearMaxDistance ?? '未报告'} · 宽高比容差 {result.parameters.aspectRatioTolerance ?? '未报告'} · 模糊阈值 {result.parameters.blurThreshold ?? '未启用'}</p><p>比较上限 {result.parameters.maxComparisons ?? '未报告'} · 候选对上限 {result.parameters.maxPairs ?? '未报告'}</p></details></>}
    <div className="tabs screening-section-tabs">{Object.entries(sectionNames).map(([key, label]) => <button key={key} className={key === section ? 'selected' : ''} onClick={() => { setSection(key as ScreeningSection); setOffset(0); }}>{label}</button>)}</div>{loading || result?.section !== section ? <p className="muted">正在读取已保存的分析结果…</p> : result && <><div className="screening-table">{result.items.map((value, index) => {
      if (section === 'items') { const item = value as ScreeningItem, metadata = item.input.metadata as Record<string, unknown> | undefined; return <article key={item.assetId}><ScreeningThumbnail assetId={item.assetId} contentHash={item.feature.contentHash}/><div className="section-toolbar"><strong>{typeof item.input.name === 'string' ? item.input.name : <AssetLabel id={item.assetId}/>}</strong><span>{screeningRecommendations[item.recommendation]}</span></div><p className="muted tiny">{item.feature.width} × {item.feature.height} · 分析图 {item.feature.analysisWidth} × {item.feature.analysisHeight} · 模糊分数 {item.feature.laplacianVariance === null ? '未计算' : item.feature.laplacianVariance.toFixed(3)}{item.protected ? ' · 人工版本受保护' : ''}</p>{metadata?.timeSeconds !== undefined && <p className="muted tiny">视频来源时间 {String(metadata.timeSeconds)} 秒 · 源帧序号 {String(metadata.sourcePresentationIndex ?? '未记录')}</p>}<ScreeningReasons reasons={item.reasons}/>{onApplyExclude && <label className="checkbox-row"><input aria-label={`排除素材 ${item.assetId}`} type="checkbox" checked={selected.includes(item.assetId)} onChange={e => setSelected(ids => e.target.checked ? [...new Set([...ids, item.assetId])] : ids.filter(id => id !== item.assetId))}/>明确从此流程输入排除{item.protected ? '（保留原人工标注）' : ''}</label>}<details><summary>素材与来源诊断信息</summary><p>素材 ID：{item.assetId}</p>{item.exactRepresentativeAssetId && <p>精确重复代表：<AssetLabel id={item.exactRepresentativeAssetId}/></p>}<pre>{JSON.stringify({ assetId: item.assetId, contentHash: item.feature.contentHash, version: item.input.version, inputVersion: item.feature.inputVersion, status: item.input.status, metadata }, null, 2)}</pre></details></article>; }
      if (section === 'nearPairs') { const pair = value as ScreeningNearPair; return <article key={`${pair.leftAssetId}-${pair.rightAssetId}`}><div className="screening-pair"><AssetLabel id={pair.leftAssetId}/><span>与</span><AssetLabel id={pair.rightAssetId}/></div><p>距离 {pair.distance} / 阈值 {pair.threshold} · 宽高比差 {pair.aspectRatioDifference.toFixed(4)} / 容差 {pair.aspectRatioTolerance}</p><p className="muted tiny">仅作候选提示，需人工检查{pair.lowInformation ? ' · 图片信息量较低' : ''}{pair.crossPartition ? ' · 涉及不同分区' : ''}</p><details><summary>配对诊断信息</summary><pre>{JSON.stringify(pair, null, 2)}</pre></details></article>; }
      const group = value as ScreeningExactGroup | ScreeningSourceGroup; return <article key={index}><strong>{section === 'exactGroups' ? `相同内容 · ${group.members.length} 张` : `${(group as ScreeningSourceGroup).kind === 'sourceVideoId' ? '同一视频来源' : '同一来源组'} · ${group.members.length} 张`}</strong><p>代表素材：<AssetLabel id={group.representativeAssetId}/></p><Members ids={group.members}/><p className="muted tiny">分区：{group.partitions.join('、') || '未指定'}{section === 'sourceLeakageGroups' ? ' · 需检查来源泄漏风险' : ''}</p><details><summary>分组诊断信息</summary><pre>{JSON.stringify(group, null, 2)}</pre></details></article>;
    })}{!result.items.length && <p className="quiet-empty">此分类没有已报告的结果，请结合上方未分析范围查看。</p>}</div><div className="pagination"><Button disabled={loading || offset === 0} onClick={() => setOffset(n => Math.max(0, n - 20))}>上一页分析</Button><span>{result.total ? offset + 1 : 0}–{offset + result.items.length} / {result.total}</span><Button disabled={loading || offset + result.items.length >= result.total} onClick={() => setOffset(n => n + 20)}>下一页分析</Button></div></>}
    {onApplyExclude && <div className="screening-apply"><p>已明确选择排除 {selected.length} 张（跨页保留选择）。保存到当前节点后仍需预检和运行流程，原素材及人工标注继续保留。</p><Button className="primary" disabled={loading || !result || result.section !== section} onClick={() => onApplyExclude(selected)}>将明确排除项写入当前筛选节点</Button></div>}<MediaError error={error}/></section>;
}
