import { useCallback, useEffect, useState } from 'react';
import { ListTodo, RefreshCw, Play, Pause, Square, RotateCcw, ArrowUpRight, Clock3, Activity, X } from 'lucide-react';
import { useApp } from './context';
import { request, isDemo, errorMessage } from './bridge';
import { Button, Empty, IconButton, PageHeader, SearchField } from './ui';
import { statusNames, type Run } from './types';
import QualityCenter from './QualityCenter';
import { BudgetEditor } from './CostControls';
import FlowRuns from './FlowRuns';
import MediaJobs from './MediaJobs';
import VideoTimeline from './VideoTimeline';
import ReuseProvenance from './ReuseProvenance';
import InputReuseSource from './InputReuseSource';
import { eventName } from './eventNames';
import ModelInputResult, { InputProgressView } from './ModelInputResult';

const stageNames: Record<string,string> = { preparing:'准备输入',sending:'发送请求',waiting:'等待模型响应',parsing:'解析结果',validating:'校验标注',saving:'保存结果',retry_wait:'等待重试',...statusNames };
export default function Tasks() {
  const { events, engine, notify, navigate, assets, project, mediaTaskId } = useApp();
  const [kind, setKind] = useState<'flow' | 'annotation' | 'media' | 'tracks'>(mediaTaskId ? 'media' : 'flow');
  useEffect(() => { if (mediaTaskId) setKind('media'); }, [mediaTaskId]);
  const [runs,setRuns]=useState<Run[]>([]);
  const [quality,setQuality]=useState(false);
  const [selected,setSelected]=useState<Run|null>(null);
  const [filter,setFilter]=useState('all'); const [search,setSearch]=useState('');
  const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const refresh=useCallback(async()=>{setLoading(true);try{const result=await request<Run[]>('run.list');setRuns(result);setError('');}catch(e){setError(errorMessage(e));}finally{setLoading(false);}},[]);
  useEffect(()=>{void refresh();},[refresh]);
  useEffect(()=>{if(!events.length)return;const timer=setTimeout(()=>{void refresh();if(selected)void request<Run>('run.get',{runId:selected.id}).then(setSelected).catch(()=>{});},180);return()=>clearTimeout(timer);},[events.at(-1)?.sequence,selected?.id,refresh]);
  async function control(action:string){if(!selected)return;setBusy(true);try{const run=await request<Run>(`run.${action}`,{runId:selected.id});setSelected(run);await refresh();notify(`操作已提交，任务状态：${stageNames[run.status]??run.status}。`);}catch(e){notify(errorMessage(e),true);}finally{setBusy(false);}}
  const visible=runs.filter(run=>(filter==='all'||(filter==='active'?['running','queued','paused','needs_attention'].includes(run.status):['completed','completed_with_errors','succeeded','failed','cancelled','partial'].includes(run.status)))&&`${run.model} ${run.id}`.toLowerCase().includes(search.toLowerCase()));
  const recent=events.filter(e=>!selected||e.runId===selected.id).slice(-35).reverse();
  return <div className="content tasks-page">{quality&&<QualityCenter onClose={()=>setQuality(false)}/>}<PageHeader title="任务中心" description="查看执行状态、样本结果与实际发生的事件" actions={<><Button onClick={()=>setQuality(true)}>评测与复核</Button>{kind==='annotation'&&<Button busy={loading} disabled={loading} onClick={()=>void refresh()}><RefreshCw size={14}/>刷新标注任务</Button>}<Button className="primary" onClick={()=>void navigate('workflow')}><PlusIcon/>创建任务</Button></>}/>
    <div className="tabs task-kind-tabs"><button className={kind==='flow'?'selected':''} onClick={()=>setKind('flow')}>流程运行</button><button className={kind==='annotation'?'selected':''} onClick={()=>setKind('annotation')}>标注任务</button><button className={kind==='media'?'selected':''} onClick={()=>setKind('media')}>素材处理</button><button className={kind==='tracks'?'selected':''} disabled={!project||!['detect','pose'].includes(project.taskType)} onClick={()=>setKind('tracks')}>轨迹候选</button></div>
    {kind==='tracks'?project&&<VideoTimeline key={project.id} project={project} tasksOnly/>:kind==='flow'?<FlowRuns projectId={project?.id}/>:kind==='media'?<MediaJobs initialJobId={mediaTaskId}/>:<><div className="section-toolbar"><div className="tabs">{[['all','全部任务'],['active','进行中'],['done','已结束']].map(([key,label])=><button key={key} className={filter===key?'selected':''} onClick={()=>setFilter(key)}>{label}</button>)}</div><SearchField placeholder="搜索模型或任务" value={search} onChange={setSearch}/></div>
    {error&&<p role="alert" className="inline-error">{error}</p>}
    <div className="tasks-layout"><div className="tasks-main">{loading?<div className="page-loading tasks-loading" role="status"><RefreshCw size={18} className="spin"/>正在读取标注任务…</div>:visible.length?<div className="run-list">{visible.map(run=>{const s=run.statistics??{};const total=s.total??run.total??0;const completed=s.completed??0;return <button key={run.id} className={`run-row ${selected?.id===run.id?'selected':''}`} onClick={()=>void request<Run>('run.get',{runId:run.id}).then(setSelected).catch(e=>notify(errorMessage(e),true))}><div className="run-icon"><Activity size={20}/></div><div className="run-summary"><strong>{String(run.name??run.model??'标注任务')}{run.kind==='local'&&' · 本地模型'}</strong><p>{run.createdAt?new Date(run.createdAt).toLocaleString('zh-CN'):'创建时间未知'}</p><div className="progress"><span style={{width:`${total?Math.min(100,completed/total*100):0}%`}}/></div><small>完成 {completed} / {total} · 成功 {s.succeeded??0}（含复用 {s.reused??0}）· 失败 {s.failed??0} · 已发送请求 {s.requestsUsed??'未知'}</small><InputProgressView statistics={s}/></div><span className="tiny-badge">{stageNames[run.status]??run.status}</span></button>;})}</div>:<Empty icon={<ListTodo size={28}/>} title="还没有运行任务" description={isDemo?'当前是浏览器演示，不生成模拟任务或进度。':'从流程编辑器启动你的第一个标注任务。'}><Button onClick={()=>void navigate('workflow')}>打开流程编辑器<ArrowUpRight size={14}/></Button></Empty>}
      {selected&&<section className="run-detail"><div className="section-toolbar"><h2>任务详情</h2><IconButton label="关闭任务详情" onClick={()=>setSelected(null)}><X size={15}/></IconButton></div><div className="run-controls"><Button busy={busy} disabled={!['running','queued'].includes(selected.status)} onClick={()=>void control('pause')}><Pause size={13}/>暂停</Button><Button busy={busy} disabled={selected.status!=='paused'} onClick={()=>void control('resume')}><Play size={13}/>恢复</Button><Button busy={busy} disabled={!['running','paused','queued'].includes(selected.status)} onClick={()=>void control('cancel')}><Square size={12}/>取消</Button><Button busy={busy} disabled={!(selected.statistics?.failed)} onClick={()=>void control('retry')}><RotateCcw size={13}/>重试失败样本</Button></div><p className="muted">{selected.kind==='local'?'本地模型任务不发送云端标注请求；执行与停止状态以引擎返回为准。':'已发送请求不能保证在远端撤销。结果未知的请求不会通过“重试失败样本”自动重发。'}</p><InputProgressView statistics={selected.statistics}/>{selected.kind==='local'&&<p className="muted tiny">固定模型版本：{selected.modelVersion??'未报告'} · 请求设备：{selected.device??'未报告'}</p>}<div className="run-counts">{[['在途请求','inFlight'],['已发送请求','requestsUsed'],['成功中复用','reused'],['等待重试','retry_wait'],['结果未知','unknown']].map(([label,key])=><div key={key}><span>{label}</span><strong>{selected.statistics?.[key]??'未知'}</strong></div>)}</div>{typeof selected.budgetScopeId==='string'&&<BudgetEditor key={selected.id} scopeId={selected.budgetScopeId}/>}<div className="sample-table"><div className="sample-row table-head"><span>样本</span><span>当前状态</span></div>{selected.samples?.map((sample,index)=><div className="sample-row" key={sample.id??`${sample.assetId}-${sample.inputId??index}`}><span>{sample.name??assets.find(a=>a.id===sample.assetId)?.name??sample.assetId}{sample.inputId&&<small className="sample-input-label">模型输入 {index+1}</small>}</span><span>{stageNames[sample.status]??sample.status}{sample.reused && (sample.inputReusedFrom ? ' · 输入结果复用（0 次 API 请求）' : ' · 复用成功（本样本 0 请求）')}</span>{(sample.inputId||sample.resultId)&&<div className="sample-input-action"><ModelInputResult inputId={sample.inputId} resultId={sample.resultId} name={sample.name??assets.find(a=>a.id===sample.assetId)?.name??'模型输入'}/></div>}{sample.inputReusedFrom ? <InputReuseSource source={sample.inputReusedFrom}/> : sample.reused && <ReuseProvenance source={sample.reusedFrom}/>}</div>)}</div></section>}
    </div><aside className="event-panel"><div className="section-toolbar"><h2>最近事件</h2><Clock3 size={14}/></div><p className="event-connection"><span className={`status-dot ${engine.state}`}/>{isDemo?'演示模式 · 未连接事件流':engine.state==='ready'?'引擎已连接':'事件连接中断'}</p>{recent.length?<ol className="timeline">{recent.map(event=><li key={event.sequence}><span className="event-dot"/><div><strong>{eventName(event.type)}</strong><time>{new Date(event.timestamp).toLocaleTimeString('zh-CN')}</time><details><summary>查看事件内容</summary><p className="event-raw-type">原始类型：{event.type}</p><pre>{JSON.stringify(event.payload,null,2)}</pre></details></div></li>)}</ol>:<div className="quiet-empty">暂无引擎事件<p>执行后将记录真实状态变化。</p></div>}</aside></div>
  </>} </div>;
}
function PlusIcon(){return <span aria-hidden="true" className="simple-plus">+</span>;}
