import { useEffect, useRef, useState } from 'react';
import type { TrackGeneration, TrackGenerationFrame, TrackGenerationInterval, TrackGenerationResults, TrackGenerationSection, TrackSkippedFrame } from '../../shared/tracks';
import { errorMessage } from './bridge';
import { Button, Notice } from './ui';
import { frameStates, generationActive, generationStates, TrackError, TrackIssues, trackRequest } from './trackUi';

export default function TrackGenerationPanel({ trackId, initialId, onSettled }: { trackId: string; initialId?: string; onSettled?: () => void }) {
  const [history, setHistory] = useState<TrackGeneration[]>([]), [total, setTotal] = useState(0), [offset, setOffset] = useState(0), [selected, setSelected] = useState(initialId ?? '');
  const [job, setJob] = useState<TrackGeneration | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [refresh, setRefresh] = useState(0);
  const settled = useRef(new Set<string>());
  useEffect(() => { setSelected(initialId ?? ''); setJob(null); setOffset(0); }, [trackId, initialId]);
  useEffect(() => { let live = true; void trackRequest('track.generation.list', { trackId, offset, limit: 20 }).then(result => { if (live) { setHistory(result.items); setTotal(result.total); setSelected(id => id || result.items[0]?.id || ''); } }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [trackId, offset, refresh]);
  useEffect(() => {
    if (!selected) return; let live = true, timer: ReturnType<typeof setTimeout>, sequence = -1;
    setJob(null); setError('');
    async function read() { try { const result = await trackRequest('track.generation.get', { generationId: selected }); if (!live) return; if (result.sequence >= sequence) { sequence = result.sequence; setJob(result); setError(''); } const active = generationActive(result.status); if (!active && !settled.current.has(result.id)) { settled.current.add(result.id); onSettled?.(); setRefresh(v => v + 1); } if (active) timer = setTimeout(() => void read(), 800); } catch (e) { if (live) { setError(errorMessage(e)); timer = setTimeout(() => void read(), 5000); } } }
    void read(); return () => { live = false; clearTimeout(timer); };
  }, [selected, refresh]);
  async function control(retry: boolean) { if (!job) return; setBusy(true); setError(''); try { const next = await trackRequest(retry ? 'track.generation.retry' : 'track.generation.cancel', { generationId: job.id }); setJob(next); setSelected(next.id); setRefresh(v => v + 1); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <section className="track-generation-panel"><div className="section-toolbar"><h3>候选生成记录</h3><Button disabled={busy} onClick={() => setRefresh(v => v + 1)}>刷新记录</Button></div>{history.length > 0 ? <><select aria-label="轨迹生成记录" value={selected} onChange={e => setSelected(e.target.value)}>{!history.some(v => v.id === selected) && selected && <option value={selected}>本次生成任务</option>}{history.map(item => <option key={item.id} value={item.id}>{new Date(item.createdAt).toLocaleString('zh-CN')} · {generationStates[item.status]} · {item.scope === 'all' ? '全部范围' : '受影响范围'}</option>)}</select><div className="pagination"><Button disabled={offset === 0} onClick={() => setOffset(v => Math.max(0, v - 20))}>上一页记录</Button><span>{offset + 1}–{offset + history.length} / {total}</span><Button disabled={offset + history.length >= total} onClick={() => setOffset(v => v + 20)}>下一页记录</Button></div></> : <p className="muted tiny">此轨迹还没有候选生成记录。</p>}
    {job && <div className="track-generation-detail"><div className="section-toolbar"><strong>{generationStates[job.status]}</strong><div className="actions"><Button busy={busy} disabled={!job.canCancel} onClick={() => void control(false)}>取消生成</Button>{['cancelled', 'interrupted', 'failed', 'completed_with_errors'].includes(job.status) && <Button busy={busy} onClick={() => void control(true)}>新建继续任务</Button>}</div></div><p>已处理 {job.progress.completed} / {job.progress.total} · 已保存 {job.progress.applied} · 保护 {job.progress.protected} · 冲突 {job.progress.conflicts} · 失败 {job.progress.failed}</p><progress max={Math.max(1, job.progress.total)} value={job.progress.completed}/><Notice>生成结果为待复核候选，不继承人工确认。人工版本和草稿继续受到保护。</Notice>{job.error && <TrackError error={`${job.error.code}：${job.error.message}`}/>}<details><summary>任务与固定范围</summary><p>轨迹版本 {job.trackVersion} · 时间轴版本 {job.timelineVersion}</p><p>范围：{job.scope === 'all' ? '全部' : '受影响区间'}</p><pre>{JSON.stringify({ generationId: job.id, parameters: job.parameters, summary: job.summary }, null, 2)}</pre></details>{!generationActive(job.status) && <GenerationResults key={`${job.id}-${job.sequence}`} generationId={job.id}/>}</div>}<TrackError error={error}/></section>;
}

function GenerationResults({ generationId }: { generationId: string }) {
  const [section, setSection] = useState<TrackGenerationSection>('frames'), [offset, setOffset] = useState(0), [result, setResult] = useState<TrackGenerationResults | null>(null), [error, setError] = useState('');
  useEffect(() => { let live = true; setResult(null); setError(''); void trackRequest('track.generation.results', { generationId, section, offset, limit: 20 }).then(value => { if (live) setResult(value); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [generationId, section, offset]);
  return <div className="track-generation-results"><div className="tabs">{[['frames', '逐帧结果'], ['intervals', '区间与阈值'], ['skipped', '跳过范围']].map(([value, label]) => <button key={value} className={section === value ? 'selected' : ''} onClick={() => { setSection(value as TrackGenerationSection); setOffset(0); }}>{label}</button>)}</div>{result?.section === section ? <><div className="track-result-list">{result.items.map((value, i) => {
    if (section === 'frames') { const frame = value as TrackGenerationFrame; return <article key={frame.frameId}><strong>帧 {frame.frameId} · {frameStates[frame.status]}</strong>{frame.requiresReview && <p className="text-error">需要人工复核或补齐属性</p>}{frame.candidateVersion !== undefined && <p>候选版本 {frame.candidateVersion}</p>}<TrackIssues issues={frame.reasons}/><details><summary>此帧贡献详情</summary><pre>{JSON.stringify(frame, null, 2)}</pre></details></article>; }
    if (section === 'intervals') { const interval = value as TrackGenerationInterval; return <article key={interval.intervalId}><strong>{interval.leftFrameId} → {interval.rightFrameId}</strong><p>{interval.blocked ? '区间被阻断' : interval.requiresReview ? '区间需复核' : '区间检查通过'}</p><TrackIssues issues={interval.reviewIssues}/><details><summary>实际阈值与区间诊断</summary><pre>{JSON.stringify(interval, null, 2)}</pre></details></article>; }
    const skipped = value as TrackSkippedFrame; return <article key={i}><strong>帧 {skipped.frameId} · {frameStates[skipped.annotationState]}</strong><p>{skipped.message}</p><details><summary>跳过原因</summary><pre>{JSON.stringify(skipped, null, 2)}</pre></details></article>;
  })}{result.items.length === 0 && <p className="muted tiny">此分类没有记录。</p>}</div><div className="pagination"><Button disabled={offset === 0} onClick={() => setOffset(v => Math.max(0, v - 20))}>上一页结果</Button><span>{result.total ? offset + 1 : 0}–{offset + result.items.length} / {result.total}</span><Button disabled={offset + result.items.length >= result.total} onClick={() => setOffset(v => v + 20)}>下一页结果</Button></div></> : !error && <p className="muted tiny">正在读取已保存的生成结果…</p>}<TrackError error={error}/></div>;
}
