import { useEffect, useState } from 'react';
import { FolderOpen, Plus, Trash2 } from 'lucide-react';
import type { MediaJob, VideoCreateRequest, VideoExtractionParameters, VideoInspection, VideoTimeRange } from '../../shared/media';
import { getBridge, request, errorMessage, isDemo } from './bridge';
import { Button, Field, IconButton, Modal, Notice } from './ui';
import { MediaError } from './mediaUi';

export default function VideoImport({ projectId, onClose, onCreated }: { projectId: string; onClose: () => void; onCreated: (job: MediaJob) => void }) {
  const [sourcePath, setSourcePath] = useState(''), [inspection, setInspection] = useState<VideoInspection | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [mode, setMode] = useState<VideoExtractionParameters['mode']>('interval'), [sampling, setSampling] = useState('1');
  const [whole, setWhole] = useState(true), [ranges, setRanges] = useState<VideoTimeRange[]>([{ start: 0, end: 1 }]);
  const [resize, setResize] = useState(false), [width, setWidth] = useState('640'), [height, setHeight] = useState('640'), [fit, setFit] = useState<'contain' | 'stretch'>('contain');
  const [format, setFormat] = useState<'png' | 'jpg'>('png'), [quality, setQuality] = useState('3');
  useEffect(() => { setError(''); }, [mode, sampling, whole, ranges, resize, width, height, fit, format, quality]);
  async function choose() {
    setBusy(true); setError('');
    try { const paths = await (await getBridge()).chooseFiles({ kind: 'video' }); if (!paths[0]) return; setSourcePath(paths[0]); setInspection(null); const info = await request<VideoInspection>('media.video.inspect', { sourcePath: paths[0] }); setInspection(info); setWhole(info.durationSeconds !== null); setRanges([{ start: 0, end: info.durationSeconds ?? 0 }]); }
    catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  function parameters(): VideoExtractionParameters {
    if (!inspection) throw new Error('请先选择并成功检查视频。');
    const selectedRanges = whole && inspection.durationSeconds !== null ? [{ start: 0, end: inspection.durationSeconds }] : ranges;
    if (!selectedRanges.length || selectedRanges.length > 32 || selectedRanges.some((r, i) => !Number.isFinite(r.start) || !Number.isFinite(r.end) || r.start < 0 || r.end > 604800 || r.end <= r.start || (inspection.durationSeconds !== null && r.end > inspection.durationSeconds) || (i > 0 && r.start < selectedRanges[i - 1].end))) throw new Error('时间段需按先后顺序填写：起点非负、终点大于起点、范围互不重叠，且不超过已知视频时长。');
    const value = Number(sampling); if (!Number.isFinite(value) || (mode === 'every_n' ? !Number.isSafeInteger(value) || value < 1 || value > 1000000 : value < .001 || value > (mode === 'fps' ? 240 : 604800))) throw new Error('间隔范围为 0.001～604800 秒；源帧间隔为 1～1000000 整数；目标帧率为 0.001～240。');
    const size = { width: Number(width), height: Number(height), fit };
    if (resize && (!Number.isSafeInteger(size.width) || !Number.isSafeInteger(size.height) || size.width < 1 || size.height < 1 || size.width > 20000 || size.height > 20000 || size.width * size.height > 40000000)) throw new Error('输出宽高需为 1～20000 的整数，且不超过 4000 万像素。');
    const jpegQuality = Number(quality); if (format === 'jpg' && (!Number.isInteger(jpegQuality) || jpegQuality < 2 || jpegQuality > 31)) throw new Error('JPEG 质量参数需为 2～31 的整数。');
    return { ranges: selectedRanges, streamIndex: inspection.streamIndex, ...(resize ? { outputSize: size } : {}), format, ...(format === 'jpg' ? { jpegQuality } : {}), ...(mode === 'interval' ? { mode, intervalSeconds: value } : mode === 'every_n' ? { mode, everyNFrames: value } : { mode, targetFps: value }) };
  }
  async function create() { setBusy(true); setError(''); try { const payload: VideoCreateRequest = { projectId, sourcePath, expectedSourceHash: inspection!.sourceHash, parameters: parameters() }; const job = await request<MediaJob>('media.video.create', { ...payload }); onCreated(job); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <Modal title="从视频抽取素材" onClose={() => { if (!busy) onClose(); }}><div className="form-stack video-import"><Button busy={busy} disabled={isDemo} onClick={() => void choose()}><FolderOpen size={14}/>选择并检查视频</Button>{inspection ? <div className="video-inspection"><strong>{inspection.sourceName}</strong><p>{inspection.width} × {inspection.height} · {inspection.durationSeconds === null ? '时长未知' : `${inspection.durationSeconds.toFixed(2)} 秒`}</p><p className="muted tiny">报告帧率：{inspection.reportedFrameRate ?? '未知'} · 报告帧数：{inspection.reportedFrameCount ?? '未知'}</p></div> : <p className="muted tiny">{sourcePath ? '该视频尚未完成检查。' : '选择本机视频，抽帧任务在后台执行。'}</p>}
    {inspection?.geometryNotice && <Notice>{inspection.geometryNotice}</Notice>}
    <div className="field-grid"><Field label="采样方式"><select aria-label="视频采样方式" disabled={busy} value={mode} onChange={e => { setMode(e.target.value as typeof mode); setSampling('1'); }}><option value="interval">每隔指定秒数</option><option value="every_n">每 N 个源帧</option><option value="fps">按目标帧率</option></select></Field><Field label={mode === 'interval' ? '间隔（秒）' : mode === 'every_n' ? '源帧间隔 N' : '目标帧率（帧/秒）'}><input aria-label="视频采样值" type="number" min={mode === 'every_n' ? 1 : 0.001} step={mode === 'every_n' ? 1 : 'any'} disabled={busy} value={sampling} onChange={e => setSampling(e.target.value)}/></Field></div>
    <details className="video-ranges" open={inspection?.durationSeconds === null ? true : undefined}><summary>时间范围 · {whole && inspection?.durationSeconds !== null ? '整段视频' : `${ranges.length} 个时间段`}</summary>{inspection?.durationSeconds === null && <Notice>视频时长未知，请明确填写抽帧时间范围。</Notice>}<label className="checkbox-row"><input type="checkbox" disabled={busy || !inspection || inspection.durationSeconds === null} checked={whole} onChange={e => setWhole(e.target.checked)}/>使用整段已知时长</label>{!whole && <><p className="muted tiny">单位为秒，相对首个实际源帧；包含起点，不包含终点。相邻时间段允许接续。</p>{ranges.map((range, i) => <div className="video-range-row" key={i}><Field label={`第 ${i + 1} 段起点`}><input aria-label={`视频时间段 ${i + 1} 起点`} type="number" min={0} step="any" disabled={busy} value={range.start} onChange={e => setRanges(list => list.map((r, index) => index === i ? { ...r, start: Number(e.target.value) } : r))}/></Field><Field label="终点"><input aria-label={`视频时间段 ${i + 1} 终点`} type="number" min={0} step="any" disabled={busy} value={range.end} onChange={e => setRanges(list => list.map((r, index) => index === i ? { ...r, end: Number(e.target.value) } : r))}/></Field><IconButton label={`移除时间段 ${i + 1}`} disabled={busy || ranges.length === 1} onClick={() => setRanges(list => list.filter((_, index) => i !== index))}><Trash2 size={14}/></IconButton></div>)}<Button disabled={busy || ranges.length >= 32} onClick={() => setRanges(list => [...list, { start: list.at(-1)?.end ?? 0, end: (list.at(-1)?.end ?? 0) + 1 }])}><Plus size={13}/>添加时间段</Button></>}</details>
    <details className="video-output-options"><summary>输出尺寸与格式</summary><label className="checkbox-row"><input type="checkbox" disabled={busy} checked={resize} onChange={e => setResize(e.target.checked)}/>指定输出尺寸</label>{resize && <><div className="field-grid"><Field label="宽度（像素）"><input aria-label="视频输出宽度" type="number" min={1} disabled={busy} value={width} onChange={e => setWidth(e.target.value)}/></Field><Field label="高度（像素）"><input aria-label="视频输出高度" type="number" min={1} disabled={busy} value={height} onChange={e => setHeight(e.target.value)}/></Field></div><Field label="适配方式"><select aria-label="视频尺寸适配" disabled={busy} value={fit} onChange={e => setFit(e.target.value as typeof fit)}><option value="contain">等比缩放并留边</option><option value="stretch">拉伸到指定尺寸</option></select></Field></>}<Field label="输出格式"><select aria-label="视频输出格式" disabled={busy} value={format} onChange={e => setFormat(e.target.value as typeof format)}><option value="png">PNG</option><option value="jpg">JPEG</option></select></Field>{format === 'jpg' && <Field label="JPEG 质量参数（2 高，31 低）"><input aria-label="视频JPEG质量" type="number" min={2} max={31} disabled={busy} value={quality} onChange={e => setQuality(e.target.value)}/></Field>}</details>
    <p className="muted tiny">抽帧完成后可预览帧记录，再明确导入项目素材。每 N 帧按全局源帧序号选择，按秒与目标帧率均从首个实际源帧建立采样网格。</p><MediaError error={error}/><div className="modal-actions"><Button disabled={busy} onClick={onClose}>取消</Button><Button className="primary" disabled={!inspection || isDemo} busy={busy} onClick={() => void create()}>创建抽帧任务</Button></div></div></Modal>;
}
