import { useCallback, useEffect, useState } from 'react';
import type { MediaJob } from '../../shared/media';
import type { Track, TrackAffectedScope, TrackFrame, TrackFramePage, TrackGeneration, TrackKeyframePage, TrackPage, TrackTimeline, TrackTimelineDetail } from '../../shared/tracks';
import type { Asset, Project } from './types';
import { errorMessage, request } from './bridge';
import { Button, Field, Loading } from './ui';
import QualityCanvas from './QualityCanvas';
import TrackKeyframeEditor from './TrackKeyframeEditor';
import TrackTools, { type TrackToolResult } from './TrackTools';
import TrackGenerationPanel from './TrackGenerationPanel';
import { frameStates, keyframeStates, TrackError, trackRequest } from './trackUi';

export default function VideoTimeline({ project, tasksOnly = false }: { project: Project; tasksOnly?: boolean }) {
  const [timelines, setTimelines] = useState<TrackPage<TrackTimeline>>({ items: [], total: 0 }), [offset, setOffset] = useState(0), [id, setId] = useState(''), [detail, setDetail] = useState<TrackTimelineDetail | null>(null);
  const [jobs, setJobs] = useState<MediaJob[]>([]), [jobOffset, setJobOffset] = useState(0), [jobTotal, setJobTotal] = useState(0), [jobId, setJobId] = useState('');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [refresh, setRefresh] = useState(0);
  useEffect(() => { setOffset(0); setId(''); setDetail(null); setJobId(''); setJobOffset(0); }, [project.id]);
  useEffect(() => { let live = true; setError(''); void trackRequest('track.timeline.list', { projectId: project.id, offset, limit: 50 }).then(result => { if (live) { setTimelines(result); setId(value => value || result.items[0]?.id || ''); } }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [project.id, offset, refresh]);
  useEffect(() => { if (!id) return; let live = true; setDetail(null); void trackRequest('track.timeline.get', { timelineId: id }).then(value => { if (live) setDetail(value); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [id, refresh]);
  useEffect(() => { if (tasksOnly) return; let live = true; void request<{ items: MediaJob[]; total: number }>('media.job.list', { projectId: project.id, kind: 'video_extract', offset: jobOffset, limit: 50 }).then(result => { if (live) { setJobs(result.items); setJobTotal(result.total); } }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [project.id, jobOffset, tasksOnly, refresh]);
  async function create() { if (!jobId) return; setBusy(true); setError(''); try { const timeline = await trackRequest('track.timeline.create', { projectId: project.id, mediaJobId: jobId }); setId(timeline.id); setRefresh(v => v + 1); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <section className="video-timeline"><div className="section-toolbar"><h2>{tasksOnly ? '轨迹候选任务' : '视频时间轴与轨迹'}</h2><Button disabled={busy} onClick={() => setRefresh(v => v + 1)}>刷新时间轴</Button></div><div className="timeline-picker"><Field label="时间轴"><select aria-label="视频时间轴" value={id} disabled={busy} onChange={e => setId(e.target.value)}><option value="">选择时间轴</option>{id && !timelines.items.some(t => t.id === id) && <option value={id}>{detail?.name ?? '当前时间轴'}</option>}{timelines.items.map(t => <option key={t.id} value={t.id}>{t.name} · {t.frameCount} 帧 · {new Date(t.createdAt).toLocaleString('zh-CN')}</option>)}</select></Field><div className="pagination"><Button disabled={offset === 0} onClick={() => setOffset(v => Math.max(0, v - 50))}>前一页时间轴</Button><span>{timelines.total} 个</span><Button disabled={offset + timelines.items.length >= timelines.total} onClick={() => setOffset(v => v + 50)}>后一页时间轴</Button></div></div>
    {!tasksOnly && <details className="timeline-create" open={!timelines.total}><summary>从已导入视频帧建立时间轴</summary><p className="muted tiny">每个抽帧任务单独建立时间轴，并固定当前模板；同一视频的不同抽帧批次不会合并。</p><div className="timeline-create-row"><select aria-label="时间轴来源抽帧任务" disabled={busy} value={jobId} onChange={e => setJobId(e.target.value)}><option value="">选择已入库的抽帧任务</option>{jobs.map(job => <option key={job.id} disabled={!job.assetsCommitted || job.status !== 'completed'} value={job.id}>{job.sourceName ?? '视频抽帧'} · {new Date(job.createdAt).toLocaleString('zh-CN')}{job.assetsCommitted ? ' · 已入库' : ' · 尚未入库'}</option>)}</select><Button disabled={!jobId} busy={busy} onClick={() => void create()}>建立时间轴</Button></div>{jobTotal > 50 && <div className="pagination"><Button disabled={jobOffset === 0} onClick={() => setJobOffset(v => Math.max(0, v - 50))}>前一页视频任务</Button><Button disabled={jobOffset + jobs.length >= jobTotal} onClick={() => setJobOffset(v => v + 50)}>后一页视频任务</Button></div>}</details>}
    {detail?.id === id ? <TimelineWorkspace key={detail.id} timeline={detail} tasksOnly={tasksOnly} onTimelineChanged={() => setRefresh(v => v + 1)}/> : id && !error ? <Loading compact label="正在读取固定时间轴…" /> : null}<TrackError error={error}/></section>;
}

function TimelineWorkspace({ timeline, tasksOnly, onTimelineChanged }: { timeline: TrackTimelineDetail; tasksOnly: boolean; onTimelineChanged: () => void }) {
  const [tracks, setTracks] = useState<TrackPage<Track>>({ items: [], total: 0 }), [trackOffset, setTrackOffset] = useState(0), [trackId, setTrackId] = useState(''), [track, setTrack] = useState<Track | null>(null);
  const [pageRequest, setPageRequest] = useState<{ offset: number } | { aroundFrameId: string }>({ offset: 0 }), [frames, setFrames] = useState<TrackFramePage | null>(null), [frameId, setFrameId] = useState(''), [pageInput, setPageInput] = useState('1');
  const [keys, setKeys] = useState<TrackKeyframePage | null>(null), [keyOffset, setKeyOffset] = useState(0), [keyRefresh, setKeyRefresh] = useState(0), [refresh, setRefresh] = useState(0), [editing, setEditing] = useState(false);
  const [creating, setCreating] = useState(false), [name, setName] = useState(''), [classId, setClassId] = useState(timeline.template.classes[0]?.id ?? ''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [generation, setGeneration] = useState<TrackGeneration | null>(null), [affected, setAffected] = useState<TrackAffectedScope | null>(null);
  const frame = frames?.items.find(f => f.frameId === frameId) ?? frames?.items[0];
  const refreshData = useCallback(() => { setRefresh(v => v + 1); }, []);
  useEffect(() => { let live = true; void trackRequest('track.list', { timelineId: timeline.id, offset: trackOffset, limit: 50, includeArchived: true }).then(result => { if (live) { setTracks(result); setTrackId(value => value || result.items.find(t => t.status === 'active')?.id || result.items[0]?.id || ''); } }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [timeline.id, timeline.version, trackOffset, refresh]);
  useEffect(() => { if (!trackId) return; let live = true; setTrack(null); void trackRequest('track.get', { trackId }).then(value => { if (live) setTrack(value); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [trackId, refresh]);
  useEffect(() => { if (tasksOnly) return; let live = true; setFrames(null); void trackRequest('track.timeline.frames', { timelineId: timeline.id, ...(trackId ? { trackId } : {}), ...pageRequest, limit: 50 }).then(result => { if (live) { setFrames(result); setPageInput(String(Math.floor(result.offset / 50) + 1)); } }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [timeline.id, timeline.version, trackId, pageRequest, refresh, tasksOnly]);
  useEffect(() => { if (!trackId || tasksOnly) return; let live = true; setKeys(null); void trackRequest('track.keyframe.list', { trackId, offset: keyOffset, limit: 20, ...(frame?.frameId ? { aroundFrameId: frame.frameId } : {}) }).then(value => { if (live) setKeys(value); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [trackId, frame?.frameId, keyOffset, keyRefresh, refresh, tasksOnly]);
  function changed(result: TrackToolResult) { setTrackId(result.trackId); setAffected(result.affected ?? null); setGeneration(result.generation ?? null); setEditing(false); setError(''); refreshData(); }
  async function createTrack() { setBusy(true); setError(''); try { const created = await trackRequest('track.create', { timelineId: timeline.id, timelineVersion: timeline.version, classId, ...(name.trim() ? { name: name.trim() } : {}) }); setTrackId(created.id); setCreating(false); setName(''); refreshData(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function edit() { if (!frame || !track || track.id !== trackId) return; setBusy(true); setError(''); try { const exact = await trackRequest('track.timeline.frames', { timelineId: timeline.id, trackId: track.id, aroundFrameId: frame.frameId, limit: 1 }); if (exact.items[0]?.frameId !== frame.frameId) throw new Error('目标帧已不可用，请刷新时间轴。'); setFrames(previous => previous ? { ...previous, items: previous.items.map(item => item.frameId === frame.frameId ? exact.items[0] : item) } : previous); setEditing(true); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  function jump(id: string) { setFrameId(id); if (!frames?.items.some(f => f.frameId === id)) setPageRequest({ aroundFrameId: id }); }
  async function removeKey() { if (!track || track.id !== trackId || !frame?.keyframe) return; setBusy(true); setError(''); try { const result = await trackRequest('track.keyframe.delete', { trackId: track.id, baseVersion: track.version, timelineVersion: timeline.version, keyframeId: frame.keyframe.keyframeId }); changed({ trackId: result.track.id, affected: result.affected, generation: result.generation }); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <div className="timeline-workspace"><div className="timeline-track-picker"><Field label="对象轨迹"><select aria-label="对象轨迹" value={trackId} onChange={e => { setTrackId(e.target.value); setTrack(null); setFrames(null); setKeys(null); setEditing(false); setGeneration(null); setAffected(null); setKeyOffset(0); }}><option value="">选择轨迹</option>{trackId && !tracks.items.some(t => t.id === trackId) && <option value={trackId}>{track?.name ?? '当前轨迹'}</option>}{tracks.items.map(t => <option key={t.id} value={t.id}>{t.name}{t.status === 'active' ? '' : t.status === 'deleted' ? ' · 已删除' : ' · 已拆分或合并'}</option>)}</select></Field>{!tasksOnly && <Button onClick={() => setCreating(v => !v)}>新建对象轨迹</Button>}{tracks.total > 50 && <div className="pagination"><Button disabled={trackOffset === 0} onClick={() => setTrackOffset(v => Math.max(0, v - 50))}>前一页轨迹</Button><Button disabled={trackOffset + tracks.items.length >= tracks.total} onClick={() => setTrackOffset(v => v + 50)}>后一页轨迹</Button></div>}</div>
    {creating && <div className="track-create-form"><Field label="轨迹名称"><input aria-label="新轨迹名称" maxLength={200} value={name} onChange={e => setName(e.target.value)} placeholder="例如：行人 A"/></Field><Field label="固定模板类别"><select aria-label="新轨迹类别" value={classId} onChange={e => setClassId(e.target.value)}>{timeline.template.classes.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Button className="primary" busy={busy} disabled={!classId} onClick={() => void createTrack()}>创建轨迹</Button></div>}
    {!tasksOnly && <>{frames ? <><div className="timeline-frame-strip">{frames.items.map((item, i) => <button key={item.frameId} className={`${frame?.frameId === item.frameId ? 'selected' : ''} ${i > 0 && frames.items[i - 1].rangeIndex !== item.rangeIndex ? 'range-start' : ''}`} aria-label={`选择视频帧 ${item.frameId}`} onClick={() => setFrameId(item.frameId)}><strong>{item.timeSeconds.toFixed(3)} 秒</strong><small>源帧 {item.sourcePresentationIndex}</small><span>{item.keyframe ? `◆ ${keyframeStates[item.keyframe.state]}` : item.protected ? '人工 / 草稿保护' : frameStates[item.annotationState]}</span><small>{item.sceneId === null ? '场景未检查' : `场景 ${item.sceneId}`}</small></button>)}</div><div className="pagination"><Button disabled={frames.offset === 0} onClick={() => { setFrameId(''); setPageRequest({ offset: Math.max(0, frames.offset - 50) }); }}>上一页帧</Button><span>{frames.total ? frames.offset + 1 : 0}–{frames.offset + frames.items.length} / {frames.total}</span><input aria-label="视频帧页码" type="number" min={1} max={Math.max(1, Math.ceil(frames.total / 50))} value={pageInput} onChange={e => setPageInput(e.target.value)}/><Button onClick={() => { const n = Number(pageInput); if (Number.isInteger(n) && n >= 1 && n <= Math.ceil(frames.total / 50)) { setFrameId(''); setPageRequest({ offset: (n - 1) * 50 }); } }}>跳转帧页</Button><Button disabled={frames.offset + frames.items.length >= frames.total} onClick={() => { setFrameId(''); setPageRequest({ offset: frames.offset + 50 }); }}>下一页帧</Button></div></> : <Loading compact label="正在读取真实视频帧…" />}
    {frame && <div className="timeline-editor-columns"><section><FramePreview key={frame.frameId} frame={frame} timeline={timeline}/><div className="actions"><Button disabled={busy || !track || track.status !== 'active'} onClick={() => void edit()}>{frame.keyframe ? '编辑此帧关键帧' : '将此帧设为关键帧'}</Button>{frame.keyframe && <Button busy={busy} disabled={track?.status !== 'active'} onClick={() => void removeKey()}>移除关键帧边界</Button>}<Button disabled={!keys?.previous} onClick={() => keys?.previous && jump(keys.previous.frameId)}>上一关键帧</Button><Button disabled={!keys?.next} onClick={() => keys?.next && jump(keys.next.frameId)}>下一关键帧</Button></div><small className="muted">移除关键帧只更改轨迹边界，已保存的人工标注继续保留。</small><SceneEditor key={`${timeline.version}-${frame.frameId}`} timeline={timeline} frame={frame} frames={frames?.items ?? []} onChanged={onTimelineChanged}/></section><aside>{track?.id === trackId && <TrackTools key={`${track.id}-${track.version}-${timeline.version}`} timeline={timeline} track={track} frame={frame} tracks={tracks.items} onChanged={changed}/>}<details className="track-keyframe-list"><summary>关键帧列表 · {keys?.total ?? 0}</summary>{keys?.items.map(item => <button key={item.keyframeId} onClick={() => jump(item.frameId)}>{item.timeSeconds.toFixed(3)} 秒 · {keyframeStates[item.state]}</button>)}{keys && <div className="pagination"><Button disabled={keyOffset === 0} onClick={() => { setKeyOffset(v => Math.max(0, v - 20)); setKeyRefresh(v => v + 1); }}>上一页关键帧</Button><Button disabled={keyOffset + keys.items.length >= keys.total} onClick={() => { setKeyOffset(v => v + 20); setKeyRefresh(v => v + 1); }}>下一页关键帧</Button></div>}</details></aside></div>}</>}
    {affected && <div className="track-affected"><p>本次变更影响 {affected.affectedFrameIds.length} 帧 · 保护 {affected.protectedFrames.length} 帧{affected.requiresRecompute ? ' · 需要重新生成候选' : ''}</p><details><summary>受影响区间与保护范围</summary><pre>{JSON.stringify(affected, null, 2)}</pre></details></div>}{(generation || track) && <TrackGenerationPanel key={generation?.trackId ?? track!.id} trackId={generation?.trackId ?? track!.id} initialId={generation?.id} onSettled={refreshData}/>}<TrackError error={error}/>
    {editing && track && frame && <TrackKeyframeEditor timeline={timeline} track={track} frame={frame} onClose={() => { setEditing(false); refreshData(); }} onSaved={result => changed({ trackId: result.track.id, affected: result.affected, generation: result.generation })}/>}<details className="timeline-identity"><summary>时间轴与固定模板</summary><p>{timeline.frameCount} 帧 · {timeline.width} × {timeline.height} · 模板固定于时间轴建立时</p><pre>{JSON.stringify({ timelineId: timeline.id, mediaJobId: timeline.mediaJobId, sourceVideoId: timeline.sourceVideoId, version: timeline.version, templateHash: timeline.templateHash, template: timeline.template }, null, 2)}</pre></details></div>;
}

function FramePreview({ frame, timeline }: { frame: TrackFrame; timeline: TrackTimelineDetail }) {
  const [asset, setAsset] = useState<Asset | null>(null), [error, setError] = useState('');
  useEffect(() => { let live = true; setAsset(null); void request<Asset>('asset.get', { assetId: frame.assetId }).then(value => { if (value.contentHash !== frame.contentHash || value.width !== frame.width || value.height !== frame.height) throw new Error('基准帧与固定时间轴内容不一致。'); if (live) setAsset(value); }).catch(e => { if (live) setError(errorMessage(e)); }); return () => { live = false; }; }, [frame.assetId, frame.contentHash]);
  return <div className="timeline-frame-preview"><div className="section-toolbar"><strong>{frame.timeSeconds.toFixed(3)} 秒 · 源帧 {frame.sourcePresentationIndex}</strong><span>{frameStates[frame.annotationState]}{frame.draftSavedAt ? ' · 有草稿' : ''}</span></div>{asset?.mediaUrl ? <QualityCanvas mediaUrl={asset.mediaUrl} width={frame.width} height={frame.height} annotations={frame.keyframe?.annotation ? [frame.keyframe.annotation] : []} taskType={timeline.taskType} classes={timeline.template.classes} keypointConnections={timeline.template.settings.keypointConnections} templateSettings={timeline.template.settings} title={frame.keyframe ? `固定关键帧 · ${keyframeStates[frame.keyframe.state]}` : '此帧尚无当前轨迹的关键帧'}/> : !error && <p className="muted">正在核对固定帧图像…</p>}<details><summary>真实帧时间与身份</summary><pre>{JSON.stringify({ frameId: frame.frameId, sourceFrameId: frame.sourceFrameId, sourcePts: frame.sourcePts, originPts: frame.originPts, relativePts: frame.relativePts, timeBase: frame.timeBase, rangeIndex: frame.rangeIndex, sceneId: frame.sceneId, annotationVersion: frame.annotationVersion, draftSavedAt: frame.draftSavedAt }, null, 2)}</pre></details><TrackError error={error}/></div>;
}

function SceneEditor({ timeline, frame, frames, onChanged }: { timeline: TrackTimelineDetail; frame: TrackFrame; frames: TrackFrame[]; onChanged: () => void }) {
  const [endId, setEndId] = useState(frame.frameId), [endInput, setEndInput] = useState(frame.frameId), [sceneId, setSceneId] = useState(frame.sceneId ?? ''), [unknown, setUnknown] = useState(frame.sceneId === null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { setEndId(frame.frameId); setEndInput(frame.frameId); setSceneId(frame.sceneId ?? ''); setUnknown(frame.sceneId === null); }, [frame.frameId, frame.sceneId]);
  async function save() { setBusy(true); setError(''); try { await trackRequest('track.timeline.update', { timelineId: timeline.id, baseVersion: timeline.version, scenes: [{ startFrameId: frame.frameId, endFrameId: endId, sceneId: unknown ? null : sceneId.trim() }] }); onChanged(); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function locateEnd() {
    const candidate = endInput.trim();
    if (!candidate) { setError('请输入区间终点帧 ID。'); return; }
    setBusy(true); setError('');
    try {
      const result = await trackRequest('track.timeline.frames', { timelineId: timeline.id, aroundFrameId: candidate, limit: 1 });
      if (result.items[0]?.frameId !== candidate) throw new Error('没有找到完全匹配的终点帧 ID，请从时间轴帧列表复制。');
      setEndId(candidate);
    } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); }
  }
  return <details className="scene-editor"><summary>人工标记场景区间</summary><p className="muted tiny">起点为当前帧，两端均包含。可直接输入任意已入库帧 ID，跨分页也会先向引擎核对；未检查的场景保留“未检查”。</p><Field label="区间终点（帧 ID）"><div className="scene-end-input"><input aria-label="场景区间终点帧 ID" value={endInput} disabled={busy} onChange={e => { setEndInput(e.target.value); if (e.target.value === endId) return; setEndId(''); }} placeholder="例如 frame-000120"/><Button disabled={busy || !endInput.trim()} onClick={() => void locateEnd()}>定位</Button></div></Field>{frames.length > 0 && <Field label="当前页快速选择"><select aria-label="当前页场景区间终点" value={frames.some(item => item.frameId === endId) ? endId : ''} disabled={busy} onChange={e => { setEndId(e.target.value); setEndInput(e.target.value); }}>{frames.map(item => <option key={item.frameId} value={item.frameId}>{item.timeSeconds.toFixed(3)} 秒 · 源帧 {item.sourcePresentationIndex}</option>)}</select></Field>}<p className="muted tiny">当前终点：{endId || '尚未定位'}</p><label className="checkbox-row"><input type="checkbox" aria-label="场景尚未检查" checked={unknown} disabled={busy} onChange={e => setUnknown(e.target.checked)}/>场景尚未检查</label>{!unknown && <Field label="场景名称"><input aria-label="场景名称" value={sceneId} disabled={busy} maxLength={128} onChange={e => setSceneId(e.target.value)} placeholder="例如：路口镜头 A"/></Field>}<Button busy={busy} disabled={!endId || (!unknown && !sceneId.trim())} onClick={() => void save()}>保存场景区间</Button><TrackError error={error}/></details>;
}
