import { useEffect, useRef, useState } from 'react';
import { Upload, Box, UserRound, Download, Plus, ArrowUp, ArrowDown, Trash2, Play, Save, FolderOpen, Filter } from 'lucide-react';
import { defaultFlow, STEP_LABELS, type FlowCapabilities, type FlowDefinition, type FlowExecution, type FlowInput, type FlowPreflight, type FlowRun, type FlowStartRequest, type StepKind } from '../../shared/flow';
import { resolveConfiguration } from '../../shared/configuration';
import type { LibraryResource } from '../../shared/resources';
import { useApp } from './context';
import { request, errorMessage, isDemo } from './bridge';
import { Button, Field, IconButton, Modal, Notice, PageHeader } from './ui';
import type { Project } from './types';
import FlowParameters from './FlowParameters';
import { ArtifactPicker } from './FlowArtifacts';
import FlowRuns from './FlowRuns';
import { transformParameterIssues } from './TransformParametersEditor';

const icons = { import: Upload, api: Box, review: UserRound, export: Download, filter: Filter, transform: Box, local: Box };
const descriptions: Record<StepKind, string> = { import: '导入后固定本次输入', filter: '按状态、尺寸和内容筛选', api: '生成独立候选并保留人工版本', review: '建立问题或抽查清单，等待人工放行', export: '从固定版本生成数据集', transform: '按顺序裁剪、缩放与切片', local: '使用本地模型生成独立候选' };
type InputScope = 'all' | 'unlabeled' | 'page' | 'selected' | 'artifact';
const count = (value: number | null) => value === null ? '执行后确定' : String(value);
export default function Workflow() {
  const { project, assets, assetTotal, selectedAssetIds, prefs, engine, notify, guard, setProject, syncWindowDirtySource } = useApp();
  const [flow, setFlow] = useState<FlowDefinition>(() => project?.settings.flow as FlowDefinition ?? defaultFlow());
  const saved = useRef(structuredClone(flow));
  const [dirty, setDirty] = useState(false), [selected, setSelected] = useState(flow.steps.find(s => s.kind === 'api')?.id ?? flow.steps[0]?.id ?? '');
  const [tab, setTab] = useState<'edit' | 'runs'>('edit'), [runId, setRunId] = useState('');
  const [scope, setScope] = useState<InputScope>('all'), [artifactId, setArtifactId] = useState(''), [mode, setMode] = useState<'all' | 'single'>('all');
  const [maxRequests, setMaxRequests] = useState(() => String(resolveConfiguration('annotation', prefs, project?.settings).maxRequests ?? ''));
  const [failurePolicy, setFailurePolicy] = useState<'continue' | 'pause'>('pause');
  const [capabilities, setCapabilities] = useState<FlowCapabilities | null>(null), [capabilityError, setCapabilityError] = useState('');
  const [busy, setBusy] = useState(false), [adding, setAdding] = useState(false), [error, setError] = useState('');
  const [resource, setResource] = useState<LibraryResource | null>(null), [templates, setTemplates] = useState<LibraryResource[] | null>(null);
  const [preflight, setPreflight] = useState<{ fingerprint: string; result: FlowPreflight } | null>(null);
  const step = flow.steps.find(s => s.id === selected), enabled = flow.steps.filter(s => s.enabled);
  const needsArtifact = mode === 'single' && enabled[0]?.id !== selected;
  useEffect(() => { let live = true; setCapabilities(null); if (isDemo) { setCapabilityError('浏览器演示不执行流程，请使用桌面引擎。'); return; } void request<FlowCapabilities>('flow.capabilities').then(c => { if (live) { setCapabilities(c); setCapabilityError(''); } }).catch(e => { if (live) setCapabilityError(`流程执行能力不可用：${errorMessage(e)}`); }); return () => { live = false; }; }, [engine.state]);
  useEffect(() => { if (!dirty) return; const beforeLeave = async () => { throw new Error('流程有未保存修改，请先保存流程，或点击“放弃流程修改”。'); }; guard.current = beforeLeave; return () => { if (guard.current === beforeLeave) guard.current = null; }; }, [dirty, guard]);
  useEffect(() => { syncWindowDirtySource('workflow', dirty); return () => syncWindowDirtySource('workflow', false); }, [dirty, syncWindowDirtySource]);
  function change(next: FlowDefinition) { setFlow(next); setDirty(true); setError(''); }
  function parameter(key: string, value: unknown) { change({ ...flow, steps: flow.steps.map(s => { if (s.id !== selected) return s; const p = { ...s.parameters }; if (value === undefined) delete p[key]; else p[key] = value; if (key === 'providerId') delete p.model; return { ...s, parameters: p }; }) }); }
  function move(delta: number) { const steps = [...flow.steps], index = steps.findIndex(s => s.id === selected), other = index + delta; if (other < 0 || other >= steps.length) return; [steps[index], steps[other]] = [steps[other], steps[index]]; change({ ...flow, steps }); }
  // 模板保留继承关系；执行前按统一规则固定各 API 节点的实际配置。
  const definition: FlowDefinition = { ...flow, steps: flow.steps.map(s => {
    if (s.kind === 'api') { const resolved = resolveConfiguration('annotation', prefs, project?.settings, s.parameters), p = { ...s.parameters }; for (const key of ['providerId', 'model', 'prompt', 'concurrency', 'maxRequests'] as const) { const value = resolved[key]; if (value == null || value === '') delete p[key]; else p[key] = value; } return { ...s, parameters: p }; }
    if (s.kind === 'review') return { ...s, parameters: { ...s.parameters, buildIssues: s.parameters.buildIssues !== false, waitForHuman: s.parameters.waitForHuman !== false } };
    if (s.kind === 'export' && !s.parameters.outputDir) { const p = { ...s.parameters }; delete p.outputDir; return { ...s, parameters: p }; }
    return s;
  }) };
  const input: FlowInput = scope === 'artifact' ? { source: 'artifact', artifactId } : scope === 'all' || scope === 'unlabeled' ? { source: 'project', selection: scope } : { source: 'project', selection: 'explicit', assetIds: scope === 'page' ? assets.map(a => a.id) : [...selectedAssetIds] };
  const execution: FlowExecution = mode === 'single' ? { mode, stepId: selected } : { mode };
  const candidate: FlowStartRequest = { projectId: project?.id ?? '', definition, input, execution, failurePolicy, ...(maxRequests ? { maxRequests: Number(maxRequests) } : {}) };
  const fingerprint = JSON.stringify(candidate), checked = preflight?.fingerprint === fingerprint ? preflight.result : null;
  const orderIssues = enabled.flatMap((s, i) => s.kind === 'import' && i !== 0 ? [{ stepId: s.id, message: '导入必须是第一个启用步骤。' }] : s.kind === 'export' && i !== enabled.length - 1 ? [{ stepId: s.id, message: '导出必须是最后一个启用步骤。' }] : []);
  async function check() { setBusy(true); setError(''); setPreflight(null); try { if (!project) throw new Error('请先打开项目。'); for (const s of definition.steps.filter(s => s.enabled && s.kind === 'transform')) { const issues = transformParameterIssues(s.parameters); if (issues.length) throw new Error(`图像处理参数待完善：${issues.join(' ')}`); } if (definition.steps.some(s => s.enabled && s.kind === 'export' && s.parameters.trainRatio !== undefined && (!Number.isFinite(Number(s.parameters.trainRatio)) || Number(s.parameters.trainRatio) <= 0 || Number(s.parameters.trainRatio) >= 1))) throw new Error('训练集比例必须大于 0 且小于 1。'); if (needsArtifact && scope !== 'artifact') throw new Error('非首步单独执行必须明确选择兼容的固定产物，不会隐式执行前驱。'); if (scope === 'artifact' && !artifactId) throw new Error('请选择固定输入产物。'); const result = await request<FlowPreflight>('flow.preflight', candidate as unknown as Record<string, unknown>); setPreflight({ fingerprint, result }); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function start() { if (!checked?.canStart) return; setBusy(true); setError(''); try { const run = await request<FlowRun>('flow.create', candidate as unknown as Record<string, unknown>); setRunId(run.id); setTab('runs'); notify('流程运行已创建，后续状态由引擎记录。'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function save() { setBusy(true); setError(''); try { const result = await request<LibraryResource>('resource.save', { ...(resource ? { id: resource.id, baseVersion: resource.version ?? 0 } : {}), kind: 'flow', name: flow.name, content: flow }); setResource(result); if (project) setProject(await request<Project>('project.update', { projectId: project.id, settings: { flow } })); saved.current = structuredClone(flow); setDirty(false); notify('流程定义已保存。'); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  function load(template: LibraryResource) { try { const next = typeof template.content === 'string' ? JSON.parse(template.content) : template.content; if (next?.version !== 1 || !Array.isArray(next.steps) || next.steps.some((s: { kind: StepKind }) => !(s.kind in STEP_LABELS))) throw new Error('资源不是受支持的流程定义。'); setFlow(next); saved.current = structuredClone(next); setResource(template); setDirty(false); setSelected(next.steps[0]?.id ?? ''); setTemplates(null); setPreflight(null); } catch (e) { setError(errorMessage(e)); } }
  return <div className="workflow-page"><PageHeader title="流程编辑器" description="固定输入、逐步执行，并保留每次运行的产物" actions={<><Button disabled={busy || dirty} onClick={() => void request<LibraryResource[]>('resource.list', { kind: 'flow', limit: 100 }).then(setTemplates).catch(e => setError(errorMessage(e)))}><FolderOpen size={14}/>载入模板</Button>{dirty && <Button disabled={busy} onClick={() => { setFlow(structuredClone(saved.current)); setDirty(false); setSelected(saved.current.steps[0]?.id ?? ''); }}>放弃流程修改</Button>}<Button busy={busy} onClick={() => void save()}><Save size={14}/>保存流程</Button></>}/><div className="tabs flow-view-tabs"><button className={tab === 'edit' ? 'selected' : ''} onClick={() => setTab('edit')}>编辑流程</button><button className={tab === 'runs' ? 'selected' : ''} onClick={() => setTab('runs')}>运行记录</button></div>{capabilityError && <div className="flow-capability-notice"><Notice>{isDemo ? '浏览器仅提供流程编辑预览，请打开桌面应用执行流程。' : /command_not_implemented|unknown_command/.test(capabilityError) ? '当前引擎不支持流程执行。请更新并重启桌面应用；现有流程仍可编辑和保存。' : '流程引擎暂不可用。请检查引擎连接并重启应用；现有流程仍可编辑和保存。'}{!isDemo && <details><summary>诊断详情</summary><p className="break-word">{capabilityError}</p></details>}</Notice></div>}{error && <p className="inline-error" role="alert">{error}</p>}
    {tab === 'runs' ? <FlowRuns projectId={project?.id} initialRunId={runId}/> : <><section className="flow-input-panel">
      <div className="flow-entry-row">
        <Field label="流程输入范围"><select aria-label="流程输入范围" disabled={busy} value={scope} onChange={e => { setScope(e.target.value as InputScope); setArtifactId(''); }}><option value="all">全项目 · {assetTotal} 张</option><option value="unlabeled">全项目未标注素材 · 预检统计</option><option value="page">当前页 · {assets.length} 张</option><option value="selected">已勾选（跨页）· {selectedAssetIds.length} 张</option><option value="artifact">固定上游产物</option></select></Field>
        <Field label="执行方式"><select aria-label="流程执行方式" disabled={busy} value={mode} onChange={e => setMode(e.target.value as 'all' | 'single')}><option value="all">运行全部启用步骤</option><option value="single">只运行当前步骤</option></select></Field>
        <Field label="共享请求上限 · API 必填"><input aria-label="流程共享请求上限" title="API 节点及重试共用此上限" disabled={busy} type="number" min={1} max={1000000} value={maxRequests} onChange={e => setMaxRequests(e.target.value)} placeholder="请明确设置"/></Field>
        <div className="actions"><Button disabled={busy || !capabilities || !project} onClick={() => void check()}>预检当前流程</Button><Button className="primary" disabled={busy || !checked?.canStart || !capabilities} onClick={() => void start()}><Play size={14}/>{mode === 'single' ? '执行当前单步' : '运行完整流程'}</Button></div>
      </div>
      <details className="flow-run-options"><summary>更多运行选项</summary><Field label="样本失败后的策略"><select disabled={busy} value={failurePolicy} onChange={e => setFailurePolicy(e.target.value as 'continue' | 'pause')}><option value="pause">暂停并检查失败</option><option value="continue">继续处理其余样本</option></select></Field></details>
      {scope === 'artifact' && project && <ArtifactPicker projectId={project.id} value={artifactId} onChange={setArtifactId} disabled={busy || !capabilities}/>}
      {needsArtifact && <p className="muted tiny">当前单步有前驱，必须明确选择兼容的固定产物作为输入。</p>}
      {preflight && !checked && <p className="muted tiny">配置或范围已变化，请重新预检。</p>}
      {checked && <details className="flow-preflight" key={preflight?.fingerprint}><summary><strong>{checked.canStart ? '预检通过' : '预检尚未通过'}</strong><span>输入 {count(checked.inputCount)} 张 · 计划请求 {count(checked.plannedRequests)} · 含重试最多 {count(checked.estimatedMaxRequests)}</span><span>{checked.issues.length ? checked.issues.length + ' 项提示 · 展开查看' : '查看步骤详情'}</span></summary><div className="flow-preflight-details"><p>受人工保护 {checked.manualProtectedCount} 张</p>{checked.steps.map(s => <p key={s.stepId}>{STEP_LABELS[s.kind]}{s.enabled ? '' : '（停用）'}：输入 {count(s.inputCount)} · 请求 {count(s.plannedRequests)}</p>)}{checked.issues.map((issue, i) => <div className={`flow-issue ${issue.severity}`} key={i}><span>{issue.stepId && `${STEP_LABELS[flow.steps.find(s => s.id === issue.stepId)?.kind ?? 'review']}：`}{issue.message}<small>{issue.code}</small></span></div>)}</div></details>}
    </section><div className="workflow-layout"><div className="flow-stage"><input className="flow-name" aria-label="流程名称" maxLength={200} disabled={busy} value={flow.name} onChange={e => change({ ...flow, name: e.target.value })}/><div className="flow-nodes">{flow.steps.map((item, i) => { const Icon = icons[item.kind]; return <div className="flow-item" key={item.id}>{i > 0 && <div className="flow-connector"/>}<button disabled={busy} className={`flow-node ${item.id === selected ? 'selected' : ''} ${item.enabled ? '' : 'disabled'}`} onClick={() => setSelected(item.id)}><Icon size={21}/><div><strong>{i + 1}. {STEP_LABELS[item.kind]}</strong><p>{descriptions[item.kind]}</p></div><span className={`node-state ${item.enabled ? 'on' : ''}`}/></button>{orderIssues.filter(issue => issue.stepId === item.id).map(issue => <small key={issue.stepId} className="text-error">{issue.message}</small>)}</div>; })}<div className="flow-connector"/><Button className="add-step" disabled={busy || flow.steps.length >= (capabilities?.maxSteps ?? 30)} onClick={() => setAdding(true)}><Plus size={14}/>添加步骤</Button></div></div><aside className="flow-inspector">{step ? <><div className="inspector-header"><h2>{STEP_LABELS[step.kind]}参数</h2><div className="actions"><IconButton label="步骤上移" disabled={busy || flow.steps[0].id === selected} onClick={() => move(-1)}><ArrowUp size={14}/></IconButton><IconButton label="步骤下移" disabled={busy || flow.steps.at(-1)?.id === selected} onClick={() => move(1)}><ArrowDown size={14}/></IconButton><IconButton label="移除步骤" disabled={busy} onClick={() => { change({ ...flow, steps: flow.steps.filter(s => s.id !== selected) }); setSelected(flow.steps.find(s => s.id !== selected)?.id ?? ''); }}><Trash2 size={14}/></IconButton></div></div><section className="inspector-section"><label className="checkbox-row"><input type="checkbox" aria-label="启用当前步骤" disabled={busy || (!step.enabled && (capabilities ? !capabilities.availableSteps.includes(step.kind) : ['transform', 'local'].includes(step.kind)))} checked={step.enabled} onChange={e => change({ ...flow, steps: flow.steps.map(s => s.id === selected ? { ...s, enabled: e.target.checked } : s) })}/>启用这个步骤</label><FlowParameters key={step.id} step={step} onChange={parameter} onParametersChange={parameters => change({ ...flow, steps: flow.steps.map(s => s.id === selected ? { ...s, parameters } : s) })} disabled={busy} canExecute={Boolean(capabilities?.availableSteps.includes(step.kind))}/></section></> : <Notice>添加或选择一个流程步骤。</Notice>}</aside></div></>}
    {adding && <Modal title="添加流程步骤" onClose={() => setAdding(false)}><div className="module-list">{(Object.keys(STEP_LABELS) as StepKind[]).map(kind => { const Icon = icons[kind], available = capabilities?.availableSteps.includes(kind) ?? !['transform', 'local'].includes(kind); return <button key={kind} disabled={!available && !['transform', 'local'].includes(kind)} onClick={() => { const id = crypto.randomUUID(); change({ ...flow, steps: [...flow.steps, { id, kind, enabled: available, parameters: kind === 'review' ? { waitForHuman: true, buildIssues: true } : kind === 'transform' ? { operations: [] } : kind === 'local' ? { classMap: {} } : {} }] }); setSelected(id); setAdding(false); }}><Icon size={20}/><div><strong>{STEP_LABELS[kind]}{!available && (['transform', 'local'].includes(kind) ? ' · 仅编辑计划' : ' · 尚未开放')}</strong><p>{descriptions[kind]}</p></div><Plus size={16}/></button>; })}</div></Modal>}{templates && <Modal title="载入流程模板" onClose={() => setTemplates(null)}><div className="module-list">{templates.map(t => <button key={t.id} onClick={() => load(t)}><FolderOpen size={17}/>{t.name} · 版本 {t.version}</button>)}{!templates.length && <p className="quiet-empty">尚无保存的流程模板。</p>}</div></Modal>}
  </div>;
}
