import type { BrowserWindow } from 'electron';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { gotoNav, gotoWelcome, openProjectOverview } from './desktop-navigation';

/**
 * 五类任务类型的完整链路验收：人工定标 → 固定版本 → 真实重跑 → 指标口径。
 *
 * 当前状态：入口、项目与素材准备、以及「概览 → 标准答案集 → 新建 → 进入答案编辑器 → 画框」都已走通；
 * 卡在答案编辑器里的「保存独立标准答案」之后真值版本没有变成 1（保存被提交了，但没有产生新版本）。
 * 剩的是答案编辑器内部的一处细节，不再是缺失的界面——要继续就从 `保存独立标准答案` 与
 * `.truth-savebar` 的确认勾选看起。之前的失败原因与此无关，看到红不要误判为产品回归。
 */
export async function checkDesktopFive(window:BrowserWindow,output:string):Promise<void>{
  const json=JSON.stringify,jsRaw=<T=any>(s:string):Promise<T>=>window.webContents.executeJavaScript(s);let lastEval='';
  /** 包一层记录最后一条脚本：Electron 只回一句「Script failed to execute」，不给是哪一条。 */
  const js=<T=any>(s:string):Promise<T>=>{lastEval=s;return jsRaw<T>(s);};
  const api=(command:string,payload:unknown={})=>js(`window.autoLabel.request(${json(command)},${json(payload)})`);
  let calls=0;const checks:unknown[]=[];
  const box={x:200,y:200,width:300,height:200},points=[{x:200,y:200},{x:500,y:200},{x:470,y:400},{x:220,y:430}];
  const server=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);calls++;let assetId='';for(const part of body.messages.flatMap((m:any)=>Array.isArray(m.content)?m.content:[]))if(part.type==='text')try{const p=JSON.parse(part.text);if(p.role==='target')assetId=p.assetId;}catch{/* 普通提示不含素材身份。 */}
    if(body.model==='classify-failed'){res.writeHead(400,{'Content-Type':'application/json'});res.end(json({error:{message:'local protocol failure'}}));return;}const task=body.model.split('-')[0],annotation:any={id:'fixture-shape',type:task,classId:body.model==='classify-wrong'?'class-2':'class-1'};if(task==='segment')annotation.points=points;else if(task!=='classify'){annotation.bbox=box;if(task==='obb')annotation.rotation=30;if(task==='pose')annotation.keypoints=['左上','右上','右下','左下'].map(name=>({name,x:0,y:0,visibility:0}));}res.writeHead(200,{'Content-Type':'application/json'});res.end(json({choices:[{message:{role:'assistant',content:json({assetId,annotations:body.model==='classify-empty'?[]:[annotation]})},finish_reason:'stop'}]}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
  async function wait(e:string){const end=Date.now()+12000;while(Date.now()<end){if(await js(e))return;await new Promise(r=>setTimeout(r,50));}throw new Error(`五类界面等待超时：${e}`);}
  async function button(label:string,scope='document'){await wait(`!!${scope}&&[...${scope}.querySelectorAll('button')].some(b=>b.innerText.trim()===${json(label)}&&!b.disabled)`);await js(`[...${scope}.querySelectorAll('button')].find(b=>b.innerText.trim()===${json(label)}&&!b.disabled).click()`);}
  async function fill(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${json(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
  async function select(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});e.value=${json(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
  async function point(x:number,y:number){return js<{x:number;y:number}>(`(()=>{const r=document.querySelector('svg[aria-label="独立标准答案画布"]').getBoundingClientRect();return{x:Math.round(r.x+${x}/1586*r.width),y:Math.round(r.y+${y}/992*r.height)}})()`);}
  async function click(x:number,y:number){const p=await point(x,y);window.webContents.sendInputEvent({type:'mouseDown',...p,button:'left',clickCount:1});window.webContents.sendInputEvent({type:'mouseUp',...p,button:'left',clickCount:1});await js('new Promise(r=>requestAnimationFrame(r))');}
  async function capture(selector:string,suffix:string){await js(`document.activeElement?.blur();document.querySelector(${json(selector)}).scrollIntoView({block:'start',behavior:'instant'})`);await new Promise(r=>setTimeout(r,350));await writeFile(output.replace(/\.json$/,suffix),(await window.webContents.capturePage()).toPNG());}
  // 对话夹具必须写到本次运行真实的 userData：写错目录会让主进程去弹真实文件对话框，测试就挂在那里。
  const userData=process.env.AUTOLABEL_TEST_USER_DATA??path.join(path.dirname(output),'manual-check-user-data'),fixtures=path.join(userData,'fixtures');await mkdir(fixtures,{recursive:true});window.show();
  try{
    await wait(`!!window.autoLabel&&!document.querySelector('.connection-banner')`);const provider=await api('provider.save',{name:`五类 UI 协议-${Date.now()}`,baseUrl:`http://127.0.0.1:${(server.address() as {port:number}).port}/v1`,protocol:'chat-completions',maxRetries:0});await api('credential.set',{providerId:provider.id,key:'isolated-five-ui-fixture'});await new Promise<void>(r=>{window.webContents.once('did-finish-load',()=>r());window.webContents.reload();});await wait(`!!window.autoLabel&&!document.querySelector('.connection-banner')`);
    for(const task of ['detect','pose','obb','segment','classify']){
      // 项目走引擎接口（界面已不再提供任务类型选择）；素材必须走界面导入，
      // 直接用 asset.import 会被路径授权拦下——路径只能来自用户选择。
      const name=`五类界面 ${task}-${Date.now()}`;
      // 类别要显式给出：接口建项目不会自带类别，没有类别就画不出标准答案，保存会因类别校验失败。
      const classes=task==='classify'?[{id:'class-1',name:'合格',color:'#477b93'},{id:'class-2',name:'不合格',color:'#b45f5f'}]:[{id:'class-1',name:'目标',color:'#477b93'}];
      const project=await api<{id:string}>('project.create',{name,taskType:task,classes});
      if(task==='pose')await api('project.update',{projectId:project.id,settings:{keypointNames:['左上','右上','右下','左下']}});
      const picture=path.join(fixtures,`${task}-${Date.now()}.png`);await copyFile(path.join(path.dirname(path.dirname(output)),'renderer/public/example-street.png'),picture);await new Promise<void>(r=>{window.webContents.once('did-finish-load',()=>r());window.webContents.reload();});await wait(`!!document.querySelector('.sidebar')&&!document.querySelector('.connection-banner')`);await gotoWelcome({js,wait});await writeFile(path.join(userData,'dialog-fixtures.json'),json([{kind:'images',paths:[picture]}]));const clicked=await js<boolean>(`(()=>{const b=[...document.querySelectorAll('.onboarding-lane button')].find(x=>x.innerText.trim()==='导入图片');if(!b)return false;b.click();return true;})()`);assert.ok(clicked,'欢迎页找不到「导入图片」入口');const prompt="document.querySelector('dialog[open]')";await button('选择已有项目',prompt);const picked=await js<boolean>(`(()=>{const e=${prompt}.querySelector('select');if(!e)return false;e.value=${json(project.id)};e.dispatchEvent(new Event('change',{bubbles:true}));return true;})()`);assert.ok(picked,'项目确认框里没有可选的已有项目');await button('导入并继续',prompt);await wait(`!!document.querySelector('.chat-panel textarea')`);const assetId=(await api('asset.list',{projectId:project.id,limit:1})).items[0].id;const original=await api('asset.get',{assetId});
      await openProjectOverview({js,wait},name);await button('标准答案集');await button('新建标准答案集');await fill('dialog:last-of-type .field input',name+'标准');await js(`document.querySelector('dialog:last-of-type .quality-asset-picks input').click()`);await button('创建独立答案集');await wait(`!!document.querySelector('.truth-asset-list button')`);const set=(await api('evaluationSet.list',{projectId:original.projectId}))[0];await js(`document.querySelector('.truth-asset-list button').click()`);await wait(`!!document.querySelector('.truth-editor img')&&document.querySelector('.truth-editor img').complete`);
      if(task==='classify'){await js(`document.querySelector('.truth-savebar input').click()`);assert.equal(await js(`document.querySelector('.truth-savebar .primary').disabled`),true);await select('[aria-label="人工标准分类"]','class-1');}
      else if(task==='segment'){await button('绘制标准多边形');for(const p of points)await click(p.x,p.y);await js(`document.querySelector('.truth-savebar input').click()`);assert.equal(await js(`document.querySelector('.truth-savebar .primary').disabled`),true);await button('完成标准多边形');for(const [i,p]of points.entries())for(const key of ['x','y'] as const)await fill(`[aria-label="标准边界点${i+1}${key}"]`,String(p[key]));}
      else{await button(task==='obb'?'绘制标准旋转框':'绘制标准框');const start=await point(200,200),end=await point(500,400);window.webContents.sendInputEvent({type:'mouseDown',...start,button:'left',clickCount:1});await js('new Promise(r=>requestAnimationFrame(r))');window.webContents.sendInputEvent({type:'mouseMove',...end,movementX:end.x-start.x,movementY:end.y-start.y});window.webContents.sendInputEvent({type:'mouseUp',...end,button:'left',clickCount:1});await wait(`!!document.querySelector('[aria-label="标准答案对象x"]')`);for(const [key,value]of Object.entries(box))await fill(`[aria-label="标准答案对象${key}"]`,String(value));if(task==='obb')await fill('[aria-label="标准旋转角度"]','30');}
      await js(`document.querySelector('.truth-savebar input').click()`);await button('保存独立标准答案');await wait(`window.autoLabel.request('evaluationSet.getTruth',{setId:${json(set.id)},assetId:${json(assetId)}}).then(t=>t.truthVersion===1).catch(()=>false)`);const truth=await api('evaluationSet.getTruth',{setId:set.id,assetId});assert.equal(truth.annotations[0].type,task);assert.deepEqual(await api('asset.get',{assetId}),original);if(['obb','segment','classify'].includes(task))await capture('.truth-editor',`-five-${task}-truth.png`);await button('返回答案集');await wait(`document.querySelectorAll('dialog[open]').length===1`);await js(`document.querySelector('.operation-section input').click()`);await button('发布标准答案版本');await wait(`document.querySelector('.quality-summary')?.innerText.includes('固定版本 1')`);const versionId=(await api('evaluationSet.get',{setId:set.id})).publishedVersions[0].id;await js(`document.querySelector('dialog[open] [aria-label="关闭弹窗"]').click()`);
      await gotoNav({js,wait},'任务');await button('评测与复核');await wait(`!!document.querySelector('[aria-label="重跑标准版本"]')`);await select('[aria-label="重跑标准版本"]',versionId);const models=task==='classify'?['classify-good','classify-wrong','classify-empty','classify-failed']:[task+'-good'];for(const [i,model]of models.entries()){if(i)await button('添加方案');await select(`[aria-label="方案${i+1}接口"]`,provider.id);await fill(`[aria-label="方案${i+1}模型"]`,model);await fill(`[aria-label="方案${i+1}提示词"]`,'独立本地协议验收');}await button('检查重跑输入与预算');await wait(`!!document.querySelector('[aria-label="确认真实重跑"]')`);await js(`document.querySelector('[aria-label="确认真实重跑"]').click()`);await button('开始真实重跑对比');await wait(`document.querySelector('.rerun-progress h3')?.innerText.includes('所有方案已结束')`);await button('生成固定评测结果');await wait(`!!document.querySelector('.evaluation-detail .quality-table')`);const evaluation=(await api('evaluation.list',{projectId:original.projectId}))[0];assert.equal(evaluation.taskType,task);assert.deepEqual(await api('asset.get',{assetId}),original);
      if(task==='classify'){const m=(suffix:string)=>evaluation.schemes.find((s:any)=>s.model==='classify-'+suffix).metrics;assert.equal(m('good').classification.correct,1);assert.equal(m('wrong').classification.incorrect,1);assert.equal(m('empty').classification.missingPrediction,1);assert.equal(m('empty').classification.samples,1);assert.equal(m('failed').classification.samples,0);assert.equal(m('failed').classification.accuracy,null);const text=await js<string>(`document.querySelector('.evaluation-detail').innerText`);assert.ok(text.includes('不可用（分母为 0）'));assert.ok(text.includes('分类混淆矩阵'));assert.ok(!text.includes('平均 IoU'));await capture('.classification-results','-five-classification.png');}
      else{assert.ok(evaluation.schemes[0].metrics.meanMatchedIoU>.99);if(task==='obb')assert.equal(evaluation.schemes[0].metrics.overlapMetric,'rotated_iou');if(task==='segment')assert.equal(evaluation.schemes[0].metrics.overlapMetric,'polygon_iou');}
      await js(`document.querySelector('.evaluation-results button').click()`);await wait(`document.querySelectorAll('.comparison-canvases img').length===2&&[...document.querySelectorAll('.comparison-canvases img')].every(i=>i.complete)`);if(task==='obb')assert.ok(await js(`!!document.querySelector('.comparison-canvases svg g[transform^="rotate(30"]')`));if(task==='segment')assert.equal(await js(`document.querySelectorAll('.comparison-canvases polygon').length`),2);if(['obb','segment'].includes(task))await capture('.result-comparison',`-five-${task}-comparison.png`);checks.push({task,manualEditor:true,truthIndependent:true,actualRerun:true,metricKind:evaluation.schemes[0].metrics.metricKind,projectUnchanged:true});await js(`document.querySelector('dialog[open] [aria-label="关闭弹窗"]').click()`);
    }
    assert.equal(calls,8);await writeFile(output,json({passed:true,mode:'five-ui',checks,protocolFixtureCalls:calls}));
  }catch(e){await writeFile(output.replace(/\.json$/,'-five-failure.png'),(await window.webContents.capturePage()).toPNG());await writeFile(output,json({passed:false,mode:'five-ui',checks,error:e instanceof Error?e.message:String(e),lastEval:lastEval.slice(0,400),body:await jsRaw('document.body.innerText')}));throw e;}finally{await new Promise<void>(r=>server.close(()=>r()));}
}
