import type { BrowserWindow } from 'electron';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { writeFile } from 'node:fs/promises';
import { gotoSettings, gotoNav } from './desktop-navigation';

// 本地协议响应只验证界面到 Java 的真实调用、版本和费用口径，不代表外部模型质量。
export async function checkDesktopRerun(window:BrowserWindow,output:string):Promise<void>{
  let calls=0;const checks:Record<string,unknown>[]=[];const server=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;calls++;const body=JSON.parse(raw);let assetId='';for(const part of (body.messages??[]).flatMap((m:any)=>Array.isArray(m.content)?m.content:[]))if(part.type==='text')try{const p=JSON.parse(part.text);if(p.role==='target')assetId=p.assetId;}catch{/* 非结构化提示词不含目标身份。 */}assert.ok(!raw.includes('human-only-answer-id'),'人工答案不得进入请求');res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({choices:[{message:{role:'assistant',content:JSON.stringify({assetId,annotations:[{id:'local-candidate',type:'detect',classId:'vehicle',bbox:{x:221,y:483,width:537,height:350}}]})},finish_reason:'stop'}],usage:{prompt_tokens:100,completion_tokens:10,prompt_tokens_details:{cached_tokens:20}}}));});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
  const js=<T=any>(code:string):Promise<T>=>window.webContents.executeJavaScript(code),json=JSON.stringify;const api=(command:string,payload:unknown={})=>js(`window.autoLabel.request(${json(command)},${json(payload)})`);
  async function wait(e:string){const end=Date.now()+15000;while(Date.now()<end){if(await js(e))return;await new Promise(r=>setTimeout(r,60));}throw new Error(`重跑界面等待超时：${e}`);}
  async function button(label:string,scope='document'){await wait(`[...${scope}.querySelectorAll('button')].some(b=>b.innerText.trim()===${json(label)}&&!b.disabled)`);await js(`[...${scope}.querySelectorAll('button')].find(b=>b.innerText.trim()===${json(label)}).click()`);}
  async function fill(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${json(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
  async function select(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});e.value=${json(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
  async function capture(selector:string,suffix:string){await js(`document.activeElement?.blur();document.querySelector(${json(selector)}).scrollIntoView({block:'center',behavior:'instant'})`);await wait(`(()=>{const r=document.querySelector(${json(selector)}).getBoundingClientRect();return r.top>=0&&r.top<innerHeight})()`);await new Promise(r=>setTimeout(r,350));await writeFile(output.replace(/\.json$/,suffix),(await window.webContents.capturePage()).toPNG());}
  window.show();try{
    await wait(`!!window.autoLabel&&!document.querySelector('.connection-banner')`);const project=await api('project.example');const asset=(await api('asset.list',{projectId:project.id})).items[0];const original=await api('asset.get',{assetId:asset.id});const set=await api('evaluationSet.create',{projectId:project.id,name:`重跑 UI 人工协议标准-${Date.now()}`,assetIds:[asset.id]});await api('evaluationSet.saveTruth',{setId:set.id,assetId:asset.id,baseTruthVersion:0,source:'manual',note:'独立固定协议夹具，人工答案不送模型',annotations:[{id:'human-only-answer-id',classId:'vehicle',type:'detect',bbox:{x:221,y:483,width:537,height:350}}]});const current=await api('evaluationSet.get',{setId:set.id});const fixed=await api('evaluationSet.publish',{setId:set.id,baseSetRevision:current.revision});const port=(server.address() as {port:number}).port;const name=`费用 UI 本地协议-${Date.now()}`;const provider=await api('provider.save',{name,baseUrl:`http://127.0.0.1:${port}/v1`,protocol:'chat-completions',model:'fixture-priced',maxRetries:0});await api('credential.set',{providerId:provider.id,key:'isolated-rerun-ui-fixture'});
    await new Promise<void>(resolve=>{window.webContents.once('did-finish-load',()=>resolve());window.webContents.reload();});await wait(`!!document.querySelector('.nav-item')&&!document.querySelector('.connection-banner')`);await gotoSettings({js,wait},'软件 AI 配置');await wait(`!!document.querySelector('.provider-list')&&document.body.innerText.includes(${json(name)})`);await js(`[...document.querySelectorAll('.provider-list button')].find(b=>b.innerText.includes(${json(name)})).click()`);await wait(`!!document.querySelector('.provider-form .advanced-toggle')`);await js(`([...document.querySelectorAll('.provider-form .advanced-toggle')].find(b=>b.innerText.includes('手动配置'))).click()`);await wait(`!!document.querySelector('.pricing-form')`);await js(`document.querySelector('.pricing-form input[type="checkbox"]').click()`);for(const [label,value]of [['单价对应模型','fixture-priced'],['单价币种','USD'],['输入 / 百万 token','2'],['缓存输入 / 百万 token','0.5'],['输出 / 百万 token','6']])await fill(`[aria-label="${label}"]`,value);await button('保存接口');await wait(`window.autoLabel.request('provider.list',{}).then(ps=>ps.find(p=>p.id===${json(provider.id)})?.pricing?.cachedInputPerMillion===0.5)`);checks.push({check:'manual-model-prices',savedThroughUi:true,emptyPricesNotDefaulted:true});
    await gotoNav({js,wait},'任务');await button('评测与复核');await wait(`!!document.querySelector('.quality-body>.section-toolbar select')&&!document.querySelector('.quality-body>.section-toolbar select').disabled`);await select('.quality-body>.section-toolbar select',project.id);await wait(`!!document.querySelector('[aria-label="重跑标准版本"]')&&[...document.querySelector('[aria-label="重跑标准版本"]').options].some(o=>o.value===${json(fixed.id)})`);assert.ok(await js(`document.querySelector('.quality-body>.tabs button').classList.contains('selected')`));await select('[aria-label="重跑标准版本"]',fixed.id);await select('[aria-label="方案1接口"]',provider.id);await fill('[aria-label="方案1模型"]','fixture-priced');await fill('[aria-label="方案1提示词"]','本地协议验证：输出目标的候选框。');await button('添加方案');await select('[aria-label="方案2接口"]',provider.id);await fill('[aria-label="方案2模型"]','fixture-unpriced');await fill('[aria-label="方案2提示词"]','同一输入的第二个完整方案。');await fill('[aria-label="重跑共享请求上限"]','2');
    await js(`document.querySelectorAll('.rerun-scheme details').forEach(e=>e.open=true)`);for(const i of [1,2]){await fill(`[aria-label="方案${i}inputToken"]`,'100');await fill(`[aria-label="方案${i}outputToken"]`,'10');}await button('按填写的假设估算费用');await wait(`document.querySelectorAll('.estimate-result').length===2`);assert.ok(await js(`document.querySelector('.estimate-result').innerText.includes('未知')&&document.querySelector('.estimate-result').innerText.includes('缓存假设 未提供')`));assert.equal(calls,0);await fill('[aria-label="方案1cachedToken"]','0');await button('按填写的假设估算费用');await wait(`document.querySelector('.estimate-result')?.innerText.includes('USD')`);checks.push({check:'explicit-token-estimate',omittedCacheUnknown:true,explicitZeroAccepted:true,modelCalls:0});
    await fill('[aria-label="重跑费用币种"]','USD');await fill('[aria-label="重跑费用阈值"]','1');await button('检查重跑输入与预算');await wait(`document.querySelector('.rerun-create .quality-summary')?.innerText.includes('budget_pricing_unknown')`);assert.equal(calls,0);assert.equal(await js(`document.querySelector('[aria-label="确认真实重跑"]')`),null);await fill('[aria-label="重跑费用阈值"]','');await button('检查重跑输入与预算');await wait(`!!document.querySelector('[aria-label="确认真实重跑"]')`);assert.equal(calls,0);await js(`document.querySelector('[aria-label="确认真实重跑"]').click()`);await button('开始真实重跑对比');await wait(`document.querySelector('.rerun-progress h3')?.innerText.includes('所有方案已结束')`);assert.equal(calls,2);
    const comparisonId=await js<string>(`document.querySelector('[aria-label="重跑记录"]').value`);const rerun=await api('evaluation.rerun.get',{comparisonId});assert.equal(rerun.budget.requestsUsed,2);assert.equal(rerun.budget.cost.unknownCalls,1);assert.equal(rerun.budget.cost.knownCalls,1);assert.equal(rerun.budget.cost.hardLimit,false);assert.ok(Math.abs(rerun.budget.cost.knownCost-.00023)<1e-10);assert.deepEqual(await api('asset.get',{assetId:asset.id}),original);await capture('.rerun-progress','-rerun-progress.png');checks.push({check:'native-rerun',schemes:2,newCalls:2,knownCost:.00023,unknownCalls:1,sharedBudget:true,projectAnnotationsUnchanged:true});
    await button('生成固定评测结果');await wait(`!!document.querySelector('.quality-table')`);assert.ok(await js(`document.querySelector('.evaluation-detail>.quality-summary').innerText.includes('固定图片真实重跑')`));const done=await api('evaluation.rerun.get',{comparisonId});const evaluation=await api('evaluation.get',{evaluationId:done.evaluationId});assert.equal(evaluation.source,'fresh_run_snapshot');assert.equal(evaluation.schemes.length,2);await js(`document.querySelector('.evaluation-results button').click()`);await wait(`document.querySelectorAll('.comparison-canvases img').length===2&&[...document.querySelectorAll('.comparison-canvases img')].every(i=>i.complete&&i.naturalWidth===1586)`);await capture('.result-comparison','-quality-comparison.png');assert.equal(calls,2);checks.push({check:'fresh-evaluation',fixedCandidateVersions:true,frozenImages:true,noExtraFinishCalls:true});
    await writeFile(output,json({passed:true,mode:'rerun-ui',checks,protocolFixtureCalls:calls}));
  }catch(e){await writeFile(output.replace(/\.json$/,'-rerun-failure.png'),(await window.webContents.capturePage()).toPNG());await writeFile(output,json({passed:false,mode:'rerun-ui',checks,error:e instanceof Error?e.message:String(e),body:await js('document.body.innerText')}));throw e;}finally{await new Promise<void>(r=>server.close(()=>r()));}
}
