import type { BrowserWindow } from 'electron';
import assert from 'node:assert/strict';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import ClassificationResults from '../src/ClassificationResults';
import type { Evaluation } from '../../shared/quality';

export async function checkDesktopResources(window:BrowserWindow,output:string):Promise<void>{
  const checks:unknown[]=[],json=JSON.stringify,js=<T=any>(s:string):Promise<T>=>window.webContents.executeJavaScript(s),api=(command:string,payload:unknown={})=>js(`window.autoLabel.request(${json(command)},${json(payload)})`);const top="[...document.querySelectorAll('dialog[open]')].at(-1)";
  async function wait(e:string){const end=Date.now()+12000;while(Date.now()<end){if(await js(e))return;await new Promise(r=>setTimeout(r,50));}throw new Error(`资源界面等待超时：${e}`);}
  async function button(label:string,scope='document'){await wait(`!!(${scope})&&[...(${scope}).querySelectorAll('button')].some(b=>b.innerText.trim()===${json(label)}&&!b.disabled)`);await js(`[...(${scope}).querySelectorAll('button')].find(b=>b.innerText.trim()===${json(label)}).click()`);}
  async function fill(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${json(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
  async function select(selector:string,value:string){await js(`(()=>{const e=document.querySelector(${json(selector)});e.value=${json(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
  async function openProject(name:string){await js(`document.querySelectorAll('.nav-item')[0].click()`);await wait(`!!document.querySelector('.project-row')`);await js(`[...document.querySelectorAll('.project-row')].find(b=>b.innerText.includes(${json(name)})).click()`);await wait(`!!document.querySelector('.workbench')`);}
  async function capture(selector:string,suffix:string){await js(`document.activeElement?.blur();document.querySelector(${json(selector)}).scrollIntoView({block:'start',behavior:'instant'})`);await new Promise(r=>setTimeout(r,350));await writeFile(output.replace(/\.json$/,suffix),(await window.webContents.capturePage()).toPNG());}
  window.show();try{
    // 用实际组件进行只读渲染；一万类模板只产生出现类别的矩阵，大量组合切为一百行分页。
    const classes=Array.from({length:10000},(_,i)=>({id:`c${i}`,name:`类别${i}`,color:'#437fe5'}));const metric:any={totalTruthLabels:1,notApplicableReasons:{},classification:{samples:1,correct:1,incorrect:0,missingPrediction:0,accuracy:1,confusion:[{truthClassId:'c1',predictionClassId:'c1',count:1}]}};const fixture={schemes:[{id:'s',name:'只读呈现夹具',metrics:metric}]} as Evaluation;let html=renderToStaticMarkup(createElement(ClassificationResults,{evaluation:fixture,classes}));assert.ok(html.length<10000);assert.ok((html.match(/<td/g)??[]).length<30);metric.classification.confusion=Array.from({length:1000},(_,i)=>({truthClassId:`c${i}`,predictionClassId:`c${i}`,count:1}));html=renderToStaticMarkup(createElement(ClassificationResults,{evaluation:fixture,classes}));assert.ok(html.includes('分页计数表'));assert.ok((html.match(/<td/g)??[]).length<250);checks.push({check:'large-class-render',templateClasses:10000,sparseCombinations:1000,maxVisibleRows:100,noModelCalls:true});
    await wait(`!!window.autoLabel&&!document.querySelector('.connection-banner')`);const stamp=Date.now(),source=await api('project.example');await api('project.update',{projectId:source.id,name:`资源来源-${stamp}`});const sourceAsset=(await api('asset.list',{projectId:source.id})).items[0];const original=await api('asset.get',{assetId:sourceAsset.id});const a=await api('provider.save',{name:`全局接口-${stamp}`,baseUrl:'http://127.0.0.1:9/v1',protocol:'chat-completions'}),b=await api('provider.save',{name:`项目接口-${stamp}`,baseUrl:'http://127.0.0.1:9/v1',protocol:'chat-completions'});const target=await api('project.create',{name:`资源目标-${stamp}`,taskType:'detect',classes:[{id:'mapped-vehicle',name:'车',color:'#437fe5'},{id:'mapped-person',name:'人',color:'#3a9563'}]});await api('project.update',{projectId:target.id,settings:{annotationProviderId:b.id,annotationModel:'project-model',chatProviderId:b.id,chatModel:'project-chat',concurrency:3,maxRequests:5,prompt:'project-prompt'}});await api('settings.save',{settings:{annotationProviderId:a.id,annotationModel:'global-model',chatProviderId:a.id,chatModel:'global-chat',concurrency:7,maxRequests:9}});const obb=await api('project.create',{name:`四角旋转框-${stamp}`,taskType:'obb',classes:[{id:'box',name:'旋转目标',color:'#437fe5'}]});await new Promise<void>(r=>{window.webContents.once('did-finish-load',()=>r());window.webContents.reload();});await wait(`!!document.querySelector('.nav-item')&&!document.querySelector('.connection-banner')`);await openProject(target.name);
    await js(`document.querySelectorAll('.nav-item')[2].click()`);await wait(`!!document.querySelector('[aria-label="步骤接口"]')`);assert.ok(await js(`document.querySelector('.configuration-view').innerText.includes('project-model')&&document.querySelector('.configuration-view').innerText.includes('项目设置')`));await fill('[aria-label="步骤请求上限"]','');assert.ok(await js(`document.querySelector('.configuration-view').innerText.includes('请求上限：未设置（当前步骤）')`));await select('[aria-label="步骤接口"]',a.id);assert.ok(await js(`document.querySelector('.configuration-view').innerText.includes('模型：未配置')`));await fill('[aria-label="步骤模型"]','step-model');await fill('[aria-label="步骤并发"]','2');await button('保存流程');await wait(`window.autoLabel.request('project.open',{projectId:${json(target.id)}}).then(p=>p.settings.flow?.steps.some(s=>s.kind==='api'&&s.parameters.maxRequests===null&&s.parameters.model==='step-model'))`);checks.push({check:'configuration-precedence',projectOverridesGlobal:true,interfaceChangeClearsModel:true,explicitNullCap:true,stepConcurrencySaved:true});
    await js(`document.querySelectorAll('.nav-item')[4].click()`);await button('新建资源');const promptName=`资源版本验证-${stamp}`;await fill('[aria-label="资源名称"]',promptName);await fill('[aria-label="资源分类"]','UI专项');await fill('[aria-label="资源内容"]','固定提示词第一版');await button('保存资源');await wait(`document.querySelector('[aria-label="资源版本"]')?.value==='1'`);const resource=(await api('resource.list',{query:promptName}))[0];await fill('[aria-label="资源内容"]','固定提示词第二版');await button('保存为新版本');await wait(`document.querySelector('[aria-label="资源版本"]')?.value==='2'`);await fill('[aria-label="资源版本"]','1');await button('读取指定版本');await wait(`document.querySelector('[aria-label="资源内容"]').value==='固定提示词第一版'`);assert.equal(await js(`document.querySelector('[aria-label="资源内容"]').readOnly`),true);await button('应用当前版本到项目');await select('[aria-label="资源目标项目"]',target.id);await js(`document.querySelector('[aria-label="应用标注提示词"]').click()`);await js(`document.querySelector('[aria-label="确认覆盖资源字段"]').click()`);await button('应用所选字段');await wait(`!document.querySelector('dialog[open]')`);const applied=await api('project.open',{projectId:target.id});assert.equal(applied.settings.prompt,'固定提示词第一版');assert.equal(applied.settings.concurrency,3);assert.equal(applied.settings.resourceOrigins.prompt.version,1);await button('读取最新版本');await wait(`document.querySelector('[aria-label="资源版本"]').value==='2'`);await api('resource.save',{id:resource.id,baseVersion:2,kind:'prompt',name:promptName,content:'外部已保存第三版'});await fill('[aria-label="资源内容"]','保留当前未保存内容');await button('保存为新版本');await wait(`document.querySelector('.resource-editor .inline-error')?.innerText.includes('resource_version_conflict')`);assert.equal(await js(`document.querySelector('[aria-label="资源内容"]').value`),'保留当前未保存内容');await button('放弃编辑并收起');checks.push({check:'versioned-resource',oldVersionReadonly:true,explicitSingleFieldApply:true,conflictKeepsDraft:true});
    await button('保存人工参考');await select('[aria-label="参考来源项目"]',source.id);await wait(`document.querySelector('[aria-label="参考来源素材"]')?.options.length===2`);await select('[aria-label="参考来源素材"]',sourceAsset.id);const refName=`固定人工参考-${stamp}`;await fill('[aria-label="参考名称"]',refName);await fill('[aria-label="参考人工说明"]','只使用人工确认边界，固定第一版。');await js(`document.querySelector('[aria-label="确认保存人工参考"]').click()`);await button('保存固定人工参考');await wait(`!!document.querySelector('.resource-editor .quality-canvas img')&&document.querySelector('.resource-editor .quality-canvas img').complete`);const reference=(await api('resource.list',{kind:'reference',query:refName}))[0];assert.equal(reference.version,1);assert.equal(reference.content.sourceAssetVersion,original.version);assert.ok(await js(`document.querySelector('.resource-editor img').src.includes('/1')&&document.querySelector('.resource-editor img').naturalWidth===1586`));const edited=structuredClone(original.annotations);edited[0].bbox.x+=10;const changed=await api('annotation.save',{assetId:sourceAsset.id,annotations:edited,baseVersion:original.version,confirm:true});await button('从人工标注建立新版本');await wait(`document.querySelector('[aria-label="参考来源素材"]')?.options.length===2`);await select('[aria-label="参考来源素材"]',sourceAsset.id);await js(`document.querySelector('[aria-label="确认保存人工参考"]').click()`);await button('保存固定人工参考');await wait(`document.querySelector('[aria-label="资源版本"]')?.value==='2'`);assert.equal((await api('resource.get',{resourceId:reference.id,version:2})).content.sourceAssetVersion,changed.version);assert.deepEqual((await api('resource.get',{resourceId:reference.id,version:1})).content.annotations,original.annotations);await fill('[aria-label="资源版本"]','1');await button('读取指定版本');await wait(`document.querySelector('.resource-editor img')?.src.includes('/1')`);await capture('.resource-editor','-resource-reference.png');checks.push({check:'managed-human-reference',versions:2,oldAnnotationsFrozen:true,actualImage:true});
    await js(`document.querySelectorAll('.nav-item')[2].click()`);await wait(`!!document.querySelector('.reference-picker button')`);await button('选择跨项目人工参考（0）');await wait(`[...document.querySelectorAll('dialog .quality-list button')].some(b=>b.innerText.includes(${json(refName)}))`);await js(`[...document.querySelectorAll('dialog .quality-list button')].find(b=>b.innerText.includes(${json(refName)})).click()`);await wait(`!!document.querySelector('[aria-label="选择参考版本"]')`);await fill('[aria-label="选择参考版本"]','1');await button('读取参考版本');await wait(`document.querySelector('[aria-label="选择参考版本"]').value==='1'&&!document.querySelector('[aria-label="选择参考版本"]').disabled&&document.querySelector('dialog .quality-canvas img').src.endsWith('/1')`);await select('[aria-label="参考类别vehicle映射"]','mapped-vehicle');await select('[aria-label="参考类别person映射"]','mapped-person');await button('使用此固定参考版本');await button('保存流程');await wait(`window.autoLabel.request('project.open',{projectId:${json(target.id)}}).then(p=>p.settings.flow.steps.some(s=>s.kind==='api'&&s.parameters.referenceResources?.[0]?.version===1))`);const flow=(await api('project.open',{projectId:target.id})).settings.flow;const selection=flow.steps.find((s:any)=>s.kind==='api').parameters.referenceResources[0];assert.equal(selection.resourceId,reference.id);assert.equal(selection.classMap.vehicle,'mapped-vehicle');checks.push({check:'cross-project-selection',concreteVersion:1,explicitCompleteClassMap:true,savedToWorkflow:true});
    await openProject(obb.name);const userData=path.join(path.dirname(output),'manual-check-user-data'),fixtures=path.join(userData,'fixtures');await mkdir(fixtures,{recursive:true});const picture=path.join(fixtures,`obb-corners-${stamp}.png`);await copyFile(path.join(path.dirname(path.dirname(output)),'renderer/public/example-street.png'),picture);await writeFile(path.join(userData,'dialog-fixtures.json'),json([{kind:'images',paths:[picture]}]));await button('导入图片');await wait(`!!document.querySelector('.annotation-canvas image')`);const obbAssetId=await js<string>(`new URL(document.querySelector('.annotation-canvas image').getAttribute('href')).pathname.slice(1)`);const set=await api('evaluationSet.create',{projectId:obb.id,name:'四角 OBB 人工验证',assetIds:[obbAssetId]});await js(`document.querySelectorAll('.nav-item')[4].click()`);await button('标准答案集');await wait(`!!document.querySelector('.quality-list button')`);await js(`document.querySelector('.quality-list button').click()`);await wait(`!!document.querySelector('.truth-asset-list button')`);await js(`document.querySelector('.truth-asset-list button').click()`);await wait(`!!document.querySelector('.truth-editor img')&&document.querySelector('.truth-editor img').complete`);await button('粘贴人工答案 JSON');await fill('.human-json textarea',json([{id:'manual-corners',type:'obb',classId:'box',points:[{x:300,y:300},{x:600,y:300},{x:600,y:500},{x:300,y:500}]}]));await button('载入人工答案数组');await select('.truth-properties>.field select','manual-corners');assert.equal(await js(`document.querySelectorAll('[data-quality-vertex]').length`),0);await fill('[aria-label="标准旋转角度"]','30');await js(`document.querySelector('.truth-savebar input').click()`);await button('保存独立标准答案');await wait(`window.autoLabel.request('evaluationSet.getTruth',{setId:${json(set.id)},assetId:${json(obbAssetId)}}).then(t=>t.truthVersion===1).catch(()=>false)`);const shape=(await api('evaluationSet.getTruth',{setId:set.id,assetId:obbAssetId})).annotations[0];assert.ok(Math.abs(Math.atan2(shape.points[1].y-shape.points[0].y,shape.points[1].x-shape.points[0].x)*180/Math.PI-30)<.01);assert.equal(shape.bbox,undefined);assert.equal(await js(`document.querySelectorAll('.truth-editor svg [data-quality-object] polygon').length`),1);await capture('.truth-editor','-obb-corners.png');checks.push({check:'imported-obb-corners',rotationDegrees:30,saved:true,noFreeVertexHandles:true,noDuplicateBox:true});
    await writeFile(output,json({passed:true,mode:'resources-ui',checks,newModelCalls:0}));
  }catch(e){await writeFile(output.replace(/\.json$/,'-resources-failure.png'),(await window.webContents.capturePage()).toPNG());await writeFile(output,json({passed:false,mode:'resources-ui',checks,error:e instanceof Error?e.message:String(e),body:await js('document.body.innerText')}));throw e;}
}
