import type { BrowserWindow } from 'electron';
import { strict as assert } from 'node:assert';
import { createServer } from 'node:http';
import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

// 复用主控质量协议夹具的 target 身份解析；只监听回环，记录为模拟协议，不代表真实模型质量。
/**
 * 独立人工答案与画布协议验收。
 *
 * 当前状态：跑不通，且原因与「画布协议」无关——它仍引用三处已移除的界面：
 * 「标准答案集」编辑界面（TruthSets.tsx 已无渲染处）、工作台（.workbench）、旧画布标记（.annotation-canvas / [data-point]）。
 * 要恢复得按现界面重写：定标与发布走 evaluationSet.*，画布改用 .quality-image img 与 [data-quality-*]。
 */
export async function checkDesktopQuality(window:BrowserWindow,output:string):Promise<void>{
  let calls=0;const checks:Record<string,unknown>[]=[];
  const server=createServer(async(incoming,outgoing)=>{let raw='';for await(const part of incoming)raw+=part;const body=JSON.parse(raw);calls++;
    const parts=(body.messages??[]).flatMap((m:{content:unknown})=>Array.isArray(m.content)?m.content:[]);let target:string|undefined;
    for(const part of parts)if(part.type==='text')try{const value=JSON.parse(part.text);if(value.role==='target')target=value.assetId;}catch{/* 普通提示词不作为素材身份。 */}
    if(body.model==='fixture-failed'){outgoing.writeHead(400,{'Content-Type':'application/json'});outgoing.end(JSON.stringify({error:{message:'isolated protocol failure'}}));return;}
    const content=JSON.stringify({assetId:target,annotations:body.model==='fixture-empty'?[]:[{id:'protocol-candidate',classId:'vehicle',type:'detect',bbox:{x:221,y:483,width:537,height:350}}]});
    outgoing.writeHead(200,{'Content-Type':'application/json'});outgoing.end(JSON.stringify({choices:[{message:{role:'assistant',content},finish_reason:'stop'}],usage:{prompt_tokens:10,completion_tokens:10,total_tokens:20}}));
  });await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  const json=JSON.stringify;const js=<T=any>(code:string):Promise<T>=>window.webContents.executeJavaScript(code);
  const top="[...document.querySelectorAll('dialog[open]')].at(-1)";
  async function wait(expression:string){const end=Date.now()+12000;while(Date.now()<end){if(await js(expression))return;await new Promise(resolve=>setTimeout(resolve,50));}throw new Error(`质量界面等待超时：${expression}`);}
  async function button(text:string,scope=top){await wait(`!!(${scope})&&[...(${scope}).querySelectorAll('button')].some(b=>b.innerText.trim()===${json(text)}&&!b.disabled)`);await js(`[...(${scope}).querySelectorAll('button')].find(b=>b.innerText.trim()===${json(text)}).click()`);}
  async function fill(selector:string,value:string){await js(`(()=>{const e=(${top}).querySelector(${json(selector)});e.focus();Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value').set.call(e,${json(value)});e.dispatchEvent(new Event('input',{bubbles:true}));})()`);}
  async function select(selector:string,value:string){await js(`(()=>{const e=(${top}).querySelector(${json(selector)});e.value=${json(value)};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
  const api=<T=any>(command:string,payload:unknown={}):Promise<T>=>js(`window.autoLabel.request(${json(command)},${json(payload)})`);
  async function tick(text:string){await js(`([...(${top}).querySelectorAll('label')].find(l=>l.innerText.includes(${json(text)}))).querySelector('input').click()`);}
  async function draw(x:number,y:number,width:number,height:number){await button('绘制标准框');const r=await js<{x:number;y:number;width:number;height:number}>(`(()=>{const r=document.querySelector('.truth-editor svg[aria-label="独立标准答案画布"]').getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height}})()`);const start={x:Math.round(r.x+x/1586*r.width),y:Math.round(r.y+y/992*r.height)},end={x:Math.round(r.x+(x+width)/1586*r.width),y:Math.round(r.y+(y+height)/992*r.height)};
    window.webContents.sendInputEvent({type:'mouseDown',...start,button:'left',clickCount:1});await js('new Promise(r=>requestAnimationFrame(r))');window.webContents.sendInputEvent({type:'mouseMove',...end,movementX:end.x-start.x,movementY:end.y-start.y});await js('new Promise(r=>requestAnimationFrame(r))');window.webContents.sendInputEvent({type:'mouseUp',...end,button:'left',clickCount:1});await wait(`!!document.querySelector('[aria-label="标准答案对象x"]')`);
    for(const [key,value]of Object.entries({x,y,width,height}))await fill(`[aria-label="标准答案对象${key}"]`,String(value));
  }
  window.show();
  try{
    await wait(`!!document.querySelector('.onboarding-lanes button')&&!document.querySelector('.skeleton-list')&&!document.querySelector('.connection-banner')`);await button('打开示例','document');await wait(`!!document.querySelector('.annotation-canvas image')`);
    const assetId=await js<string>(`new URL(document.querySelector('.annotation-canvas image').getAttribute('href')).pathname.slice(1)`);const initial=await api('asset.get',{assetId});const projectId=initial.projectId;
    await js(`document.querySelectorAll('.nav-item')[4].click()`);await button('标准答案集','document');await button('新建标准答案集');const name=`独立人工协议验证-${Date.now()}`;await fill('.field input',name);await js(`(${top}).querySelector('.quality-asset-picks input').click()`);await button('创建独立答案集');await wait(`document.querySelector('.quality-detail')?.innerText.includes(${json(name)})`);
    const set=(await api('evaluationSet.list',{projectId})).find((s:any)=>s.name===name);assert.equal(set.truthCount,0);await js(`document.querySelector('.truth-asset-list button').click()`);await wait(`!!document.querySelector('.truth-editor img')&&document.querySelector('.truth-editor img').complete`);
    assert.equal(await js(`document.querySelectorAll('.truth-editor [data-quality-object]').length`),0,'不能自动把项目候选或确认标注当作独立答案');
    await draw(221,483,537,350);await draw(771,512,314,202);await tick('确认这些是独立制作');await button('保存独立标准答案');await wait(`window.autoLabel.request('evaluationSet.getTruth',{setId:${json(set.id)},assetId:${json(assetId)}}).then(t=>t.annotations.length===2).catch(()=>false)`);
    const truth=await api('evaluationSet.getTruth',{setId:set.id,assetId});assert.equal(truth.source,'manual');assert.deepEqual((await api('asset.get',{assetId})).annotations,initial.annotations);await writeFile(output.replace(/\.json$/,'-quality-truth.png'),(await window.webContents.capturePage()).toPNG());await button('返回答案集');await wait(`document.querySelectorAll('dialog[open]').length===1`);await tick('发布为固定评测版本');await button('发布标准答案版本');await wait(`!!document.querySelector('.quality-summary')?.innerText.includes('固定版本 1')`);
    const setView=await api('evaluationSet.get',{setId:set.id});const versionId=setView.publishedVersions[0].id;const frozen=await api('evaluationSet.get',{setId:set.id,versionId});assert.equal(frozen.truthObjectCount,2);checks.push({check:'independent-truth',startedEmpty:true,manualObjects:2,projectAnnotationsUnchanged:true,published:true});
    await js(`(${top}).querySelector('[aria-label="关闭弹窗"]').click()`);await wait(`!document.querySelector('dialog[open]')`);
    const address=server.address() as {port:number};const provider=await api('provider.save',{name:'质量 UI 回环协议夹具',baseUrl:`http://127.0.0.1:${address.port}/v1`,protocol:'chat-completions',maxRetries:0,timeoutMs:3000});await api('credential.set',{providerId:provider.id,key:'isolated-quality-ui-fixture'});
    const runs:any[]=[];for(const model of ['fixture-match','fixture-empty','fixture-failed']){const run=await api('run.create',{projectId,assetIds:[assetId],providerId:provider.id,model,prompt:'仅用于本地协议验收的固定响应，不代表模型质量',maxRequests:1,concurrency:1});await wait(`window.autoLabel.request('run.get',{runId:${json(run.id)}}).then(r=>r.statistics.completed===1)`);runs.push(await api('run.get',{runId:run.id}));}
    assert.equal(calls,3);const beforeEvaluation=calls;
    await js(`document.querySelectorAll('.nav-item')[3].click()`);await button('评测与复核','document');await button('已有运行对比');await wait(`!!document.querySelector('.evaluation-create')`);await select('.evaluation-create>.field select',versionId);await js(`document.querySelectorAll('.quality-run-picks input').forEach(e=>e.click())`);await button('检查评测输入');await wait(`document.querySelector('.evaluation-create .quality-summary')?.innerText.includes('输入检查通过')`);await button('生成已有运行对比');await wait(`!!document.querySelector('.quality-table')`);
    assert.equal(calls,beforeEvaluation,'历史评测不得发起新标注请求');const evaluation=(await api('evaluation.list',{projectId}))[0];const match=evaluation.schemes.find((s:any)=>s.model==='fixture-match'),empty=evaluation.schemes.find((s:any)=>s.model==='fixture-empty'),failed=evaluation.schemes.find((s:any)=>s.model==='fixture-failed');assert.equal(match.metrics.matchedObjects,1);assert.equal(match.metrics.missedObjects,1);assert.equal(empty.metrics.extraRate,null);assert.equal(failed.metrics.failedSamples,1);assert.equal(failed.metrics.scorableSamples,0);assert.equal(evaluation.pairedComparableSamples,0);
    assert.ok((await js<string>(`document.querySelector('.quality-table').innerText`)).includes('不可用（分母为 0）'));await select('.evaluation-detail>.field select',match.id);await wait(`!!document.querySelector('.evaluation-results button')`);await js(`document.querySelector('.evaluation-results button').click()`);await wait(`document.querySelectorAll('.comparison-canvases img').length===2&&[...document.querySelectorAll('.comparison-canvases img')].every(i=>i.complete&&i.naturalWidth===1586)`);assert.equal(await js(`document.querySelectorAll('.comparison-canvases .quality-canvas:first-child [data-quality-object]').length`),1);assert.equal(await js(`document.querySelectorAll('.comparison-canvases .quality-canvas:last-child [data-quality-object]').length`),2);assert.ok(await js(`document.querySelector('.comparison-canvases img').src.startsWith('autolabel-media://evaluation/')`));await js(`document.querySelector('.result-comparison').scrollIntoView({block:'center',behavior:'instant'});new Promise(r=>requestAnimationFrame(r))`);await new Promise(r=>setTimeout(r,350));await writeFile(output.replace(/\.json$/,'-quality-comparison.png'),(await window.webContents.capturePage()).toPNG());
    checks.push({check:'existing-run-comparison',localProtocolOnly:true,newModelCalls:0,match:1,miss:1,zeroDenominatorUnavailable:true,failedScorable:0,frozenImages:true});
    await button('进入问题复核');await button('从所选记录建立复核问题');await wait(`!!document.querySelector('.review-list button')`);const beforeReview=await api('asset.get',{assetId});await js(`document.querySelector('.review-list button').click()`);await wait(`document.querySelectorAll('.review-detail .comparison-canvases img').length===2&&[...document.querySelectorAll('.review-detail .comparison-canvases img')].every(i=>i.complete)`);await js(`document.querySelector('.review-detail').scrollIntoView({block:'center',behavior:'instant'});new Promise(r=>requestAnimationFrame(r))`);await writeFile(output.replace(/\.json$/,'-quality-review.png'),(await window.webContents.capturePage()).toPNG());await button('标记已核对');await wait(`document.querySelector('.review-detail h3')?.innerText.includes('已核对')`);assert.deepEqual(await api('asset.get',{assetId}),beforeReview);assert.deepEqual(await api('evaluationSet.getTruth',{setId:set.id,assetId}),truth);assert.equal(calls,beforeEvaluation);
    await select('.review-panel>.field-grid>.field:first-child select','random');await button('新建随机抽查');await wait(`!!document.querySelector('.random-sample-form .quality-asset-picks input')`);await js(`document.querySelector('.random-sample-form .quality-asset-picks input').click()`);await fill('.random-sample-form .field-grid>.field:first-child input','quality-ui-fixed-seed');await fill('.random-sample-form input[type="number"]','1');await button('固定随机名单');await wait(`!!document.querySelector('.review-list button')&&document.querySelector('.review-panel>.quality-summary')?.innerText.includes('随机抽查 1 / 1')`);await js(`document.querySelector('.review-list button').click()`);await button('标为待重标');await wait(`document.querySelector('.review-detail h3')?.innerText.includes('待重标')`);assert.equal(calls,beforeEvaluation);assert.deepEqual(await api('asset.get',{assetId}),beforeReview);
    checks.push({check:'review-separation',annotationWrites:0,truthWrites:0,relabelRequests:0,randomPopulation:1,randomCount:1});
    await js(`(${top}).querySelector('[aria-label="关闭弹窗"]').click()`);await wait(`!document.querySelector('dialog[open]')`);await js(`document.querySelectorAll('.nav-item')[0].click()`);await button('新建项目','document');await fill('.field input',`Pose 独立答案验证-${Date.now()}`);await select('form select','pose');await button('创建并打开');await wait(`!!document.querySelector('.workbench')&&!document.querySelector('dialog[open]')`);
    const userData=path.join(path.dirname(output),'manual-check-user-data'),fixtures=path.join(userData,'fixtures');await mkdir(fixtures,{recursive:true});const picture=path.join(fixtures,`quality-pose-${Date.now()}.png`);await copyFile(path.join(path.dirname(path.dirname(output)),'renderer/public/example-street.png'),picture);await writeFile(path.join(userData,'dialog-fixtures.json'),json([{kind:'images',paths:[picture]}]));await button('导入图片','document');await wait(`!!document.querySelector('.annotation-canvas image')`);
    const poseAssetId=await js<string>(`new URL(document.querySelector('.annotation-canvas image').getAttribute('href')).pathname.slice(1)`);const poseAsset=await api('asset.get',{assetId:poseAssetId});await js(`document.querySelectorAll('.nav-item')[4].click()`);await button('标准答案集','document');await button('新建标准答案集');const poseSetName=`Pose 人工协议答案-${Date.now()}`;await fill('.field input',poseSetName);await js(`(${top}).querySelector('.quality-asset-picks input').click()`);await button('创建独立答案集');await wait(`document.querySelector('.quality-detail')?.innerText.includes(${json(poseSetName)})`);const poseSet=(await api('evaluationSet.list',{projectId:poseAsset.projectId})).find((s:any)=>s.name===poseSetName);await js(`document.querySelector('.truth-asset-list button').click()`);await wait(`!!document.querySelector('.truth-editor img')&&document.querySelector('.truth-editor img').complete`);await draw(100,100,300,300);await wait(`document.querySelectorAll('.truth-point').length===4`);
    assert.equal(await js(`document.querySelector('.quality-canvas-heading input[type="checkbox"]').checked`),false);await js(`document.querySelector('.truth-point button').click()`);const point=await js<{x:number;y:number}>(`(()=>{const r=document.querySelector('svg[aria-label="独立标准答案画布"]').getBoundingClientRect();return{x:Math.round(r.x+150/1586*r.width),y:Math.round(r.y+150/992*r.height)}})()`);window.webContents.sendInputEvent({type:'mouseDown',...point,button:'left',clickCount:1});window.webContents.sendInputEvent({type:'mouseUp',...point,button:'left',clickCount:1});await select('[aria-label="左上标准可见性"]','1');await js(`document.querySelector('.quality-canvas-heading input[type="checkbox"]').click()`);await wait(`document.querySelector('svg[aria-label="独立标准答案画布"]').textContent.includes('左上')`);await tick('确认这些是独立制作');await button('保存独立标准答案');await wait(`window.autoLabel.request('evaluationSet.getTruth',{setId:${json(poseSet.id)},assetId:${json(poseAssetId)}}).then(t=>t.annotations.length===1).catch(()=>false)`);const poseTruth=await api('evaluationSet.getTruth',{setId:poseSet.id,assetId:poseAssetId});assert.equal(poseTruth.annotations[0].keypoints.length,4);assert.equal(poseTruth.annotations[0].keypoints[0].visibility,1);assert.ok(Math.abs(poseTruth.annotations[0].keypoints[0].x-150)<3);assert.equal((await api('asset.get',{assetId:poseAssetId})).version,0);
    assert.ok(await js(`(()=>{const button=document.querySelector('.truth-savebar .primary').getBoundingClientRect();const modal=(${top}).getBoundingClientRect();return button.top>=modal.top&&button.bottom<=modal.bottom})()`),'保存按钮需要完整位于弹窗可见区域');await writeFile(output.replace(/\.json$/,'-quality-pose.png'),(await window.webContents.capturePage()).toPNG());checks.push({check:'pose-independent-editor',points:4,occludedLocatedPoint:true,pointNamesToggle:true,stickySaveVisible:true,projectVersionUnchanged:true});
    await button('返回答案集');await wait(`document.querySelectorAll('dialog[open]').length===1`);await js(`(${top}).querySelector('[aria-label="关闭弹窗"]').click()`);await js(`document.querySelectorAll('.nav-item')[1].click()`);await wait(`!!document.querySelector('.annotation-canvas image')`);await js(`document.querySelector('[aria-label="关键点 · P"]').click()`);
    await wait(`document.querySelector('[aria-label="关键点 · P"]').classList.contains('active')`);await js('new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)))');const workPoint=async(x:number,y:number)=>js<{x:number;y:number}>(`(()=>{const r=document.querySelector('.annotation-canvas').getBoundingClientRect();return{x:Math.round(r.x+${x}/1586*r.width),y:Math.round(r.y+${y}/992*r.height)}})()`);const ws=await workPoint(100,100),we=await workPoint(600,500);
    window.webContents.sendInputEvent({type:'mouseDown',...ws,button:'left',clickCount:1});await js('new Promise(r=>requestAnimationFrame(r))');window.webContents.sendInputEvent({type:'mouseMove',...we,movementX:we.x-ws.x,movementY:we.y-ws.y});await js('new Promise(r=>requestAnimationFrame(r))');window.webContents.sendInputEvent({type:'mouseUp',...we,button:'left',clickCount:1});await wait(`document.querySelectorAll('.keypoint-field').length===4`);await button('保存','document');await wait(`window.autoLabel.request('asset.get',{assetId:${json(poseAssetId)}}).then(a=>a.version===1)`);assert.ok((await api('asset.get',{assetId:poseAssetId})).annotations[0].keypoints.every((p:any)=>p.x===0&&p.y===0&&p.visibility===0));assert.equal(await js(`document.querySelectorAll('.annotation-canvas circle[data-point]').length`),0);
    for(const [i,name]of ['左上','右上','右下','左下'].entries()){await js(`document.querySelector('[aria-label="定位${name}"]').click()`);const p=await workPoint(200+i*60,200+i*35);window.webContents.sendInputEvent({type:'mouseDown',...p,button:'left',clickCount:1});window.webContents.sendInputEvent({type:'mouseUp',...p,button:'left',clickCount:1});await wait(`document.querySelector('[aria-label="${name}可见性"]').value==='2'`);}
    await button('保存','document');await wait(`window.autoLabel.request('asset.get',{assetId:${json(poseAssetId)}}).then(a=>a.version===2)`);assert.ok((await api('asset.get',{assetId:poseAssetId})).annotations[0].keypoints.every((p:any,i:number)=>p.visibility===2&&Math.abs(p.x-(200+i*60))<4));checks.push({check:'workbench-pose-manual-location',initialUnknownPoints:4,locatedPoints:4,saved:true});
    await writeFile(output,json({passed:true,mode:'quality-ui',checks,protocolFixtureCalls:calls}));
  }catch(error){await writeFile(output.replace(/\.json$/,'-quality-failure.png'),(await window.webContents.capturePage()).toPNG());await writeFile(output,json({passed:false,mode:'quality-ui',checks,error:error instanceof Error?error.message:String(error),body:await js('document.body.innerText')}));throw error;}
  finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
}
