package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;

final class BackupIntegrationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    static void run(Path root)throws Exception{cancelOrdering(root);files(root);}
    static void cancelOrdering(Path root)throws Exception{
        try(Engine e=new Engine(root.resolve("maintenance-cancel-order"))){JsonObject early=Json.obj("operationId","cancel-arrives-first"),normal=Json.obj("operationId","normal-owner");
            check(Json.bool(cmd(e,"system.cancelDataMaintenance",early),"released",false),"cancel before prepare records terminal operation");
            ManualChainTest.rejects("maintenance_operation_cancelled",()->cmd(e,"system.prepareDataMaintenance",early));check(Json.bool(cmd(e,"system.cancelDataMaintenance",early),"released",false),"repeated unlocked cancel idempotent");
            check(Json.bool(cmd(e,"system.prepareDataMaintenance",normal),"ready",false),"fresh operation can lock after earlier cancellation");ManualChainTest.rejects("maintenance_owner_conflict",()->cmd(e,"system.cancelDataMaintenance",early));check(Json.bool(cmd(e,"system.prepareDataMaintenance",normal),"locked",false),"cancelled other owner cannot release current lock");
            cmd(e,"system.cancelDataMaintenance",normal);check(Json.bool(cmd(e,"system.cancelDataMaintenance",normal),"released",false),"normal released owner cancellation idempotent");ManualChainTest.rejects("maintenance_operation_cancelled",()->cmd(e,"system.prepareDataMaintenance",normal));
            check(Json.bool(cmd(e,"system.prepareUpdate",new JsonObject()),"ready",false),"update acquired after terminal data operation");ManualChainTest.rejects("maintenance_mode_conflict",()->cmd(e,"system.cancelDataMaintenance",normal));check(Json.bool(cmd(e,"system.canUpdate",new JsonObject()),"locked",false),"idempotent cancellation cannot release update lock");cmd(e,"system.cancelUpdate",new JsonObject());
        }
    }
    static void files(Path root)throws Exception{
        Path output=Files.createDirectories(root.resolve("接线 备份")),target=Files.createDirectories(root.resolve("接线 恢复"));
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("backup-command-live"))){JsonObject provider=EngineTest.provider(e,mock,"responses");String providerId=Json.required(provider,"id"),pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,2);String aid=ids.get(0).getAsString();JsonArray original=Json.arr(EngineTest.label("detect"));cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",0,"annotations",original,"confirm",true));cmd(e,"annotation.draft",Json.obj("assetId",aid,"baseVersion",1,"annotations",original));e.runs.suspend(true);JsonObject run=cmd(e,"run.create",DataMaintenanceTest.request(provider,pid,Json.arr(ids.get(1))));String rid=Json.required(run,"id");cmd(e,"run.pause",Json.obj("runId",rid));
            JsonObject preflight=cmd(e,"backup.preflight",Json.obj("outputDir",output.toString()));check(Json.bool(preflight,"ready",false)&&Json.integer(preflight,"fileCount",0)>0,"routed preflight includes managed dependencies");
            ManualChainTest.rejects("invalid_argument",()->cmd(e,"backup.create",Json.obj("outputDir",output.toString())));ManualChainTest.rejects("maintenance_mode_conflict",()->cmd(e,"backup.create",Json.obj("outputDir",output.toString(),"operationId","no-lock")));
            JsonObject owner=Json.obj("operationId","backup-command-owner");check(Json.bool(cmd(e,"system.prepareDataMaintenance",owner),"ready",false),"paused queued run permits owned backup");ManualChainTest.rejects("engine_data_maintenance_locked",()->cmd(e,"backup.preflight",Json.obj("outputDir",output.toString())));ManualChainTest.rejects("maintenance_owner_conflict",()->cmd(e,"backup.create",Json.obj("outputDir",output.toString(),"operationId","wrong-owner")));
            JsonObject invalid=owner.deepCopy();ManualChainTest.rejects("invalid_argument",()->cmd(e,"backup.create",invalid));check(Json.bool(cmd(e,"system.prepareDataMaintenance",owner),"ready",false),"failed owned command releases its activity count");
            JsonObject request=owner.deepCopy();request.addProperty("outputDir",output.toString());JsonObject backup=cmd(e,"backup.create",request);Path archive=Path.of(Json.required(backup,"backupPath"));check(Files.isRegularFile(archive)&&Json.required(backup,"status").equals("completed"),"owner command publishes a verified archive");check(!Json.bool(backup,"credentialsIncluded",true)&&Json.bool(backup,"credentialRebindRequired",false),"routed backup declares credential boundary");check(Json.bool(cmd(e,"backup.inspect",Json.obj("backupPath",archive.toString())),"valid",false),"backup inspect works under same data lock");
            JsonArray events=(JsonArray)e.command("event.list",Json.obj("after",0));check(events.asList().stream().anyMatch(item->Json.str(item.getAsJsonObject(),"type","").equals("backup.progress")&&Json.str(Json.object(item.getAsJsonObject(),"payload"),"operationId","").equals("backup-command-owner")),"backup progress uses the desktop operation identity");cmd(e,"system.cancelDataMaintenance",owner);
            JsonObject changed=EngineTest.label("detect");Json.object(changed,"bbox").addProperty("x",210);cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",1,"annotations",Json.arr(changed),"confirm",true));
            ManualChainTest.rejects("invalid_argument",()->cmd(e,"restore.prepare",Json.obj("backupPath",archive.toString(),"targetParent",target.toString())));JsonObject restoreOwner=Json.obj("operationId","restore-command-owner");cmd(e,"system.prepareDataMaintenance",restoreOwner);JsonObject restoreRequest=restoreOwner.deepCopy();restoreRequest.addProperty("backupPath",archive.toString());restoreRequest.addProperty("targetParent",target.toString());JsonObject prepared=cmd(e,"restore.prepare",restoreRequest);Path restoredPath=Path.of(Json.required(prepared,"dataDir"));check(restoredPath.startsWith(target)&&Files.isRegularFile(restoredPath.resolve("autolabel.db"))&&!Json.bool(prepared,"currentDataChanged",true),"restore prepares fresh data without switching current engine");check(Json.integer(e.projects.asset(aid),"version",0)==2,"restore leaves later live annotation intact");
            try(Engine restored=new Engine(restoredPath)){JsonObject asset=restored.projects.asset(aid);check(Json.integer(asset,"version",0)==1&&asset.has("draft"),"restored engine reads frozen manual annotation and draft");check(Json.required(restored.runs.get(rid),"pauseReason").equals("user")&&Json.integer(Json.object(restored.runs.get(rid),"statistics"),"queued",0)==1,"paused run and queued input survive backup and reopen");check(Files.isRegularFile(restored.projects.path(aid))&&restored.projects.path(aid).startsWith(restoredPath),"restored media path belongs to prepared directory");ManualChainTest.rejects("credential_missing",()->restored.providers.requireCredential(restored.providers.get(providerId)));}
            check(mock.calls.get()==0,"backup inspect and restore never issue model requests");check(Json.bool(cmd(e,"system.prepareDataMaintenance",restoreOwner),"ready",false),"restore owner activity released after completion");cmd(e,"system.cancelDataMaintenance",restoreOwner);
        }
    }
}
