package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;

final class CostRerunTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String name,JsonObject p)throws Exception{return (JsonObject)e.command(name,p);}
    static JsonObject pricing(String currency,double input,double cached,double output){return Json.obj("model","fixture","currency",currency,"inputPerMillion",input,"cachedInputPerMillion",cached,"outputPerMillion",output);}
    static void run(Path root)throws Exception{arithmetic();workflow(root);}
    static void arithmetic(){JsonObject price=pricing("CNY",2,0.5,4),chat=Json.obj("prompt_tokens",1000,"completion_tokens",200,"prompt_tokens_details",Json.obj("cached_tokens",600),"completion_tokens_details",Json.obj("reasoning_tokens",150)),responses=Json.obj("input_tokens",1000,"output_tokens",200,"input_tokens_details",Json.obj("cached_tokens",600),"output_tokens_details",Json.obj("reasoning_tokens",150));
        check(Math.abs(Json.decimal(Costs.calculate(price,chat),"amount",0)-0.0019)<1e-12,"chat cache subset priced without duplicate reasoning");check(Costs.calculate(price,chat).equals(Costs.calculate(price,responses)),"both usage protocols have same accounting");
        check(Json.required(Costs.calculate(price,JsonNull.INSTANCE),"status").equals("unknown"),"missing usage not free");responses.remove("input_tokens_details");check(Json.required(Costs.calculate(price,responses),"reason").equals("cached_usage_missing"),"unknown cache with different rates remains unknown");
        JsonObject missing=price.deepCopy();missing.remove("outputPerMillion");check(Json.required(Costs.calculate(missing,chat),"status").equals("unknown"),"missing price remains unknown");JsonObject invalid=chat.deepCopy();Json.object(invalid,"prompt_tokens_details").addProperty("cached_tokens",1001);check(Json.required(Costs.calculate(price,invalid),"status").equals("unknown"),"cache count cannot exceed input");
        Json.object(chat,"prompt_tokens_details").addProperty("cache_write_tokens",10);check(Json.required(Costs.calculate(price,chat),"reason").equals("usage_category_unpriced"),"unpriced cache writes not silently ordinary input");
    }
    static void workflow(Path root)throws Exception{Path data=root.resolve("cost-rerun-data");String comparisonId,evaluationId,versionId;
        try(EngineTest.Mock mock=new EngineTest.Mock()){
            try(Engine e=new Engine(data)){JsonObject provider=EngineTest.provider(e,mock,"responses");String providerId=Json.required(provider,"id");provider=e.providers.save(Json.obj("id",providerId,"pricing",pricing("CNY",2,2,3)));JsonObject project=EngineTest.project(e,"detect");String pid=Json.required(project,"id");JsonArray ids=EngineTest.importSamples(e,pid,2);String first=ids.get(0).getAsString();
                JsonObject set=cmd(e,"evaluationSet.create",Json.obj("projectId",pid,"name","重跑fixture","assetIds",ids));check(Json.array(set,"publishedVersions").isEmpty(),"created set exposes empty published versions");JsonObject truth=EngineTest.label("detect");truth.addProperty("id","TRUTH_ONLY_NEVER_SEND");int revision=1;
                for(JsonElement asset:ids)revision=Json.integer(cmd(e,"evaluationSet.saveTruth",Json.obj("setId",set.get("id"),"assetId",asset,"baseTruthVersion",0,"source","manual","annotations",Json.arr(truth))),"setRevision",0);JsonObject version=cmd(e,"evaluationSet.publish",Json.obj("setId",set.get("id"),"baseSetRevision",revision));versionId=Json.required(version,"id");
                JsonObject spec=Json.obj("providerId",providerId,"model","fixture","prompt","locate items","concurrency",1,"maxRetries",0),request=Json.obj("setVersionId",versionId,"schemes",Json.arr(spec,spec.deepCopy()),"budgetScopeId","fresh-fixture","maxRequests",4);
                JsonObject insufficient=request.deepCopy();insufficient.addProperty("maxRequests",3);check(!Json.bool(cmd(e,"evaluation.rerun.preflight",insufficient),"canStart",true),"insufficient total budget preflight");ManualChainTest.rejects("evaluation_budget_insufficient",()->cmd(e,"evaluation.rerun.create",insufficient));check(e.store.read(c->Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM runs"),"n",0))==0&&mock.calls.get()==0,"failed preflight creates no partial runs or calls");
                JsonObject leaked=request.deepCopy();Json.array(leaked,"schemes").get(0).getAsJsonObject().add("referenceAssetIds",Json.arr(first));e.projects.save(Json.obj("assetId",first,"baseVersion",0,"confirm",true,"annotations",Json.arr(EngineTest.label("detect"))));ManualChainTest.rejects("evaluation_reference_overlap",()->cmd(e,"evaluation.rerun.create",leaked));
                JsonObject dollar=e.providers.save(Json.obj("name","美元fixture","baseUrl",mock.url(),"protocol","responses","pricing",pricing("USD",2,2,3)));e.providers.credential(Json.obj("providerId",dollar.get("id"),"key","fixture-secret-never-persist"));JsonObject mixed=request.deepCopy();Json.array(mixed,"schemes").get(1).getAsJsonObject().add("providerId",dollar.get("id"));ManualChainTest.rejects("budget_currency_mismatch",()->cmd(e,"evaluation.rerun.create",mixed));check(e.store.read(c->Json.number(Store.one(c,"SELECT COUNT(*) AS n FROM runs"),"n",0))==0,"mixed currency rejection remains atomic");
                byte[] original=Files.readAllBytes(e.projects.path(first));Files.write(e.projects.path(first),new byte[]{0,1,2});JsonObject comparison=cmd(e,"evaluation.rerun.create",request);comparisonId=Json.required(comparison,"id");ManualChainTest.rejects("evaluation_runs_unfinished",()->cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparisonId)));
                for(JsonElement run:Json.array(comparison,"runIds"))check(Json.required(EngineTest.waitRun(e,run.getAsString(),15000),"status").equals("completed"),"fixed image run succeeds despite mutable baseline damage");Files.write(e.projects.path(first),original);check(mock.calls.get()==4,"two repeated configurations perform four actual calls");check(mock.bodies.stream().noneMatch(b->b.toString().contains("TRUTH_ONLY_NEVER_SEND")),"ground truth never enters model request");check(Json.integer(e.projects.asset(first),"version",0)==1&&Json.integer(e.projects.asset(ids.get(1).getAsString()),"version",-1)==0,"fresh evaluation does not promote current annotations");
                JsonObject evaluation;var finishing=java.util.concurrent.Executors.newFixedThreadPool(2);try{var one=finishing.submit(()->cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparisonId)));var two=finishing.submit(()->cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparisonId)));evaluation=one.get(10,java.util.concurrent.TimeUnit.SECONDS);check(two.get(10,java.util.concurrent.TimeUnit.SECONDS).equals(evaluation),"concurrent finishes commit one evaluation");}finally{finishing.shutdownNow();}evaluationId=Json.required(evaluation,"id");check(Json.required(evaluation,"source").equals("fresh_run_snapshot")&&Json.integer(evaluation,"pairedComparableSamples",0)==2,"fresh provenance and paired coverage");for(JsonElement scheme:Json.array(evaluation,"schemes"))check(Json.integer(Json.object(scheme.getAsJsonObject(),"metrics"),"matchedObjects",0)==2&&Json.integer(Json.object(scheme.getAsJsonObject(),"cost"),"knownCalls",0)==2,"fresh snapshots include matching and immutable run-scoped cost");check(cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparisonId)).equals(evaluation),"finish is idempotent");check(mock.calls.get()==4,"finish never sends calls");
                JsonObject cost=Json.object(cmd(e,"budget.get",Json.obj("budgetScopeId","fresh-fixture")),"cost");check(Math.abs(Json.decimal(cost,"knownCost",0)-4*0.000095)<1e-12&&Json.integer(cost,"unknownCalls",-1)==0&&!Json.bool(cost,"hardLimit",true),"reported usage priced separately from hard request cap");
                cmd(e,"review.sample",Json.obj("projectId",pid,"assetIds",ids,"seed","source-filter","count",1));check(Json.integer(cmd(e,"review.list",Json.obj("projectId",pid,"source","random")),"total",0)==1&&Json.integer(cmd(e,"review.list",Json.obj("projectId",pid,"source","truth_comparison")),"total",-1)==0,"review source pagination uses matching totals");
                JsonObject estimate=Json.obj("providerId",providerId,"model","fixture","requests",2,"inputTokensPerRequest",1000,"outputTokensPerRequest",200);e.providers.save(Json.obj("id",providerId,"pricing",pricing("CNY",2,0.5,4)));JsonObject missingCache=cmd(e,"budget.estimate",estimate);check(missingCache.get("estimatedCost").isJsonNull()&&Json.object(missingCache,"assumptions").get("cachedInputTokensPerRequest").isJsonNull(),"estimate omitted cache not silently user-zero");estimate.addProperty("cachedInputTokensPerRequest",600);check(Math.abs(Json.decimal(cmd(e,"budget.estimate",estimate),"estimatedCost",0)-0.0038)<1e-12,"explicit estimate preserves token assumptions");
                e.providers.save(Json.obj("id",providerId,"pricing",pricing("CNY",2,2,3)));cmd(e,"budget.update",Json.obj("budgetScopeId","cost-stop","maxRequests",2,"costLimit",Json.obj("currency","CNY","amount",0.00005)));JsonObject paused=e.runs.create(Json.obj("projectId",pid,"providerId",providerId,"model","fixture","prompt","locate","assetIds",ids,"budgetScopeId","cost-stop","maxRequests",2,"concurrency",1));String pausedId=Json.required(paused,"id");JsonObject stopped=EngineTest.waitRun(e,pausedId,15000);check(Json.required(stopped,"pauseReason").equals("budget_cost_exhausted")&&Json.number(stopped,"requestsUsed",0)==1,"observed cost threshold pauses remaining dispatch");
                e.providers.save(Json.obj("id",providerId,"pricing",pricing("CNY",200,200,300)));cmd(e,"budget.update",Json.obj("budgetScopeId","cost-stop","costLimit",Json.obj("currency","CNY","amount",0.001)));e.runs.control("resume",Json.obj("runId",pausedId));check(Json.required(EngineTest.waitRun(e,pausedId,15000),"status").equals("completed"),"budget increase resumes remaining work");check(Math.abs(Json.decimal(Json.object(cmd(e,"budget.get",Json.obj("budgetScopeId","cost-stop")),"cost"),"knownCost",0)-2*0.000095)<1e-12,"in-progress run keeps original prices after provider edit");ManualChainTest.rejects("budget_currency_mismatch",()->cmd(e,"budget.update",Json.obj("budgetScopeId","cost-stop","costLimit",Json.obj("currency","USD","amount",1))));
                e.providers.save(Json.obj("id",providerId,"pricing",pricing("CNY",2,2,3)));cmd(e,"budget.update",Json.obj("budgetScopeId","cost-unknown","maxRequests",2,"costLimit",Json.obj("currency","CNY","amount",1)));mock.retryOnce.set(true);JsonObject retry=e.runs.create(Json.obj("projectId",pid,"providerId",providerId,"model","fixture","prompt","locate","assetIds",Json.arr(first),"budgetScopeId","cost-unknown","maxRequests",2,"maxRetries",1,"concurrency",1));String retryId=Json.required(retry,"id");JsonObject unknown=EngineTest.waitRun(e,retryId,15000);check(Json.required(unknown,"pauseReason").equals("budget_cost_unknown")&&Json.number(unknown,"requestsUsed",0)==1,"HTTP error missing usage pauses monetary retry rather than free retry");check(Json.integer(Json.object(unknown,"budget").getAsJsonObject("cost"),"unknownCalls",0)==1,"failed usage unknown persisted");cmd(e,"budget.update",Json.obj("budgetScopeId","cost-unknown","costLimit",null));e.runs.control("resume",Json.obj("runId",retryId));check(Json.required(EngineTest.waitRun(e,retryId,15000),"status").equals("completed"),"explicitly removing cost threshold allows requested retry");
                e.store.tx(c->{JsonObject row=Store.one(c,"SELECT id,data FROM attempts LIMIT 1"),attempt=Json.parse(row.get("data").getAsString());attempt.addProperty("largeFixtureTrace","x".repeat(120000));Store.update(c,"UPDATE attempts SET data=? WHERE id=?",attempt,Json.required(row,"id"));return null;});check(cmd(e,"budget.get",Json.obj("budgetScopeId","fresh-fixture")).has("cost"),"long stored traces bypass text-input length cap");
                int beforeRace=mock.calls.get();var racing=java.util.concurrent.Executors.newFixedThreadPool(2);try{JsonObject chat=Json.obj("providerId",providerId,"model","fixture","budgetScopeId","last-request","maxRequests",1,"messages",Json.arr(Json.obj("role","user","content","hello")));java.util.concurrent.Callable<String> call=()->{try{e.providers.chat(chat);return "sent";}catch(ApiError failure){return failure.code;}};var one=racing.submit(call);var two=racing.submit(call);Set<String> outcomes=Set.of(one.get(10,java.util.concurrent.TimeUnit.SECONDS),two.get(10,java.util.concurrent.TimeUnit.SECONDS));check(outcomes.equals(Set.of("sent","budget_exhausted"))&&mock.calls.get()==beforeRace+1,"new cost integration preserves atomic last request cap; outcomes="+outcomes+" extraCalls="+(mock.calls.get()-beforeRace));}finally{racing.shutdownNow();}
                check(Json.bool(cmd(e,"system.prepareUpdate",new JsonObject()),"ready",false),"completed comparisons allow maintenance");ManualChainTest.rejects("engine_update_locked",()->cmd(e,"evaluation.rerun.create",request));ManualChainTest.rejects("engine_update_locked",()->cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparisonId)));check(cmd(e,"evaluation.rerun.get",Json.obj("comparisonId",comparisonId)).has("evaluationId")&&cmd(e,"budget.estimate",estimate).has("estimatedCost"),"new read commands remain usable under maintenance");cmd(e,"system.cancelUpdate",new JsonObject());
            }
            int calls=mock.calls.get();try(Engine e=new Engine(data)){check(Json.required(cmd(e,"evaluation.rerun.get",Json.obj("comparisonId",comparisonId)),"evaluationId").equals(evaluationId),"comparison evaluation link survives restart");check(Json.integer(Json.object(cmd(e,"budget.get",Json.obj("budgetScopeId","cost-unknown")),"cost"),"unknownCalls",0)==1,"unknown fee survives restart");check(mock.calls.get()==calls,"restart does not rerun completed comparisons");}
        }
    }
}
