package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;

final class EvaluationTest {
    static Path root;
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    static void run(Path directory)throws Exception{root=directory;migration();matching();matchingOracle();workflow();}
    static void migration()throws Exception{
        Path data=root.resolve("v1-migration");Files.createDirectories(data);try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+data.resolve("autolabel.db"));Statement s=c.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("PRAGMA user_version=1");s.execute("CREATE TABLE projects(id TEXT PRIMARY KEY,data TEXT NOT NULL)");Store.update(c,"INSERT INTO projects(id,data) VALUES(?,?)","old",Json.obj("id","old","name","保留项目","taskType","detect","classes",new JsonArray(),"settings",new JsonObject()));}
        try(Engine e=new Engine(data)){check(Json.required(e.projects.get("old"),"name").equals("保留项目"),"v1 project preserved");check(e.store.read(c->Store.one(c,"PRAGMA user_version").get("user_version").getAsInt())==Store.SCHEMA_VERSION,"current schema migration committed");}
        List<Path> backups;try(var files=Files.list(data.resolve("backups"))){backups=files.toList();}check(backups.size()==1,"one consistent migration backup");try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+backups.get(0))){check(Store.one(c,"PRAGMA user_version").get("user_version").getAsInt()==1,"backup remains v1");check(Store.one(c,"SELECT COUNT(*) AS n FROM projects").get("n").getAsInt()==1,"backup includes logical data");}
        try(Engine ignored=new Engine(data)){}try(var files=Files.list(data.resolve("backups"))){check(files.count()==1,"idempotent current schema start does not backup again");}
        Path failure=root.resolve("v1-failed");Files.createDirectories(failure);try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+failure.resolve("autolabel.db"));Statement s=c.createStatement()){s.execute("PRAGMA user_version=1");s.execute("CREATE TABLE projects(id TEXT PRIMARY KEY,data TEXT NOT NULL)");s.execute("CREATE TABLE evaluation_results(id TEXT PRIMARY KEY)");Store.update(c,"INSERT INTO projects(id,data) VALUES('old','{}')");}
        ManualChainTest.rejects("database_migration_failed",()->{try(Engine ignored=new Engine(failure)){}});try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+failure.resolve("autolabel.db"))){check(Store.one(c,"PRAGMA user_version").get("user_version").getAsInt()==1,"failed migration retains v1");check(Store.one(c,"SELECT COUNT(*) AS n FROM projects").get("n").getAsInt()==1,"failed migration retains old rows");check(Store.one(c,"SELECT COUNT(*) AS n FROM sqlite_master WHERE name='truth_versions'").get("n").getAsInt()==0,"failed migration rolls back new tables");}
    }
    static JsonObject box(String id,double x){return Json.obj("id",id,"classId","item","type","detect","bbox",Json.obj("x",x,"y",20,"width",10,"height",10));}
    static void matching(){JsonArray truth=Json.arr(box("t1",10),box("t2",16)),prediction=Json.arr(box("p1",12),box("p2",6));var pairs=Matching.maximum(truth,prediction,0.4);check(pairs.size()==2,"maximum cardinality beats greedy counterexample");check(pairs.stream().anyMatch(p->p.truth()==0&&p.prediction()==1)&&pairs.stream().anyMatch(p->p.truth()==1&&p.prediction()==0),"augmenting path repairs greedy assignment");
        var exact=Matching.maximum(Json.arr(box("t1",10),box("t2",12)),Json.arr(box("p1",10),box("p2",12)),0.1);check(Math.abs(exact.stream().mapToDouble(Matching.Pair::iou).sum()-2)<1e-9,"maximum total IoU within maximum count");JsonObject wrong=box("wrong",10);wrong.addProperty("classId","other");check(Matching.maximum(Json.arr(box("t",10)),Json.arr(wrong),0).isEmpty(),"class constraints never cross-match");
        JsonObject empty=Json.object(Matching.evaluate(new JsonArray(),new JsonArray(),0.5,100),"metrics");check(empty.get("missedRate").isJsonNull()&&empty.get("extraRate").isJsonNull(),"zero denominators are null");
        JsonObject pose=box("truth-pose",10);pose.addProperty("type","pose");pose.add("keypoints",Json.arr(Json.obj("name","a","x",10,"y",20,"visibility",2),Json.obj("name","b","x",15,"y",25,"visibility",1),Json.obj("name","c","x",0,"y",0,"visibility",0)));
        JsonObject pred=pose.deepCopy();pred.addProperty("id","pred-pose");Json.array(pred,"keypoints").get(0).getAsJsonObject().addProperty("x",20);Json.array(pred,"keypoints").get(1).getAsJsonObject().addProperty("visibility",0);Json.array(pred,"keypoints").get(2).getAsJsonObject().addProperty("visibility",2);
        JsonObject unmatched=pose.deepCopy();unmatched.addProperty("id","unmatched");Json.object(unmatched,"bbox").addProperty("x",100);JsonObject metrics=Json.object(Matching.evaluate(Json.arr(pose,unmatched),Json.arr(pred),0.5,200),"metrics");check(Json.integer(metrics,"pairedKeypoints",0)==1&&Json.integer(metrics,"missingPredictedKeypoints",0)==1,"occluded located GT and absent prediction distinguished");check(Json.integer(metrics,"ignoredUnknownTruthKeypoints",0)==2&&Json.integer(metrics,"unmatchedObjectKeypoints",0)==2,"unknown and unmatched keypoints separate");check(Math.abs(Json.decimal(metrics,"meanPointErrorNormalized",0)-0.05)<1e-9,"keypoint normalization uses diagonal and paired denominator");}
    static double[] exhaustive(JsonArray truth,JsonArray prediction,double threshold,int index,int used){
        if(index==truth.size())return new double[]{0,0};double[] best=exhaustive(truth,prediction,threshold,index+1,used);
        for(int j=0;j<prediction.size();j++){if((used&(1<<j))!=0)continue;JsonObject a=truth.get(index).getAsJsonObject(),b=prediction.get(j).getAsJsonObject();double overlap=Matching.iou(a,b);if(!Json.required(a,"classId").equals(Json.required(b,"classId"))||overlap+1e-12<threshold)continue;double[] next=exhaustive(truth,prediction,threshold,index+1,used|(1<<j));next[0]++;next[1]+=overlap;if(next[0]>best[0]||(next[0]==best[0]&&next[1]>best[1]))best=next;}
        return best;
    }
    static void matchingOracle(){Random rng=new Random(2037);boolean count=true,cost=true;
        // 小规模穷举独立于残量网络，校验最大数量和次级 IoU 目标，覆盖重叠、断边与类别混合。
        for(int sample=0;sample<80;sample++){JsonArray truth=new JsonArray(),prediction=new JsonArray();for(int i=0;i<4;i++){JsonObject a=box("t"+i,rng.nextInt(25)),b=box("p"+i,rng.nextInt(25));if(rng.nextBoolean())a.addProperty("classId","other");if(rng.nextBoolean())b.addProperty("classId","other");truth.add(a);prediction.add(b);}double threshold=(sample%3)*0.25;double[] expected=exhaustive(truth,prediction,threshold,0,0);var result=Matching.maximum(truth,prediction,threshold);count&=result.size()==expected[0];cost&=Math.abs(result.stream().mapToDouble(Matching.Pair::iou).sum()-expected[1])<1e-9;}
        check(count,"80 exhaustive fixtures agree on maximum count");check(cost,"80 exhaustive fixtures agree on maximum IoU");
    }
    static String fixtureRun(Engine e,String pid,JsonArray ids,List<JsonArray> predictions,JsonArray references)throws Exception{String rid=Json.id();return e.store.tx(c->{JsonObject project=Store.document(c,"projects",pid);JsonObject run=Json.obj("id",rid,"projectId",pid,"name","受控既有运行","status","completed_with_errors","total",ids.size(),"model","fixture","providerId","fixture","prompt","fixture only","requestsUsed",ids.size(),"createdAt",Json.now(),"snapshot",Json.obj("project",project,"references",references));Store.update(c,"INSERT INTO runs(id,project_id,status,data) VALUES(?,?,?,?)",rid,pid,"completed_with_errors",run);
            for(int i=0;i<ids.size();i++){String aid=ids.get(i).getAsString(),sid=Json.id(),attempt=Json.id();JsonObject asset=Store.document(c,"assets",aid),data=Json.obj("asset",asset,"assetId",aid);String status=predictions.get(i)==null?"failed":"succeeded";
                if(predictions.get(i)!=null){int version=Projects.nextVersion(c,aid);JsonObject candidate=asset.deepCopy();candidate.addProperty("source","api");candidate.addProperty("runId",rid);candidate.addProperty("attemptId",attempt);candidate.addProperty("version",version);candidate.add("annotations",predictions.get(i));Store.update(c,"INSERT INTO versions(asset_id,version,source,data,attempt_id,created_at) VALUES(?,?,?,?,?,?)",aid,version,"api",candidate,attempt,Json.now());data.addProperty("candidateVersion",version);}else data.addProperty("errorCode","controlled_fixture_failure");
                Store.update(c,"INSERT INTO samples(id,run_id,asset_id,input_id,status,active_attempt,data) VALUES(?,?,?,?,?,?,?)",sid,rid,aid,aid,status,attempt,data);Store.update(c,"INSERT INTO attempts(id,run_id,sample_id,group_id,status,data) VALUES(?,?,?,?,?,?)",attempt,rid,sid,"fixture",status.equals("failed")?"failed":"completed",Json.obj("id",attempt,"usage",Json.obj("input_tokens",10,"output_tokens",10),"sentAt",Json.now()));}
            return rid;});}
    static void workflow()throws Exception{
        Path data=root.resolve("evaluation-data");String evaluationId,versionId,aid0;JsonObject originalEvaluation;
        try(Engine e=new Engine(data)){JsonObject project=EngineTest.project(e,"detect");String pid=Json.required(project,"id");JsonArray ids=EngineTest.importSamples(e,pid,3);aid0=ids.get(0).getAsString();e.projects.save(Json.obj("assetId",aid0,"baseVersion",0,"annotations",Json.arr(EngineTest.label("detect")),"confirm",true));
            JsonObject set=cmd(e,"evaluationSet.create",Json.obj("projectId",pid,"name","独立人工fixture","assetIds",ids));String setId=Json.required(set,"id");check(Json.integer(set,"truthCount",-1)==0,"confirmed asset not automatically truth");ManualChainTest.rejects("evaluation_truth_incomplete",()->cmd(e,"evaluationSet.publish",Json.obj("setId",setId,"baseSetRevision",1)));
            ManualChainTest.rejects("evaluation_truth_source_invalid",()->cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",aid0,"baseTruthVersion",0,"source","api","annotations",new JsonArray())));
            JsonArray gt=Json.arr(EngineTest.label("detect"));int revision=1;for(int i=0;i<3;i++)revision=Json.integer(cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",ids.get(i),"baseTruthVersion",0,"source","manual","annotations",i==1?new JsonArray():gt,"note","合成已知答案测试，不是真实人工效率验证")),"setRevision",0);
            ManualChainTest.rejects("evaluation_truth_conflict",()->cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",aid0,"baseTruthVersion",0,"source","manual","annotations",gt)));
            JsonObject version=cmd(e,"evaluationSet.publish",Json.obj("setId",setId,"baseSetRevision",revision));versionId=Json.required(version,"id");check(Json.integer(version,"truthObjectCount",0)==2&&Json.integer(version,"sampleCount",0)==3,"published truth coverage fixed");JsonObject summary=cmd(e,"evaluationSet.get",Json.obj("setId",setId));check(!Json.array(summary,"publishedVersions").toString().contains("annotations"),"published list summary contains no truth");
            String first=fixtureRun(e,pid,ids,Arrays.asList(new JsonArray(),gt,null),new JsonArray()),second=fixtureRun(e,pid,ids,Arrays.asList(gt,new JsonArray(),gt),new JsonArray());
            JsonObject request=Json.obj("setVersionId",versionId,"schemes",Json.arr(Json.obj("runId",first),Json.obj("runId",second)));JsonObject preflight=cmd(e,"evaluation.preflight",request);check(Json.bool(preflight,"canEvaluate",false)&&Json.integer(preflight,"pairedComparableSamples",0)==2,"same fixed samples and paired availability");long attempts=e.store.read(c->Store.one(c,"SELECT COUNT(*) AS n FROM attempts").get("n").getAsLong());JsonObject evaluation=cmd(e,"evaluation.create",request);evaluationId=Json.required(evaluation,"id");originalEvaluation=evaluation.deepCopy();
            JsonObject metrics=Json.object(Json.array(evaluation,"schemes").get(0).getAsJsonObject(),"metrics");check(Json.integer(metrics,"failedSamples",0)==1&&Json.integer(metrics,"scorableSamples",0)==2,"failure is separate from successful no-target");check(Json.integer(metrics,"totalTruthObjects",0)==2&&Json.integer(metrics,"scorableTruthObjects",0)==1,"full truth denominator and scorable denominator explicit");check(Json.integer(metrics,"missedObjects",0)==1&&Json.integer(metrics,"extraObjects",0)==1,"missed and extra counted on successful outputs");check(e.store.read(c->Store.one(c,"SELECT COUNT(*) AS n FROM attempts").get("n").getAsLong())==attempts,"existing-run evaluation causes no calls");
            JsonObject details=cmd(e,"evaluation.results",Json.obj("evaluationId",evaluationId,"limit",2));check(Json.array(details,"items").size()==2&&Json.integer(details,"total",0)==6,"evaluation results paginate");check(Json.required(Json.array(details,"items").get(0).getAsJsonObject(),"mediaUrl").startsWith("autolabel-media://evaluation/"+versionId),"frozen image media reference");
            cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",aid0,"baseTruthVersion",1,"source","manual","annotations",new JsonArray()));check(cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).equals(originalEvaluation),"truth revision does not rewrite existing evaluation");check(Json.array(Json.object(Json.array(new EvaluationSets(e.store,e.projects).version(versionId),"assets").get(0).getAsJsonObject(),"truth"),"annotations").size()==1,"published truth remains original version");
            JsonObject reference=e.projects.asset(ids.get(0).getAsString()).deepCopy();reference.addProperty("id",Json.id());String leaked=fixtureRun(e,pid,ids,Arrays.asList(gt,new JsonArray(),gt),Json.arr(reference));JsonObject leakRequest=Json.obj("setVersionId",versionId,"schemes",Json.arr(Json.obj("runId",leaked)));check(!Json.bool(cmd(e,"evaluation.preflight",leakRequest),"canEvaluate",true),"different asset ID same content reference blocked");ManualChainTest.rejects("evaluation_reference_overlap",()->cmd(e,"evaluation.create",leakRequest));
            JsonObject sourceReference=e.projects.asset(ids.get(1).getAsString()).deepCopy();Json.object(sourceReference,"metadata").addProperty("parentAssetId",aid0);sourceReference.addProperty("id",Json.id());check(Evaluations.overlap(EvaluationSets.input(sourceReference),Json.array(version,"assets").get(0).getAsJsonObject()),"known parent source group blocks leakage across different image hashes");
            JsonObject review=cmd(e,"review.build",Json.obj("evaluationId",evaluationId));check(Json.integer(review,"created",0)==3,"review derives missed extra failure facts");JsonObject repeated=cmd(e,"review.build",Json.obj("evaluationId",evaluationId));check(Json.integer(repeated,"created",-1)==0&&Json.integer(repeated,"existing",0)==3,"review build idempotent");JsonObject item=Json.array(review,"items").get(0).getAsJsonObject();ManualChainTest.rejects("review_version_conflict",()->cmd(e,"review.resolve",Json.obj("itemId",item.get("id"),"baseCandidateVersion",999,"action","checked")));cmd(e,"review.resolve",Json.obj("itemId",item.get("id"),"baseCandidateVersion",item.get("candidateVersion"),"action","checked"));check(Json.integer(e.projects.asset(aid0),"version",0)==1,"review does not alter formal annotation");
            JsonObject random=cmd(e,"review.sample",Json.obj("projectId",pid,"assetIds",ids,"seed","fixed-seed","count",2)),random2=cmd(e,"review.sample",Json.obj("projectId",pid,"assetIds",ids,"seed","fixed-seed","count",2));check(Json.array(random,"assetVersions").equals(Json.array(random2,"assetVersions")),"random selection reproducible");JsonObject sampled=cmd(e,"review.list",Json.obj("projectId",pid,"sampleId",random.get("id")));check(Json.integer(sampled,"total",0)==2&&Json.required(Json.array(sampled,"items").get(0).getAsJsonObject(),"source").equals("random"),"random review kept separate from directed errors");
            snapshotEdges(e,pid,ids,gt,versionId);
            check(Json.bool(cmd(e,"system.prepareUpdate",new JsonObject()),"ready",false),"idle evaluation engine update ready");ManualChainTest.rejects("engine_update_locked",()->cmd(e,"evaluationSet.saveTruth",new JsonObject()));check(cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).has("projectId"),"evaluation read permitted while update locked");cmd(e,"system.cancelUpdate",new JsonObject());
        }
        try(Engine e=new Engine(data)){check(cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).equals(originalEvaluation),"evaluation snapshot survives restart");check(new EvaluationSets(e.store,e.projects).image(versionId,aid0).toFile().isFile(),"frozen image survives restart");}
        mediaHttp(data,versionId,aid0);
    }
    static void snapshotEdges(Engine e,String pid,JsonArray ids,JsonArray gt,String version)throws Exception{
        String run=fixtureRun(e,pid,ids,Arrays.asList(gt,new JsonArray(),gt),new JsonArray());
        e.store.tx(c->{for(JsonObject row:Store.rows(c,"SELECT asset_id,version,data FROM versions WHERE json_extract(data,'$.runId')=?",run)){JsonObject value=Json.parse(Json.required(row,"data"));value.remove("annotations");Store.update(c,"UPDATE versions SET data=? WHERE asset_id=? AND version=?",value,Json.required(row,"asset_id"),Json.integer(row,"version",0));}Store.update(c,"UPDATE samples SET status='unknown' WHERE run_id=? AND asset_id=?",run,ids.get(1).getAsString());Store.update(c,"UPDATE samples SET status='queued' WHERE run_id=? AND asset_id=?",run,ids.get(2).getAsString());return null;});
        JsonObject request=Json.obj("setVersionId",version,"schemes",Json.arr(Json.obj("runId",run))),evaluation=cmd(e,"evaluation.create",request),metrics=Json.object(Json.array(evaluation,"schemes").get(0).getAsJsonObject(),"metrics");
        check(Json.integer(metrics,"scorableSamples",-1)==0&&Json.integer(metrics,"invalidSamples",0)==1&&Json.integer(metrics,"unknownSamples",0)==1&&Json.integer(metrics,"pendingSamples",0)==1,"missing annotations unknown and pending are independently unavailable");check(metrics.get("missedRate").isJsonNull()&&Json.integer(metrics,"missedObjects",-1)==0,"unavailable predictions are never empty negatives");
        JsonObject rows=cmd(e,"evaluation.results",Json.obj("evaluationId",evaluation.get("id")));JsonObject invalid=Json.array(rows,"items").get(0).getAsJsonObject();check(Json.required(invalid,"errorCode").equals("candidate_annotations_missing")&&!invalid.get("candidateVersion").isJsonNull(),"invalid candidate preserves version and diagnostic");
        JsonObject review=cmd(e,"review.build",Json.obj("evaluationId",evaluation.get("id")));check(Json.array(review,"items").asList().stream().anyMatch(item->Json.str(item.getAsJsonObject(),"reason","").equals("prediction_pending")&&Json.str(item.getAsJsonObject(),"severity","").equals("info")),"pending review states availability without claiming failure");
        e.store.tx(c->{JsonObject row=Store.one(c,"SELECT data,version FROM versions WHERE asset_id=? AND json_extract(data,'$.runId')=?",ids.get(0).getAsString(),run),value=Json.parse(Json.required(row,"data"));value.add("annotations",gt);value.addProperty("contentHash","changed-fixture");Store.update(c,"UPDATE versions SET data=? WHERE asset_id=? AND version=?",value,ids.get(0).getAsString(),Json.integer(row,"version",0));return null;});
        check(!Json.bool(cmd(e,"evaluation.preflight",request),"canEvaluate",true),"candidate input mismatch blocks preflight");ManualChainTest.rejects("evaluation_input_mismatch",()->cmd(e,"evaluation.create",request));e.store.tx(c->{Store.update(c,"UPDATE samples SET status='cancelled' WHERE run_id=?",run);return null;});
        JsonObject shifted=gt.get(0).getAsJsonObject().deepCopy();Json.object(shifted,"bbox").addProperty("x",220);String localization=fixtureRun(e,pid,ids,Arrays.asList(Json.arr(shifted),new JsonArray(),gt),new JsonArray());JsonObject compared=cmd(e,"evaluation.create",Json.obj("setVersionId",version,"schemes",Json.arr(Json.obj("runId",localization))));
        JsonObject low=cmd(e,"review.build",Json.obj("evaluationId",compared.get("id"),"rules",Json.obj("minMatchedIoU",0.9))),high=cmd(e,"review.build",Json.obj("evaluationId",compared.get("id"),"rules",Json.obj("minMatchedIoU",0.95)));
        check(Json.integer(low,"created",0)==1&&Json.integer(high,"created",0)==1,"changed localization threshold creates distinct evidence");check(Math.abs(Json.decimal(Json.object(Json.array(high,"items").get(0).getAsJsonObject(),"rules"),"minMatchedIoU",0)-0.95)<1e-9,"review retains the triggering threshold");check(Json.integer(cmd(e,"review.build",Json.obj("evaluationId",compared.get("id"),"rules",Json.obj("minMatchedIoU",0.95,"maxNormalizedPointError",0.1))),"created",-1)==0,"irrelevant rule does not duplicate localization review");
    }
    static void mediaHttp(Path data,String version,String asset)throws Exception{
        Process process=new ProcessBuilder(Path.of(System.getProperty("java.home"),"bin/java.exe").toString(),"-jar",Path.of("engine/build/autolabel-engine.jar").toAbsolutePath().toString()).redirectError(root.resolve("media-http-stderr.txt").toFile()).start();
        try{String token="evaluation-media-test-token-00000000000";var writer=process.outputWriter(java.nio.charset.StandardCharsets.UTF_8);writer.write(Json.obj("token",token,"dataDir",data.toString(),"protocolVersion",1).toString()+"\n");writer.flush();JsonObject ready=Json.parse(process.inputReader(java.nio.charset.StandardCharsets.UTF_8).readLine());String base="http://127.0.0.1:"+Json.integer(ready,"port",0);var http=java.net.http.HttpClient.newHttpClient();var uri=java.net.URI.create(base+"/evaluation-media/"+version+"/"+asset);check(http.send(java.net.http.HttpRequest.newBuilder(uri).GET().build(),java.net.http.HttpResponse.BodyHandlers.ofByteArray()).statusCode()==401,"frozen media authenticated");var response=http.send(java.net.http.HttpRequest.newBuilder(uri).header("Authorization","Bearer "+token).GET().build(),java.net.http.HttpResponse.BodyHandlers.ofByteArray());check(response.statusCode()==200&&javax.imageio.ImageIO.read(new java.io.ByteArrayInputStream(response.body()))!=null,"frozen media actual PNG served");http.send(java.net.http.HttpRequest.newBuilder(java.net.URI.create(base+"/command")).header("Authorization","Bearer "+token).POST(java.net.http.HttpRequest.BodyPublishers.ofString("{\"command\":\"engine.shutdown\"}")).build(),java.net.http.HttpResponse.BodyHandlers.ofString());check(process.waitFor(12,java.util.concurrent.TimeUnit.SECONDS),"evaluation JAR exits cleanly");}finally{process.destroyForcibly();}
    }
}
