package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import static cn.autolabel.engine.FlowIntegrationTest.*;

final class FlowLifecycleTest {
    static void run(Path root)throws Exception{parameterBoundaries(root);reviewPause(root);importRetry(root,false);importRetry(root,true);apiRetry(root);unknownRetry(root);cancelAndRestart(root);sharedBudget(root);templateChange(root);}
    static void parameterBoundaries(Path root)throws Exception{
        try(Engine e=new Engine(root.resolve("flow-parameter-boundaries"))){String pid=Json.required(EngineTest.project(e,"detect"),"id");EngineTest.importSamples(e,pid,1);JsonObject request=request(pid,Json.arr(step("filter","filter",new JsonObject()))),fractional=request.deepCopy();Json.object(fractional,"definition").addProperty("version",1.5);ManualChainTest.rejects("flow_definition_invalid",()->cmd(e,"flow.preflight",fractional));JsonObject malformed=request.deepCopy();malformed.add("execution",Json.arr("all"));ManualChainTest.rejects("flow_parameter_invalid",()->cmd(e,"flow.preflight",malformed));JsonObject disabled=api(Json.obj("id","unused"));disabled.addProperty("enabled",false);Json.object(disabled,"parameters").add("referenceResources",Json.arr(42));Json.array(Json.object(request,"definition"),"steps").add(disabled);check(!Json.bool(cmd(e,"flow.preflight",request),"canStart",true),"disabled API still validates provided nested reference parameter types");}
    }
    static JsonObject api(JsonObject provider){return step("api","api",Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","concurrency",1,"maxRetries",0));}
    static JsonObject start(Engine e,String pid,JsonArray steps,int max)throws Exception{JsonObject request=request(pid,steps);request.addProperty("maxRequests",max);return cmd(e,"flow.create",request);}
    static JsonObject timeout(Engine e,JsonObject provider,int millis){return e.store.tx(c->{JsonObject current=Store.document(c,"providers",Json.required(provider,"id"));current.addProperty("timeoutMs",millis);Store.update(c,"UPDATE providers SET data=? WHERE id=?",current,current.get("id").getAsString());return current;});}
    static String artifactRecord(Engine e,String id){return e.store.read(c->Store.document(c,"flow_artifacts",id).toString()+FlowArtifacts.items(c,id).toString());}
    static void reviewPause(Path root)throws Exception{
        try(Engine e=new Engine(root.resolve("flow-review-race"))){e.runs.suspend(true);String pid=Json.required(EngineTest.project(e,"detect"),"id");String aid=EngineTest.importSamples(e,pid,1).get(0).getAsString();cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",0,"annotations",Json.arr(EngineTest.label("detect")),"confirm",true));JsonObject created=cmd(e,"flow.create",request(pid,Json.arr(step("review","review",Json.obj("waitForHuman",true)),step("export","export",Json.obj("outputDir",root.resolve("race-export").toString())))));String fid=Json.required(created,"id");
            // 固定在 worker 已封存、父流程刚提交 pausing 的交错点，避免依赖毫秒级时序。
            e.store.tx(c->{JsonObject flow=Store.document(c,"flow_runs",fid),step=Flows.step(c,fid,"review");step.addProperty("workerActive",true);step.addProperty("status","running");flow.addProperty("status","pausing");flow.addProperty("pauseReason","user");String artifact=FlowArtifacts.create(c,flow,"review","review",FlowArtifacts.items(c,Json.required(flow,"inputArtifactId")),true);e.flows.completeStep(c,flow,step,Store.document(c,"flow_artifacts",artifact));return null;});
            check(Json.required(e.flows.get(fid),"status").equals("pausing")&&Json.required(state(e.flows.get(fid),"review"),"status").equals("needs_attention"),"review seal preserves pausing parent and durable acknowledgement gate");e.store.tx(c->e.flows.advance(c,fid));ManualChainTest.rejects("flow_review_acknowledgement_required",()->cmd(e,"flow.resume",Json.obj("flowRunId",fid)));ManualChainTest.rejects("flow_review_acknowledgement_required",()->cmd(e,"flow.retry",Json.obj("flowRunId",fid)));
            cmd(e,"flow.pause",Json.obj("flowRunId",fid));check(Json.required(state(e.flows.get(fid),"review"),"status").equals("needs_attention"),"pausing an already sealed review cannot erase its gate");e.store.tx(c->e.flows.advance(c,fid));e.flows.recover();check(Json.required(e.flows.get(fid),"pauseReason").equals("user")&&Json.required(state(e.flows.get(fid),"review"),"status").equals("needs_attention"),"recovery keeps user pause and human acknowledgement state");cmd(e,"flow.resume",Json.obj("flowRunId",fid,"acknowledgeReviewStepId","review"));e.runs.suspend(false);waitFlow(e,fid,"completed");check(e.exporter.list(pid).size()==1,"explicit review acknowledgement allows one downstream export");
        }
    }
    static void importRetry(Path root,boolean crash)throws Exception{
        try(Engine e=new Engine(root.resolve("flow-import-retry-"+crash))){e.runs.suspend(true);String pid=Json.required(EngineTest.project(e,"detect"),"id");Path good=root.resolve("retry-good-"+crash+".png"),missing=root.resolve("retry-missing-"+crash+".png");Media.sample(good,0);Media.sample(missing,1);byte[] bytes=Files.readAllBytes(missing);String fid=Json.required(cmd(e,"flow.create",request(pid,Json.arr(step("import","import",Json.obj("paths",Json.arr(good.toString(),missing.toString())))))),"id");Files.delete(missing);e.runs.suspend(false);JsonObject failed=waitFlow(e,fid,"completed_with_errors");String old=Json.required(state(failed,"import"),"outputArtifactId"),record=artifactRecord(e,old);e.runs.suspend(true);
            if(crash)e.store.tx(c->{JsonObject flow=Store.document(c,"flow_runs",fid),step=Flows.step(c,fid,"import");flow.addProperty("status","failed");step.addProperty("status","failed");step.remove("outputArtifactId");Flows.saveFlow(c,flow);Flows.saveStep(c,step);return null;});
            ManualChainTest.rejects("flow_artifact_sealed",()->e.store.tx(c->{JsonObject item=FlowArtifacts.items(c,old).get(0);item.addProperty("outcome","failed");FlowArtifacts.updateItem(c,item);return null;}));Files.write(missing,bytes);cmd(e,"flow.retry",Json.obj("flowRunId",fid,"stepId","import"));String working=e.store.read(c->Json.required(Flows.step(c,fid,"import"),"workingArtifactId"));check(!working.equals(old)&&record.equals(artifactRecord(e,old)),"import retry clones sealed artifact without changing old header or items, crash="+crash);e.runs.suspend(false);JsonObject done=waitFlow(e,fid,"completed");JsonObject artifact=cmd(e,"flow.artifact",Json.obj("artifactId",state(done,"import").get("outputArtifactId")));check(Json.integer(Json.object(artifact,"statistics"),"succeeded",0)==2&&Json.integer(e.projects.get(pid),"assetCount",0)==2,"import retry resumes only failed file and keeps successful asset, crash="+crash);check(record.equals(artifactRecord(e,old))&&Json.array(artifact,"items").asList().stream().allMatch(v->Json.str(v.getAsJsonObject(),"sourceArtifactId","").equals(old)),"retry result retains old artifact provenance, crash="+crash);
        }
    }
    static void apiRetry(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-api-retry"))){JsonObject provider=provider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,2);mock.retryOnce.set(true);String fid=Json.required(start(e,pid,Json.arr(api(provider)),3),"id");JsonObject failed=waitFlow(e,fid,"completed_with_errors");String old=Json.required(state(failed,"api"),"outputArtifactId"),record=artifactRecord(e,old),child=Json.required(state(failed,"api"),"childRunId");check(mock.calls.get()==2&&Json.integer(Json.object(state(failed,"api"),"statistics"),"failed",0)==1,"mixed API completion retains one success and one deterministic failure");cmd(e,"flow.retry",Json.obj("flowRunId",fid,"stepId","api"));JsonObject done=waitFlow(e,fid,"completed");check(mock.calls.get()==3&&Json.required(state(done,"api"),"childRunId").equals(child),"last API step retries only failed sample in original child snapshot");check(record.equals(artifactRecord(e,old))&&!Json.required(state(done,"api"),"outputArtifactId").equals(old),"API retry publishes new artifact and preserves sealed previous result");for(JsonElement id:ids)check(e.projects.history(id.getAsString()).size()==1,"successful API sample is not requested again during failed-item retry");
            String preserved=Json.required(e.flows.get(fid),"status");cmd(e,"flow.cancel",Json.obj("flowRunId",fid));check(Json.required(e.flows.get(fid),"status").equals(preserved),"cancel on completed flow leaves historical completion unchanged");
        }
    }
    static void unknownRetry(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-unknown-retry"))){JsonObject provider=provider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");EngineTest.importSamples(e,pid,1);mock.slow=true;String fid=Json.required(start(e,pid,Json.arr(api(provider)),2),"id");waitFlow(e,fid,"needs_attention");ManualChainTest.rejects("flow_unknown_retry_required",()->cmd(e,"flow.resume",Json.obj("flowRunId",fid)));ManualChainTest.rejects("flow_unknown_retry_required",()->cmd(e,"flow.retry",Json.obj("flowRunId",fid)));check(mock.calls.get()==1,"unknown result is not sent again by resume or implicit retry");mock.slow=false;cmd(e,"flow.retry",Json.obj("flowRunId",fid,"retryUnknown",true));JsonObject done=waitFlow(e,fid,"completed");check(mock.calls.get()==2&&Json.integer(Json.object(done,"statistics"),"requestsUsed",0)==2,"explicit unknown retry consumes one additional real request");
        }
    }
    static void cancelAndRestart(Path root)throws Exception{
        Path data=root.resolve("flow-cancel-restart");String fid,pid,aid;
        try(EngineTest.Mock mock=new EngineTest.Mock()){
            try(Engine e=new Engine(data)){JsonObject provider=timeout(e,provider(e,mock),5000);pid=Json.required(EngineTest.project(e,"detect"),"id");aid=EngineTest.importSamples(e,pid,1).get(0).getAsString();mock.slow=true;fid=Json.required(start(e,pid,Json.arr(api(provider),step("export","export",Json.obj("outputDir",root.resolve("cancel-export").toString()))),2),"id");DataMaintenanceTest.await(()->mock.calls.get()==1,"parent cancellation fixture request sent");cmd(e,"flow.cancel",Json.obj("flowRunId",fid));waitFlow(e,fid,"cancelled");check(e.projects.history(aid).size()==1&&Json.integer(e.projects.asset(aid),"version",-1)==0&&e.exporter.list(pid).isEmpty(),"late known response after flow cancel preserves candidate without promoting or exporting");for(String action:List.of("pause","resume","retry"))ManualChainTest.rejects("flow_cancelled",()->cmd(e,"flow."+action,Json.obj("flowRunId",fid)));}
            try(Engine e=new Engine(data)){check(Json.required(e.flows.get(fid),"status").equals("cancelled")&&mock.calls.get()==1&&e.exporter.list(pid).isEmpty(),"cancelled parent and child survive restart without dispatching downstream");}
        }
    }
    static void sharedBudget(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-shared-budget"))){JsonObject provider=provider(e,mock),second=api(provider);second.addProperty("id","api2");String pid=Json.required(EngineTest.project(e,"detect"),"id");EngineTest.importSamples(e,pid,1);String fid=Json.required(start(e,pid,Json.arr(api(provider),second),1),"id");JsonObject paused=waitFlow(e,fid,"needs_attention");check(Json.required(paused,"pauseReason").equals("budget_exhausted")&&mock.calls.get()==1&&state(paused,"api2").has("childRunId"),"second API node shares first node request budget");cmd(e,"flow.resume",Json.obj("flowRunId",fid,"maxRequests",2));JsonObject done=waitFlow(e,fid,"completed");check(mock.calls.get()==2&&Json.integer(Json.object(done,"budget"),"requestsUsed",0)==2,"raising shared budget resumes only pending second API request");
        }
    }
    static void templateChange(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-semantic-change"))){JsonObject provider=timeout(e,provider(e,mock),5000);String pid=Json.required(EngineTest.project(e,"detect"),"id"),aid=EngineTest.importSamples(e,pid,1).get(0).getAsString();mock.slow=true;String fid=Json.required(start(e,pid,Json.arr(api(provider)),1),"id");DataMaintenanceTest.await(()->mock.calls.get()==1,"semantic change request sent");JsonArray classes=Json.array(e.projects.get(pid),"classes").deepCopy();classes.get(0).getAsJsonObject().addProperty("name","新语义类别");cmd(e,"project.update",Json.obj("projectId",pid,"classes",classes));waitFlow(e,fid,"completed");check(Json.integer(e.projects.asset(aid),"version",-1)==0&&e.projects.history(aid).size()==1,"same class ID with changed semantic name keeps old-template candidate off current formal asset");}
    }
}
