package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;

final class FlowFoundationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    static void run(Path root)throws Exception{lateResults(root);bindingAndAtomic(root);}
    static void lateResults(Path root)throws Exception{
        Path data=root.resolve("flow-foundation-late");String cancelledRun,unknownRun;
        try(EngineTest.Mock mock=new EngineTest.Mock()){
            try(Engine e=new Engine(data)){mock.slow=true;JsonObject provider=EngineTest.provider(e,mock,"responses");provider=e.providers.save(Json.obj("id",provider.get("id"),"timeoutMs",5000));String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);String aid=ids.get(0).getAsString();
                JsonObject settings=Json.obj("keypointNames",Json.arr("left","right"),"keypointConnections",Json.arr(Json.arr(0,1)),"attributes",Json.obj("kind",Json.arr("normal")),"rules","FROZEN_RULE","occlusionRules","visible-only","blurRules","skip-blurred","privatePath","DO_NOT_SEND_PRIVATE_PATH");cmd(e,"project.update",Json.obj("projectId",pid,"settings",settings));e.runs.suspend(true);JsonObject run=cmd(e,"run.create",DataMaintenanceTest.request(provider,pid,ids));cancelledRun=Json.required(run,"id");check(Json.str(Json.object(run,"snapshot"),"validatorVersion","").equals(TaskTemplates.VALIDATOR_VERSION)&&Json.str(Json.object(run,"snapshot"),"requestContractVersion","").equals(TaskTemplates.REQUEST_CONTRACT_VERSION),"new run records exact validator and request contracts");cmd(e,"project.update",Json.obj("projectId",pid,"settings",Json.obj("rules","NEW_RULE_NOT_IN_OLD_REQUEST")));e.runs.suspend(false);DataMaintenanceTest.await(()->mock.calls.get()==1&&!mock.bodies.isEmpty(),"template request actually sent");
                JsonObject first=Json.array(Json.array(mock.bodies.get(0),"input").get(0).getAsJsonObject(),"content").get(0).getAsJsonObject(),instruction=Json.parse(Json.required(first,"text")),template=Json.object(instruction,"template");check(List.of("classes","keypointNames","keypointConnections","attributes","rules","occlusionRules","blurRules").stream().allMatch(template::has)&&Json.required(template,"rules").equals("FROZEN_RULE")&&!first.toString().contains("DO_NOT_SEND_PRIVATE_PATH")&&!first.toString().contains("NEW_RULE_NOT_IN_OLD_REQUEST"),"captured request contains frozen semantic whitelist only");
                cmd(e,"run.cancel",Json.obj("runId",cancelledRun));DataMaintenanceTest.await(()->Json.integer(e.runs.diagnostics(),"activeWorkers",1)==0,"late successful request drains");JsonObject cancelled=e.runs.get(cancelledRun);check(Json.required(cancelled,"status").equals("cancelled")&&Json.integer(Json.object(cancelled,"statistics"),"cancelled",0)==1&&Json.integer(Json.object(cancelled,"statistics"),"succeeded",0)==0,"late success cannot revive cancelled execution");check(Json.integer(e.projects.asset(aid),"version",-1)==0&&e.projects.history(aid).size()==1,"late candidate retained without changing current annotation");check(Json.required(e.runs.attempts(Json.obj("runId",cancelledRun)).get(0).getAsJsonObject(),"status").equals("completed"),"known late reply retains real completed attempt");
                for(String action:List.of("pause","resume","retry"))ManualChainTest.rejects("run_cancelled",()->cmd(e,"run."+action,Json.obj("runId",cancelledRun)));
                provider=e.providers.save(Json.obj("id",provider.get("id"),"timeoutMs",1000));JsonObject request=DataMaintenanceTest.request(provider,pid,ids);request.addProperty("failurePolicy","pause");unknownRun=Json.required(cmd(e,"run.create",request),"id");DataMaintenanceTest.await(()->mock.calls.get()==2,"second request actually sent");cmd(e,"run.cancel",Json.obj("runId",unknownRun));DataMaintenanceTest.await(()->Json.integer(e.runs.diagnostics(),"activeWorkers",1)==0,"cancelled timeout drains");JsonObject unknown=e.runs.get(unknownRun);check(Json.required(unknown,"status").equals("cancelled")&&Json.integer(Json.object(unknown,"statistics"),"cancelled",0)==1,"failure pause policy cannot revive cancelled task");check(Json.required(e.runs.attempts(Json.obj("runId",unknownRun)).get(0).getAsJsonObject(),"status").equals("unknown"),"cancelled timeout retains unknown remote attempt");
                JsonObject legacy=run.deepCopy();Json.object(legacy,"snapshot").remove("requestContractVersion");Json.object(legacy,"snapshot").remove("validatorVersion");JsonObject sample=e.store.read(c->Json.parse(Store.one(c,"SELECT data FROM samples WHERE run_id=?",cancelledRun).get("data").getAsString()));String oldBody=e.runs.messages(legacy,sample).toString();check(oldBody.contains("classes")&&!oldBody.contains("FROZEN_RULE")&&!Json.object(legacy,"snapshot").has("requestContractVersion"),"legacy frozen run retains old contract without backfill");
            }
            try(Engine e=new Engine(data)){check(Json.required(e.runs.get(cancelledRun),"status").equals("cancelled")&&Json.required(e.runs.get(unknownRun),"status").equals("cancelled"),"cancelled terminal states survive restart");check(Json.required(e.runs.attempts(Json.obj("runId",unknownRun)).get(0).getAsJsonObject(),"status").equals("unknown")&&mock.calls.get()==2,"restart retains uncertainty without another request");}
        }
    }
    static void bindingAndAtomic(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-foundation-binding"))){JsonObject provider=EngineTest.provider(e,mock,"responses");String providerId=Json.required(provider,"id"),pid=Json.required(EngineTest.project(e,"detect"),"id"),bindingA=Json.id(),bindingB=Json.id();JsonArray ids=EngineTest.importSamples(e,pid,1);e.runs.suspend(true);cmd(e,"credential.set",Json.obj("providerId",providerId,"key","fixture-secret-A","credentialBindingVersion",bindingA));JsonObject request=DataMaintenanceTest.request(provider,pid,ids);Runs.Prepared prepared=e.store.read(c->e.runs.prepare(request,Json.id(),Store.document(c,"projects",pid),provider,new JsonArray(),Store.rows(c,"SELECT data,path FROM assets WHERE project_id=?",pid)));
            ManualChainTest.rejects("fixture_abort",()->e.store.tx(c->{Runs.insert(c,prepared);throw new ApiError(409,"fixture_abort","模拟父步骤写入失败");}));check(e.store.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM runs"),"n",1))==0&&e.store.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM samples"),"n",1))==0&&e.store.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM budgets"),"n",1))==0,"child run samples and budget roll back with caller transaction");
            JsonObject run=cmd(e,"run.create",request);String rid=Json.required(run,"id");check(Json.str(Json.object(run,"snapshot"),"credentialBindingVersion","").equals(bindingA),"new run freezes non-secret credential binding");Providers.Credential captured=e.providers.credentialFor(provider,Json.object(run,"snapshot"));cmd(e,"credential.set",Json.obj("providerId",providerId,"key","fixture-secret-B","credentialBindingVersion",bindingB));check(!e.providers.redact(Json.obj("nested",Json.arr(Json.obj("message","echo fixture-secret-A and fixture-secret-B"))),captured).toString().contains("fixture-secret"),"trace masks captured request credential even after key rotation");e.runs.suspend(false);DataMaintenanceTest.await(()->Json.str(e.runs.get(rid),"status","").equals("paused"),"binding mismatch stops queued run");check(Json.str(e.runs.get(rid),"pauseReason","").equals("credential_binding_changed")&&mock.calls.get()==0&&Json.integer(e.runs.get(rid),"requestsUsed",-1)==0,"binding mismatch does not reserve budget or send");cmd(e,"credential.set",Json.obj("providerId",providerId,"key","fixture-secret-A","credentialBindingVersion",bindingA));cmd(e,"run.resume",Json.obj("runId",rid));check(Json.required(EngineTest.waitRun(e,rid,10000),"status").equals("completed")&&mock.calls.get()==1,"same persisted binding can resume after reinjection");check(!e.providers.get(providerId).toString().contains("fixture-secret")&&!e.runs.get(rid).toString().contains("fixture-secret"),"credential value never enters provider or run snapshots");
        }
    }
}
