package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;

final class FlowIntegrationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    static JsonObject step(String id,String kind,JsonObject p){return Json.obj("id",id,"kind",kind,"enabled",true,"parameters",p);}
    static JsonObject request(String pid,JsonArray steps){return Json.obj("projectId",pid,"definition",Json.obj("version",1,"name","真实流程 fixture","steps",steps),"input",Json.obj("source","project","selection","all"));}
    static JsonObject waitFlow(Engine e,String id,String expected)throws Exception{long until=System.currentTimeMillis()+15000;JsonObject flow;do{flow=e.flows.get(id);String status=Json.required(flow,"status");if(status.equals(expected))return flow;if(Set.of("failed","cancelled","completed","completed_with_errors").contains(status)&&!expected.equals(status))throw new AssertionError("Unexpected flow: "+flow);Thread.sleep(20);}while(System.currentTimeMillis()<until);throw new AssertionError("Flow timeout: "+flow);}
    static JsonObject state(JsonObject flow,String id){return Json.array(flow,"steps").asList().stream().map(JsonElement::getAsJsonObject).filter(step->Json.required(step,"stepId").equals(id)).findFirst().orElseThrow();}
    static JsonObject provider(Engine e,EngineTest.Mock mock)throws Exception{JsonObject provider=EngineTest.provider(e,mock,"responses");e.store.tx(c->{JsonObject current=Store.document(c,"providers",Json.required(provider,"id")),tests=new JsonObject();for(String capability:List.of("image","multiImage","structured"))tests.add(capability,Json.obj("status","verified","revision",current.get("revision"),"model","fixture"));current.add("capabilities",Json.obj("fixture",tests));Store.update(c,"UPDATE providers SET data=? WHERE id=?",current,Json.required(current,"id"));return null;});return e.providers.get(Json.required(provider,"id"));}
    static void run(Path root)throws Exception{workflow(root);pauseImport(root);failureAndRecovery(root);migration(root);EvaluationTest.root=root;EvaluationTest.migration();FlowLifecycleTest.run(root);}
    static void workflow(Path root)throws Exception{
        Path data=root.resolve("flow-chain"),exports=Files.createDirectories(root.resolve("流程 导出")),archives=Files.createDirectories(root.resolve("流程 备份")),restore=Files.createDirectories(root.resolve("流程 恢复"));String fid,artifactId,pid;
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(data)){JsonObject provider=provider(e,mock);pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);String aid=ids.get(0).getAsString();JsonArray original=Json.arr(EngineTest.label("detect"));cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",0,"annotations",original,"confirm",true));Path added=root.resolve("flow-added.png");Media.sample(added,2);
            JsonObject api=Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","concurrency",1,"maxRetries",0);JsonArray steps=Json.arr(step("import","import",Json.obj("paths",Json.arr(added.toString()))),step("pick","filter",Json.obj("assetIds",ids)),step("label","api",api),step("review","review",Json.obj("waitForHuman",true,"randomSample",Json.obj("count",1,"seed","fixed"))),step("export","export",Json.obj("outputDir",exports.toString(),"trainRatio",0.8)));JsonObject start=request(pid,steps);start.addProperty("maxRequests",3);start.addProperty("budgetScopeId","flow-shared");
            JsonObject missing=request(pid,Json.arr(step("api","api",new JsonObject()),step("export","export",new JsonObject())));JsonObject preflight=cmd(e,"flow.preflight",missing);check(!Json.bool(preflight,"canStart",true)&&Json.array(preflight,"issues").size()>=3,"preflight reports missing API export and budget without executing");check(mock.calls.get()==0,"missing preflight issues cause no requests");ManualChainTest.rejects("flow_preflight_failed",()->cmd(e,"flow.create",missing));
            JsonObject empty=start.deepCopy();empty.add("input",Json.obj("source","project","selection","explicit","assetIds",new JsonArray()));ManualChainTest.rejects("flow_input_limit",()->cmd(e,"flow.preflight",empty));JsonObject invalid=start.deepCopy();Json.array(Json.object(invalid,"definition"),"steps").get(1).getAsJsonObject().add("parameters",Json.obj("assetIds",new JsonArray()));check(!Json.bool(cmd(e,"flow.preflight",invalid),"canStart",true),"empty filter selection is rejected");
            JsonObject single=start.deepCopy();single.add("execution",Json.obj("mode","single","stepId","export"));check(!Json.bool(cmd(e,"flow.preflight",single),"canStart",true),"non-first single step requires explicit artifact");
            check(Json.bool(cmd(e,"flow.preflight",start),"canStart",false),"five real nodes pass preflight");JsonObject flow=cmd(e,"flow.create",start);fid=Json.required(flow,"id");String initialArtifact=Json.required(flow,"inputArtifactId");JsonObject frozenInput=e.store.read(c->FlowArtifacts.items(c,initialArtifact).get(0));check(!frozenInput.has("willAnnotate"),"preflight inference does not leak into saved input");flow=waitFlow(e,fid,"needs_attention");check(Json.required(flow,"pauseReason").equals("review")&&mock.calls.get()==1,"API completes one actual call then waits for human review");check(Json.integer(Json.object(flow,"statistics"),"stepsCompleted",0)==3,"only actually completed steps counted before manual gate");check(Json.integer(e.projects.get(pid),"assetCount",0)==2,"import actually persisted added image");check(Json.integer(e.projects.asset(aid),"version",0)==1,"API step preserves confirmed current annotation");
            ManualChainTest.rejects("flow_review_acknowledgement_required",()->cmd(e,"flow.resume",Json.obj("flowRunId",fid)));artifactId=Json.required(state(flow,"review"),"outputArtifactId");JsonObject artifact=cmd(e,"flow.artifact",Json.obj("artifactId",artifactId));check(Json.required(artifact,"projectId").equals(pid)&&!artifact.toString().contains("inputPath")&&Json.array(artifact,"items").size()==2,"artifact is paged project scoped and hides managed paths");
            JsonObject changed=EngineTest.label("detect");Json.object(changed,"bbox").addProperty("x",215);JsonObject edited=cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",1,"annotations",Json.arr(changed),"confirm",true));check(Json.integer(edited,"version",0)==3,"manual save follows independently stored API candidate version");cmd(e,"flow.resume",Json.obj("flowRunId",fid,"acknowledgeReviewStepId","review"));flow=waitFlow(e,fid,"completed");JsonObject exported=cmd(e,"flow.artifact",Json.obj("artifactId",state(flow,"export").get("outputArtifactId")));String exportId=Json.required(exported,"exportId");JsonObject fixed=new ExportHistory(e.store).fixed(exportId).manifest();JsonObject saved=Json.array(fixed,"assets").get(0).getAsJsonObject();check(Json.integer(saved,"version",0)==1&&Json.decimal(Json.object(Json.array(saved,"annotations").get(0).getAsJsonObject(),"bbox"),"x",0)==200,"export uses fixed protected version after live manual edit");check(Json.integer(e.projects.asset(aid),"version",0)==3,"fixed export never restores old data over live manual version");
            JsonArray events=(JsonArray)e.command("event.list",Json.obj("flowRunId",fid));String child=Json.required(state(flow,"label"),"childRunId");check(events.asList().stream().anyMatch(value->{JsonObject event=value.getAsJsonObject();return Json.str(event,"type","").equals("sample.succeeded")&&Json.str(event,"flowRunId","").equals(fid)&&Json.str(event,"stepId","").equals("label")&&Json.str(event,"runId","").equals(child);}),"durable sample event binds flow real step and child run once");check(Json.array(cmd(e,"flow.list",Json.obj("projectId",pid,"limit",1)),"items").size()==1,"flow list returns items and total");
            JsonObject rerun=cmd(e,"flow.rerun",Json.obj("flowRunId",fid,"fromStepId","export"));JsonObject next=waitFlow(e,Json.required(Json.object(rerun,"run"),"id"),"completed");check(Json.integer(next,"revision",0)==2&&Json.array(rerun,"invalidatedStepIds").equals(Json.arr("export"))&&state(next,"review").has("inheritedFrom")&&mock.calls.get()==1,"export rerun inherits fixed upstream with no extra API request");
            single.add("input",Json.obj("source","artifact","artifactId",artifactId));JsonObject singleRun=waitFlow(e,Json.required(cmd(e,"flow.create",single),"id"),"completed");check(Json.integer(Json.object(singleRun,"statistics"),"stepsTotal",0)==1&&mock.calls.get()==1,"artifact single execution runs only requested node");
            JsonObject owner=Json.obj("operationId","flow-backup-owner");check(Json.bool(cmd(e,"system.prepareDataMaintenance",owner),"ready",false),"completed flows allow data maintenance");JsonObject backup=cmd(e,"backup.create",Json.obj("operationId","flow-backup-owner","outputDir",archives.toString()));JsonObject prepared=cmd(e,"restore.prepare",Json.obj("operationId","flow-backup-owner","backupPath",backup.get("backupPath"),"targetParent",restore.toString()));try(Engine restored=new Engine(Path.of(Json.required(prepared,"dataDir")))){check(Json.required(restored.flows.get(fid),"status").equals("completed"),"flow state survives full backup restore");JsonObject fixedArtifact=cmd(restored,"flow.artifact",Json.obj("artifactId",artifactId));check(Json.integer(fixedArtifact,"total",0)==2,"fixed artifact survives full backup restore");for(JsonObject item:restored.store.read(c->FlowArtifacts.items(c,artifactId)))if(FlowArtifacts.included(item))check(Path.of(Json.required(item,"inputPath")).startsWith(restored.store.root)&&Files.isRegularFile(Path.of(Json.required(item,"inputPath"))),"restored flow artifact input is relocated and readable");}cmd(e,"system.cancelDataMaintenance",owner);
        }
    }
    static void pauseImport(Path root)throws Exception{
        try(Engine e=new Engine(root.resolve("flow-import-pause"))){String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray paths=new JsonArray();for(int i=0;i<3;i++){Path path=root.resolve("pause-import-"+i+".png");Media.sample(path,i);paths.add(path.toString());}JsonObject start=request(pid,Json.arr(step("import","import",Json.obj("paths",paths)),step("filter","filter",new JsonObject())));String id;
            synchronized(e.projects.media){id=Json.required(cmd(e,"flow.create",start),"id");DataMaintenanceTest.await(()->Json.integer(e.flows.diagnostics(),"activeWorkers",0)>0,"local import worker really starts");cmd(e,"flow.pause",Json.obj("flowRunId",id));}JsonObject paused=waitFlow(e,id,"paused");int count=Json.integer(e.projects.get(pid),"assetCount",0);check(count<3&&Json.required(paused,"pauseReason").equals("user"),"pause stops remaining file dispatch");cmd(e,"flow.resume",Json.obj("flowRunId",id));waitFlow(e,id,"completed");check(Json.integer(e.projects.get(pid),"assetCount",0)==3,"resume imports each fixed file once without enlarging scope");
        }
    }
    static void failureAndRecovery(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("flow-failure"))){JsonObject provider=provider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");EngineTest.importSamples(e,pid,1);mock.retryOnce.set(true);JsonObject start=request(pid,Json.arr(step("api","api",Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","maxRetries",0)),step("review","review",new JsonObject()),step("export","export",Json.obj("outputDir",root.resolve("failure-export").toString()))));start.addProperty("maxRequests",2);JsonObject run=cmd(e,"flow.create",start);JsonObject failed=waitFlow(e,Json.required(run,"id"),"failed");JsonObject artifact=cmd(e,"flow.artifact",Json.obj("artifactId",state(failed,"api").get("outputArtifactId")));check(Json.integer(Json.object(artifact,"statistics"),"failed",0)==1&&Json.integer(Json.object(artifact,"statistics"),"succeeded",1)==0,"failed request stays failed rather than a valid empty label");check(e.exporter.list(pid).isEmpty(),"all failed API flow cannot publish an empty dataset");ManualChainTest.rejects("flow_rerun_required",()->cmd(e,"flow.retry",Json.obj("flowRunId",run.get("id"),"stepId","api")));}
    }
    static void migration(Path root)throws Exception{
        Path data=root.resolve("flow-schema2-migration");try(Store store=new Store(data)){new Projects(store).create(Json.obj("name","旧项目","taskType","detect"));}
        try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+data.resolve("autolabel.db"));Statement s=c.createStatement()){s.execute("DROP TABLE flow_artifact_items");s.execute("DROP TABLE flow_artifacts");s.execute("DROP TABLE flow_steps");s.execute("DROP TABLE flow_runs");s.execute("DROP INDEX events_flow");s.execute("ALTER TABLE events DROP COLUMN step_id");s.execute("ALTER TABLE events DROP COLUMN flow_run_id");s.execute("PRAGMA user_version=2");}
        try(Engine e=new Engine(data)){check(Json.integer(cmd(e,"diagnostics.get",new JsonObject()),"databaseVersion",0)==Store.SCHEMA_VERSION&&e.projects.list().size()==1,"schema2 upgrades to current schema without losing project");try(var files=Files.list(data.resolve("backups"))){check(files.anyMatch(path->path.getFileName().toString().startsWith("schema-v2-")),"schema2 migration creates consistent backup first");}}
        try(Engine e=new Engine(data)){check(e.projects.list().size()==1,"current schema migration reopens idempotently");}
    }
}
