package cn.autolabel.engine;

import com.google.gson.*;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.atomic.*;

public final class ImageScreeningTest {
    private static int checks;
    private static Path root;
    private record Fixture(JsonObject input,ImageScreening.Feature feature){}
    private interface Action{void run()throws Exception;}
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    private static void rejects(String code,Action action)throws Exception{try{action.run();throw new AssertionError("Expected "+code);}catch(ApiError error){check(error.code.equals(code),"Expected "+code+", got "+error.code);}}

    public static void main(String[] args)throws Exception{
        root=Files.createTempDirectory("autolabel-screening-");Fixture sharp=fixture("sharp",texture(120,96,0)),bright=fixture("bright",texture(120,96,20)),blurred=fixture("blurred",blur(texture(120,96,0),5));
        metrics(sharp,bright,blurred);plans(sharp,bright,blurred);budgetsAndIdentity(sharp);invalidAndCancellation(sharp);
        System.out.println("Image screening: "+checks+" checks passed; isolated fixtures: "+root);
    }
    private static Fixture fixture(String id,BufferedImage image)throws Exception{Path path=root.resolve(id+".png");ImageIO.write(image,"png",path.toFile());JsonObject input=Json.obj("assetId",id,"inputPath",path.toString(),"contentHash",Media.hash(path),"width",image.getWidth(),"height",image.getHeight(),"normalizationVersion",Media.NORMALIZATION_VERSION,"inputVersion",1,"version",0,"status","unlabeled","source","import");image.flush();return new Fixture(input,ImageScreening.feature(input,null));}
    private static BufferedImage texture(int width,int height,int brightness){BufferedImage image=new BufferedImage(width,height,BufferedImage.TYPE_INT_RGB);for(int y=0;y<height;y++)for(int x=0;x<width;x++){int value=40+((x/5+y/7)%2)*105+(x*3+y*5)%21+brightness;image.setRGB(x,y,(value<<16)|(value<<8)|value);}return image;}
    private static BufferedImage blur(BufferedImage source,int radius){BufferedImage result=new BufferedImage(source.getWidth(),source.getHeight(),BufferedImage.TYPE_INT_RGB);for(int y=0;y<source.getHeight();y++)for(int x=0;x<source.getWidth();x++){long sum=0;int n=0;for(int yy=Math.max(0,y-radius);yy<=Math.min(source.getHeight()-1,y+radius);yy++)for(int xx=Math.max(0,x-radius);xx<=Math.min(source.getWidth()-1,x+radius);xx++){sum+=source.getRGB(xx,yy)&255;n++;}int value=(int)(sum/n);result.setRGB(x,y,(value<<16)|(value<<8)|value);}source.flush();return result;}
    private static JsonArray inputs(Fixture...fixtures){JsonArray inputs=new JsonArray();for(Fixture fixture:fixtures)inputs.add(fixture.input.deepCopy());return inputs;}
    private static List<ImageScreening.Feature> features(Fixture...fixtures){return Arrays.stream(fixtures).map(Fixture::feature).toList();}
    private static JsonObject row(JsonObject plan,String id){for(JsonElement value:Json.array(plan,"items"))if(Json.required(value.getAsJsonObject(),"assetId").equals(id))return value.getAsJsonObject();throw new AssertionError("Missing "+id);}
    private static boolean reason(JsonObject row,String code){for(JsonElement value:Json.array(row,"reasons"))if(Json.required(value.getAsJsonObject(),"code").equals(code))return true;return false;}

    private static void metrics(Fixture sharp,Fixture bright,Fixture blurred)throws Exception{
        check(sharp.feature.featureVersion().contains("floor-bins")&&sharp.feature.featureVersion().contains("interior-pop"),"feature version fixes sampling and boundary policy");check(sharp.feature.analysisWidth()==120&&sharp.feature.analysisHeight()==96,"analysis does not upscale small baselines");
        check(sharp.feature.laplacianVariance()>blurred.feature.laplacianVariance()*5,"actual sharp texture has substantially higher Laplacian variance than its box blur");check(sharp.feature.dHash64().equals(bright.feature.dHash64()),"unclipped brightness shift preserves coarse gradient hash");check(!sharp.feature.contentHash().equals(bright.feature.contentHash()),"different brightness remains different exact content");
        check(ImageScreening.feature(sharp.input,null).equals(sharp.feature),"feature computation is reproducible");JsonObject serialized=sharp.feature.json();serialized.addProperty("dHash64","0000000000000000");check(ImageScreening.feature(sharp.input,null).equals(sharp.feature),"feature JSON snapshots cannot mutate cached records");
        Fixture large=fixture("large",texture(600,300,0));check(large.feature.analysisWidth()==256&&large.feature.analysisHeight()==128,"large baseline keeps aspect ratio at fixed analysis edge");
        BufferedImage checker=new BufferedImage(256,256,BufferedImage.TYPE_INT_RGB);for(int y=0;y<256;y++)for(int x=0;x<256;x++)checker.setRGB(x,y,(x+y)%2==0?0:0xffffff);Fixture extreme=fixture("checker",checker);check(Math.abs(extreme.feature.laplacianVariance()-1040400)<0.000001,"maximum contrast remains valid at the floating point variance boundary");
        Fixture tiny=fixture("tiny",texture(1,1,0));check(tiny.feature.laplacianVariance()==null,"tiny image has no invented blur score");JsonObject tinyPlan=ImageScreening.plan(inputs(tiny),features(tiny),Json.obj("blurEnabled",true,"blurThreshold",10),null);check(Json.required(tinyPlan,"status").equals("incomplete")&&Json.array(tinyPlan,"unexaminedBlurAssetIds").size()==1,"unavailable blur score remains explicitly unexamined");
        System.out.println("Sharp/blur analysis variance: "+sharp.feature.laplacianVariance()+" / "+blurred.feature.laplacianVariance());
    }

    private static void plans(Fixture sharp,Fixture bright,Fixture blurred)throws Exception{
        JsonArray fixed=inputs(sharp,bright,blurred);fixed.get(0).getAsJsonObject().addProperty("partition","train");fixed.get(1).getAsJsonObject().addProperty("partition","val");fixed.get(2).getAsJsonObject().addProperty("status","confirmed");fixed.get(2).getAsJsonObject().addProperty("version",7);
        fixed.get(0).getAsJsonObject().addProperty("sourceVideoId","video-a");fixed.get(1).getAsJsonObject().addProperty("sourceVideoId","video-a");JsonObject options=Json.obj("nearMaxDistance",0,"blurEnabled",true,"blurThreshold",(sharp.feature.laplacianVariance()+blurred.feature.laplacianVariance())/2);
        String before=fixed.toString();JsonObject plan=ImageScreening.plan(fixed,features(sharp,bright,blurred),options,null);check(fixed.toString().equals(before),"fixed caller inputs remain untouched");check(Json.array(plan,"nearPairs").size()>=1,"brightness variant is a near duplicate candidate");
        JsonObject pair=Json.array(plan,"nearPairs").get(0).getAsJsonObject();check(Json.integer(pair,"distance",-1)==0&&Json.required(pair,"action").equals("candidate_only")&&Json.bool(pair,"requiresReview",false),"zero gradient distance is still only a candidate");check(Json.bool(pair,"crossPartition",false),"near pair shows cross-partition risk");check(Json.array(plan,"sourceLeakageGroups").size()==1,"same source video across partitions is grouped without Cartesian expansion");
        JsonObject human=row(plan,"blurred");check(Json.required(human,"recommendation").equals("keep_protected")&&reason(human,"blur_candidate")&&Json.integer(Json.object(human,"input"),"version",-1)==7,"blur score cannot remove or rewrite human version");check(Json.required(row(plan,"sharp"),"recommendation").equals("keep"),"near match alone never suggests exclusion");check(!Json.bool(plan,"changesApplied",true)&&!Json.bool(plan,"identityMerge",true),"plan applies no changes or identity merges");
        JsonArray reversed=new JsonArray();for(int i=fixed.size()-1;i>=0;i--)reversed.add(fixed.get(i));List<ImageScreening.Feature> reverseFeatures=new ArrayList<>(features(sharp,bright,blurred));Collections.reverse(reverseFeatures);check(plan.equals(ImageScreening.plan(reversed,reverseFeatures,options,null)),"input and cache ordering cannot change the screening plan");
        BufferedImage original=texture(120,96,0),wide=new BufferedImage(240,96,BufferedImage.TYPE_INT_RGB);for(int y=0;y<96;y++)for(int x=0;x<240;x++)wide.setRGB(x,y,original.getRGB(x/2,y));original.flush();Fixture stretched=fixture("stretched",wide);JsonObject incompatible=ImageScreening.plan(inputs(sharp,stretched),features(sharp,stretched),Json.obj("nearMaxDistance",64),null);check(Json.array(incompatible,"nearPairs").isEmpty()&&Json.number(Json.object(incompatible,"nearCheck"),"aspectIncompatibleContentPairs",0)==1,"different aspect ratios are explicitly outside configured comparison scope");
        JsonObject permissive=ImageScreening.plan(inputs(sharp,stretched),features(sharp,stretched),Json.obj("nearMaxDistance",64,"aspectRatioTolerance",0.6),null);check(Json.array(permissive,"nearPairs").size()==1,"aspect tolerance is an explicit configurable heuristic");
        rejects("screening_parameters_invalid",()->ImageScreening.plan(inputs(sharp),features(sharp),Json.obj("blurEnabled",true),null));
    }

    private static void budgetsAndIdentity(Fixture sharp)throws Exception{
        List<Fixture> pool=new ArrayList<>();for(int i=0;i<5;i++)pool.add(fixture("budget-"+i,texture(120,96,i*3)));JsonArray input=inputs(pool.toArray(Fixture[]::new));List<ImageScreening.Feature> values=pool.stream().map(Fixture::feature).toList();JsonObject limited=ImageScreening.plan(input,values,Json.obj("nearMaxDistance",64,"maxComparisons",2),null),coverage=Json.object(limited,"nearCheck");
        check(Json.required(limited,"status").equals("incomplete")&&Json.required(coverage,"stopReason").equals("comparison_budget"),"comparison budget produces incomplete plan");check(Json.number(coverage,"comparedContentPairs",-1)==2&&Json.number(coverage,"unexaminedContentPairs",-1)==8&&Json.number(coverage,"unexaminedIdentityPairUpperBound",-1)==8,"budget reports unexamined scope without claiming no duplicates");
        JsonObject outputLimited=ImageScreening.plan(input,values,Json.obj("nearMaxDistance",64,"maxPairs",1),null);check(Json.array(outputLimited,"nearPairs").size()==1&&Json.required(Json.object(outputLimited,"nearCheck"),"stopReason").equals("pair_output_limit"),"reported pair budget bounds output");JsonObject disabled=ImageScreening.plan(input,values,Json.obj("nearEnabled",false),null);check(Json.required(Json.object(disabled,"nearCheck"),"status").equals("disabled")&&Json.number(Json.object(disabled,"nearCheck"),"hammingComparisons",-1)==0,"disabled near checking is never presented as checked clean");
        JsonArray frames=new JsonArray();for(int i=0;i<10000;i++){JsonObject frame=sharp.input.deepCopy();frame.addProperty("assetId",String.format(Locale.ROOT,"frame-%05d",i));frame.addProperty("sourceVideoId","static-video");frame.addProperty("sourcePts",Integer.toString(i));frame.addProperty("partition","train");if(i==9999){frame.addProperty("status","confirmed");frame.addProperty("version",3);}if(i==5){frame.addProperty("status","modified");frame.addProperty("version",2);}frames.add(frame);}
        JsonObject plan=ImageScreening.plan(frames,List.of(sharp.feature),Json.obj("deduplicate",true,"maxComparisons",0,"maxPairs",0),null);JsonObject group=Json.array(plan,"exactGroups").get(0).getAsJsonObject();check(Json.array(plan,"items").size()==10000&&Json.array(group,"members").size()==10000,"same-hash static video retains every frame identity");check(Json.required(group,"representativeAssetId").equals("frame-09999"),"human-confirmed representative wins stable selection");
        check(Json.required(row(plan,"frame-00005"),"recommendation").equals("keep_protected")&&Json.required(row(plan,"frame-09999"),"recommendation").equals("keep_protected"),"all manual versions remain protected even when not representative");check(Json.required(row(plan,"frame-00000"),"recommendation").equals("exclude_suggested")&&Json.required(Json.object(row(plan,"frame-00000"),"input"),"sourcePts").equals("0"),"explicit exact deduplication suggests exclusion without merging frame metadata");check(Json.required(plan,"status").equals("complete")&&Json.number(Json.object(plan,"nearCheck"),"totalContentPairs",-1)==0,"large exact group never expands to millions of near pairs");
        JsonArray few=Json.arr(frames.get(0),frames.get(5),frames.get(9999));JsonObject noDedup=ImageScreening.plan(few,List.of(sharp.feature),new JsonObject(),null);check(Json.required(row(noDedup,"frame-00000"),"recommendation").equals("keep"),"exact matching does not suggest exclusion until deduplicate is enabled");frames.add(sharp.input);rejects("screening_batch_invalid",()->ImageScreening.plan(frames,List.of(sharp.feature),new JsonObject(),null));
    }

    private static void invalidAndCancellation(Fixture sharp)throws Exception{
        JsonObject wrongDimensions=sharp.input.deepCopy();wrongDimensions.addProperty("width",121);rejects("screening_input_mismatch",()->ImageScreening.feature(wrongDimensions,null));JsonObject newer=sharp.input.deepCopy();newer.addProperty("inputVersion",2);rejects("screening_feature_missing",()->ImageScreening.plan(Json.arr(newer),List.of(sharp.feature),new JsonObject(),null));JsonObject old=sharp.input.deepCopy();old.addProperty("normalizationVersion","old-v1");rejects("screening_normalization_mismatch",()->ImageScreening.feature(old,null));
        rejects("screening_asset_duplicate",()->ImageScreening.plan(Json.arr(sharp.input,sharp.input),List.of(sharp.feature),new JsonObject(),null));
        check(ImageScreening.plan(inputs(sharp),features(sharp),null,null).equals(ImageScreening.plan(inputs(sharp),features(sharp),new JsonObject(),null)),"omitted options use the same explicit defaults");JsonObject invalidPath=sharp.input.deepCopy();invalidPath.addProperty("inputPath","invalid\u0000path");rejects("screening_input_invalid",()->ImageScreening.feature(invalidPath,null));JsonObject invalidNumber=sharp.input.deepCopy();invalidNumber.addProperty("sourceTime",Double.NaN);rejects("screening_input_invalid",()->ImageScreening.feature(invalidNumber,null));JsonObject excessMetadata=sharp.input.deepCopy();excessMetadata.add("metadata",Json.obj("a","x".repeat(23000),"b","x".repeat(23000),"c","x".repeat(23000)));rejects("screening_input_invalid",()->ImageScreening.feature(excessMetadata,null));
        Fixture mutable=fixture("mutable",texture(120,96,0));Path path=Path.of(Json.required(mutable.input,"inputPath"));Files.writeString(path,"changed content");rejects("screening_content_changed",()->ImageScreening.plan(inputs(mutable),features(mutable),new JsonObject(),null));rejects("screening_content_changed",()->ImageScreening.feature(mutable.input,null));
        Fixture during=fixture("during",texture(120,96,0));AtomicBoolean changed=new AtomicBoolean();rejects("screening_content_changed",()->ImageScreening.feature(during.input,new ImageScreening.Control(){public void progress(JsonObject event){if(Json.str(event,"phase","").equals("feature_decoded")){try{Files.writeString(Path.of(Json.required(during.input,"inputPath")),"changed after decode");changed.set(true);}catch(Exception error){throw new RuntimeException(error);}}}}));check(changed.get(),"hash after decoding prevents a feature for changed pixels");
        BufferedImage noise=new BufferedImage(512,512,BufferedImage.TYPE_INT_RGB);Random random=new Random(31);for(int y=0;y<512;y++)for(int x=0;x<512;x++)noise.setRGB(x,y,random.nextInt(1<<24));Fixture large=fixture("noise",noise);AtomicInteger checkpoints=new AtomicInteger();rejects("screening_cancelled",()->ImageScreening.feature(large.input,new ImageScreening.Control(){public boolean cancelled(){return checkpoints.incrementAndGet()>4;}}));check(checkpoints.get()<=6,"file hashing checks cancellation between blocks");
        rejects("screening_cancelled",()->ImageScreening.plan(inputs(sharp),features(sharp),new JsonObject(),new ImageScreening.Control(){public boolean cancelled(){return true;}}));check(Media.hash(Path.of(Json.required(sharp.input,"inputPath"))).equals(sharp.feature.contentHash()),"screening never modifies baseline files");
    }
}
