package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.util.*;

final class LocalRunIntegrationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine engine,String command,JsonObject p)throws Exception{return (JsonObject)engine.command(command,p);}
    static JsonObject waitRun(Engine engine,String id,String... expected)throws Exception{long until=System.currentTimeMillis()+10000;JsonObject result;do{result=engine.runs.get(id);if(Set.of(expected).contains(Json.required(result,"status")))return result;Thread.sleep(20);}while(System.currentTimeMillis()<until);throw new AssertionError("Local run timeout: "+result);}
    static JsonObject waitSample(Engine engine,String id,String status)throws Exception{long until=System.currentTimeMillis()+10000;JsonObject result;do{result=engine.runs.get(id);if(Json.array(result,"samples").asList().stream().anyMatch(value->status.equals(Json.str(value.getAsJsonObject(),"status",""))))return result;Thread.sleep(10);}while(System.currentTimeMillis()<until);throw new AssertionError("Local sample timeout: "+result);}
    static void flow(Engine engine,Path root,String projectId,String assetId,String modelId,Path mode)throws Exception{
        Files.writeString(mode,"zero");JsonObject local=Json.obj("modelId",modelId,"classMap",Json.obj("0","target","1",null));JsonArray operations=Json.arr(Json.obj("kind","tile","width",32,"height",48),Json.obj("kind","resize","width",64,"height",48,"fit","stretch"));JsonObject request=FlowIntegrationTest.request(projectId,Json.arr(FlowIntegrationTest.step("transform","transform",Json.obj("operations",operations)),FlowIntegrationTest.step("local","local",local),FlowIntegrationTest.step("export","export",Json.obj("outputDir",root.resolve("local-flow-export").toString()))));
        check(Json.bool(cmd(engine,"flow.preflight",request),"canStart",false),"tile resize local export preflight");JsonObject created=cmd(engine,"flow.create",request);JsonObject flow=FlowIntegrationTest.waitFlow(engine,Json.required(created,"id"),"completed");JsonObject state=FlowIntegrationTest.state(flow,"local"),child=engine.runs.get(Json.required(state,"childRunId"));check(Json.required(Json.object(state,"local"),"modelId").equals(modelId),"flow step exposes frozen local model selection");check(Json.integer(Json.object(child,"statistics"),"baselineTotal",0)==1&&Json.integer(Json.object(child,"statistics"),"inputTotal",0)==2,"views have independent input count and one parent");check(Json.integer(Json.object(flow,"statistics"),"inputAssets",0)==1&&Json.integer(Json.object(flow,"statistics"),"inputViews",0)==2,"flow parent and view counts stay distinct");JsonObject artifact=cmd(engine,"flow.artifact",Json.obj("artifactId",FlowIntegrationTest.state(flow,"transform").get("outputArtifactId")));Set<String> inputIds=new HashSet<>();for(JsonElement value:Json.array(artifact,"items")){JsonObject input=value.getAsJsonObject();String inputId=Json.required(input,"inputId");inputIds.add(inputId);check(!inputId.equals(assetId)&&Json.required(input,"assetId").equals(assetId),"each view retains parent with independent input identity");JsonObject image=cmd(engine,"flow.input.image",Json.obj("inputId",inputId));check(Files.isRegularFile(Path.of(Json.required(image,"path")))&&Json.integer(image,"width",0)==64&&Json.integer(image,"height",0)==48,"fixed view PNG is generated with actual resized dimensions");}check(inputIds.size()==2,"two tile identities remain distinct even for identical pixels");
        Set<String> results=new HashSet<>();for(JsonElement value:Json.array(child,"samples")){JsonObject sample=value.getAsJsonObject();results.add(Json.required(sample,"resultId"));JsonObject result=cmd(engine,"run.result.get",Json.obj("resultId",sample.get("resultId")));check(Json.array(result,"annotations").isEmpty()&&Json.required(result,"status").equals("succeeded"),"empty successful view results remain valid independent facts");}check(results.size()==2,"view results persist individually");JsonObject parent=engine.store.read(c->Json.parse(Store.one(c,"SELECT data FROM versions WHERE asset_id=? AND version=?",assetId,Json.array(child,"samples").get(0).getAsJsonObject().get("candidateVersion").getAsInt()).get("data").getAsString()));check(Json.bool(Json.object(Json.object(parent,"metadata"),"coverage"),"complete",false)&&!Json.bool(Json.object(parent,"metadata"),"requiresGeometryReview",true),"successful empty tiles cover complete baseline without invented review flag");check(Json.array(parent,"annotations").isEmpty(),"full empty parent is a legal negative");check(Json.integer(Json.object(child,"statistics"),"requestsUsed",-1)==0&&((JsonArray)engine.command("run.attempts",Json.obj("runId",child.get("id")))).isEmpty(),"view local flow creates no API request or fake attempts");JsonObject exported=cmd(engine,"flow.artifact",Json.obj("artifactId",FlowIntegrationTest.state(flow,"export").get("outputArtifactId")));check(Json.integer(exported,"total",0)==1,"export collapses views to a single baseline image");Files.writeString(mode,"normal");
    }
    static void reuse(Engine engine,Path root,String projectId,String modelId,Path mode)throws Exception{
        Files.writeString(mode,"zero");JsonObject local=Json.obj("modelId",modelId,"classMap",Json.obj("0","target","1",null));JsonObject request=FlowIntegrationTest.request(projectId,Json.arr(FlowIntegrationTest.step("transform","transform",Json.obj("operations",Json.arr(Json.obj("kind","tile","width",32,"height",48),Json.obj("kind","resize","width",64,"height",48,"fit","stretch")))),FlowIntegrationTest.step("local","local",local)));JsonObject flow=cmd(engine,"flow.create",request);flow=FlowIntegrationTest.waitFlow(engine,Json.required(flow,"id"),"completed");JsonObject hit=engine.runs.get(Json.required(FlowIntegrationTest.state(flow,"local"),"childRunId"));check(Json.integer(hit,"reused",0)==2&&Json.integer(hit,"requestsUsed",-1)==0,"local input reuse avoids repeated prediction and API budget");for(JsonElement value:Json.array(hit,"samples")){JsonObject sample=value.getAsJsonObject(),source=Json.object(sample,"inputReusedFrom");check(Json.required(source,"source").equals("local")&&source.has("sourceModelId")&&source.has("sourceModelHash")&&source.has("sourceWorkerHash")&&!source.has("sourceAttemptId"),"local reuse provenance contains exact model and worker without API attempt");}
        local.addProperty("forceRerun",true);Json.object(Json.array(Json.object(request,"definition"),"steps").get(1).getAsJsonObject(),"parameters").addProperty("forceRerun",true);JsonObject fresh=cmd(engine,"flow.create",request);fresh=FlowIntegrationTest.waitFlow(engine,Json.required(fresh,"id"),"completed");JsonObject actual=engine.runs.get(Json.required(FlowIntegrationTest.state(fresh,"local"),"childRunId"));check(Json.integer(actual,"reused",-1)==0&&Json.array(actual,"samples").asList().stream().allMatch(value->!value.getAsJsonObject().has("inputReusedFrom")),"force local rerun recomputes results without stale reuse origin");Json.object(Json.array(Json.object(request,"definition"),"steps").get(1).getAsJsonObject(),"parameters").remove("forceRerun");JsonObject newest=cmd(engine,"flow.create",request);newest=FlowIntegrationTest.waitFlow(engine,Json.required(newest,"id"),"completed");JsonObject selected=engine.runs.get(Json.required(FlowIntegrationTest.state(newest,"local"),"childRunId"));check(Json.array(selected,"samples").asList().stream().allMatch(value->Json.required(Json.object(value.getAsJsonObject(),"inputReusedFrom"),"sourceRunId").equals(Json.required(actual,"id"))),"next local reuse selects latest real model result");Files.writeString(mode,"normal");
    }
    static void environmentChange(Engine engine,JsonObject request,Path worker,Path python,String modelId)throws Exception{
        cmd(engine,"system.suspend",new JsonObject());String run=Json.required(cmd(engine,"local.run.create",request),"id");JsonObject original=Json.object(Json.object(engine.store.read(c->Store.document(c,"runs",run)),"snapshot"),"local");Path environment=worker.resolveSibling("fixture_worker.environment");Files.writeString(environment,"fixture-numpy-next");cmd(engine,"local.runtime.configure",Json.obj("pythonPath",python.toString()));JsonObject loaded=cmd(engine,"local.model.load",Json.obj("modelId",modelId));check(Json.required(loaded,"workerHash").equals(Json.required(original,"workerHash")),"environment fixture keeps same worker hash");check(Json.required(Json.object(loaded,"model"),"modelHash").equals(Json.required(Json.object(original,"model"),"modelHash")),"environment fixture keeps same model bytes");cmd(engine,"system.resume",new JsonObject());JsonObject paused=waitRun(engine,run,"paused");check(Json.required(paused,"pauseReason").equals("local_environment_changed"),"changed runtime version pauses fixed old run");check(engine.store.read(c->Store.one(c,"SELECT id FROM input_results WHERE run_id=?",run))==null&&engine.store.read(c->Store.one(c,"SELECT sequence FROM events WHERE run_id=? AND type='local.progress'",run))==null,"changed environment performs no prediction and attaches no stale cache key");DataMaintenanceTest.await(()->engine.localRuntime.active()==0,"environment refusal releases local slot");Files.delete(environment);cmd(engine,"local.runtime.configure",Json.obj("pythonPath",python.toString()));cmd(engine,"local.model.load",Json.obj("modelId",modelId));cmd(engine,"run.cancel",Json.obj("runId",run));
    }
    static void run(Path root)throws Exception{
        Path python=Path.of("C:/Users/zhy23/AppData/Local/Programs/Python/Python310/python.exe"),worker=root.resolve("fixture_worker.py"),mode=root.resolve("fixture_worker.mode"),model=root.resolve("fixture.pt"),image=root.resolve("local.png"),data=root.resolve("local-data");
        String script=LocalInferenceTest.WORKER.replace("data={'available':True,","data={'pythonVersion':'fixture-python','ultralyticsVersion':'fixture-yolo','torchVersion':'fixture-torch','numpyVersion':(pathlib.Path(__file__).with_suffix('.environment').read_text() if pathlib.Path(__file__).with_suffix('.environment').exists() else 'fixture-numpy'),'opencvVersion':'fixture-opencv','onnxruntimeVersion':None,'available':True,").replace("event={'type':'event'","mode=pathlib.Path(__file__).with_suffix('.mode').read_text()\n        event={'type':'event'").replace("if rid in ('hang','hang-child'):time.sleep(30)","if mode=='hang' or rid in ('hang','hang-child'):time.sleep(30)\n        if mode=='delay':time.sleep(0.5)").replace("if rid=='geometry':","if mode=='geometry' or rid=='geometry':").replace("annotations=[] if rid in ('zero','excluded') else [annotation]","annotations=[] if mode=='zero' or rid in ('zero','excluded') else [annotation]");
        Files.writeString(worker,script);Files.writeString(mode,"normal");Files.writeString(model,"isolated model fixture");ImageIO.write(new BufferedImage(64,48,BufferedImage.TYPE_INT_RGB),"png",image.toFile());JsonObject startup=Json.obj("localWorkerPath",worker.toString(),"localPythonPath",python.toString());String modelId,projectId,assetId,resultId,waiting;
        try(Engine engine=new Engine(data,startup)){
            check(Json.integer(cmd(engine,"diagnostics.get",new JsonObject()),"databaseVersion",0)==Store.SCHEMA_VERSION,"current schema is active");
            check(Json.array(cmd(engine,"local.runtime.get",new JsonObject()),"slots").isEmpty(),"read-only runtime never starts a worker");
            JsonObject project=cmd(engine,"project.create",Json.obj("name","本地链路","taskType","detect","classes",Json.arr(Json.obj("id","target","name","目标"))));projectId=Json.required(project,"id");assetId=Json.array(cmd(engine,"asset.import",Json.obj("projectId",projectId,"paths",Json.arr(image.toString()))),"assetIds").get(0).getAsString();
            JsonObject registered=cmd(engine,"local.model.register",Json.obj("name","固定模型","taskType","detect","modelPath",model.toString()));modelId=Json.required(registered,"id");check(!registered.toString().contains("modelPath")&&Json.integer(registered,"version",0)==1,"public model omits private path");
            ManualChainTest.rejects("local_model_authorization_required",()->cmd(engine,"local.model.load",Json.obj("modelId",modelId)));
            cmd(engine,"local.model.authorize",Json.obj("path",model.toString(),"modelHash",Media.hash(model)));cmd(engine,"local.runtime.probe",new JsonObject());cmd(engine,"local.model.load",Json.obj("modelId",modelId));JsonObject slot=Json.array(cmd(engine,"local.runtime.get",new JsonObject()),"slots").get(0).getAsJsonObject();check(Json.array(slot,"classes").size()==2&&slot.has("workerHash"),"read-only loaded state reports actual classes and worker");
            JsonObject request=Json.obj("projectId",projectId,"assetIds",Json.arr(assetId),"modelId",modelId,"classMap",Json.obj("0","target","1",null),"forceRerun",true);JsonObject first=cmd(engine,"local.run.create",request);first=waitRun(engine,Json.required(first,"id"),"completed");String firstId=Json.required(first,"id");JsonObject stats=Json.object(first,"statistics");check(Json.integer(stats,"inputTotal",0)==1&&Json.integer(stats,"baselineCompleted",0)==1&&Json.integer(stats,"inputCompleted",0)==1,"normal local input and baseline counters");check(Json.integer(stats,"requestsUsed",-1)==0&&((JsonArray)engine.command("run.attempts",Json.obj("runId",firstId))).isEmpty(),"local inference makes no API attempt or request");check(!first.toString().contains("modelPath"),"public local run does not expose execution path");
            JsonObject sample=Json.array(first,"samples").get(0).getAsJsonObject();resultId=Json.required(sample,"resultId");JsonObject result=cmd(engine,"run.result.get",Json.obj("resultId",resultId));check(Json.required(result,"inputId").equals(assetId)&&Json.required(result,"status").equals("succeeded")&&Json.array(result,"annotations").size()==1,"immutable normal input result validates independently");check(!Json.object(result,"provenance").has("modelPath"),"public provenance hides model path");JsonObject candidate=engine.projects.asset(assetId);check(Json.required(candidate,"source").equals("local")&&!Json.bool(Json.object(candidate,"metadata"),"requiresGeometryReview",true),"whole valid input creates legal parent candidate");
            check(Json.bool(Json.object(cmd(engine,"export.preflight",Json.obj("projectId",projectId)),"summary"),"canExport",false),"complete local candidate exports");
            Files.writeString(mode,"geometry");JsonObject failed=cmd(engine,"local.run.create",request);failed=waitRun(engine,Json.required(failed,"id"),"completed_with_errors");JsonObject flagged=engine.projects.asset(assetId);check(Json.bool(Json.object(flagged,"metadata"),"requiresGeometryReview",false),"invalid raw geometry blocks parent candidate");JsonObject raw=cmd(engine,"run.result.get",Json.obj("resultId",Json.array(failed,"samples").get(0).getAsJsonObject().get("resultId")));check(Json.array(Json.object(raw,"rawResult"),"annotations").size()==1&&raw.get("annotations").isJsonNull(),"invalid input raw retained while validated annotations absent");check(!Json.bool(Json.object(cmd(engine,"export.preflight",Json.obj("projectId",projectId)),"summary"),"canExport",true),"unresolved geometry cannot export");String old=flagged.toString();JsonObject manual=cmd(engine,"annotation.save",Json.obj("assetId",assetId,"baseVersion",flagged.get("version"),"annotations",Json.array(candidate,"annotations"),"confirm",true));check(!Json.bool(Json.object(manual,"metadata"),"requiresGeometryReview",true),"explicit manual version resolves current review");check(engine.projects.history(assetId).asList().stream().anyMatch(value->value.toString().equals(old)),"original flagged candidate remains immutable");
            Files.writeString(mode,"delay");JsonObject paused=cmd(engine,"local.run.create",request);String pausedId=Json.required(paused,"id");DataMaintenanceTest.await(()->engine.store.read(c->Store.one(c,"SELECT sequence FROM events WHERE run_id=? AND type='local.progress' LIMIT 1",pausedId))!=null,"prediction actually started before pause");cmd(engine,"run.pause",Json.obj("runId",pausedId));waitSample(engine,pausedId,"succeeded");check(Json.required(engine.runs.get(pausedId),"status").equals("paused"),"pause allows current prediction save without restarting dispatch");check(Json.integer(engine.projects.asset(assetId),"version",0)==Json.integer(manual,"version",-1),"local inference preserves manual current version");cmd(engine,"run.resume",Json.obj("runId",pausedId));waitRun(engine,pausedId,"completed");
            Files.writeString(mode,"hang");JsonObject cancelled=cmd(engine,"local.run.create",request);String cancelledId=Json.required(cancelled,"id");DataMaintenanceTest.await(()->engine.store.read(c->Store.one(c,"SELECT sequence FROM events WHERE run_id=? AND type='local.progress' LIMIT 1",cancelledId))!=null,"prediction actually started before cancel");DataMaintenanceTest.await(()->engine.localRuntime.active()==1,"local device occupies an independent slot");JsonObject owner=Json.obj("operationId","local-maintenance");check(!Json.bool(cmd(engine,"system.prepareDataMaintenance",owner),"ready",true),"maintenance waits for active local slot");cmd(engine,"system.cancelDataMaintenance",owner);cmd(engine,"run.cancel",Json.obj("runId",cancelledId));waitSample(engine,cancelledId,"cancelled");DataMaintenanceTest.await(()->engine.localRuntime.active()==0,"cancel releases owned worker slot");check(Json.required(engine.runs.get(cancelledId),"status").equals("cancelled"),"late cancellation preserves terminal run");
            Files.writeString(mode,"normal");cmd(engine,"local.model.load",Json.obj("modelId",modelId));flow(engine,root,projectId,assetId,modelId,mode);reuse(engine,root,projectId,modelId,mode);environmentChange(engine,request,worker,python,modelId);cmd(engine,"system.suspend",new JsonObject());waiting=Json.required(cmd(engine,"local.run.create",request),"id");
            check(Json.required(cmd(engine,"local.model.get",Json.obj("modelId",modelId,"modelVersion",1)),"modelHash").equals(Media.hash(model)),"specified model metadata reads exact version");
        }
        try(Engine restored=new Engine(data,startup)){check(Json.required(restored.runs.get(waiting),"status").equals("paused"),"restart keeps unstarted local run paused");check(Json.required(cmd(restored,"run.result.get",Json.obj("resultId",resultId)),"status").equals("succeeded"),"immutable local result survives restart");ManualChainTest.rejects("local_model_authorization_required",()->cmd(restored,"local.model.load",Json.obj("modelId",modelId)));check(restored.store.read(c->Store.one(c,"SELECT id FROM budgets WHERE id=?",waiting))==null,"restart never creates API budget for local run");}
    }
}
