package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;

public final class MediaJobsIntegrationTest {
    private static int checks;
    private static Path root,ffmpeg,ffprobe,video;
    private interface Action{void run()throws Exception;}
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    private static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    private static void rejects(String code,Action action)throws Exception{try{action.run();throw new AssertionError("Expected "+code);}catch(ApiError e){check(code.equals(e.code),"Expected "+code+" got "+e.code);}}
    private static JsonObject startup(){return Json.obj("mediaFfmpegPath",ffmpeg.toString(),"mediaFfprobePath",ffprobe.toString());}
    private static JsonObject project(Engine e)throws Exception{return cmd(e,"project.create",Json.obj("name","媒体集成","taskType","detect","classes",Json.arr(Json.obj("id","object","name","对象","color","#223344"))));}
    private static JsonObject parameters(){return Json.obj("ranges",Json.arr(Json.obj("start",0,"end",0.5),Json.obj("start",1,"end",1.5)),"mode","interval","intervalSeconds",0.2,"outputSize",Json.obj("width",320,"height",240,"fit","contain"),"format","png","timeoutMs",30000);}
    private static JsonObject await(Engine e,String id)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(90);while(System.nanoTime()<end){JsonObject job=cmd(e,"media.job.get",Json.obj("jobId",id));if(!Set.of("queued","running","cancelling").contains(Json.required(job,"status")))return job;Thread.sleep(40);}throw new AssertionError("Media timeout "+id);}
    private static JsonObject awaitFlow(Engine e,String id)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(90);while(System.nanoTime()<end){JsonObject flow=cmd(e,"flow.get",Json.obj("flowRunId",id));if(!Set.of("queued","running").contains(Json.required(flow,"status")))return flow;Thread.sleep(50);}throw new AssertionError("Flow timeout "+id);}
    private static JsonObject flow(Engine e,String pid,JsonArray steps)throws Exception{return cmd(e,"flow.create",Json.obj("projectId",pid,"input",Json.obj("source","project","selection","all"),"definition",Json.obj("version",1,"name","媒体链路","steps",steps)));}
    private static JsonObject step(String id,String kind,JsonObject p){return Json.obj("id",id,"kind",kind,"enabled",true,"parameters",p);}
    public static void main(String[] args)throws Exception{
        if(args.length!=3)throw new IllegalArgumentException("ffmpeg ffprobe video");ffmpeg=Path.of(args[0]).toAbsolutePath();ffprobe=Path.of(args[1]).toAbsolutePath();video=Path.of(args[2]).toAbsolutePath();root=Path.of("engine/build/verification/media-jobs-"+System.currentTimeMillis()).toAbsolutePath();Files.createDirectories(root);
        realVideo();sameContent();bulkImport();recoveryAndCancellation();artifactRecovery();System.out.println("PASS "+checks+" media integration checks; VERIFICATION_DIR="+root);
    }
    private static void realVideo()throws Exception{
        try(Engine e=new Engine(root.resolve("real"),startup())){
            String pid=Json.required(project(e),"id");JsonObject info=cmd(e,"media.video.inspect",Json.obj("sourcePath",video.toString()));check(Json.integer(info,"width",0)==768&&Json.integer(info,"height",0)==576,"actual AVI dimensions");// 像素比例只有两种合法结局：缺失 → 显式按方形像素假设并给出告知；已声明 → 原样采信且不提示。测试视频随环境可能自带 1:1 声明（本机 .qa 夹具即如此），两种都认，但绝不允许悄悄猜。
            boolean sarAssumed=Json.bool(info,"sampleAspectRatioAssumed",false);String sarNotice=Json.str(info,"geometryNotice","");
            check(sarAssumed&&sarNotice.contains("方形像素")||!sarAssumed&&sarNotice.isEmpty(),"SAR must be explicitly declared or explicitly assumed with notice");check(Math.abs(Json.decimal(info,"durationSeconds",0)-79.5)<0.01,"actual duration");
            JsonObject created=cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"expectedSourceHash",info.get("sourceHash"),"parameters",parameters()));String id=Json.required(created,"id");JsonObject ready=await(e,id);check(Json.required(ready,"status").equals("completed"),"video completed: "+ready);check(Json.bool(ready,"canImport",false)&&!Json.bool(ready,"assetsCommitted",true),"separate complete artifact and assets");check(Json.integer(e.projects.get(pid),"assetCount",-1)==0,"no assets before import");
            JsonArray frames=Json.array(cmd(e,"media.video.frames",Json.obj("jobId",id)),"items");check(frames.size()==6,"two unequal ranges six real frames");List<String> pts=new ArrayList<>();for(JsonElement frame:frames){JsonObject row=frame.getAsJsonObject();pts.add(Json.required(row,"sourcePts"));check(row.get("sourcePts").getAsJsonPrimitive().isString()&&!row.has("imagePath"),"PTS string and private path stripped");}check(pts.equals(List.of("0","2","4","10","12","14")),"actual source PTS "+pts);
            JsonObject started=flow(e,pid,Json.arr(step("video","import",Json.obj("mediaJobId",id)),step("quality","filter",Json.obj("screening",Json.obj("nearEnabled",true,"maxComparisons",0)))));JsonObject done=awaitFlow(e,Json.required(started,"id"));check(Json.required(done,"status").equals("completed"),"video to screening flow "+done);check(Json.integer(e.projects.get(pid),"assetCount",0)==6,"all independent frame assets committed");check(Json.bool(cmd(e,"media.video.import",Json.obj("jobId",id)),"assetsCommitted",false)&&Json.integer(e.projects.get(pid),"assetCount",0)==6,"repeat import idempotent");
            JsonObject output=Json.array(done,"steps").get(1).getAsJsonObject();JsonObject artifact=cmd(e,"flow.artifact",Json.obj("artifactId",output.get("outputArtifactId")));check(Json.integer(artifact,"total",0)==6,"screening suggestions do not exclude inputs");check(Json.str(Json.object(artifact,"screeningSummary"),"status","").equals("incomplete"),"bounded incomplete retained on flow artifact");String screeningId=Json.required(artifact,"screeningJobId");JsonObject result=cmd(e,"media.screening.result",Json.obj("jobId",screeningId,"limit",2,"offset",1));check(Json.integer(result,"total",0)==6&&Json.array(result,"items").size()==2,"screening pagination");check(!result.toString().contains("inputPath")&&!result.toString().contains("inputImage"),"screening public result has no internal image path");check(Json.number(Json.object(Json.object(result,"summary"),"nearCheck"),"unexaminedContentPairs",0)>0,"unexamined comparisons explicit");
            JsonArray assets=Json.array(e.projects.listAssets(Json.obj("projectId",pid)),"items");for(JsonElement item:assets){JsonObject asset=item.getAsJsonObject(),metadata=Json.object(asset,"metadata");check(metadata.has("sourceVideoId")&&metadata.has("videoSourceHash")&&metadata.has("relativePts"),"frame provenance on baseline");cmd(e,"annotation.save",Json.obj("assetId",asset.get("id"),"baseVersion",0,"annotations",new JsonArray(),"confirm",true));}
            JsonObject preflight=cmd(e,"export.preflight",Json.obj("projectId",pid));check(Json.str(Json.object(preflight,"screening"),"status","").equals("incomplete"),"export reuses exact screening scope with incomplete boundary");Path directory=root.resolve("exports");Files.createDirectories(directory);JsonObject exported=cmd(e,"export.create",Json.obj("projectId",pid,"outputDir",directory.toString()));JsonObject manifest=Json.parse(Files.readString(Path.of(Json.required(exported,"manifestPath"))));Set<String> splits=new HashSet<>();for(JsonElement item:Json.array(manifest,"assets")){JsonObject asset=item.getAsJsonObject();splits.add(Json.required(asset,"split"));check(Json.object(asset,"videoFrame").has("sourcePts")&&!Json.object(asset,"videoFrame").toString().contains("Path"),"export exact video provenance without local paths");}check(splits.size()==1,"all same-video frames share split");
            JsonArray events=e.store.read(c->Store.events(c,0,null,null,2000));check(java.util.stream.StreamSupport.stream(events.spliterator(),false).anyMatch(value->value.getAsJsonObject().has("mediaJobId")),"persistent SSE media job context");for(JsonElement value:events){JsonObject event=value.getAsJsonObject();if(Json.str(event,"type","").startsWith("media.job."))check(!event.toString().contains("manifestPath")&&!event.toString().contains("sourcePath")&&!event.toString().contains("inputPath"),"public media progress strips helper completion paths");}
            JsonObject tooMany=parameters();tooMany.addProperty("maxFrames",10001);rejects("video_parameters_invalid",()->cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",tooMany)));
        }
    }
    private static void sameContent()throws Exception{
        Path still=root.resolve("still.mp4");Process process=new ProcessBuilder(ffmpeg.toString(),"-v","error","-f","lavfi","-i","color=c=blue:duration=1:size=64x48:rate=4","-c:v","libx264","-threads","1",still.toString()).inheritIO().start();check(process.waitFor()==0,"real still-video fixture");
        try(Engine e=new Engine(root.resolve("still"),startup())){String pid=Json.required(project(e),"id");JsonObject p=Json.obj("ranges",Json.arr(Json.obj("start",0,"end",1)),"mode","every_n","everyNFrames",1,"timeoutMs",30000);String id=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",still.toString(),"parameters",p)),"id");check(Json.required(await(e,id),"status").equals("completed"),"still extraction completed");cmd(e,"media.video.import",Json.obj("jobId",id));check(Json.bool(await(e,id),"assetsCommitted",false),"still import completed");JsonArray assets=Json.array(e.projects.listAssets(Json.obj("projectId",pid)),"items");Set<String> ids=new HashSet<>(),hashes=new HashSet<>(),pts=new HashSet<>();for(JsonElement item:assets){JsonObject asset=item.getAsJsonObject();ids.add(Json.required(asset,"id"));hashes.add(Json.required(asset,"contentHash"));pts.add(Json.required(Json.object(asset,"metadata"),"sourcePts"));}check(ids.size()==4&&hashes.size()==1&&pts.size()==4,"same SHA at four PTS preserves four identities");
            // 场景变化抽帧在完全静止的画面上只留首帧：候选两帧的灰度差异为 0，第二帧被判为近重复 —— 证明去重门真的在生效。
            String sceneId=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",still.toString(),"parameters",Json.obj("ranges",Json.arr(Json.obj("start",0,"end",1)),"mode","scene","sceneThreshold",0.35,"minIntervalSeconds",0.5,"timeoutMs",30000))),"id");check(Json.required(await(e,sceneId),"status").equals("completed"),"scene extraction on static video completed");
            JsonArray sceneFrames=Json.array(cmd(e,"media.video.frames",Json.obj("jobId",sceneId)),"items");check(sceneFrames.size()==1,"static video keeps only the first frame under scene dedup, got "+sceneFrames.size());check(Json.decimal(sceneFrames.get(0).getAsJsonObject(),"timeSeconds",-1)==0,"scene dedup keeps the first frame");
            // 去重丢帧后的清单必须仍能入库（frameId 与文件名同源的回归）：丢帧场景的 frameId 序号有空洞。
            cmd(e,"media.video.import",Json.obj("jobId",sceneId));check(Json.bool(await(e,sceneId),"assetsCommitted",false),"deduplicated manifest imports without identity mismatch");
            String confirmed=Json.required(assets.get(1).getAsJsonObject(),"id"),draft=Json.required(assets.get(3).getAsJsonObject(),"id");cmd(e,"annotation.save",Json.obj("assetId",confirmed,"baseVersion",0,"annotations",new JsonArray(),"confirm",true));cmd(e,"annotation.draft",Json.obj("assetId",draft,"baseVersion",0,"annotations",new JsonArray()));
            JsonObject run=flow(e,pid,Json.arr(step("duplicates","filter",Json.obj("deduplicate",true,"screening",Json.obj("deduplicate",true)))));JsonObject done=awaitFlow(e,Json.required(run,"id"));check(Json.required(done,"status").equals("completed"),"duplicate flow completed");JsonObject result=cmd(e,"flow.artifact",Json.obj("artifactId",Json.array(done,"steps").get(0).getAsJsonObject().get("outputArtifactId")));Set<String> retained=new HashSet<>();for(JsonElement item:Json.array(result,"items")){JsonObject value=item.getAsJsonObject();if(Json.str(value,"outcome","").equals("included"))retained.add(Json.required(value,"assetId"));}check(retained.equals(Set.of(confirmed,draft)),"manual saved and empty draft both protected from exact dedup");check(e.projects.asset(draft).has("draft")&&Json.integer(e.projects.asset(confirmed),"version",0)==1,"screening does not write annotations");
            List<JsonObject> grouping=new ArrayList<>();grouping.add(Json.obj("id","a","contentHash","same","metadata",Json.obj("sourceVideoId","v1")));grouping.add(Json.obj("id","b","contentHash","same","metadata",Json.obj("sourceVideoId","v2")));grouping.add(Json.obj("id","c","contentHash","other","metadata",Json.obj("sourceVideoId","v2")));check(Exporter.groups(grouping).values().stream().distinct().count()==1,"content and source grouping transitive closure");
        }
    }
    private static void recoveryAndCancellation()throws Exception{
        Path data=root.resolve("recovery");String pid,queued;try(Engine e=new Engine(data,startup())){pid=Json.required(project(e),"id");cmd(e,"system.suspend",new JsonObject());queued=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",parameters())),"id");JsonObject cancelled=cmd(e,"media.job.cancel",Json.obj("jobId",queued));check(Json.required(cancelled,"status").equals("cancelled")&&!Json.bool(cancelled,"artifactCommitted",true),"queued cancellation publishes no artifact");queued=Json.required(cmd(e,"media.job.retry",Json.obj("jobId",queued)),"id");check(Json.required(cmd(e,"media.job.get",Json.obj("jobId",queued)),"status").equals("queued"),"retry new persistent job");}
        try(Engine e=new Engine(data,startup())){JsonObject interrupted=cmd(e,"media.job.get",Json.obj("jobId",queued));check(Json.required(interrupted,"status").equals("interrupted")&&Json.bool(interrupted,"canRetry",false),"restart does not silently re-extract queued job");check(cmd(e,"media.job.resolve",Json.obj("jobId",queued)).has("sourcePath"),"private retry source reauthorization descriptor");JsonObject p=parameters();p.addProperty("maxOutputBytes",1);String limited=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",p)),"id");JsonObject failed=await(e,limited);check(Json.required(failed,"status").equals("failed")&&!Json.bool(failed,"artifactCommitted",true),"actual output cap cannot publish partial frames");rejects("media_artifact_incomplete",()->cmd(e,"media.video.import",Json.obj("jobId",limited)));check(Json.integer(e.projects.get(pid),"assetCount",-1)==0,"failed media operation leaves no imported assets");}
    }
    private static void bulkImport()throws Exception{
        try(Engine e=new Engine(root.resolve("bulk-import"),startup())){
            String pid=Json.required(project(e),"id");Path source=root.resolve("bulk-src");Files.createDirectories(source);
            List<String> paths=new ArrayList<>();for(int i=0;i<1000;i++){Path file=source.resolve(String.format("bulk-%04d.png",i));
                // 每张都画出唯一像素（色块位置 + 编号文字）：Media.sample 的图案会画出画布外，第 30 张起完全同图。
                java.awt.image.BufferedImage sample=new java.awt.image.BufferedImage(320,240,java.awt.image.BufferedImage.TYPE_INT_RGB);java.awt.Graphics2D g=sample.createGraphics();
                g.setColor(java.awt.Color.WHITE);g.fillRect(0,0,320,240);g.setColor(new java.awt.Color(i*7%256,i*13%256,i*29%256));g.fillRect((i%16)*20,(i/16%12)*20,20,20);
                g.setColor(java.awt.Color.BLACK);g.setFont(new java.awt.Font(java.awt.Font.SANS_SERIF,java.awt.Font.BOLD,40));g.drawString(Integer.toString(i),20,130);g.dispose();
                javax.imageio.ImageIO.write(sample,"png",file.toFile());sample.flush();paths.add(file.toString());}
            // 反例：扩展名是 jpg、内容是坏字节 —— 必须整批跳过并逐条报因，不许中断、不许写脏记录。
            Path corrupt=source.resolve("corrupt.jpg");Files.write(corrupt,new byte[]{(byte)0xFF,(byte)0xD8,1,2,3});paths.add(corrupt.toString());
            long started=System.currentTimeMillis();
            JsonObject queued=cmd(e,"asset.import",Json.obj("projectId",pid,"paths",Json.arr(paths.toArray()),"mode","copy"));
            check(Json.bool(queued,"queued",false)&&queued.has("jobId"),"bulk import switches to a background job: "+queued);
            long submitMs=System.currentTimeMillis()-started;check(submitMs<30000,"bulk import submission stays interactive, took "+submitMs+"ms");
            String jobId=Json.required(queued,"jobId");JsonObject done=awaitLong(e,jobId,600);check(Json.required(done,"status").equals("completed"),"bulk import completed: "+done);
            long elapsed=(System.currentTimeMillis()-started)/1000;
            JsonObject summary=Json.object(done,"summary");check(Json.integer(summary,"imported",-1)==1000,"1000 images imported, got "+summary);
            check(Json.integer(summary,"skipped",-1)==0,"no duplicates skipped, got "+summary);
            check(Json.array(summary,"errors").size()==1&&Json.required(Json.array(summary,"errors").get(0).getAsJsonObject(),"name").equals("corrupt.jpg"),"corrupt jpg reported once with its name");
            check(Json.integer(e.projects.get(pid),"assetCount",-1)==1000,"assets committed incrementally without dirty rows");
            check(Json.integer(Json.object(done,"progress"),"completed",-1)==1001,"progress accounted for every file");
            check(elapsed<180,"1000-image import well under the old 120s command timeout budget, took "+elapsed+"s");
            System.out.println("bulk import: 1000 images + 1 corrupt in "+elapsed+"s (submit "+submitMs+"ms)");
        }
    }
    private static JsonObject awaitLong(Engine e,String id,int seconds)throws Exception{long end=System.nanoTime()+TimeUnit.SECONDS.toNanos(seconds);while(System.nanoTime()<end){JsonObject job=cmd(e,"media.job.get",Json.obj("jobId",id));if(!Set.of("queued","running","cancelling").contains(Json.required(job,"status")))return job;Thread.sleep(50);}throw new AssertionError("bulk import timeout "+id);}
    private static void artifactRecovery()throws Exception{
        Path data=root.resolve("artifact-recovery");String id,pid;
        try(Engine e=new Engine(data,startup())){pid=Json.required(project(e),"id");id=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",parameters())),"id");check(Json.bool(await(e,id),"artifactCommitted",false),"artifact fixture completed");String jobId=id;e.store.tx(c->{JsonObject job=Store.document(c,"media_jobs",jobId);job.addProperty("status","running");job.addProperty("artifactCommitted",false);job.remove("manifestHash");job.remove("completeHash");job.remove("summary");Store.update(c,"UPDATE media_jobs SET status='running',data=? WHERE id=?",job,jobId);return null;});}
        try(Engine e=new Engine(data,startup())){JsonObject recovered=cmd(e,"media.job.get",Json.obj("jobId",id));check(Json.required(recovered,"status").equals("interrupted")&&Json.bool(recovered,"canImport",false),"reconcile complete file before DB bookkeeping crash gap");cmd(e,"media.video.import",Json.obj("jobId",id));check(Json.bool(await(e,id),"assetsCommitted",false),"recovered artifact imports without re-extraction");
            String damaged=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",parameters())),"id");check(Json.bool(await(e,damaged),"artifactCommitted",false),"tamper fixture completed");Path frame=data.resolve("media-jobs/"+damaged+"/generation/frames/frame-00000000.png");Files.write(frame,new byte[]{1},StandardOpenOption.APPEND);cmd(e,"media.video.import",Json.obj("jobId",damaged));JsonObject failed=await(e,damaged);check(Json.required(failed,"status").equals("failed")&&!Json.bool(failed,"assetsCommitted",true),"changed frame prevents complete import transaction");check(Json.integer(e.projects.get(pid),"assetCount",0)==6,"tampered artifact adds zero assets");
            cmd(e,"system.suspend",new JsonObject());String queued=Json.required(cmd(e,"media.video.create",Json.obj("projectId",pid,"sourcePath",video.toString(),"parameters",parameters())),"id");check(!Json.bool(cmd(e,"system.prepareUpdate",new JsonObject()),"ready",true),"queued media blocks installer update");JsonObject lock=cmd(e,"system.prepareDataMaintenance",Json.obj("operationId","media-backup-check"));check(Json.bool(lock,"ready",false),"queued media can be backed up without dispatch");check(Json.required(cmd(e,"media.job.get",Json.obj("jobId",queued)),"status").equals("queued"),"data maintenance preserves queued media");cmd(e,"system.cancelDataMaintenance",Json.obj("operationId","media-backup-check"));
        }
    }
}
