package cn.autolabel.engine;

import com.google.gson.*;
import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

final class MultiTaskEvaluationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static void near(double actual,double expected,String message){check(Math.abs(actual-expected)<1e-8,message+": "+actual);}
    static JsonObject polygon(String id,double... coordinates){JsonArray points=new JsonArray();for(int i=0;i<coordinates.length;i+=2)points.add(Json.obj("x",coordinates[i],"y",coordinates[i+1]));return Json.obj("id",id,"type","segment","classId","item","points",points);}
    static JsonObject box(String id,double x,double y,double w,double h,double angle){return Json.obj("id",id,"type","obb","classId","item","bbox",Json.obj("x",x,"y",y,"width",w,"height",h),"rotation",angle);}
    static void run(Path root)throws Exception{geometry();EvaluationTest.matching();EvaluationTest.matchingOracle();classification(root);fresh(root);}
    static void geometry(){
        JsonObject horizontal=box("a",10,10,10,2,0),vertical=box("b",10,10,10,2,90);near(Matching.iou(horizontal,vertical),1.0/9,"rotated cross uses rectangle intersection rather than stored bbox");near(Matching.iou(box("a",20,20,10,10,0),box("b",20,20,10,10,45)),1/Math.sqrt(2),"45 degree equal squares have analytic IoU");
        JsonObject explicit=Json.obj("id","corners","type","obb","classId","item","points",Annotations.obb(vertical));near(Matching.iou(vertical,explicit),1,"bbox-angle and ordered corners equivalent");JsonArray reverse=new JsonArray();for(int i=3;i>=0;i--)reverse.add(Json.array(explicit,"points").get(i));explicit.add("points",reverse);near(Matching.iou(vertical,explicit),1,"corner winding does not change area");
        JsonObject l=polygon("l",0,0,4,0,4,1,1,1,1,4,0,4),square=polygon("s",0,0,2,0,2,2,0,2);near(Matching.iou(l,square),3.0/8,"concave L overlap analytic area");near(Matching.iou(l,polygon("inside",0,0,1,0,1,1,0,1)),1.0/7,"contained polygon area");near(Matching.iou(l,polygon("notch",2,2,3,2,3,3,2,3)),0,"overlapping bounding boxes with empty true region");near(Matching.iou(l,polygon("touch",4,0,5,0,5,1,4,1)),0,"boundary contact has zero area");
        JsonObject u=polygon("u",0,0,4,0,4,4,3,4,3,1,1,1,1,4,0,4),strip=polygon("strip",0,2,4,2,4,3,0,3);near(Matching.iou(u,strip),1.0/6,"two disconnected intersection components both counted");JsonObject result=Matching.evaluate("segment",Json.arr(l),Json.arr(square),0.1,100);near(Json.decimal(Json.object(result,"metrics"),"meanCenterErrorPixels",0),Math.sqrt(2)*5/14,"region centroid replaces bbox center");
        var ring=new java.awt.geom.Area(new java.awt.geom.Rectangle2D.Double(0,0,4,4));ring.subtract(new java.awt.geom.Area(new java.awt.geom.Rectangle2D.Double(1,1,2,2)));near(RegionGeometry.area(ring),12,"internal area accumulator subtracts holes");
        Random rng=new Random(956);boolean all=true;for(int i=0;i<60;i++){int x=rng.nextInt(6),y=rng.nextInt(6),w=1+rng.nextInt(4),h=1+rng.nextInt(4);JsonObject rectangle=polygon("r",x,y,x+w,y,x+w,y+h,x,y+h),a=i%2==0?l:u;int intersection=0,union=0;for(int row=0;row<10;row++)for(int col=0;col<10;col++){boolean insideA=inside(Json.array(a,"points"),col+0.5,row+0.5),insideB=col>=x&&col<x+w&&row>=y&&row<y+h;if(insideA&&insideB)intersection++;if(insideA||insideB)union++;}all&=Math.abs(Matching.iou(a,rectangle)-(double)intersection/union)<1e-9;}check(all,"60 integer concave fixtures agree with independent exact cell oracle");
        l.add("keypoints",Json.arr(Json.obj("name","irrelevant","x",1,"y",1,"visibility",2)));JsonObject polygonMetrics=Json.object(Matching.evaluate("segment",Json.arr(l),Json.arr(square),0.1,100),"metrics");check(Json.integer(polygonMetrics,"locatedTruthKeypoints",-1)==0&&Json.integer(polygonMetrics,"pairedKeypoints",-1)==0,"non-Pose auxiliary fields cannot become keypoint metrics");
    }
    static boolean inside(JsonArray points,double x,double y){boolean contained=false;for(int i=0,j=points.size()-1;i<points.size();j=i++){JsonObject a=points.get(i).getAsJsonObject(),b=points.get(j).getAsJsonObject();double ax=Annotations.num(a,"x"),ay=Annotations.num(a,"y"),bx=Annotations.num(b,"x"),by=Annotations.num(b,"y");if((ay>y)!=(by>y)&&x<(bx-ax)*(y-ay)/(by-ay)+ax)contained=!contained;}return contained;}
    static JsonObject cmd(Engine e,String name,JsonObject p)throws Exception{return (JsonObject)e.command(name,p);}
    static void classification(Path root)throws Exception{String evaluationId;JsonObject fixed;try(Engine e=new Engine(root.resolve("classification-data"))){JsonObject project=EngineTest.project(e,"classify");String pid=Json.required(project,"id");e.projects.update(Json.obj("projectId",pid,"classes",Json.arr(Json.obj("id","item","name","物品"),Json.obj("id","other","name","其他"))));JsonArray ids=EngineTest.importSamples(e,pid,5);JsonObject set=cmd(e,"evaluationSet.create",Json.obj("projectId",pid,"name","分类独立答案","assetIds",ids));String setId=Json.required(set,"id");
            ManualChainTest.rejects("evaluation_classification_truth_required",()->cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",ids.get(0),"baseTruthVersion",0,"source","manual","annotations",new JsonArray())));JsonObject correct=EngineTest.label("classify"),wrong=correct.deepCopy();wrong.addProperty("id",Json.id());wrong.addProperty("classId","other");int revision=1;for(JsonElement id:ids)revision=Json.integer(cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",id,"baseTruthVersion",0,"source","manual","annotations",Json.arr(correct))),"setRevision",0);JsonObject version=cmd(e,"evaluationSet.publish",Json.obj("setId",setId,"baseSetRevision",revision));
            String run=EvaluationTest.fixtureRun(e,pid,ids,Arrays.asList(Json.arr(correct),Json.arr(wrong),new JsonArray(),null,null),new JsonArray());e.store.tx(c->{Store.update(c,"UPDATE samples SET status='unknown' WHERE run_id=? AND asset_id=?",run,ids.get(4).getAsString());return null;});JsonObject evaluation=cmd(e,"evaluation.create",Json.obj("setVersionId",version.get("id"),"schemes",Json.arr(Json.obj("runId",run))));evaluationId=Json.required(evaluation,"id");fixed=evaluation.deepCopy();JsonObject metrics=Json.object(Json.array(evaluation,"schemes").get(0).getAsJsonObject(),"metrics"),classified=Json.object(metrics,"classification");
            check(Json.required(metrics,"metricKind").equals("classification")&&metrics.get("meanMatchedIoU").isJsonNull()&&metrics.get("missedObjects").isJsonNull(),"classification never exposes box or missed-object metrics");check(Json.required(Json.object(metrics,"notApplicableReasons"),"meanMatchedIoU").equals("task_not_applicable"),"irrelevant geometry explicitly not applicable");check(Json.integer(classified,"samples",0)==3&&Json.integer(classified,"correct",0)==1&&Json.integer(classified,"incorrect",0)==1&&Json.integer(classified,"missingPrediction",0)==1,"correct wrong and missing predictions separate");near(Json.decimal(classified,"accuracy",0),1.0/3,"empty successful classification belongs in denominator");check(Json.integer(metrics,"failedSamples",0)==1&&Json.integer(metrics,"unknownSamples",0)==1&&Json.integer(metrics,"totalTruthLabels",0)==5,"classification coverage includes unavailable counts and full labels");check(Json.array(classified,"confusion").size()==3&&Json.array(classified,"confusion").asList().stream().anyMatch(c->c.getAsJsonObject().get("predictionClassId").isJsonNull()),"confusion matrix retains missing prediction cell");
            JsonObject rows=cmd(e,"evaluation.results",Json.obj("evaluationId",evaluationId));check(Json.array(rows,"items").get(1).getAsJsonObject().has("classResult")&&Json.array(Json.array(rows,"items").get(1).getAsJsonObject(),"pairs").isEmpty(),"classification row separate from geometric pairs");JsonObject reviews=cmd(e,"review.build",Json.obj("evaluationId",evaluationId,"rules",Json.obj("minMatchedIoU",0.99,"maxNormalizedPointError",0)));Set<String> reasons=new HashSet<>();for(JsonElement item:Json.array(reviews,"items"))reasons.add(Json.required(item.getAsJsonObject(),"reason"));check(reasons.equals(Set.of("classification_wrong","classification_missing","prediction_failed","prediction_unknown")),"classification reviews do not apply geometry thresholds");
            cmd(e,"evaluationSet.saveTruth",Json.obj("setId",setId,"assetId",ids.get(0),"baseTruthVersion",1,"source","manual","annotations",Json.arr(wrong)));check(cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).equals(fixed),"class truth edit does not change prior evaluation");String failed=EvaluationTest.fixtureRun(e,pid,ids,Arrays.asList(null,null,null,null,null),new JsonArray());JsonObject empty=cmd(e,"evaluation.create",Json.obj("setVersionId",version.get("id"),"schemes",Json.arr(Json.obj("runId",failed))));JsonObject emptyMetrics=Json.object(Json.array(empty,"schemes").get(0).getAsJsonObject(),"metrics");check(Json.object(emptyMetrics,"classification").get("accuracy").isJsonNull()&&Json.required(Json.object(emptyMetrics,"notApplicableReasons"),"classification.accuracy").equals("zero_denominator"),"all unavailable classification accuracy is null");
        }try(Engine e=new Engine(root.resolve("classification-data"))){check(cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).equals(fixed),"classification snapshot survives restart");}}
    static void fresh(Path root)throws Exception{List<JsonObject> bodies=new java.util.concurrent.CopyOnWriteArrayList<>();HttpServer server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),8);server.createContext("/v1/responses",exchange->{try{JsonObject body=Json.parse(new String(exchange.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));bodies.add(body);String target=null,task=null;for(JsonElement message:Json.array(body,"input"))for(JsonElement part:Json.array(message.getAsJsonObject(),"content")){String text=Json.str(part.getAsJsonObject(),"text","");if(text.startsWith("{")){JsonObject value=Json.parse(text);if(value.has("taskType"))task=Json.required(value,"taskType");if(Json.str(value,"role","").equals("target"))target=Json.required(value,"assetId");}}String content=Json.obj("assetId",target,"annotations",Json.arr(EngineTest.label(task))).toString();EngineTest.Mock.respond(exchange,200,Json.obj("status","completed","output",Json.arr(Json.obj("type","message","content",Json.arr(Json.obj("type","output_text","text",content))))));}catch(Exception error){EngineTest.Mock.respond(exchange,500,Json.obj("error","fixture failure"));}finally{exchange.close();}});server.start();
        try(Engine e=new Engine(root.resolve("five-task-fresh"))){JsonObject provider=e.providers.save(Json.obj("name","五类重跑协议fixture","baseUrl","http://127.0.0.1:"+server.getAddress().getPort()+"/v1","protocol","responses","requestsPerMinute",60000,"timeoutMs",5000));e.providers.credential(Json.obj("providerId",provider.get("id"),"key","local-fixture-only"));
            for(String task:List.of("obb","segment","classify")){JsonObject project=EngineTest.project(e,task);String pid=Json.required(project,"id");JsonArray ids=EngineTest.importSamples(e,pid,1);JsonObject set=cmd(e,"evaluationSet.create",Json.obj("projectId",pid,"name",task,"assetIds",ids));JsonObject truth=EngineTest.label(task);truth.addProperty("id","STAGE5_TRUTH_NEVER_SENT");JsonObject saved=cmd(e,"evaluationSet.saveTruth",Json.obj("setId",set.get("id"),"assetId",ids.get(0),"baseTruthVersion",0,"source","manual","annotations",Json.arr(truth)));JsonObject version=cmd(e,"evaluationSet.publish",Json.obj("setId",set.get("id"),"baseSetRevision",saved.get("setRevision")));JsonObject comparison=cmd(e,"evaluation.rerun.create",Json.obj("setVersionId",version.get("id"),"budgetScopeId","fresh-"+task,"maxRequests",1,"schemes",Json.arr(Json.obj("providerId",provider.get("id"),"model","fixture","prompt","classify or locate the visible object"))));
                check(Json.required(EngineTest.waitRun(e,Json.array(comparison,"runIds").get(0).getAsString(),10000),"status").equals("completed"),task+" fresh model result validates");JsonObject result=cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparison.get("id"))),metrics=Json.object(Json.array(result,"schemes").get(0).getAsJsonObject(),"metrics");near(task.equals("classify")?Json.decimal(Json.object(metrics,"classification"),"accuracy",0):Json.decimal(metrics,"meanMatchedIoU",0),1,task+" fresh task metric");check(task.equals("classify")?metrics.get("overlapMetric").isJsonNull():Json.required(metrics,"overlapMetric").equals(task.equals("obb")?"rotated_iou":"polygon_iou"),task+" actual metric declared");check(Json.required(result,"source").equals("fresh_run_snapshot")&&Json.integer(e.projects.asset(ids.get(0).getAsString()),"version",-1)==0,task+" provenance and formal protection retained");
            }check(bodies.size()==3&&bodies.stream().noneMatch(b->b.toString().contains("STAGE5_TRUTH_NEVER_SENT")),"three fresh requests contain no ground truth");
        }finally{server.stop(0);}
    }
}
