package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;

final class ResourceIntegrationTest {
    static void check(boolean value,String message){EngineTest.check(value,message);}
    static JsonObject cmd(Engine e,String name,JsonObject p)throws Exception{return (JsonObject)e.command(name,p);}
    static void run(Path root)throws Exception{Path data=root.resolve("resource-integration");String referenceId,runId,evaluationId;
        try(EngineTest.Mock mock=new EngineTest.Mock()){
            try(Engine e=new Engine(data)){JsonObject provider=EngineTest.provider(e,mock,"responses"),source=EngineTest.project(e,"detect"),target=EngineTest.project(e,"detect");String sourcePid=Json.required(source,"id"),targetPid=Json.required(target,"id");e.projects.update(Json.obj("projectId",sourcePid,"classes",Json.arr(Json.obj("id","source","name","来源类别"))));String sourceAsset=EngineTest.importSamples(e,sourcePid,1).get(0).getAsString();JsonArray targets=EngineTest.importSamples(e,targetPid,2);JsonObject annotation=EngineTest.label("detect");annotation.addProperty("classId","source");annotation.addProperty("id","REFERENCE_VERSION_ONE");e.projects.save(Json.obj("assetId",sourceAsset,"baseVersion",0,"confirm",true,"annotations",Json.arr(annotation)));
                JsonObject prompt=cmd(e,"resource.save",Json.obj("kind","prompt","name","资源提示词","content","按可见边界标注"));JsonObject applied=cmd(e,"resource.apply",Json.obj("projectId",targetPid,"resourceId",prompt.get("id"),"version",1,"fields",Json.arr("prompt")));check(Json.str(Json.object(Json.object(applied,"project"),"settings"),"prompt","").equals("按可见边界标注"),"resource save and explicit apply routed");ManualChainTest.rejects("reference_invalid",()->cmd(e,"resource.image",Json.obj("resourceId",prompt.get("id"))));
                JsonObject reference=cmd(e,"resource.reference",Json.obj("assetId",sourceAsset,"assetVersion",1,"name","固定人工参考","note","人工版本一"));referenceId=Json.required(reference,"id");JsonObject media=cmd(e,"resource.image",Json.obj("resourceId",referenceId,"version",1));Path fixedPath=Path.of(Json.required(media,"path"));check(Json.integer(media,"resourceVersion",0)==1&&Media.hash(fixedPath).equals(Json.required(media,"contentHash")),"resource.image resolves exact version and managed hash");check(!fixedPath.equals(e.projects.path(sourceAsset))&&javax.imageio.ImageIO.read(fixedPath.toFile())!=null,"resource media is independent valid PNG");
                JsonObject selection=Json.obj("resourceId",referenceId),runRequest=Json.obj("projectId",targetPid,"providerId",provider.get("id"),"model","fixture","prompt","locate","assetIds",Json.arr(targets.get(1)),"maxRequests",1,"referenceResources",Json.arr(selection));ManualChainTest.rejects("reference_class_map_required",()->cmd(e,"run.create",runRequest));check(mock.calls.get()==0,"unmapped shared reference fails before calls");selection.add("classMap",Json.obj("source","item"));e.runs.suspend(true);JsonObject run=cmd(e,"run.create",runRequest);runId=Json.required(run,"id");JsonObject frozen=Json.array(Json.object(run,"snapshot"),"references").get(0).getAsJsonObject();check(Json.integer(frozen,"resourceVersion",0)==1&&Json.required(Json.array(frozen,"annotations").get(0).getAsJsonObject(),"classId").equals("item"),"run freezes resolved resource version and mapped class");
                JsonObject changed=annotation.deepCopy();changed.addProperty("id","REFERENCE_VERSION_TWO");Json.object(changed,"bbox").addProperty("x",210);e.projects.save(Json.obj("assetId",sourceAsset,"baseVersion",1,"confirm",true,"annotations",Json.arr(changed)));cmd(e,"resource.reference",Json.obj("id",referenceId,"baseVersion",1,"assetId",sourceAsset,"assetVersion",2,"name","固定人工参考更新","note","人工版本二"));check(Json.integer(cmd(e,"resource.get",Json.obj("resourceId",referenceId)),"version",0)==2&&Json.integer(cmd(e,"resource.get",Json.obj("resourceId",referenceId,"version",1)),"version",0)==1,"resource head and historical read routed");
                Files.delete(e.projects.path(sourceAsset));e.runs.suspend(false);check(Json.required(EngineTest.waitRun(e,runId,15000),"status").equals("completed"),"shared reference runs after source file removal");check(mock.bodies.get(0).toString().contains("REFERENCE_VERSION_ONE")&&!mock.bodies.get(0).toString().contains("REFERENCE_VERSION_TWO"),"sending uses frozen reference annotation version");check(mock.bodies.get(0).toString().contains("人工版本一")&&mock.bodies.get(0).toString().contains(referenceId)&&!mock.bodies.get(0).toString().contains("referenceImage"),"reference note and version provenance sent without file paths");check(Json.array(Json.array(mock.bodies.get(0),"input").get(0).getAsJsonObject(),"content").asList().stream().filter(part->Json.str(part.getAsJsonObject(),"type","").equals("input_image")).count()==2,"actual request includes managed reference plus target images");
                JsonObject set=cmd(e,"evaluationSet.create",Json.obj("projectId",targetPid,"name","共享参考评测","assetIds",Json.arr(targets.get(1))));JsonObject saved=cmd(e,"evaluationSet.saveTruth",Json.obj("setId",set.get("id"),"assetId",targets.get(1),"baseTruthVersion",0,"source","manual","annotations",Json.arr(EngineTest.label("detect"))));JsonObject version=cmd(e,"evaluationSet.publish",Json.obj("setId",set.get("id"),"baseSetRevision",saved.get("setRevision")));JsonObject freshSpec=Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","referenceResources",Json.arr(Json.obj("resourceId",referenceId,"version",1,"classMap",Json.obj("source","item"))));JsonObject comparison=cmd(e,"evaluation.rerun.create",Json.obj("setVersionId",version.get("id"),"budgetScopeId","resource-fresh","maxRequests",1,"schemes",Json.arr(freshSpec)));check(Json.required(EngineTest.waitRun(e,Json.array(comparison,"runIds").get(0).getAsString(),15000),"status").equals("completed"),"fresh comparison sends selected shared reference");JsonObject evaluation=cmd(e,"evaluation.rerun.finish",Json.obj("comparisonId",comparison.get("id")));evaluationId=Json.required(evaluation,"id");check(Json.integer(Json.object(Json.array(evaluation,"schemes").get(0).getAsJsonObject(),"metrics"),"matchedObjects",0)==1,"fresh shared reference produces fixed quality result");
                JsonObject leakSet=cmd(e,"evaluationSet.create",Json.obj("projectId",targetPid,"name","同内容泄漏fixture","assetIds",Json.arr(targets.get(0))));JsonObject leakTruth=cmd(e,"evaluationSet.saveTruth",Json.obj("setId",leakSet.get("id"),"assetId",targets.get(0),"baseTruthVersion",0,"source","manual","annotations",Json.arr(EngineTest.label("detect"))));JsonObject leakVersion=cmd(e,"evaluationSet.publish",Json.obj("setId",leakSet.get("id"),"baseSetRevision",leakTruth.get("setRevision")));JsonObject leak=Json.obj("setVersionId",leakVersion.get("id"),"budgetScopeId","resource-leak","maxRequests",1,"schemes",Json.arr(freshSpec));check(!Json.bool(cmd(e,"evaluation.rerun.preflight",leak),"canStart",true),"shared reference same content leakage blocked in preflight");ManualChainTest.rejects("evaluation_reference_overlap",()->cmd(e,"evaluation.rerun.create",leak));check(mock.calls.get()==2,"blocked shared leak does not send third call");
                JsonArray heads=(JsonArray)e.command("resource.list",new JsonObject());check(heads.size()==2&&heads.asList().stream().noneMatch(item->Set.of("resource_version","evaluation_comparison").contains(Json.str(item.getAsJsonObject(),"kind",""))),"resource list hides internal revisions and comparison");check(((JsonArray)e.command("resource.list",Json.obj("kind","evaluation_comparison"))).size()==1,"explicit comparison lookup still works");
                check(Json.bool(cmd(e,"system.prepareUpdate",new JsonObject()),"ready",false),"resource commands leave no active work");for(String command:List.of("resource.save","resource.apply","resource.reference"))ManualChainTest.rejects("engine_update_locked",()->cmd(e,command,new JsonObject()));check(cmd(e,"resource.image",Json.obj("resourceId",referenceId,"version",1)).has("path")&&cmd(e,"resource.get",Json.obj("resourceId",referenceId)).has("content"),"resource image and metadata readable under maintenance");cmd(e,"system.cancelUpdate",new JsonObject());
            }
            int sent=mock.calls.get();try(Engine e=new Engine(data)){check(Json.integer(Json.array(Json.object(e.runs.get(runId),"snapshot"),"references").get(0).getAsJsonObject(),"resourceVersion",0)==1,"run retains pinned resource after restart");check(cmd(e,"resource.image",Json.obj("resourceId",referenceId,"version",1)).has("path")&&cmd(e,"evaluation.get",Json.obj("evaluationId",evaluationId)).has("schemes"),"resource media and evaluation survive restart");check(mock.calls.get()==sent,"restart sends no duplicate shared-reference calls");}
        }
    }
}
