package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import static cn.autolabel.engine.FlowIntegrationTest.*;

final class ReuseIntegrationTest {
    static void run(Path root)throws Exception{sameInput(root);invalidations(root);retryAndLegacy(root);flowAndRestart(root);workerConcurrency(root);bindingCommitRace(root);}
    static JsonObject boundProvider(Engine e,EngineTest.Mock mock)throws Exception{JsonObject provider=provider(e,mock);cmd(e,"credential.set",Json.obj("providerId",provider.get("id"),"key","reuse-fixture-secret","credentialBindingVersion",Json.id()));return provider;}
    static JsonObject request(JsonObject provider,String pid,JsonArray ids){return Json.obj("projectId",pid,"providerId",provider.get("id"),"model","fixture","prompt","locate","assetIds",ids,"concurrency",1,"maxRetries",0,"maxRequests",1);}
    static JsonObject finished(Engine e,JsonObject request)throws Exception{JsonObject run=cmd(e,"run.create",request);return EngineTest.waitRun(e,Json.required(run,"id"),12000);}
    static JsonObject sample(JsonObject run){return Json.array(run,"samples").get(0).getAsJsonObject();}
    static void sameInput(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("reuse-same"))){JsonObject provider=boundProvider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);String aid=ids.get(0).getAsString();JsonObject request=request(provider,pid,ids);request.addProperty("budgetScopeId","reuse-exhausted");JsonObject first=finished(e,request);String source=Json.required(first,"id");JsonObject attempt=e.runs.attempts(Json.obj("runId",source)).get(0).getAsJsonObject();check(Json.required(first,"status").equals("completed")&&mock.calls.get()==1&&attempt.has("reuseFingerprint")&&attempt.has("credentialBindingVersion"),"actual first request persists proven reusable fingerprint and binding");
            JsonObject second=finished(e,request);String secondId=Json.required(second,"id");check(Json.required(second,"status").equals("completed")&&mock.calls.get()==1&&Json.integer(second,"requestsUsed",-1)==0&&Json.integer(Json.object(second,"budget"),"requestsUsed",0)==1,"cache hit succeeds before exhausted budget without another request");check(Json.integer(Json.object(second,"statistics"),"succeeded",0)==1&&Json.integer(Json.object(second,"statistics"),"reused",0)==1&&Json.integer(sample(second),"attemptCount",-1)==0&&e.runs.attempts(Json.obj("runId",secondId)).isEmpty(),"reuse is successful subset and creates no attempt");JsonObject provenance=Json.object(sample(second),"reusedFrom");check(Json.bool(sample(second),"reused",false)&&Json.required(provenance,"sourceRunId").equals(source)&&Json.required(provenance,"sourceAttemptId").equals(Json.required(attempt,"id")),"sample exposes exact source run candidate and real attempt provenance");JsonObject candidate=e.projects.history(aid).asList().stream().map(JsonElement::getAsJsonObject).filter(v->Json.integer(v,"version",0)==Json.integer(sample(second),"candidateVersion",0)).findFirst().orElseThrow();check(Json.bool(candidate,"reused",false)&&Json.required(candidate,"status").equals("candidate")&&!candidate.has("attemptId")&&Json.object(candidate,"reusedFrom").equals(provenance),"new independent reuse candidate has no fabricated attempt or confirmation");
            JsonObject third=finished(e,request);check(mock.calls.get()==1&&Json.required(Json.object(sample(third),"reusedFrom"),"sourceRunId").equals(source),"repeated reuse traces original real API completion instead of extending a reuse chain");JsonObject gates=e.providers.limits(),budgetMiss=request.deepCopy();budgetMiss.addProperty("prompt","uncached prompt under exhausted budget");JsonObject blocked=finished(e,budgetMiss);check(Json.required(blocked,"pauseReason").equals("budget_exhausted")&&mock.calls.get()==1&&gates.equals(e.providers.limits()),"uncached exhausted run pauses before reserving provider RPM permit");cmd(e,"run.cancel",Json.obj("runId",blocked.get("id")));
            int beforeManual=Json.integer(e.projects.asset(aid),"version",0);cmd(e,"annotation.save",Json.obj("assetId",aid,"baseVersion",beforeManual,"annotations",Json.arr(EngineTest.label("detect")),"confirm",true));int manual=Json.integer(e.projects.asset(aid),"version",0);JsonObject protectedRun=finished(e,request);check(Json.integer(protectedRun,"reused",0)==1&&Json.integer(e.projects.asset(aid),"version",0)==manual&&Json.required(e.projects.asset(aid),"status").equals("confirmed"),"reuse preserves current confirmed annotation");cmd(e,"annotation.draft",Json.obj("assetId",aid,"baseVersion",manual,"annotations",Json.arr(EngineTest.label("detect"))));JsonObject drafted=finished(e,request);check(Json.integer(drafted,"reused",0)==1&&e.projects.asset(aid).has("draft")&&Json.integer(e.projects.asset(aid),"version",0)==manual,"reuse preserves unsaved human draft and baseline");
            JsonObject forced=request.deepCopy();forced.remove("budgetScopeId");forced.addProperty("forceRerun",true);JsonObject fresh=finished(e,forced);check(mock.calls.get()==2&&Json.integer(fresh,"reused",-1)==0&&Json.bool(fresh,"forceRerun",false)&&!fresh.has("force"),"public forceRerun performs real request and hides internal force flag");JsonObject freshVersion=e.projects.history(aid).asList().stream().map(JsonElement::getAsJsonObject).filter(v->Json.integer(v,"version",0)==Json.integer(sample(fresh),"candidateVersion",0)).findFirst().orElseThrow();check(!freshVersion.has("reused")&&!freshVersion.has("reusedFrom"),"fresh API version cannot inherit reused metadata from prior current asset");JsonObject afterForced=finished(e,request);check(mock.calls.get()==2&&Json.required(Json.object(sample(afterForced),"reusedFrom"),"sourceRunId").equals(Json.required(fresh,"id")),"forced fresh success becomes the newest reusable source for a later run");
            JsonObject disabled=forced.deepCopy();disabled.remove("forceRerun");disabled.addProperty("reuseEnabled",false);JsonObject without=finished(e,disabled);check(mock.calls.get()==3&&Json.integer(without,"reused",-1)==0,"explicit reuseEnabled false bypasses lookup");JsonObject afterDisabled=finished(e,request);check(mock.calls.get()==3&&Json.required(Json.object(sample(afterDisabled),"reusedFrom"),"sourceRunId").equals(Json.required(without,"id")),"disabled lookup still records real success for a future enabled run");String persisted=e.runs.attempts(Json.obj("runId",source)).toString()+second.toString()+candidate.toString();check(!persisted.contains("reuse-fixture-secret")&&!persisted.contains("iVBOR"),"reuse fingerprint and provenance expose neither key nor base64 input");
            JsonObject invalid=request.deepCopy();invalid.addProperty("reuseMaxAgeSeconds",1.5);ManualChainTest.rejects("reuse_age_invalid",()->cmd(e,"run.create",invalid));invalid.remove("reuseMaxAgeSeconds");invalid.addProperty("reuseEnabled","true");ManualChainTest.rejects("reuse_policy_invalid",()->cmd(e,"run.create",invalid));
        }
    }
    static void workerConcurrency(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("reuse-worker-concurrency"))){JsonObject provider=boundProvider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,8);JsonObject request=request(provider,pid,ids);request.addProperty("concurrency",6);request.addProperty("maxRequests",8);JsonObject done=finished(e,request);check(Json.required(done,"status").equals("completed")&&mock.calls.get()==8&&mock.maxActive.get()==2,"parallel preparation preserves shared provider concurrency and one request per distinct sample");check(Json.integer(Json.object(done,"statistics"),"succeeded",0)==8&&Json.integer(Json.object(done,"statistics"),"reused",-1)==0,"deferred permits do not duplicate successful samples or mark misses reused");}
    }
    static void bindingCommitRace(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("reuse-binding-commit-race"))){JsonObject provider=boundProvider(e,mock);String providerId=Json.required(provider,"id"),binding=e.providers.credentialBindingVersion(providerId),pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);JsonObject request=request(provider,pid,ids);finished(e,request);e.runs.suspend(true);String rid=Json.required(cmd(e,"run.create",request),"id"),claim=Json.id();JsonObject run=e.store.read(c->Store.document(c,"runs",rid)),row=e.store.read(c->Store.one(c,"SELECT * FROM samples WHERE run_id=?",rid)),data=Json.parse(row.get("data").getAsString());String sampleId=Json.required(row,"id");JsonObject body=e.providers.body(provider,"fixture",e.runs.messages(run,data),new JsonArray(),true);Runs.ReuseRequest prepared=e.runs.prepareReuse(run,row,body,e.providers.credentialFor(provider,Json.object(run,"snapshot")));check(prepared!=null&&e.runs.reuse.find(prepared.prepared(),System.currentTimeMillis())!=null,"binding race begins with a validated real reusable source");
            // 模拟 worker 已完成读取而尚未提交复用的边界；保持同一个真实 sample claim。
            e.store.tx(c->{Store.update(c,"UPDATE samples SET status='preparing',active_attempt=? WHERE id=?",claim,sampleId);return null;});e.runs.suspend(false);cmd(e,"credential.set",Json.obj("providerId",providerId,"key","new-binding-secret","credentialBindingVersion",Json.id()));check(e.runs.applyReuse(run,row,claim,prepared),"writer handles credential change after source lookup");JsonObject paused=e.runs.get(rid);check(Json.required(paused,"status").equals("paused")&&Json.required(paused,"pauseReason").equals("credential_binding_changed")&&Json.required(sample(paused),"status").equals("queued")&&Json.integer(Json.object(paused,"statistics"),"preparing",-1)==0,"credential rejection atomically releases claimed preparing sample");check(e.runs.attempts(Json.obj("runId",rid)).isEmpty()&&mock.calls.get()==1&&Json.integer(paused,"requestsUsed",-1)==0,"credential race produces no new attempt budget or request");JsonObject owner=Json.obj("operationId","reuse-binding-maintenance");check(Json.bool(cmd(e,"system.prepareDataMaintenance",owner),"ready",false),"credential rejection leaves no phantom worker blocking maintenance");cmd(e,"system.cancelDataMaintenance",owner);cmd(e,"credential.set",Json.obj("providerId",providerId,"key","reuse-fixture-secret","credentialBindingVersion",binding));cmd(e,"run.resume",Json.obj("runId",rid));check(Json.integer(EngineTest.waitRun(e,rid,10000),"reused",0)==1&&mock.calls.get()==1,"released sample can resume with original binding without an extra API call");
        }
    }
    static void invalidations(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("reuse-invalidations"))){JsonObject provider=boundProvider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);JsonObject base=request(provider,pid,ids),first=finished(e,base);String firstId=Json.required(first,"id");e.store.tx(c->{JsonObject row=Store.one(c,"SELECT id,data FROM attempts WHERE run_id=?",firstId),attempt=Json.parse(row.get("data").getAsString());attempt.addProperty("completedAt",Instant.now().minusSeconds(60).toString());Store.update(c,"UPDATE attempts SET data=? WHERE id=?",attempt,Json.required(row,"id"));return null;});JsonObject expired=base.deepCopy();expired.addProperty("reuseMaxAgeSeconds",1);check(Json.integer(finished(e,expired),"requestsUsed",0)==1&&mock.calls.get()==2,"expired original completion performs a new request");
            JsonObject prompt=base.deepCopy();prompt.addProperty("prompt","different instruction");check(Json.integer(finished(e,prompt),"reused",-1)==0&&mock.calls.get()==3,"changed prompt invalidates reuse");cmd(e,"project.update",Json.obj("projectId",pid,"settings",Json.obj("rules","semantic rule changed")));check(Json.integer(finished(e,base),"requestsUsed",0)==1&&mock.calls.get()==4,"changed semantic template invalidates reuse");
            cmd(e,"credential.set",Json.obj("providerId",provider.get("id"),"key","replacement-secret","credentialBindingVersion",Json.id()));check(Json.integer(finished(e,base),"requestsUsed",0)==1&&mock.calls.get()==5,"new credential binding invalidates previous account result");
            e.providers.save(Json.obj("id",provider.get("id"),"headers",Json.obj("X-Fixture-Revision","changed")));check(Json.integer(finished(e,base),"requestsUsed",0)==1&&mock.calls.get()==6,"provider revision and effective custom headers invalidate reuse");
        }
    }
    static void retryAndLegacy(Path root)throws Exception{
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine e=new Engine(root.resolve("reuse-retry"))){JsonObject provider=boundProvider(e,mock);String pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);JsonObject request=request(provider,pid,ids);finished(e,request);Path input=e.projects.path(ids.get(0).getAsString());byte[] bytes=Files.readAllBytes(input);e.runs.suspend(true);JsonObject created=cmd(e,"run.create",request);String rid=Json.required(created,"id");Files.delete(input);e.runs.suspend(false);JsonObject failed=EngineTest.waitRun(e,rid,10000);check(Json.required(failed,"status").equals("completed_with_errors")&&Json.integer(sample(failed),"attemptCount",-1)==0&&mock.calls.get()==1,"missing current fixed image cannot reuse or send API");Files.write(input,bytes);cmd(e,"run.retry",Json.obj("runId",rid));JsonObject retried=EngineTest.waitRun(e,rid,10000);check(Json.required(retried,"status").equals("completed")&&Json.integer(retried,"reused",-1)==0&&mock.calls.get()==2,"explicit failed-item retry bypasses cache even when original attempt count was zero");
            String pidLegacy=Json.required(EngineTest.project(e,"detect"),"id");JsonArray legacyIds=EngineTest.importSamples(e,pidLegacy,1);cmd(e,"credential.set",Json.obj("providerId",provider.get("id"),"key","legacy-no-binding"));JsonObject legacyRequest=request(provider,pidLegacy,legacyIds),legacy=finished(e,legacyRequest);JsonObject legacyAttempt=e.runs.attempts(Json.obj("runId",legacy.get("id"))).get(0).getAsJsonObject();check(!legacyAttempt.has("reuseFingerprint"),"legacy credential without frozen binding does not mint reusable evidence");cmd(e,"credential.set",Json.obj("providerId",provider.get("id"),"key","legacy-no-binding","credentialBindingVersion",Json.id()));check(Json.integer(finished(e,legacyRequest),"requestsUsed",0)==1&&mock.calls.get()==4,"new binding does not retroactively make old source reusable");
        }
    }
    static void flowAndRestart(Path root)throws Exception{
        Path data=root.resolve("reuse-flow-restart");String fid,pid,providerId,binding;JsonObject ordinary;
        try(EngineTest.Mock mock=new EngineTest.Mock()){
            try(Engine e=new Engine(data)){JsonObject provider=boundProvider(e,mock);providerId=Json.required(provider,"id");binding=e.providers.credentialBindingVersion(providerId);pid=Json.required(EngineTest.project(e,"detect"),"id");JsonArray ids=EngineTest.importSamples(e,pid,1);ordinary=request(provider,pid,ids);JsonObject a=FlowLifecycleTest.api(provider),b=a.deepCopy();b.addProperty("id","second");JsonObject request=FlowIntegrationTest.request(pid,Json.arr(a,b,step("export","export",Json.obj("outputDir",root.resolve("reuse-export").toString()))));request.addProperty("maxRequests",1);fid=Json.required(cmd(e,"flow.create",request),"id");JsonObject flow=waitFlow(e,fid,"completed");check(mock.calls.get()==1&&Json.integer(Json.object(flow,"statistics"),"requestsUsed",0)==1&&Json.integer(Json.object(flow,"statistics"),"reused",0)==1,"two identical API nodes share first result within one-request flow budget");check(Json.integer(Json.object(state(flow,"second"),"statistics"),"reused",0)==1,"flow API step reports reused as succeeded subset");JsonObject artifact=cmd(e,"flow.artifact",Json.obj("artifactId",state(flow,"second").get("outputArtifactId")));check(Json.integer(Json.object(artifact,"statistics"),"reused",0)==1&&Json.bool(Json.array(artifact,"items").get(0).getAsJsonObject(),"reused",false),"fixed annotation artifact includes reuse statistics and source provenance");JsonArray events=(JsonArray)e.command("event.list",Json.obj("flowRunId",fid));check(events.asList().stream().map(JsonElement::getAsJsonObject).anyMatch(v->Json.str(v,"type","").equals("sample.succeeded")&&Json.str(v,"stepId","").equals("second")&&Json.bool(Json.object(v,"payload"),"reused",false)&&(!v.has("attemptId")||v.get("attemptId").isJsonNull())),"reuse completion event has real child flow association and no fake attempt");JsonObject rerun=cmd(e,"flow.rerun",Json.obj("flowRunId",fid,"fromStepId","export"));JsonObject exported=waitFlow(e,Json.required(Json.object(rerun,"run"),"id"),"completed");check(mock.calls.get()==1&&Json.integer(Json.object(exported,"statistics"),"reused",-1)==0&&Json.integer(Json.object(exported,"statistics"),"requestsUsed",-1)==0,"inherited upstream export does not count previous reuse as new activity");}
            try(Engine e=new Engine(data)){cmd(e,"credential.set",Json.obj("providerId",providerId,"key","reuse-fixture-secret","credentialBindingVersion",binding));JsonObject reused=finished(e,ordinary);check(mock.calls.get()==1&&Json.integer(reused,"reused",0)==1&&Json.required(Json.object(sample(reused),"reusedFrom"),"sourceRunId").equals(Json.required(state(e.flows.get(fid),"api"),"childRunId")),"restart with same persisted credential binding reuses original real completion");}
        }
    }
}
