package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.sql.*;

final class Schema4MigrationTest {
    static void check(boolean condition,String message){EngineTest.check(condition,message);}
    static void legacy(Path root,boolean broken)throws Exception{
        Files.createDirectories(root);try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+root.resolve("autolabel.db"));Statement s=c.createStatement()){
            s.execute("CREATE TABLE projects(id TEXT PRIMARY KEY,data TEXT NOT NULL)");s.execute("CREATE TABLE assets(id TEXT PRIMARY KEY,project_id TEXT NOT NULL REFERENCES projects(id),data TEXT NOT NULL,path TEXT NOT NULL)");s.execute("CREATE TABLE runs(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL)");s.execute("CREATE TABLE samples(id TEXT PRIMARY KEY,run_id TEXT NOT NULL REFERENCES runs(id),asset_id TEXT NOT NULL,status TEXT NOT NULL,attempt_count INTEGER NOT NULL DEFAULT 0,next_at INTEGER NOT NULL DEFAULT 0,"+(broken?"":"active_attempt TEXT,")+"data TEXT NOT NULL,UNIQUE(run_id,asset_id))");s.execute("CREATE TABLE attempts(id TEXT PRIMARY KEY,run_id TEXT,sample_id TEXT,group_id TEXT NOT NULL,status TEXT NOT NULL,data TEXT NOT NULL)");
            Store.update(c,"INSERT INTO projects VALUES(?,?)","project",Json.obj("id","project","name","旧项目","taskType","detect"));Store.update(c,"INSERT INTO assets VALUES(?,?,?,?)","asset","project",Json.obj("id","asset","projectId","project","version",3),root.resolve("asset.png").toString());Store.update(c,"INSERT INTO runs VALUES(?,?,?,?)","run","project","completed",Json.obj("id","run","projectId","project","status","completed"));Store.update(c,"INSERT INTO samples(id,run_id,asset_id,status,attempt_count,data) VALUES(?,?,?,?,?,?)","sample","run","asset","succeeded",2,Json.obj("id","sample","assetId","asset","candidateVersion",3));Store.update(c,"INSERT INTO attempts VALUES(?,?,?,?,?,?)","attempt","run","sample","group","completed",Json.obj("id","attempt","sampleId","sample","response","原始调用记录"));s.execute("PRAGMA user_version=3");
        }
    }
    static void run(Path root)throws Exception{
        Path data=root.resolve("schema3-to4");legacy(data,false);String before;try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+data.resolve("autolabel.db"))){before=Json.required(Store.one(c,"SELECT data FROM attempts"),"data");}
        try(Store store=new Store(data)){check(store.read(c->Json.integer(Store.one(c,"PRAGMA user_version"),"user_version",0))==Store.SCHEMA_VERSION,"real schema3 upgrades to current schema");JsonObject sample=store.read(c->Store.one(c,"SELECT * FROM samples"));check(Json.required(sample,"input_id").equals("asset")&&Json.integer(sample,"attempt_count",0)==2,"legacy input identity and attempt counter preserved");check(store.read(c->Json.required(Store.one(c,"SELECT data FROM attempts"),"data")).equals(before),"legacy attempt and response association preserved byte for byte");store.tx(c->{Store.update(c,"INSERT INTO samples(id,run_id,asset_id,input_id,status,data) VALUES(?,?,?,?,?,?)","view-sample","run","asset","input-view","queued",Json.obj("id","view-sample","assetId","asset","inputId","input-view"));return null;});check(store.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM samples WHERE asset_id='asset'"),"n",0))==2,"new distinct view can share same run baseline");check(store.read(c->{try{Store.update(c,"INSERT INTO samples(id,run_id,asset_id,input_id,status,data) VALUES(?,?,?,?,?,?)","duplicate","run","asset","input-view","queued",new JsonObject());return false;}catch(SQLException expected){return true;}}),"run input identity remains unique");check(store.read(c->Store.one(c,"PRAGMA foreign_key_check"))==null,"schema4 associations pass foreign key check");}
        try(Store again=new Store(data)){check(again.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM samples"),"n",0))==2,"reopening schema4 is idempotent");}try(var files=Files.list(data.resolve("backups"))){check(files.filter(path->path.getFileName().toString().startsWith("schema-v3-")).count()==1,"migration creates exactly one consistent schema3 backup");}
        Path broken=root.resolve("schema3-rollback");legacy(broken,true);try{new Store(broken);throw new AssertionError("incomplete schema migration must fail");}catch(ApiError failure){check(failure.code.equals("database_migration_failed"),"failed schema rebuild is reported");}try(Connection c=DriverManager.getConnection("jdbc:sqlite:"+broken.resolve("autolabel.db"))){check(Json.integer(Store.one(c,"PRAGMA user_version"),"user_version",0)==3,"failed rebuild retains schema3 version");check(Store.one(c,"SELECT name FROM sqlite_master WHERE name='samples_v4'")==null&&Store.one(c,"SELECT id FROM samples WHERE id='sample'")!=null,"failed rebuild rolls back temporary table and preserves original sample");}
    }
}
