package cn.autolabel.engine;

import com.google.gson.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.nio.file.*;
import java.util.*;

public final class TrackIntegrationTest {
    static int checks;static Path root;static JsonObject timeline;static JsonArray frames;
    interface Action{void run()throws Exception;}
    static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
    static JsonObject cmd(Engine e,String command,JsonObject p)throws Exception{return (JsonObject)e.command(command,p);}
    static void rejects(String code,Action action)throws Exception{try{action.run();throw new AssertionError("Expected "+code);}catch(ApiError e){check(code.equals(e.code),code+" != "+e.code);}}
    static JsonObject frame(int n){return frames.get(n).getAsJsonObject();}
    static JsonObject asset(Engine e,int n)throws Exception{return cmd(e,"asset.get",Json.obj("assetId",frame(n).get("assetId")));}
    static JsonObject track(Engine e,JsonObject track)throws Exception{return cmd(e,"track.get",Json.obj("trackId",track.get("id")));}
    static JsonObject box(String id,double x,String type){JsonObject annotation=Json.obj("id",id,"classId","obj","type",type,"bbox",Json.obj("x",x,"y",10,"width",15,"height",20));if(type.equals("pose"))annotation.add("keypoints",Json.arr(Json.obj("name","head","x",x+5,"y",15,"visibility",2)));return annotation;}
    static JsonObject createTrack(Engine e,String name)throws Exception{return cmd(e,"track.create",Json.obj("timelineId",timeline.get("id"),"timelineVersion",timeline.get("version"),"classId","obj","name",name));}
    static JsonObject bind(Engine e,JsonObject t,int n,double x,boolean attribute)throws Exception{
        t=track(e,t);JsonObject a=asset(e,n),annotation=box(Json.required(t,"id")+"-"+n,x,Json.required(timeline,"taskType"));if(attribute)annotation.add("attributes",Json.obj("material","steel"));JsonArray all=new JsonArray();for(JsonElement value:Json.array(a,"annotations"))if(!Json.required(value.getAsJsonObject(),"id").equals(Json.required(annotation,"id")))all.add(value);all.add(annotation);JsonObject saved=cmd(e,"annotation.save",Json.obj("assetId",a.get("id"),"baseVersion",a.get("version"),"annotations",all));
        JsonObject p=Json.obj("trackId",t.get("id"),"baseVersion",t.get("version"),"timelineVersion",timeline.get("version"),"frameId",frame(n).get("frameId"),"state","located","annotation",annotation,"baseAnnotationVersion",saved.get("version"),"baseDraftSavedAt",null);for(JsonElement value:Json.array(cmd(e,"track.keyframe.list",Json.obj("trackId",t.get("id"))),"items"))if(Json.required(value.getAsJsonObject(),"frameId").equals(Json.required(frame(n),"frameId")))p.add("keyframeId",value.getAsJsonObject().get("keyframeId"));return Json.object(cmd(e,"track.keyframe.save",p),"track");
    }
    static JsonObject request(Engine e,JsonObject t,String scope)throws Exception{t=track(e,t);return Json.obj("trackId",t.get("id"),"baseVersion",t.get("version"),"timelineVersion",timeline.get("version"),"scope",scope);}
    static JsonObject await(Engine e,JsonObject job)throws Exception{for(int i=0;i<800;i++){JsonObject value=cmd(e,"track.generation.get",Json.obj("generationId",job.get("id")));if(!Set.of("queued","running","cancelling").contains(Json.required(value,"status")))return value;Thread.sleep(20);}throw new AssertionError("generation timeout");}
    static JsonObject generate(Engine e,JsonObject t,String scope)throws Exception{return await(e,cmd(e,"track.generate",request(e,t,scope)));}
    static void setup(Engine e,String task,boolean attributes)throws Exception{
        JsonObject settings=task.equals("pose")?Json.obj("keypointNames",Json.arr("head")):new JsonObject();if(attributes)settings.add("attributes",Json.obj("kind","attribute_definitions","version",1,"definitions",Json.arr(Json.obj("id","material","name","材质","type","text","required",true))));
        JsonObject p=cmd(e,"project.create",Json.obj("name","轨迹事务固定图夹具","taskType",task,"classes",Json.arr(Json.obj("id","obj","name","对象","color","#557799")),"settings",settings));String pid=Json.required(p,"id"),jobId=Json.id(),source="video-fixture-"+Json.id();JsonArray paths=new JsonArray();Path images=root.resolve(pid);Files.createDirectories(images);for(int i=0;i<9;i++){BufferedImage image=new BufferedImage(128,96,BufferedImage.TYPE_INT_RGB);image.setRGB(0,0,0xff0000+i*300);Path path=images.resolve(i+".png");ImageIO.write(image,"png",path.toFile());paths.add(path.toString());}JsonArray assets=Json.array(cmd(e,"asset.import",Json.obj("projectId",pid,"paths",paths)),"assetIds");check(assets.size()==9,"nine actual image baselines");
        e.store.tx(c->{JsonObject job=Json.obj("id",jobId,"projectId",pid,"kind","video_extract","status","completed","sourceVideoId",source,"assetsCommitted",true,"summary",Json.obj("frameCount",9));Store.update(c,"INSERT INTO media_jobs(id,project_id,kind,status,data) VALUES(?,?,?,?,?)",jobId,pid,"video_extract","completed",job);for(int i=0;i<assets.size();i++){String id=assets.get(i).getAsString();JsonObject a=Store.document(c,"assets",id),metadata=Json.object(a,"metadata");for(var entry:Json.obj("mediaJobId",jobId,"frameId","frame-"+i,"sourceVideoId",source,"videoSourceHash","a".repeat(64),"sourcePresentationIndex",i,"sourcePts",Integer.toString(i),"originPts","0","relativePts",Integer.toString(i),"timeBase",Json.obj("numerator",1,"denominator",10),"timeSeconds",i/10.0,"rangeIndex",0).entrySet())metadata.add(entry.getKey(),entry.getValue());a.add("metadata",metadata);Store.update(c,"UPDATE assets SET data=? WHERE id=?",a,id);}return null;});
        timeline=cmd(e,"track.timeline.create",Json.obj("projectId",pid,"mediaJobId",jobId));frames=Json.array(cmd(e,"track.timeline.frames",Json.obj("timelineId",timeline.get("id"))),"items");timeline=Json.object(cmd(e,"track.timeline.update",Json.obj("timelineId",timeline.get("id"),"baseVersion",timeline.get("version"),"scenes",Json.arr(Json.obj("startFrameId",frame(0).get("frameId"),"endFrameId",frame(8).get("frameId"),"sceneId","one")))),"timeline");
    }
    public static void main(String[] args)throws Exception{root=Path.of("engine/build/verification/tracks-"+System.currentTimeMillis()).toAbsolutePath();Files.createDirectories(root);manualStructure();requiredAttributes();poseAndBoundaries();System.out.println("PASS "+checks+" track integration checks; VERIFICATION_DIR="+root);}
    static void manualStructure()throws Exception{
        Path data=root.resolve("manual");String interrupted,trackId,timelineId;try(Engine e=new Engine(data)){
            setup(e,"detect",false);JsonObject a=createTrack(e,"甲"),b=createTrack(e,"乙");for(int n:new int[]{0,4,8})a=bind(e,a,n,10+n,false);for(int n:new int[]{0,8})b=bind(e,b,n,50+n,false);check(Json.required(generate(e,a,"affected"),"status").equals("completed"),"first track complete");check(Json.required(generate(e,b,"affected"),"status").equals("completed"),"second track complete");check(Json.array(asset(e,1),"annotations").size()==2,"both contributions");
            JsonObject page=cmd(e,"track.timeline.frames",Json.obj("timelineId",timeline.get("id"),"aroundFrameId",frame(7).get("frameId"),"limit",1));check(Json.integer(page,"offset",-1)==7&&Json.array(page,"items").size()==1,"exact frame pagination");rejects("track_page_invalid",()->cmd(e,"track.timeline.frames",Json.obj("timelineId",timeline.get("id"),"aroundFrameId",frame(7).get("frameId"),"offset",0)));
            JsonObject neighbors=cmd(e,"track.keyframe.list",Json.obj("trackId",a.get("id"),"aroundFrameId",frame(4).get("frameId")));check(Json.required(Json.object(neighbors,"previous"),"frameId").equals("frame-0")&&Json.required(Json.object(neighbors,"next"),"frameId").equals("frame-8"),"strict neighbors");JsonObject unaffected=asset(e,6),drafted=asset(e,2);cmd(e,"annotation.draft",Json.obj("assetId",drafted.get("id"),"baseVersion",drafted.get("version"),"annotations",drafted.get("annotations")));a=bind(e,a,0,20,false);JsonObject preview=cmd(e,"track.generate.preview",request(e,a,"affected"));check(Json.integer(preview,"frameCount",0)==9&&Json.integer(preview,"affectedCount",0)==5,"full frame count separate affected");generate(e,a,"affected");check(asset(e,6).get("version").equals(unaffected.get("version")),"nonadjacent interval untouched");check(asset(e,2).get("version").equals(drafted.get("version"))&&asset(e,2).has("draft"),"draft protected");cmd(e,"annotation.draft.discard",Json.obj("assetId",drafted.get("id")));
            JsonObject split=cmd(e,"track.split",merge(request(e,a,"affected"),"scope",Json.obj("splitFrameId",frame(4).get("frameId"))));check(Json.required(await(e,Json.object(split,"generation")),"status").equals("completed"),"split generation complete");JsonObject left=Json.object(split,"leftTrack"),right=Json.object(split,"rightTrack");check(left.get("objectId").equals(right.get("objectId")),"split identity retained");check(Json.array(asset(e,1),"annotations").size()==1&&Json.array(asset(e,6),"annotations").size()==2,"split removes only bridge owner");
            JsonObject merged=cmd(e,"track.merge",Json.obj("leftTrackId",left.get("id"),"leftVersion",left.get("version"),"rightTrackId",right.get("id"),"rightVersion",right.get("version"),"timelineVersion",timeline.get("version")));check(Json.required(await(e,Json.object(merged,"generation")),"status").equals("completed"),"merge generation complete");a=Json.object(merged,"track");check(Json.array(asset(e,1),"annotations").size()==2,"merge restores bridge without losing second track");
            JsonObject deleted=cmd(e,"track.delete",merge(request(e,b,"affected"),"scope",new JsonObject()));check(Json.required(await(e,Json.object(deleted,"generation")),"status").equals("completed"),"delete generation complete");check(Json.array(asset(e,1),"annotations").size()==1,"delete removes only selected contribution");check(Json.array(cmd(e,"track.keyframe.list",Json.obj("trackId",b.get("id"))),"items").size()==2,"archived keys preserved");
            cmd(e,"system.suspend",new JsonObject());JsonObject queued=cmd(e,"track.generate",request(e,a,"all"));JsonObject update=cmd(e,"system.canUpdate",new JsonObject());check(!Json.bool(update,"canUpdate",true),"queued generation blocks update");cmd(e,"track.generation.cancel",Json.obj("generationId",queued.get("id")));JsonObject retry=cmd(e,"track.generation.retry",Json.obj("generationId",queued.get("id")));check(!retry.get("id").equals(queued.get("id"))&&retry.get("originalGenerationId").equals(queued.get("id")),"retry new durable job");cmd(e,"system.resume",new JsonObject());check(Json.required(await(e,retry),"status").equals("completed"),"retry runs after explicit resume");
            cmd(e,"system.suspend",new JsonObject());interrupted=Json.required(cmd(e,"track.generate",request(e,a,"all")),"id");trackId=Json.required(a,"id");timelineId=Json.required(timeline,"id");JsonArray events=e.store.read(c->Store.events(c,0,null,null,2000));check(events.asList().stream().anyMatch(v->v.getAsJsonObject().has("timelineId")&&v.getAsJsonObject().has("generationId")),"durable top-level event ids");check(e.store.<Long>read(c->Json.number(Store.one(c,"SELECT COUNT(*) n FROM attempts"),"n",0))==0,"zero model requests");
        }
        try(Engine e=new Engine(data)){check(Json.required(cmd(e,"track.generation.get",Json.obj("generationId",interrupted)),"status").equals("interrupted"),"restart marks queued interrupted");check(Json.required(cmd(e,"track.get",Json.obj("trackId",trackId)),"status").equals("active"),"track persisted");check(Json.object(cmd(e,"track.timeline.get",Json.obj("timelineId",timelineId)),"template").has("classes"),"full frozen template persisted");}
    }
    static JsonObject merge(JsonObject base,String remove,JsonObject extra){JsonObject out=base.deepCopy();out.remove(remove);for(var entry:extra.entrySet())out.add(entry.getKey(),entry.getValue());return out;}
    static void requiredAttributes()throws Exception{try(Engine e=new Engine(root.resolve("attributes"))){setup(e,"detect",true);JsonObject a=createTrack(e,"必填属性");a=bind(e,a,0,10,true);a=bind(e,a,8,30,true);JsonObject job=generate(e,a,"all");check(Json.required(job,"status").equals("completed_with_errors"),"required attributes block invalid candidates");JsonObject results=cmd(e,"track.generation.results",Json.obj("generationId",job.get("id")));JsonObject middle=Json.array(results,"items").get(1).getAsJsonObject();check(Json.required(middle,"status").equals("blocked")&&Json.array(middle,"annotations").size()==1&&Json.bool(middle,"requiresReview",false),"raw contribution kept for review");check(Json.array(asset(e,1),"annotations").isEmpty(),"no invalid annotation formally saved");JsonObject preflight=cmd(e,"export.preflight",Json.obj("projectId",timeline.get("projectId"),"assetIds",Json.arr(frame(1).get("assetId"))));check(!Json.bool(Json.object(preflight,"summary"),"canExport",true),"invalid candidate cannot masquerade as background");}}
    static void poseAndBoundaries()throws Exception{try(Engine e=new Engine(root.resolve("pose"))){setup(e,"pose",false);JsonObject a=createTrack(e,"姿态");a=bind(e,a,0,10,false);a=bind(e,a,8,30,false);generate(e,a,"all");JsonObject annotation=Json.array(asset(e,3),"annotations").get(0).getAsJsonObject();check(Math.abs(Json.decimal(Json.object(annotation,"bbox"),"x",0)-17.5)<1e-9,"pose bbox actual PTS");check(Math.abs(Json.decimal(Json.array(annotation,"keypoints").get(0).getAsJsonObject(),"x",0)-22.5)<1e-9,"pose points actual PTS");timeline=Json.object(cmd(e,"track.timeline.update",Json.obj("timelineId",timeline.get("id"),"baseVersion",timeline.get("version"),"scenes",Json.arr(Json.obj("startFrameId",frame(4).get("frameId"),"endFrameId",frame(8).get("frameId"),"sceneId","two")))),"timeline");JsonObject preview=cmd(e,"track.generate.preview",request(e,a,"affected"));check(Json.bool(Json.array(preview,"intervals").get(0).getAsJsonObject(),"blocked",false),"scene boundary blocks interpolation");generate(e,a,"affected");check(Json.array(asset(e,3),"annotations").isEmpty(),"blocked interval retires stale candidates");}}
}
