package cn.autolabel.engine;

import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
import static cn.autolabel.engine.FlowIntegrationTest.*;

final class ViewRunIntegrationTest {
    static JsonObject child(Engine engine,JsonObject flow){return engine.runs.get(Json.required(state(flow,"api"),"childRunId"));}
    static JsonObject completed(Engine engine,JsonObject request,String status)throws Exception{JsonObject flow=cmd(engine,"flow.create",request);return waitFlow(engine,Json.required(flow,"id"),status);}
    static void reviewResolution(Engine engine,EngineTest.Mock mock,JsonObject provider,Path root)throws Exception{
        String project=Json.required(EngineTest.project(engine,"detect"),"id"),asset=EngineTest.importSamples(engine,project,1).get(0).getAsString();JsonObject api=Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","maxRetries",0);JsonObject request=request(project,Json.arr(step("transform","transform",Json.obj("operations",Json.arr(Json.obj("kind","crop","x",0,"y",0,"width",480,"height",640)))),step("api","api",api),step("review","review",Json.obj("waitForHuman",true)),step("export","export",Json.obj("outputDir",root.resolve("reviewed-view-export").toString()))));request.addProperty("maxRequests",1);JsonObject flow=completed(engine,request,"needs_attention");String oldArtifact=Json.required(state(flow,"review"),"outputArtifactId");JsonObject blocked=engine.projects.asset(asset);int blockedVersion=Json.integer(blocked,"version",0);check(Json.bool(Json.object(blocked,"metadata"),"requiresGeometryReview",false),"partial candidate reaches an explicit geometry review gate");JsonObject manual=cmd(engine,"annotation.save",Json.obj("assetId",asset,"baseVersion",blockedVersion,"annotations",Json.arr(EngineTest.label("detect")),"confirm",true));cmd(engine,"flow.resume",Json.obj("flowRunId",flow.get("id"),"acknowledgeReviewStepId","review"));JsonObject done=waitFlow(engine,Json.required(flow,"id"),"completed_with_errors");String newArtifact=Json.required(state(done,"review"),"outputArtifactId");check(!oldArtifact.equals(newArtifact),"manual resolution seals a new review artifact without editing original");JsonObject fixed=cmd(engine,"flow.artifact",Json.obj("artifactId",newArtifact));check(Json.integer(Json.array(fixed,"items").get(0).getAsJsonObject(),"selectedVersion",0)==Json.integer(manual,"version",-1),"new review artifact freezes explicit manual revision");JsonObject unchanged=engine.store.read(c->Json.parse(Store.one(c,"SELECT data FROM versions WHERE asset_id=? AND version=?",asset,blockedVersion).get("data").getAsString()));check(Json.bool(Json.object(unchanged,"metadata"),"requiresGeometryReview",false),"resume never clears original candidate geometry issue");check(Json.required(state(done,"export"),"status").equals("completed"),"fixed manual revision can export after review");
    }
    static void run(Path root)throws Exception{
        Schema4MigrationTest.run(root);
        try(EngineTest.Mock mock=new EngineTest.Mock();Engine engine=new Engine(root.resolve("view-api-data"))){JsonObject provider=ReuseIntegrationTest.boundProvider(engine,mock);String project=Json.required(EngineTest.project(engine,"detect"),"id"),asset=EngineTest.importSamples(engine,project,1).get(0).getAsString();JsonObject api=Json.obj("providerId",provider.get("id"),"model","fixture","prompt","locate","maxRetries",0,"concurrency",2);JsonArray operations=Json.arr(Json.obj("kind","tile","width",480,"height",640),Json.obj("kind","resize","width",960,"height",640,"fit","stretch"));JsonObject request=request(project,Json.arr(step("transform","transform",Json.obj("operations",operations)),step("api","api",api)));request.addProperty("maxRequests",2);request.addProperty("budgetScopeId","view-cache-scope");
            check(Json.bool(cmd(engine,"flow.preflight",request),"canStart",false),"API view preflight accepts fixed pixel plan");JsonObject first=completed(engine,request,"completed"),firstChild=child(engine,first);check(mock.calls.get()==2&&Json.integer(Json.object(firstChild,"statistics"),"baselineCompleted",0)==1,"two actual API inputs aggregate one baseline");JsonArray samples=Json.array(firstChild,"samples");Set<String> inputs=new HashSet<>(),results=new HashSet<>();for(JsonElement value:samples){JsonObject sample=value.getAsJsonObject();inputs.add(Json.required(sample,"inputId"));results.add(Json.required(sample,"resultId"));check(Json.required(sample,"assetId").equals(asset)&&!Json.required(sample,"inputId").equals(asset),"public sample separates target identity and parent identity");JsonObject result=cmd(engine,"run.result.get",Json.obj("resultId",sample.get("resultId")));check(Json.required(Json.object(result,"rawResult"),"assetId").equals(Json.required(sample,"inputId")),"actual API echo is checked against view input identity");check(Json.decimal(Json.object(Json.array(result,"annotations").get(0).getAsJsonObject(),"bbox"),"x",0)==200,"input annotations remain in actual image space");}
            check(inputs.size()==2&&results.size()==2,"API raw and mapped results saved independently per view");JsonObject parent=engine.projects.asset(asset);check(Json.array(parent,"annotations").size()==2&&!parent.has("attemptId")&&Json.bool(Json.object(Json.object(parent,"metadata"),"coverage"),"complete",false),"parent aggregate has two objects and no fabricated single attempt");Set<Double> positions=new HashSet<>();for(JsonElement value:Json.array(parent,"annotations"))positions.add(Json.decimal(Json.object(value.getAsJsonObject(),"bbox"),"x",0));check(positions.equals(Set.of(100.0,580.0)),"inverse mapping uses each tile actual offset and scale");check(engine.runs.attempts(Json.obj("runId",firstChild.get("id"))).asList().stream().allMatch(value->Json.required(value.getAsJsonObject(),"status").equals("completed")),"successful API attempts are atomically completed with input results");
            JsonObject second=completed(engine,request,"completed"),secondChild=child(engine,second);check(mock.calls.get()==2&&Json.integer(secondChild,"reused",0)==2&&Json.integer(secondChild,"requestsUsed",-1)==0,"all view hits bypass exhausted shared API budget");check(engine.runs.attempts(Json.obj("runId",secondChild.get("id"))).isEmpty(),"view reuse creates no fake attempt");for(JsonElement value:Json.array(secondChild,"samples")){JsonObject sample=value.getAsJsonObject(),source=Json.object(sample,"inputReusedFrom");check(results.contains(Json.required(source,"sourceResultId"))&&!source.has("sourceCandidateVersion")&&Json.bool(sample,"reused",false),"view reuse reports immutable source result instead of aggregate candidate version");}
            JsonObject forced=request.deepCopy();forced.remove("budgetScopeId");Json.object(Json.array(Json.object(forced,"definition"),"steps").get(1).getAsJsonObject(),"parameters").addProperty("forceRerun",true);JsonObject third=completed(engine,forced,"completed"),thirdChild=child(engine,third);check(mock.calls.get()==4&&Json.integer(thirdChild,"reused",-1)==0,"force requests both view inputs again");JsonObject fourth=child(engine,completed(engine,request,"completed"));check(mock.calls.get()==4&&Json.array(fourth,"samples").asList().stream().allMatch(value->Json.required(Json.object(value.getAsJsonObject(),"inputReusedFrom"),"sourceRunId").equals(Json.required(thirdChild,"id"))),"later reuse selects newest real forced input source");
            int before=Json.integer(engine.projects.asset(asset),"version",0);cmd(engine,"annotation.save",Json.obj("assetId",asset,"baseVersion",before,"annotations",Json.arr(EngineTest.label("detect")),"confirm",true));int manual=Json.integer(engine.projects.asset(asset),"version",0);JsonObject protectedRun=child(engine,completed(engine,request,"completed"));check(Json.integer(protectedRun,"reused",0)==2&&Json.integer(engine.projects.asset(asset),"version",0)==manual,"view cache cannot overwrite manual parent version");
            JsonObject partial=request(project,Json.arr(step("transform","transform",Json.obj("operations",Json.arr(Json.obj("kind","crop","x",0,"y",0,"width",480,"height",640)))),step("api","api",api)));partial.addProperty("maxRequests",1);JsonObject crop=completed(engine,partial,"completed_with_errors"),cropChild=child(engine,crop);check(Json.integer(cropChild,"requestsUsed",0)==1,"different crop plan misses cache");JsonObject sample=Json.array(cropChild,"samples").get(0).getAsJsonObject();JsonObject blocked=engine.store.read(c->Json.parse(Store.one(c,"SELECT data FROM versions WHERE asset_id=? AND version=?",asset,sample.get("candidateVersion").getAsInt()).get("data").getAsString()));check(Json.bool(Json.object(blocked,"metadata"),"requiresGeometryReview",false)&&!Json.bool(Json.object(Json.object(blocked,"metadata"),"coverage"),"complete",true),"partial crop cannot silently become full baseline annotation");
            mock.slow=true;JsonObject slow=forced.deepCopy();slow.addProperty("maxRequests",4);JsonObject unknown=completed(engine,slow,"needs_attention"),unknownChild=child(engine,unknown);check(Json.integer(Json.object(unknownChild,"statistics"),"unknown",0)==2,"unknown view responses remain explicit terminal input facts");ManualChainTest.rejects("flow_unknown_retry_required",()->cmd(engine,"flow.retry",Json.obj("flowRunId",unknown.get("id"),"stepId","api")));mock.slow=false;cmd(engine,"flow.retry",Json.obj("flowRunId",unknown.get("id"),"stepId","api","retryUnknown",true));JsonObject retried=waitFlow(engine,Json.required(unknown,"id"),"completed");String retriedChild=Json.required(state(retried,"api"),"childRunId");check(Json.integer(engine.runs.get(retriedChild),"requestsUsed",0)==4,"explicit unknown retry sends fresh requests without reuse");check(engine.store.read(c->Json.integer(Store.one(c,"SELECT COUNT(*) AS n FROM input_results WHERE run_id=?",retriedChild),"n",0))==4,"retry preserves all prior immutable unknown input results");
            reviewResolution(engine,mock,provider,root);
        }
    }
}
