import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(require('electron'), [root, ...process.argv.slice(2)], { cwd: root, stdio: 'inherit', windowsHide: true, env });
child.once('exit', code => { process.exitCode = code ?? 1; });
child.once('error', error => { console.error(error.message); process.exitCode = 1; });
